### ISSUE TITLE
Inconsistent grammar in trailing comma usage

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#10104]
**Description:**
The following code does not compile because of an extraneous trailing comma. 
```
endpoint Client natsClient {
    host: config:getAsString(NATS_HOST),
    port: config:getAsInt(NATS_PORT),
};
```

And then the following code does not compile because of a lacking a trailing comma. 
```
public type Invoice record {
    int transactionId,
    string orderNo,
    string invoiceId,
    string settlementId,
    string trackingNumber
};
```

This is not consistent, is it?

**Affected Versions:**
0.980.1

**Comment by MaryamZi** [comment]
From Ballerina 0.982.0 onward, the record/object field separator was changed from `,` to `;` and thus all the fields in the record need to have the `;` at the end.
```ballerina
public type Invoice record {
    int transactionId;
    string orderNo;
    string invoiceId;
    string settlementId;
    string trackingNumber;
};
```

As for endpoints, from Ballerina 0.990.0 onward, both service and client endpoints are objects. Example definitions are as follows:
```ballerina
http:Client clientEndpoint = new("https://postman-echo.com");
```

```ballerina
http:ServiceEndpointConfiguration helloWorldEPConfig = {
    secureSocket: {
        keyStore: {
            path: "${ballerina.home}/bre/security/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
};

listener http:Listener helloWorldEP = new(9095, config = helloWorldEPConfig);
```

Closing the issue, since the inconsistency is no longer present.
