### ISSUE TITLE
Defaultable param support for non-primitive types

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#10232]
**Description:**
ATM the primitive types can only state as default-able param. The requirement is to extend the logic to support custom types as well. Please find following sample.
```ballerina
public type ForwardedConfig "enable"|"transition"|"disable";

@final public ForwardedConfig FORWARDED_ENABLE = "enable";
@final public ForwardedConfig FORWARDED_TRANSITION = "transition";
@final public ForwardedConfig FORWARDED_DISABLE = "disable";

public function post(@sensitive string path, Request|string|xml|json|byte[]|io:ByteChannel|mime:Entity[]|()
                   message, ForwardedConfig forwarded = FORWARDED_DISABLE) returns Response|error {
       //....
}
```

**Comment by hasithaa** [comment]
@chamil321 @wggihan According to the spec (Ballerina-Language-Specification-WD-2018-07-12 - see page 23) the following are allowed as defaultable value expressions.

```
dflt-value-expr :=
nil-literal
| boolean-literal
| [Sign] int-literal
| [Sign] float-literal
| string-literal
```

What you have requested is the ability to pass a final variable reference as a defaultable value. I don't see a problem with the suggested approach if the final values are static. Right now final variables can get a dynamic value because final variables get initialized at package init time, which is a problem to support this. 

Please initiate a discussion @ dev group to discuss this spec deviation.

**Comment by MaryamZi** [comment]
According to the updated spec (January 2019), any const-expr is a valid default value for a defaultable param.

Related discussion on ballerina-dev: https://groups.google.com/d/topic/ballerina-dev/p_-CqaPebmE/discussion 

Created #13187 (with the same severity level) to track this change.
