### ISSUE TITLE
Constrained JSON with closed record can be mutated

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#10315]
**Description:**
Consider the below example from bio - https://ballerina.io/learn/by-example/constrained-json.html

```ballerina
import ballerina/io;
type Person record{
    string name;
    int age;
    string city;
    !...
};

function main (string... args) {

    json<Person> person = {name:"Jon"};

    person.age = 25;
    person.city = "Colombo";
    io:println(person);

    json employee = person;

    employee.profession = "Software Engineer";
    io:println(employee);
}
```

At the end, we can add new fields to the employee json, but the actual storage type is a closed one which should not allow to modify the json.

**Comment by pubudu91** [comment]
Possibly related to #9386. Constrained JSON is not working anyways at the moment.

**Comment by warunalakshitha** [comment]
Here we have assign the person to json without constraint type. If we assign person to contraint json, then you will get compilation error.

ex.
 replace
` json employee = person;`
to 
`json<Person> employee = person;`

 **undefined field 'profession' in record 'Person'**

Since we are assigning to a non constraint json, IMO this behavior seems ok.  @Kishanthan @pubudu91 WDYT?
