### ISSUE TITLE
Incorrect output for errorneous commands

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#10407]
**Description:**
Incorrect error message for incorrect commands. First character is missing from the error message.

**Steps to reproduce:**
Issue the command 
```ballerina -version```

Expected Output:
```
ballerina: unknown command '-version'
Run 'ballerina help' for usage
```

Current Output
```
ballerina: unknown command **'-ersion'**
Run 'ballerina help' for usage
```

**Affected Versions:**

0.982.2 SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This is due to clustered short options [1] being enabled. Since `-v` is a short option for version in the Ballerina default command [2], `-v` of `-version` is identified as a valid option, but the rest `-ersion` is not. Ideally the error message here should be:
```cmd
ballerina: unknown option(s): -ersion
Run 'ballerina help' for usage.
```
Since we currently do not suggest clustered options, the other alternative is to disable clustered options since the most common use right now is not clustering the option, and the following error message would be the most useful one:
```cmd
ballerina: unknown option: -version
Run 'ballerina help' for usage.
```

[1] https://picocli.info/#_posix_clustered_short_options 
[2] https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/Main.java#L550

**Comment by MaryamZi** [comment]
We will be disabling clustered short options for the time-being. 

If we eventually do enable clustered short options, we need to carefully revisit each command to ensure that we do not return after the logic for a single flag is executed (e.g., https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/Main.java#L557), instead we have to allow execution of logic relevant to all flags.
