### ISSUE TITLE
Table emptied after count()

### ISSUE THREAD

**Issue by ponsilva** [ballerina-platform/ballerina-lang#10763]
**Description:**
It seems a select result table is emptied after executing count()

**Steps to reproduce:**
Execute a simple select on a PostgreSQL DB using jdbc and put the result in a table dt.
Then execute:
int count;
count = dt.count();
io:println("row count: " + count);
count = dt.count();
io:println("row count: " + count);

The output is:
row count: 3
row count: 0

It seems the table is emptied after the first dt.count()

It also happens using a Oracle DB

**Affected Versions:**
ballerina-0.981.1

**OS, DB, other environment details and versions:**
windows

**Comment by anupama-pathirage** [comment]
@ponsilva Yes This is the expected behavior with cursor based tables. 

The table returned by select action is a cursor based table and actually it does not contain the data. When it is created, the table actually does not contain all the data, but it contains a cursor to the actual data in DB. So when that table is accessed later it will fetch the data row by row from the DB. This table can be converted to a json or xml. But if a cursor based table is converted, it actually does not contain the data until that converted payload get accessed. The purpose of this is to support data streaming. When a service client makes a request, the result is streamed to the service client rather than building the full result in the server and returning it. This allows virtually unlimited payload sizes in the result, and the response is instantaneous to the client. Cursor based tables can be iterated once and if the user wants to access the same data set again and again, he needs to load full data set into the memory using loadToMemory=true.

So in your case dt.count(); means table data has consumed when getting the count(). So next time it shows the count as empty. 
For cursor based tables suggestion is to:
1. Use a separate "select count(*) ..." query with select action to get the total count
2. Or load the data into memory using loadToMemory=true.

**Comment by anupama-pathirage** [comment]
Closing the issue as this is the expected behavior. Please let us know if you have further issues/clarifications on this. 
Refer [1] for more details on tables.
[1] https://medium.com/@anupama.pathirage/introduction-to-ballerina-tables-205286a53752
