### ISSUE TITLE
Config value not read when running the balx file after build

### ISSUE THREAD

**Issue by pasanbox** [ballerina-platform/ballerina-lang#10785]
**Description:**
Here is my project structure:
```
.
├── Ballerina.conf
├── Ballerina.toml
├── main.bal
├── target
│   ├── Ballerina.lock
│   └── main.balx
└── test_lib
    └── source_in_lib.bal
```

The contents of my source files are as below:
**main.bal**
```
import ballerina/io;
import pasanwijesinghe/test_lib;
public function main() {
	 test_lib:testFunc();
}
```

**source_in_lib.bal**
```
import ballerina/io;
import ballerina/log;
import ballerina/config;

public function testFunc() {
	log:printInfo("Value Read: " + config:getAsString("SAMPLE_STRING"));
}
```
**Ballerina.conf**
`SAMPLE_STRING="Test 1 2 3"
`

I'm getting two results when I run this directly and when I run it after building. Please refer the below image.

<img width="649" alt="screen shot 2018-10-11 at 5 25 28 pm" src="https://user-images.githubusercontent.com/1252833/46802472-039b9700-cd7b-11e8-9785-2dd8029d2347.png">

As you can see, the config is not read in the latter case. Can you please explain this difference.

**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.982.0

**OS, DB, other environment details and versions:**
macOS 10.13.6

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
Hi Pasan,
Thanks for reporting.
Actually, this is the expected behavior. According to [1], ballerina picks the config file if there is a ballerina.conf file in the source folder or you need to specify the .conf file --config or the -c flags. 

In your first scenario, there is a ballerina.conf file in the source folder (bal-issue-4/) hence it picks the config values. In the second scenario, your source is in the target folder. Since there is no ballerina.conf file in the target folder no config values were picked.

[1] - https://ballerina.io/learn/by-example/config-api.html

**Comment by pasanbox** [comment]
Thanks for the explanation @vinok88  👍
