### ISSUE TITLE
Mismatch in the output received from the http-data-binding sample

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10815]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Apr 20, 2018 at 06:32 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/300_

----

**Description:**
No output is received when the service is invoked as below

`curl -v http://localhost:9090/hello/bindXML -X POST -d "<h:Store id = \"AST\" xmlns:h=\"http://www.test.com\"><h:street>Main</h:street><h:city>94</h:city></h:Store>" -H "Content-Type:application/xml"`

https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/http-data-binding/http-data-binding.client.sh

**Affected Product Version:**
Ballerina beta 3 nightly

**OS, DB, other environment details and versions:**    
JDK - 1.8.0_171
Windows 10

**Comment by praneesha** [comment]
Tested this using Ballerina 0.990.2. Seems this example is rewritten and now we have the _http_data_binding.client.out_ file Instead of the _http-data-binding.client.sh_ file.

The above cURL command worked fine as shown below and the below output was received.

Praneeshas-MacBook-Air:ballerina-lang praneesha$ curl -v http://localhost:9090/hello/bindXML -X POST -d "<h:Store id = \"AST\" xmlns:h=\"http://www.test.com\"><h:street>Main</h:street><h:city>94</h:city></h:Store>" -H "Content-Type:application/xml"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9090 (#0)
> POST /hello/bindXML HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/xml
> Content-Length: 104
> 
* upload completely sent off: 104 out of 104 bytes
< HTTP/1.1 200 OK
< content-type: application/xml
< content-length: 49
< server: ballerina/0.990.2
< date: Wed, 16 Jan 2019 17:42:25 +0530
< 
* Connection #0 to host localhost left intact
<h:city xmlns:h="http://www.test.com">94</h:city>Praneeshas-MacBook-Air:ballerina-lang praneesha$ 
![screen shot 2019-01-16 at 5 42 43 pm](https://user-images.githubusercontent.com/11707273/51248445-2a8aea00-19b6-11e9-9e72-c756d7e092d5.png)
