### ISSUE TITLE
Issue in top level variable definition

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#10865]
**Description:**
```ballerina
int A = 10;
A a = 2;
```

The above code snippet works without giving an error. If the same code snippet is in a function, this will give an error.

**Comment by Manuri** [comment]
Following also gets compiled without an error. Appears to be the same issue.

```ballerina
string a = "abc";

function testTransactionStmtWithNoHandlers() returns a {
    return "";
}
```

**Comment by pubudu91** [comment]
The issue here is with how the symbol for a user defined type is resolved. As it can be seen in https://github.com/ballerina-platform/ballerina-lang/blob/c0bc5d81cd4f01bd52e8d5243bb8bd4e233f7916/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java#L1138,
the symbol is looked up as a variable name. Since there's already a variable defined by the name `A`, it's resolved to that variable.
