### ISSUE TITLE
Sort the scope-list used in the authorization cache key

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#11133]
The scope list added to the "authzCacheKey" should be sorted. This will prevent having to re-validation authorization when scope ordering changes.

For example:

- JWT sent with the initial request mentions "scopes" as "read-email, read-fullname". The relevant authorization decision will get cached with the cache key `user_id-service_name-resource_name-read-email,read-fullname`. 
- JWT sent with the second request mentions "scopes" as " read-fullname, read-email". Even though this is logically equivalent to "initial request", a cache-miss will happen, resulting in the re-validating authorization. 

This improvement can be done once Ballerina provides a way to sort arrays.

> **Note**: Update https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/http/src/main/ballerina/http/auth/authz_handler.bal#L81 when issue get fixed.

**Comment by ldclakmal** [comment]
Since the sort function adds additional cost to performance, it would be better to create multiple cache keys and store in the cache rather than sorting the scopes list per request. Otherwise, for a normal use case which has sorted scopes also, the function sort it again per request.

Therefore, the issue is closed for the moment and will reopen if there are any concerns.
