### ISSUE TITLE
Union types are inconsistently rendered in API docs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#11175]
Refer to the pic below:
![screenshot from 2018-11-02 11-21-37](https://user-images.githubusercontent.com/6260009/47896307-e007d000-de92-11e8-9a32-e04d4822dc0d.png)

The unions in the "Return Type" column have spaces around `|`. The correct one is the one in the "Data Type" column (the one without spaces). This is just one place. There are other places where spaces are used around `|`

**Comment by shehan360** [comment]
This issue seems to be fixed in the latest version.
![Screenshot from 2020-07-16 13-08-49](https://user-images.githubusercontent.com/33398983/87641466-c3462580-c765-11ea-994b-0a86f7a43323.png)
![Screenshot from 2020-07-16 13-09-17](https://user-images.githubusercontent.com/33398983/87641470-c5a87f80-c765-11ea-93cf-9c8e9c060104.png)
