### ISSUE TITLE
`ballerina build` command gets failed by 'org-name' parameter in Ballerina.toml file

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#11275]
**Description:**
`ballerina build` command gets failed when the **org-name** of `Ballerina.toml` file is mentioned as _wso2_ and if there is any import with _wso2_ organization.

**Steps to reproduce:**
1. Clone following ballerina guide.
https://github.com/ballerina-guides/salesforce-twilio-integration

2. Build the package with following command.
`ballerina build sms-sender`

It prints the error as follows:
```
Compiling source
    wso2/sms-sender:0.0.2
error: wso2/sms-sender:0.0.2::sms_sender.bal:21:1: cannot resolve module 'wso2/sfdc37'
error: wso2/sms-sender:0.0.2::sms_sender.bal:22:1: cannot resolve module 'wso2/twilio'
```

If we change the **org-name** of the `Ballerina.toml` into something else without _wso2_, the issue get resolved.

**Affected Versions:**
Ballerina 0.983.0

**OS, DB, other environment details and versions:**
Ubunut 16.04 LTS

**Suggested Labels (optional):**
Component/central
Type/Bug

**Suggested Assignees (optional):**
@NatashaWso2

**Comment by NatashaWso2** [comment]
This is because the org-name in your project is the same as the org-name of the module you are trying to import from Ballerina Central. 

When resolving the versions of the modules since the org-name of the project is same as the org-name of the imported module, the version of the project will be assigned to the imported module. When trying to resolve the module dependency it will try to pull for a module pertaining to the project version which does not exist.
