### ISSUE TITLE
csvChannel.write() force to put double-quote around my field that has comma

### ISSUE THREAD

**Issue by hejunchen** [ballerina-platform/ballerina-lang#12310]
**Description:**
I have a string[][] that I want to convert into csv file. All the field values will become string even if the original data is Integer, float, etc. There are certain fields that will contain comma character. 
When I use *io:WritableCSVChannel* to write string[][] content into csv file, the field with comma will be automatically wrapped inside a double-quote. 
However, since I don't know which field has comma and which field does not. I want to put a double-quote around every single field value. However, even I have double-quote for each field, the *io:WritableCSVChannel* will always add another pair of double-quote for the field whose value has comma character. This is a over-doing to my understanding.

**Steps to reproduce:**
For example, if I have a line of data like this:
| ID 	| FirstName 	| LastName 	| Position               	|
|----	|-----------	|----------	|------------------------	|
| 1  	| John      	| Doe      	| Lead, Development Team 	|

Since the "position" value has comma, when I put the csv content (without quote) into:
*csvChannel.write(rec);*

The final csv file will be like this:
ID,FirstName,LastName,Position
1,John,Doe,"Lead, Development Team"

***However***
I may not know that the FirstName or LastName field would not have any comma, so I want to make sure I am not missing anything, so the csv file content that I prepared has already applied the double-quote around each field. I just want to write the content into csv.

I believe if I have double-quote around each field, after the csvChannel.write() function, the csv file will be like this:
ID,FirstName,LastName,Position
"1","John,Doe",""Lead, Development Team""

For fixing this issue, I will have to force to remove the comma character from my csv content prior to executing the csvChannel.write() function. This would force us to alter the original data.

Of course, if I choose to write plain text file with my double-quote data, everything will be fine. However, since Ballerina provides the csv Channel, it could be as much robust as possible.

**Affected Versions:**
0.983.0 (only tested this version, the problem might be in ealier versions as well)

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**
CSV/IO, comma, double-quote

**Suggested Assignees (optional):**
When using the csvChannel.write() function, either don't force to put double-quote around the field with comma, or have a parameter that the user can define how to treat each field seperately.

**Comment by pamod** [comment]
@hejunchen the string[] which will be provided to the csvChannel.write() function represents a record. and each element in the array would represent an individual field. 

Referring to the example you pointed,

ID,FirstName,LastName,Position
1,John,Doe,"Lead, Development Team"

In the above example you have only 4 fields, whereas in the field which represents the 'position' the value itself contains ","  i.e "Lead, Development Team" which makes it a nested field. We surround the nested fields with quotes so that when we read the same CSV which was written we would be able to distinguish between fields and values. ( just so we will not interpret  Lead, Development Team as two seperate fields but rather as an individual field with value containing comma). This is standard practice which is followed to represent nested fields. 

If you do not intend to have bracers around the nested fields one option is to split the nested fields into  seperate elements in the array rather than representing it as an individual value. in this case both Lead and Development Team will be treated as two different fields.

**Comment by wggihan** [comment]
I'm close this issue. Please reopen if you have any further questions.
