### ISSUE TITLE
Documentation sample is not rendered properly.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#12405]
**Description:**
$subject. All the ballerina doc comments have moved into right side bar.
![image](https://user-images.githubusercontent.com/16300038/49452609-82570280-f807-11e8-8f05-91cc4dd7627a.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
The issue was there only in [1]. It is fixed now as per the below screenshots.
![screen shot 2019-01-17 at 11 14 19 am](https://user-images.githubusercontent.com/11707273/51298105-2bb92700-1a49-11e9-8b83-84e4ede073b2.png)
![screen shot 2019-01-17 at 11 14 26 am](https://user-images.githubusercontent.com/11707273/51298106-2c51bd80-1a49-11e9-89c3-36def3cab7ba.png)



[1] https://ballerina.io/learn/by-example/documentation.html
