### ISSUE TITLE
[Testerina] - Testerina cannot find the tests when running `ballerina test`

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#12492]
**Description:**
> I have a project structure as follows:
> 
> <img width="304" alt="screen shot 2018-12-05 at 12 08 24 pm" src="https://user-images.githubusercontent.com/40016057/49494728-9a219b80-f886-11e8-9f23-efc7759865b9.png">
>
> When I try `ballerina build` here, the projects build fine, runs tests, and tests are passing.
> 
> <img width="426" alt="screen shot 2018-12-05 at 12 11 22 pm" src="https://user-images.githubusercontent.com/40016057/49494807-e967cc00-f886-11e8-88b0-39a5261c3452.png">
>
> But when I use `ballerina test` instead, it outputs `no tests found`.
>
> <img width="367" alt="screen shot 2018-12-05 at 12 12 11 pm" src="https://user-images.githubusercontent.com/40016057/49494850-0c927b80-f887-11e8-956a-79be31670358.png">

**Steps to reproduce:**
> Create a ballerina project with test, and try running `ballerina test`. (I used the BBG, **[messaging-with-kafka](https://github.com/ballerina-guides/messaging-with-kafka)** for this.

**Affected Versions:**
> ballerina 0.990.0-RC1

**OS, DB, other environment details and versions:**
> OS: Mac OS

**Related Issues (optional):**
> N/A

**Suggested Labels (optional):**
> bug

**Comment by ChinthakaSenanayaka** [comment]
We could narrow down the bug scenario. If there is a module without tests (either with tests/ folder or not) and 1 module with tests. The module with tests is not picked and run by ballerina test command.

**Comment by ChinthakaSenanayaka** [comment]
@lankavitharana @hasithaa @NatashaWso2

We could further narrow down the issue. This happens because of loading all the SPIs in the project level since the "ballerina test" command was issued in the project level. SPIs are loaded at once and not as the modules running.

SPIs are loaded based on the import lines of the module. Thus, 1st module does not have test files and no "import ballerina/test". Therefore TestAnnotationProcessor compilerPlugin is not loaded as SPI for the project. Then later when 2nd module executes for tests, it does not catch any tests files and outputs no tests files found.

**Comment by ChinthakaSenanayaka** [comment]
This issue is fixed in PR #12760

**Comment by ChinthakaSenanayaka** [comment]
This issue is fixed in PR #12767

**Comment by lankavitharana** [comment]
PR https://github.com/ballerina-platform/ballerina-lang/pull/12767 merged, hence closing
