### ISSUE TITLE
Issue when the default worker has errored before sending to a worker

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#12700]
**Description:**
The following ballerina program hangs without exiting.
```ballerina
import ballerina/io;

(function () returns (int)) fa = function () returns (int) {
   return 3;
};

public function main () {
    var a = test1(5);
    test2();
    int a2 = fa.call();
}

function test1(int c) returns error|() {
    worker w1 returns int {
        int|error a = <- default;
        io:println("this line will never reach"); 
        return 8;
    }
    int b = 9;
    fa = function () returns (int) {
        return wait w1;
    };
    if (true) {
        error e = error("error occurred");
        return e;
    }
    b -> w1;
    return ();
}

function test2() {}

```

**Affected Versions:**
0.990.1-SNAPSHOT

**Comment by vinok88** [comment]
@NatashaWso2, Shouldn't we fail this code in compile time with error, `invalid worker send statement position, can not be used after a non-error return` ?
IMO, since we consider error also as a common return, we should not allow.
This error comes when this is only within the main function and not for others.

**Comment by Anoukh** [comment]
Closing the issue since the PR has been merged
