### ISSUE TITLE
When documenting an endpoint, it should document the __init()

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#12792]
Currently, https://ballerina.io/learn/api-docs/ballerina/http.html#Client documents the public member fields of the endpoint object. Not the parameters to `__init()` function.

**Comment by praneesha** [comment]
Closing as this is fixed in the new design as follows.

<img width="1209" alt="Screenshot 2019-12-10 at 14 53 26" src="https://user-images.githubusercontent.com/11707273/70516566-3860d500-1b5d-11ea-8069-ca7f8862ddb7.png">

**Comment by MaryamZi** [comment]
Reopening since this is still a valid issue. The original issue was that the docs for the `__init()` method are not displayed. 

For example, the docs for the `websub:PublisherClient`'s `__init()` method https://github.com/ballerina-platform/ballerina-lang/blob/v1.0.5/stdlib/websub/src/main/ballerina/src/websub/publisher_client.bal#L27 are not displayed. 

![client_init](https://user-images.githubusercontent.com/8376983/70686011-05d7e900-1cd1-11ea-84ca-461d9e7c6316.png)

The `__init()` documentation "Initializer function for the client." is not available here.

**Comment by praneesha** [comment]
The Init method description is missing even though, the  param descriptions are there.
