### ISSUE TITLE
Support returning multiple result sets from MySQL stored procedures

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#12804]
**Description:**
Currently only returning only one resultset is supported for MySQL. Need to $subject. Need to do as discussed in [1] 

[1] Issues in Streaming ResultSets returned from operations on MySQL database @ballerina-dev (https://groups.google.com/g/ballerina-dev/c/ur8sekIxPqg/m/znAW22tmBgAJ)

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/8643

**Comment by niveathika** [comment]
The same issue occurs for MSSQL too [[1](https://github.com/ballerina-platform/ballerina-lang/issues/24903)]. A temporary fix has been to return only the first result set from the results. 

This issue is fixed in SQL lib depended on Swan Lake and we will be returning multiple sets for both DBs for procedure call[[2](https://github.com/ballerina-platform/ballerina-lang/issues/24412)]
