### ISSUE TITLE
Improve error messages given when attempting to build/run a module without a b7a project

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#12883]
The following error is given when attempting to build a module without first initializing a Ballerina project.
```
error: did you mean to build the module ? If so build from the project folder
```
A couple of things regarding this error message.
1) Doesn't the first part of the message seem redundant? The user did run the build command.
2) In this particular case, I hadn't initialized a project. Can't we be specific and ask the user to initialize a project?

The error message you get when attempting to run a module without a initialized project is similar to the format above:
```
error: did you mean to run the module ? If so, either run from the project folder or use --sourceroot to specify the project path and run the module
```

**Comment by NatashaWso2** [comment]
Closing this issue since it was fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12946

**Comment by suhand** [comment]
Thank you for logging this issue. 
We have some legacy ballerina services running on V0.983. These systems went live years back.
Recently we tried to alter the services and we have forgotten to run the `ballerina init` part before building/running the ballerina project (since this step is not there anymore in latest ballerina versions). Therefore we came across the above mentioned awkward error.
This saved lot of our time.
