### ISSUE TITLE
Goddamn weird things happen with closure, anydata type and functional iteration

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#12910]
**Description:**
This was literally driving me crazy 😱 

Code below makes the compiler crash with bad sad error
````ballerina
public function main() returns () {
    string criteria = "";
    int[] n = [1, 2, 3];
    anydata[] array = n.map(function (anydata obj) returns anydata { 
        _ = <int>obj;
        _ = criteria;
        return obj;
    });
}
````
But that's not all. Just change the type of `criteria` from `string` to `json` like that

````ballerina
public function main() returns () {
    json criteria = {};
    int[] n = [1, 2, 3];
    anydata[] array = n.map(function (anydata obj) returns anydata { 
        _ = <int>obj;
        _ = criteria;
        return obj;
    });
}
````
This code compiles but you get the runtime error below
````
error: {ballerina}TypeAssertionError {"message":"assertion error: expected 'int', found '()'"}
        at $lambda$0(test_closure.bal:5)
           $lambda$iterable0(test_closure.bal:4)
           main(test_closure.bal:4)
````

**Affected Versions:**
0.990.1-SNAPSHOT (Dec 20, 2018)

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**
Not sure, maybe #9354

**Suggested Labels (optional):**
Component/Compiler, Component/BVM, Type/Bug

**Comment by pubudu91** [comment]
Yes, you are correct. #9354 is the same issue as this (or at least a variant, considering all the recent changes). And so is #10149. However, the crash in the first case seems to be an issue unrelated to the original problem with closures and iterable ops. It seems to be an issue with the primitive types. That's why the second one is working (since `json` is a reference type). And that assertion error seems to only occur when the line `_ = criteria;` is present. When it was commented out, the 2nd program worked as expected. Definitely need to take a closer look at the iterable ops.

**Comment by davebaol** [comment]
Yep, that's exactly what I meant by "goddamn weird" 😄
