### ISSUE TITLE
[Spec Deviation] The detail mapping value of an error type should be a frozen value

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13171]
**Description:**
As per the spec (v0.990:2019-01-16) "An error value contains the following information: 
a detail, which is a frozen mapping providing additional information about the error"

Currently, the detail map is not frozen
```ballerina
@test:Config {
    groups: ["broken"]
}
function testErrorTypeDescriptorBroken() {
    error <string, map<anydata>> error1 = error("Error Three", { cause: "Core Error" });
    error1.detail().stacktrace = "xyz"; // Should fail
}
```
**Affected Versions:**
0.990.2

**Comment by MaryamZi** [comment]
As per the error constructor expression section,
```
The result of evaluating detail-expr is cloned using the Clone abstract operation 
and then frozen using the Freeze abstract operation.
```

This depends on
- https://github.com/ballerina-platform/ballerina-lang/issues/13205 since the detail needs to be restricted to pure value to allow freeze/clone
- https://github.com/ballerina-platform/ballerina-lang/issues/14480 since we need to be able to clone and freeze a map/record with errors
