### ISSUE TITLE
Behavior missmatch between type test and type assertion for nil json

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#13237]
**Description:**
In following program, type test interpret ```()``` as a json yet type assertion interpret it as not json.

```ballerina
public function main(string... args) {
    json j = ();
    any aj = j;
    if (aj is json) {
        io:println("it's json");
        json ja = <json>aj;
        io:println(ja);
    }
}
```

Error msg:
```
error: {ballerina}TypeAssertionError {"message":"assertion error: expected 'json', found '()'"}
```

Affected version 0.990.2

**Comment by MaryamZi** [comment]
With type assertion in 0.990.2, we check for an exact match of type. Thus even though we assign the `nil` value to a `json` typed variable, type assertion would fail since the actual basic type of the value is still `nil`.

With https://github.com/ballerina-platform/ballerina-lang/pull/13161 we are re-introducing the type cast expression instead of type assertion/explicitly typed expressions. With this change, `<json>aj` would not fail, since we will be checking if the type of the value (`()` here) belongs to the type being cast to (`json`) - which will evaluate to true.

The output would be as follows:
```cmd
$ ballerina run nil_json_test.bal
it's json


```
