### ISSUE TITLE
[Auth] Removing auth providers at HTTP service config and resource config

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#13327]
**Description:**
Auth providers can be engaged in HTTP service configuration and resource configuration other than the HTTP listener configuration. It is seemed to be meaningless when the auth providers are engaged in service level and resource level.

The following record is added to both configs in `http/annotations.bal`.

```ballerina
public type ListenerAuthConfig record {
    Authentication? authentication = ();
    string[]? authProviders = ();
    string[]? scopes = ();
    !...;
};
```

**Affected Versions:**
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Comment by ayomawdb** [comment]
It is possible to define:
* which auth-provider-ids should be be used to authenticate each service/resource.
* which scopes should be validated per service / per resouce 
* whether authentication should be enabled for individual service / resource 

Hence, this configuration is required to provide the necessary flexibility. Please let me know if you find otherwise.

**Comment by ayomawdb** [comment]
@ldclakmal I'm working on cleaning up the auth issues. Let's re-open if there is a concern out of the points I highlighted.

**Comment by ldclakmal** [comment]
@ayomawdb I agree on the highlighted points, but my concern is only regarding the 1st point.

If we define `basicAuthProvider`, `jwtAuthProvider1` and `jwtAuthProvider2` and engage
- `basicAuthProvider` into listener
- `jwtAuthProvider1` into service config
- and `jwtAuthProvider2` into resoure config

what should be the expected behaviour?

A sample program for above use case is as follows:

```ballerina
import ballerina/http;

http:AuthProvider basicAuthProvider = {
    scheme: "basic",
    authStoreProvider: "config"
};

http:AuthProvider jwtAuthProvider1 = {
    id:"jwtAuthProvider1",
    scheme:"jwt",
    issuer:"ballerina",
    audience: "ballerina.io",
    certificateAlias: "ballerina",
    trustStore: {
        path: "${ballerina.home}/bre/security/ballerinaTruststore.p12",
        password: "ballerina"
    }
};

http:AuthProvider jwtAuthProvider2 = {
    id:"jwtAuthProvider2",
    scheme:"jwt",
    issuer:"ballerina",
    audience: "ballerina.io",
    certificateAlias: "ballerina",
    trustStore: {
        path: "${ballerina.home}/bre/security/ballerinaTruststore.p12",
        password: "ballerina"
    }
};

listener http:Listener ep = new(9090, config = {
        authProviders: [basicAuthProvider],
        secureSocket: {
            keyStore: {
                path: "${ballerina.home}/bre/security/ballerinaKeystore.p12",
                password: "ballerina"
            }
        }
    });

@http:ServiceConfig {
    authConfig: {
        authProviders: ["jwtAuthProvider1"]
    }
}
service hello on ep {

    @http:ResourceConfig {
        authConfig: {
            authProviders: ["jwtAuthProvider2"]
        }
    }
    resource function sayHello(http:Caller caller, http:Request req) {
        _ = caller->respond("Hello, World!!!");
    }
}
```

**Comment by ayomawdb** [comment]
Great example! I got your point. 

Resource level configurations override service level configurations. Check [1], which will talk for itself. IMO this is the correct approach, since user gets the flexibility to use a different authenticator for selected resource. 

Totally agreed that this need to be documented. Shall we create an issue in www repo [3], so that we can add this to [2].

[1] https://github.com/ballerina-platform/ballerina-lang/blob/fa889af7e31e98e129c5093f59fdc65897ad51a6/stdlib/http/src/main/ballerina/http/auth/authn_filter.bal#L99
[2] https://ballerina.io/learn/how-to-write-secure-ballerina-code/
[3] https://github.com/ballerina-platform/ballerina-www

**Comment by ldclakmal** [comment]
Thanks, @ayomawdb for the explanation. I created an issue [1] to track the documentation improvement.

[1] https://github.com/ballerina-platform/ballerina-www/issues/1370
