### ISSUE TITLE
VSCode plugin seems to fail when trying to open ballerina module in stdlib in the language

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#13740]
**Description:**
Tried opening std lib module in VSCode, but there were no support from the plugin once it's opened.

**Steps to reproduce:**
Open ballerina folder inside src/main folder in the stdlib module. (tried doing project init as well) still the same issue. 

**Affected Versions:**
0.990.3

**Comment by roonyh** [comment]
In which stdlib submodule did this occur? Tried opening up few modules like auth, bir and builtin and the extension worked as expected. I get completions and diagnostics.

**Comment by lankavitharana** [comment]
I tried bir module

**Comment by nadeeshaan** [comment]
When building a module which is packed with the ballerina distribution, compiler fails with a class cast exception (log attached herewith). Due to this reason, the 
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2887874/ballerina-internal.log)
plugin fails to provide the suggestions.

**Comment by rasika** [comment]
Analyzed the error log;

``` 
org.wso2.ballerinalang.compiler.GenericPackageBinary cannot be cast to org.ballerinalang.repository.PackageSource 
```
Seems like we have an unchecked cast to `PackageSource`. On the other hand; checking `instanceOf` will be costly for micro level performance concerns.

How about writing a compiler plugin to warn user, when his source code's orgName/alias conflicts with internally packed stdlibs. This will be beneficial for the tooling as well since compilation errors causes completions, definitions...etc fails without a user information.

**Comment by hasithaa** [comment]
This is fixed in SL.
