### ISSUE TITLE
VSCode does not break at 120 characters on formatting

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#13867]
**Description:**
Formatting of a Ballerina VSCode file does not break at 120 characters while the intellij plugin does.

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/13862

**Comment by NipunaMarcus** [comment]
This will be implemented as a diagnostic provided by the Ballerina Linter. So instead of breaking from 120 characters, we will be providing a warning to the user that line is exceeding the max line length. I will attach this issue to the linter as a tracking point but we won't be breaking lines which are exceeding 120 lines with the formatting tool. We are planning to provide a code action to incorporate quick fixes to the linter issues and breaking the lines also will be a part of that. 

I'm closing this issue as this will be related to the Linter implementation.
