### ISSUE TITLE
cannot resolve module 'wso2/github4'

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#13957]
**Description:**

I am unable to import the github4 module from Ballerina central.

**Steps to reproduce:**
Create a ballerina file and try to import wso2/github4
**Affected Versions:**

**OS, DB, other environment details and versions:**
MacOS, Ballerina v0.990.2

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
@arunans23 since you have not specified a version for module github4 the build command will try to pull the latest version of the module from Ballerina Central. But the latest version of the github4 module in Ballerina Central is not compatible with your ballerina version. 

As of now the build command will try to pull the latest version of the module in Ballerina Central regardless of the ballerina version of the user. This is an issue that needs to be and is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/13519.

For now you can specify the module version compatible with your ballerina version in the `Ballerina.toml` as below:
[dependencies."wso2/github4"]
version= "0.9.19"

**Comment by NatashaWso2** [comment]
@arunans23 this issue has been fixed with https://github.com/wso2/ballerina-registry/pull/271. Now 'ballerina pull' command will pull the latest version of the module compatible with your ballerina version. Hence closing this issue.
