### ISSUE TITLE
Improvement to remote function invocation

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#13981]
**Description:**
Let's say I have a function bigqueryClient() which returns a client object. 

This code works;
bigquery2:Client bqClient = bigqueryClient();      
var listProjectsResponse = bqClient->listProjects();

The following should work too right?
var listProjectsResponse = bigqueryClient()->listProjects();

It is failing with "Invalid remote function invocation, expected an client object"

**Comment by hasithaa** [comment]
@sanjiva @hevayo @kaviththiranga We didn't allow this because we can't render the diagram for this particular scenario. But 2019R1 spec allows this.

One possible solution is we generate an anonymous endpoint (maybe with the function name) and create an arrow to it. But this only works with generating the diagram. The diagram to code will not work.

**Comment by hevayo** [comment]
@hasithaa Basically what you mention is if a function returns a client object consider it as an endpoint. Which we can do.

**Comment by sanjiva** [comment]
@hevayo how do we render that? I guess we don't bother drawing a vertical line for that .. there's no point because only one action is possible on that remote object anyway.

**Comment by hevayo** [comment]
@sanjiva Yes, it will be an endpoint line with one action going to it. I guess even though it is only one action it will improve the readability of the diagram since the user can clearly see the program is doing a remote call.  For the name of the endpoint we can use the endpoint type and the name of the function ( which can be weird ).

If a function returns a client object can we consider it as a refrence to that client object ?

**Comment by hasithaa** [comment]
This is not supported by the spec. Refer: https://ballerina.io/ballerina-spec/spec.html#action

> Actions are an intermediate syntactic category between expressions and statements. Actions are similar to expressions, in that they yield a value. However, an action cannot be nested inside an expression; it can only occur as part of a statement or nested inside other actions. This is because actions are shown in the sequence diagram in the graphical syntax.

Hence closing this issue.
