### ISSUE TITLE
XML type isn't support when the tag is start with "_-"

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#14106]
**Description:**
XML type isn't support when the tag is start with "_-"

**Steps to reproduce:**
`xml content = xml  `<_-DSD_-ROUTEACCOUNT_CORDER002></_-DSD_-ROUTEACCOUNT_CORDER002>` ;`

`ballerina run sap_idoc_producer.bal`
`error: .::sap_idoc_producer.bal:33:21: token recognition error at: '_'
error: .::sap_idoc_producer.bal:33:22: token recognition error at: '-'`

**Affected Versions:**
0.990.3

**Suggested Labels:**
Type/Improvement

**Comment by NatashaWso2** [comment]
@kalaiyarasiganeshalingam according to the W3C XML Recommendation a xml tag can start only from    
"[a-zA-Z_] " [1]. 

We have allowed a tag to be started with '_' since it is allowed in the W3C XML  specification with https://github.com/ballerina-platform/ballerina-lang/pull/14164. But starting a tag with '-' is not allowed according to the W3C XML  specification.

[1] [https://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameStartChar](https://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameStartChar)
