### ISSUE TITLE
100-continue support for HTTP client

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#14647]
**Description:**
This support is required when client wants to check whether request body will be accepted by server before sending the body.

This is achieved by setting "Expect: 100-continue" request header. Server will respond with status line "100 Continue HTTP/1.1" if request headers are fine, or with actual full response if something goes wrong. Client should not send body if response was not "100 Continue HTTP/1.1"

**Comment by shafreenAnfar** [comment]
Let's start with only forward action first.

**Comment by Bhashinee** [comment]
Above PR will stop passing the 100-continue response to the Ballerina client. Instead, it will only pass the final response. 

**Things remaining to be fixed:** 
- Currently, the client sending the 100-continue request does not wait for the 100-continue response to proceed with sending the payload. The client sends the payload along with the 100-continue request itself. In order to get the proper advantage of 100-continue, the client should wait for a little before sending the payload.
- Better to make the waiting period configurable as the client does not need not wait indefinitely if the server does not send the 100-continue response. (In curl, default waiting time is 1 sec.)

**Comment by shafreenAnfar** [comment]
This has been fixed in transport.
