### ISSUE TITLE
Incorrect handling of BIT data in SQL Data Connectors

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#14710]
**Description:**
$subject in data connectors.

In SQL Server bit contains a boolean or null [1]. But in MySQL it is different.

In mysql a type of BIT(M) enables storage of M-bit values. M can range from 1 to 64. [2]
So if BIT(1) it should get mapped to boolean, if BIT(> 1) it should get mapped to byte[] [3]
But currently both cases match into boolean which is incorrect. We need to use GetColumnClassName to get the exact type.

[1] http://www.sqlservertutorial.net/sql-server-basics/sql-server-bit/
[2] https://dev.mysql.com/doc/refman/8.0/en/bit-type.html
[3] https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html

**Steps to reproduce:**

```ballerina
import ballerina/io;
import ballerina/mysql;
import ballerina/sql;
mysql:Client testDB = new({
    host: "localhost",
    port: 3306,
    name: "",
    username: "test",
    password: "test",
    poolOptions: { maximumPoolSize: 5 },
    dbOptions: { useSSL: false }
});

type BitTypes record {
    int id;
    boolean bitVal1;
    boolean bitVal2; //This should be a byte[]
};

public function main(string... args) {
    createDatabase();
    var ret = testDB->update("CREATE TABLE testdb.bittypes(
        id INT,
        bitVal1 BIT(1),
        bitVal2 BIT(2),
        PRIMARY KEY (id)
    )");
    handleUpdate(ret, "Create bittypes table");

    ret = testDB->update("INSERT INTO testdb.bittypes(
                            id, bitVal1, bitVal2
                        ) VALUES (
                            1, b'0', b'10' )");

    var selectRet = testDB->select("Select  id, bitVal1, bitVal2 from testdb.bittypes", BitTypes);
    if (selectRet is table<BitTypes>) {
        int index = 0;
        foreach var row in selectRet {
            io:println(row.id);
            io:println(row.bitVal1);
            io:println(row.bitVal2);
        }
    } else {
        io:print("ERROR OCCURED!!!:");
        io:println(selectRet);
    }                        
    dropDatabase();
}

function createDatabase() {
    var ret = testDB->update("CREATE DATABASE testdb");
    handleUpdate(ret, "Create database testdb");
}

function dropDatabase() {
    var ret = testDB->update("DROP DATABASE testdb");
    handleUpdate(ret, "Drop Database testdb");
}

function handleUpdate(sql:UpdateResult|error returned, string message) {
    if (returned is sql:UpdateResult) {
        io:println(message + " status: " + returned.updatedRowCount);
    } else {
        io:println(message + " failed: " + <string>returned.detail().message);
    }
}

```
**OUTPUT**
```
Create database testdb status: 1
Create bittypes table status: 0
1
false
true
Drop Database testdb status: 1
```

Similarly we should be able to insert byte[] as a direct parameter in the form of a byte[] or as a sql:Parameter. Need to check on the other usage of this column (ex : in / out parameters of call method) 

```ballerina
    int id = 2;
    boolean bitVal1 = true;
    byte[] bitVal2 = [1, 2];
    ret = testDB->update("INSERT INTO testdb.bittypes(
                            id,
                            bitVal1,
                            bitVal2
                        ) VALUES (
                            ?,
                            ?,
                            ?
                        )", id, bitVal1, bitVal2);
```
**Affected Versions:**
0.990.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Biruntha** [comment]
When I run the above provided sample with mysql-connector-java-5.1.39.jar version, bitVal2 column is correctly mapping to the byte[] data type. Here, when we get the getColumnType from sql ResultSetMetaData [1], it returns column type as -3 which will get mapped to VARBINARY ballerina data type [2]. With this connector jar version, I could be able to run the above ballerina sample with the following struct definition.
```
type BitTypes record {
    int id;
    boolean bitVal1;
    byte[] bitVal2;
}; 
```
But when I use latest mysql-connector-java-8.0.16.jar, bitVal2 column is mapping to boolean. Here, when we get the getColumnType from sql ResultSetMetaData [1], it returns column type as -7 which will get mapped to BIT data type in ballerina [3] and return it as BOOLEAN type. With this connector jar version, BitTypes struct definition will be as below. And even if we use GetColumnClassName to get the exact type, it returns java.lang.Boolean as the type for bitVal2 column.
```
type BitTypes record {
    int id;
    boolean bitVal1;
    boolean bitVal2;
}; 
```
In order to check this futher, I have try out the small sample in java as in [4]. Following are the result outcome of ColumnType, ClassName, ColumnTypeName values from sql ResultSetMetaData for version 5.1.39 as in [5] and version 8.0.16 as in [6].

[1] https://github.com/ballerina-platform/ballerina-lang/blob/v0.991.0/stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDatasourceUtils.java#L1681
[2] https://github.com/ballerina-platform/ballerina-lang/blob/v0.991.0/stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDatasourceUtils.java#L973
[3] https://github.com/ballerina-platform/ballerina-lang/blob/v0.991.0/stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDatasourceUtils.java#L962
[4]
```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

public class GetAllColumnNames {
    public static void main(String[] args) {
        String JdbcURL="jdbc:mysql://localhost:3306/testdb?useSSL=false";
        String Username="root";
        String password="root";
        Connection con;
        Statement stmt;
        ResultSet rs;
        try {
            con = DriverManager.getConnection(JdbcURL, Username, password);
            stmt=con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM bittypes");
            ResultSetMetaData md = rs.getMetaData();
            int counter = md.getColumnCount();
            String colName[] = new String[counter];
            System.out.println("The column names are as follows:");
            for (int loop = 1; loop <= counter; loop++) {
                colName[loop-1] = md.getColumnLabel(loop);
                System.out.println("############ColumnName######### " + colName[loop-1]);
                System.out.println("ColumnType " + md.getColumnType(loop));
                System.out.println("ClassName " + md.getColumnClassName(loop));
                System.out.println("ColumnTypeName " + md.getColumnTypeName(loop));
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
```
[5]
```
The column names are as follows:
############ColumnName######### id
ColumnType 4
ClassName java.lang.Integer
ColumnTypeName INT
############ColumnName######### bitVal1
ColumnType -7
ClassName java.lang.Boolean
ColumnTypeName BIT
############ColumnName######### bitVal2
ColumnType -3
ClassName [B
ColumnTypeName BIT
```
[6]
```
The column names are as follows:
############ColumnName######### id
ColumnType 4
ClassName java.lang.Integer
ColumnTypeName INT
############ColumnName######### bitVal1
ColumnType -7
ClassName java.lang.Boolean
ColumnTypeName BIT
############ColumnName######### bitVal2
ColumnType -7
ClassName java.lang.Boolean
ColumnTypeName BIT
```
