### ISSUE TITLE
Gradle build doesn't fail when there is an exception in test setup

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#14827]
**Description:**
Gradle build doesn't fail when there is an exception in test setup

**Steps to reproduce:**
Throw a RuntimeException form https://github.com/ballerina-platform/ballerina-lang/blob/8c16ac850c27fe5883e004e9bef0a8dbde424830/stdlib/bir/src/test/java/org/ballerinalang/stdlib/io/bir/TypeGenTest.java#L82

It should fail the build

**Comment by Anoukh** [comment]
Build passes for maven build as well. This is because the runtime exception happens in the data provider, which does not fail the test. [This post](http://rolf-engelhard.de/2011/10/fail-instead-of-skip-a-test-when-testngs-dataprovider-throws-an-exception/) gives some solutions for this case. Shall we adopt one of these?

**Comment by manuranga** [comment]
Thanks Anoukh, fixed it that way.

**Comment by Anoukh** [comment]
Closing the issue since it is resolved.
