### ISSUE TITLE
Support Multiple Trusted JWT Issuers in JWT Validator

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#14966]
**Description:**
In the current design of the b7a jwt authenticator, we can use the config API to provide information about one trusted issuer as below. There should be way to validated jwts from multiple issuers rather than validating from a single issuer.

**Steps to reproduce:**
https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.3/stdlib/internal/src/main/ballerina/internal/jwt_validator.bal#L279

**Affected Versions:**
0.990.3

**Related Issues (optional):**
https://github.com/wso2/product-microgateway/issues/271

**Comment by ldclakmal** [comment]
Yes. Agree with your concern.

As of now, we have validated JWT with a single issuer, with the idea of JWTs are signed with different providers with the use of different certificates. Therefore, what we have allowed is to create separate JWT providers for each issuer (possibly with different certificates or same). 

Since your requirement is to validate multiple issuers using the same signing certificate, it is true that we can provide better support with the next release.

**Comment by ldclakmal** [comment]
Supporting multiple trusted JWT issuers may lead to a security issue.

Suppose there is a requirement to validate a token against either one of the issuer, audience couple of (I1, A1) and (I2, A2).
So, now the user has to configure 2 providers with the above validator configurations. If the receiving token is issued for the (I1, A2) issuer, audience couple, this will get failed.

But if we provide support for configuring multiple issuers, then the user can configure issuer, audience couple as [ (I1, I2), (A1, A2) ] in order to validate for the same requirement, but with a single provider.
Now, If the receiving token is issued for the (I1, A2) issuer, audience couple, this will get passed.

Please reopen this issue, if there are any concerns.
