### ISSUE TITLE
VSCode adding unnecessary space when formatting

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#15264]
**Description:**
I have a function as follows:
```
public function __start() returns error? {
        return self.start();
}
```
When I format this using VSCode an unncessary space is added between self and start 
```
public function __start() returns error? {
        return self. start();
}
```
**Steps to reproduce:**
Format the above function using VSCode formatter

**Affected Versions:**
0.991

**OS, DB, other environment details and versions:**
Ubuntu 19.04

**Related Issues (optional):**
Mentioned the same in a mail: https://groups.google.com/d/msg/ballerina-dev/Ayv1J9QdI0s/57e6W5QdCgAJ

**Comment by NipunaMarcus** [comment]
This is happening because of "start" is a reserved word in Ballerina. In this scenario, the formatter catch this keyword and format as to the guide by adding single space before "start". But apparently Reserved word can be used as identifiers in other contexts and the formatter has no knowledge of this.
