### ISSUE TITLE
The performance of jBallerina M4 is nowhere near existing BVM for HTTP serving

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#15528]
from https://github.com/pzfreo,

**1) I had some trouble killing the jballerina process when running an HTTP endpoint:**

Java HotSpot(TM) 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated

It seems to have created a *lot* of threads:

**2) The performance is nowhere near existing BVM for HTTP serving:**

Existing BVM:
 wrk -t 4 -c 100 -d 60s  http://localhost:9090/hello/paul
Running 1m test @ http://localhost:9090/hello/paul
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    37.81ms   56.45ms 458.53ms   85.14%
    Req/Sec     2.09k   685.49     4.12k    70.01%
  496677 requests in 1.00m, 70.58MB read
  Socket errors: connect 0, read 0, write 1, timeout 0
**Requests/sec:   8272.57**

jBallerina M4
 wrk -t 2 -c 100 -d 30s  http://localhost:9090/hello/paul
Running 30s test @ http://localhost:9090/hello/paul
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    68.33ms   47.03ms 476.89ms   72.48%
    Req/Sec   466.32    186.73     0.95k    71.77%
  21345 requests in 30.08s, 3.28MB read
  Socket errors: connect 0, read 5945, write 0, timeout 0
**Requests/sec:    709.50**

**Comment by SupunS** [comment]
This is fixed in jballerina-m5 release.
Below are some perf test results:

**Echo Service**
---
**Existing BVM(0.991.0):**
Running 1m test @ http://localhost:9092/hello/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.27ms   21.60ms 481.85ms   96.31%
    Req/Sec     5.22k     1.68k    7.58k    74.48%
  1240449 requests in 1.00m, 169.17MB read
Requests/sec:  20665.97
Transfer/sec:      2.82MB

**jBallerina** 
Running 1m test @ http://localhost:9092/hello/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    86.76ms  257.45ms   1.72s    90.68%
    Req/Sec     8.51k     3.48k   12.66k    66.72%
  1622048 requests in 1.00m, 239.77MB read
  Socket errors: connect 0, read 0, write 0, timeout 100
Requests/sec:  27019.46
Transfer/sec:      3.99MB

**Passthrough service**
---
**Existing BVM(0.991.0):**
Running 1m test @ http://localhost:9090/passthrough/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.20ms   26.91ms 498.68ms   93.70%
    Req/Sec     1.69k   608.98     2.72k    61.79%
  401925 requests in 1.00m, 54.81MB read
Requests/sec:   6693.72
Transfer/sec:      0.91MB

**jBallerina** 
Running 1m test @ http://localhost:9090/passthrough/
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    34.92ms  126.72ms   1.37s    96.08%
    Req/Sec     2.28k     1.05k    4.45k    59.26%
  516153 requests in 1.00m, 76.30MB read
Requests/sec:   8597.65
Transfer/sec:      1.27MB
