### ISSUE TITLE
Remove 'compileOnBVM()' method in jballerina tests

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#15937]
**Description:**

Some of the tests uses compileOnBVM() during running tests in jballerina. Anything related to BVM shouldn't be used when migrating to JBallerina, as they are broken and no longer maintained. These will be removed soon.

**Comment by MaryamZi** [comment]
#15884 introduces some of the changes required for this.
- `BRunUtil.invoke()` accepting an `Object[]` for JVM values, instead of `BValue[]` - https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-3cf110e99a490c3490255df187a03265R268 
- This makes use of a private method that returns the JVM param type class based on the object - https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-3cf110e99a490c3490255df187a03265R272 - currently only identifies `ObjectValue`, `XMLValue` and `String`
- `BRunUtil.invokeOnJBallerina()` and `BRunUtil.invoke()` accepting an `Object[]` and `Class<?>[]` instead of BVM values and types - https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-3cf110e99a490c3490255df187a03265R307, https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-3cf110e99a490c3490255df187a03265R372

The corresponding BVM based methods have been marked deprecated.

The following have also been migrated
- test/java/org/ballerinalang/stdlib/mime/Util.java
- test/java/org/ballerinalang/stdlib/utils/MessageUtils.java
- test/java/org/ballerinalang/stdlib/utils/MultipartUtils.java
- test/java/org/ballerinalang/stdlib/utils/TestEntityUtils.java

A new utils class was introduced to create JVM object values for HTTP - test/java/org/ballerinalang/stdlib/utils/ValueCreatorUtils.java

**Comment by SupunS** [comment]
`compileOnBVM()` method and its usages are removed, and only migrating the remaining BVM values related references from the test cases is left. Since the original issue is fixed and the later is already tracked by #17443, I'm closing this one.
