### ISSUE TITLE
Enable tuple related tests

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#16094]
**Description:**

Need to enable the following tests packages.
 - org.ballerinalang.test.statements.variabledef.*
 - org.ballerinalang.test.statements.matchstmt.*
 - org.ballerinalang.test.expressions.varref.TupleVariableReferenceTest. testNegativeTupleVariablesReferences()
 - org.ballerinalang.test.taintchecking.TaintedStatusPropagationTest.testIterableWitinIterable()
 - org.ballerinalang.test.taintchecking.TaintedStatusPropagationTest.testIterableWitinIterableNegative()

However, with the new tuple syntax, there are few issues in the compiler front end with related to tuples. For eg, unhandled exceptions such as ClassCastExceptions are thrown, type checking fails and semantic errors are thrown for valid scenarios, types of certain expressions are null, etc.. These needs to be fixed to enable the test cases

I fixed most of the syntax changes in match-statement-tests, and is available in the branch: https://github.com/SupunS/ballerina/tree/match-tests

**Comment by grainier** [comment]
Fixed in following commits;

- `org.ballerinalang.test.statements.variabledef.*` 2f6801aa53d7e6c159d5404845460be6e6dc8e24

- `org.ballerinalang.test.statements.matchstmt.*` 37e8eee80b8fb4295714ce1b18cc61d0cf2d26fb

- `org.ballerinalang.test.expressions.varref.*` 98143f0a7354c4a7de9a7041b5c3f3db344da68d

- `org.ballerinalang.test.taintchecking.*` c2d380ac562c563b3d0073833a02b6b5d41e1348
