### ISSUE TITLE
Type checking issue for union types: (json|error) cannot be assigned to (any|error)

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#16542]
**Description:**
```ballerina
import ballerina/io;

public function main() {
    io:StringReader reader = new("some words without quotes");
    io:println(reader.readJson());
}
```

Above gives a compile time error:
```
error: .::testMain.bal:21:16: incompatible types: expected '(any|error)', found '(json|error)'
```

**Comment by SupunS** [comment]
seems the issue is with error:

```ballerina
    if(x is json) {
        io:println(x);
    } else {
        io:println(x);    // gives error "incompatible types: expected '(any|error)', found 'error'"
    }
```

**Comment by pubudu91** [comment]
This is because the error returned from `readJson()` is `IOError` which has a record for its detail while the builtin error has a map for its detail. This should work once the lang lib related changes are merged to master since the builtin error detail type was changed to a record type in that branch.

**Comment by SupunS** [comment]
Works in the master
