### ISSUE TITLE
ArrayValue.append() method should check type before add the value

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#17075]
**Description:**
JBallerina `ArrayValue` `append(Object value)` method should check the type of the value before calling `add()`. It throws an error otherwise.

**Steps to reproduce:**
Create an ArrayValue variable as follows and call append method:

```java
String sample = "Sample";
ArrayValue arrayValue = new ArrayValue(new BArrayType(BTypes.typeString));
arrayValue.append(sample);
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
Hi,
This can be done, by using,
```
ArrayValue arrayValue = new ArrayValue(BTypes.typeString);
```
We should not do such type checking in the runtime due to perf concerns. Compiler guarantees that there is no such type issue. In this scenario, you are using the runtime classes outside of the compiler. Hence the caller should make sure they are invoked in type safely.

Please reopen if required.
