### ISSUE TITLE
Old tuple syntax not throwing an appropriate error message

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#17080]
**Description:**
When the user defines a tuple using the old syntax (syntax used before Ballerina M7 release), the compiler is not throwing an appropriate error message.

**Steps to reproduce:**
1. Create a module called `hello` and add below code to `main.bal`.
```ballerina
import ballerina/io;

public function main() {
    (int, string) a = (10, "John");
    io:println(a);
}
```
2. Run the hello module. Then you will see the following error message which does not describe the reason for the error.
```
error: pramodya/xxx:0.1.0::main.bal:6:9: invalid token ','
```

**Affected Versions:**
Ballerina version

Ballerina 0.992.0-m2-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
This is expected since the new grammar takes `(` as a starting point of a grouping. And within groupings, we cannot have `,`. Hence this error will occur. 

Further, we cannot have exact error messages for migrated syntaxes (i.e use `[]` instead of `()` for list constructors), when the old grammar (i.e `()`) still matches a new semantic (i.e grouping). It's sort of a limitation in the grammar.
