### ISSUE TITLE
Hide VisitMax, VerifyError and other JVM codegen related issues with proper error message

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#17449]
**Description:**
Hide VisitMax, VerifyError and other JVM codegen related issues with proper error message. User should not see them.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Reopening this issue, since the generated class verification is currently disabled due to test failures. These tests fails are BALO tests, where other modules are imported, and those are not in the class path. Hence the verification fails due to ClassNotFound issues. These should enabled once the unit tests are configured to run with the uber-jar.

However, VisitMax and other JVM codegen related errors are hidden from user now.

**Comment by SupunS** [comment]
Closing this issue since the original concerns are addressed. Created a separate issue https://github.com/ballerina-platform/ballerina-lang/issues/18503 for the verification improvement.
