### ISSUE TITLE
Array of Table value is not validating with table<record {}>[] type check

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-lang#17462]
**Description:**
$subject observed when running H2ClientActionsTest.testCall.
```
var ret = testDB->call("{call JAVAFUNC('select * from Customers where customerId=1')}", [Customer]);
table<record {}>[] dts = [];
    if (ret is table<record {}>[]) {
        dts = ret;
    } else if (ret is ()) {
        return "nil";
    } else {
        error e = ret;
        return <string> e.detail()["message"];
    }
```
Even this call function is returning array of tables, for the if (ret is table<record {}>[]) {} check this checkIsType [1] method is returning false. 

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java#L139

**Affected Versions:**
1.0.0-alpha

**Comment by MaryamZi** [comment]
In offline discussions with @anupama-pathirage and @gimantha it was decided to fix this on the standard library side.

There are a couple of issues here.

1. For arrays of tables returned from actions, an incorrect type seems to have been set in some places. 
https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/CallStatement.java#L143

```ballerina
ArrayValue bTables = new ArrayValue(BTypes.typeTable);
```
The type of the array value should have an array type here.
```ballerina
ArrayValue bTables = new ArrayValue(new BArrayType(BTypes.typeTable));
```

2. The `typeTable` in `BTypes.java` has an `anydata` constraint (https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java#L46).

Thus, using `tb is table<record {}>` like it was done before where `tb` is returned from an action, fails now since this is checking if a `table<anydata>` is a `table<record {}>`.

The solution is:
- create a new `BRecordType` with an `anydata` rest field only
- create a new `BTableType` with the above record type as the constraint
- use that table type, instead of the one defined in BTypes.java, for tables returned from actions
