### ISSUE TITLE
Suggestions not working when accessing an array element

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17775]
Refer to the image below
![Screenshot from 2019-08-15 16-47-33](https://user-images.githubusercontent.com/6260009/63091620-8d5c5800-bf7c-11e9-83e0-b02969f0633d.png)

**Comment by nadeeshaan** [comment]
This is a known limitation where there are two syntax errors in the code and the current source pruner cannot handle that without the grammar help. When getting the completions, it is expected to have only one syntax error and it should be at the cursor. In order to get the completions, please add the semicolon after }

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
