### ISSUE TITLE
[Authentication Filter] Authentication filter improvements

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#18356]
**Description:**
Ballerina checks whether the resources are secured by reading the resource level and service level annotations[1]. But it is better if we can get that detail to outside, so developers can know the resource is secured or not. My suggestion is to add whether the service/resource is secured or not into the invocation context, so developers can use that value.

[1] - https://github.com/ballerina-platform/ballerina-lang/blob/v1.0.0-alpha3/stdlib/http/src/main/ballerina/src/http/auth/utils.bal#L107-L124
**Steps to reproduce:**

**Affected Versions:**
1.0.0-alpha3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
As discussed, adding a flag to invocation context saying the calling resource is secured or not does not make sense, since the any of the filters that get invoked after authn filter, is get invoked if and only if the authn filter get succeeded. So, as an alternative, we will provide an API to check the calling resource is secured or not.
```ballerina
public function isResourceSecured(FilterContext context) returns boolean;
```
