### ISSUE TITLE
Revisit XML iterations

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#18390]
**Description:**
"In the xml module, there seems to be a misconception about how map, filter, etc work. They should iterate over their first argument in the same was as iterator, and should not access element children."

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Can we get a example of expected behavior?
`map` implementation over xml for instance seems to just do the described already.
[https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Map.java](https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Map.java)

**Comment by rdhananjaya** [comment]
Gett invalidated with new xml proposal.
