### ISSUE TITLE
NPE when running ballerina project

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#18431]
**Description:**
I have a project source (project.zip) and a module called gateway(src.zip). The project creates an executable jar file and the project imports(ballerina import)
[project.zip](https://github.com/ballerina-platform/ballerina-lang/files/3566035/project.zip)
[src.zip](https://github.com/ballerina-platform/ballerina-lang/files/3566046/src.zip)

But it give the following NPE when running the jar.
`[2019-09-02 10:31:46,712] ERROR {org.ballerinalang.jvm.util.RuntimeUtils} - null
java.lang.NullPointerException
        at org.ballerinalang.jvm.types.BServiceType.setAttachedFuncsAndProcessAnnots(BServiceType.java:38)
        at wso2.gateway.gateway.wso2_gateway_3_1_0__init_(gateway:59)
        at rajithroshan.rajitest.___init.$moduleInit(rajitest:65535)
        at rajithroshan.rajitest.___init.$lambda$$moduleInit$(rajitest)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:456)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:231)`

 the gateway module

**Steps to reproduce:**

**Affected Versions:**
1.0.0-alpha3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Rajith90** [comment]
I could not face this issue in 1.0.0-beta version

**Comment by lankavitharana** [comment]
Reopening since the PR is not merged

**Comment by vinok88** [comment]
There can be 2 situations this can occur,
1. When there are only 50 Variable assignment instructions in the init method. 
2. No global variables, there is only one service. Not sure if this is possible.

**A workaround is adding an extra global var or reducing one.** 

The reason here is we run the split function logic but the function does not get split. Then the actual init function is duplicated. At the runtime this new init function is getting executed, but it does not contain the type init logics we add in jvm codegen.
