### ISSUE TITLE
Remove "-executable" part from the generated jar file

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#18501]
`ballerina build foo.bal` generates a jar file with the name "foo-executable.jar". The "-executable" part is redundant. Please remove it. 

```
> ballerina build foo.bal
foo.jar 
```

**Comment by hevayo** [comment]
We added the executable to distinguish uber jar from any other jar file. So that it is easy to identify a jar generated from ballerina build. Also during the build another foo.jar gets created which is the thin jar of the module in target.

If we are removing "-executable" any other way to satisfy the above requirement.

**Comment by sameerajayasoma** [comment]
These things are internal technical details. In most of the languages, the default behavior is consistent. That is to create an executable with the same name as the source file/module/package. 

We can use a different name for the internal module jar file.

**Comment by hevayo** [comment]
Yeh that make sense +1 we will do this for rc1.
