### ISSUE TITLE
Few issues with VScode plugin testing with workers and interaction

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#18827]
**Description:**

Following were notice during testing worker related stuff.

1. Did not complete the 'flush' and 'wait' actions.
2. 'flush' didn't highlighted. ( wait highlighting works)
3. interaction '->' or '<-'  not highlighting as well.

**OS, DB, other environment details and versions:**

latest nightly pack + Ubuntu

**Comment by nadeeshaan** [comment]
Flush and wait keyword suggestions have been fixed

**Comment by roonyh** [comment]
-> actually highlights. it looks like its not because the default theme in vscode gives all operators the color white. If you change the theme -> highlights with the color of other operators.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/3872221/66375093-28484000-e9ca-11e9-8e36-14f70233294f.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/3872221/66375107-35652f00-e9ca-11e9-82ab-e075ba0dc451.png">

**Comment by nadeeshaan** [comment]
Closing based on the above comment
