### ISSUE TITLE
[Spec Deviation] lang.table module contains functions not defined in the spec

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18869]
$subject

**Comment by lasinicl** [comment]
This has been fixed with the new table implementation.
Spec: https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/table.bal
Functions supported in lang.table module: https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.table/src/main/ballerina/src/lang.table/table.bal
