### ISSUE TITLE
Command gives incorrectly worded output

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#18990]
**Description:**
Grammatically incorrect command output.

**Steps to reproduce:**
Run the following on a bal file:
`ballerina openapi gen-contract hello -i demo.bal`
It gives the following output:
```
Note: This is an Experimental tool ship under ballerina hence this will only support limited set of functionality.
Successfully generated the ballerina contract at location 
/home/ballerina/demo/src/demo/hello.openapi.yaml
```
Note the wording of the Note. It is grammatically incorrect and has capitalization issues. It needs to be reviewed and fixed.
**Affected Versions:**
Ballerin 1.0.0

**Comment by MaryamZi** [comment]
We updated this sentence in the help texts for the individual OpenAPI commands, but seems like we are specifically printing this for each execution of the commands themselves. https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenContractCmd.java#L52

We can update this to what we have in the help text. 

"Note: This is an experimental tool, which only supports a limited set of functionality."

We should probably remove that sentence from the help texts when we do this, since it's a duplicate anyway.

**Comment by NipunaMarcus** [comment]
@MaryamZi thank you ... will update the message printed through the CLI tools
