### ISSUE TITLE
[IDEA Plugin] Ctrl+Click on a function should jump to the function definition

### ISSUE THREAD

**Issue by a5anka** [ballerina-platform/ballerina-lang#19350]
It is very hard to navigate Ballerina code without the above feature. I have to do a global string search and go through the list of results to find the function definition. This is really painful in a large code base. Is it possible to implement this feature in the Ballerina Idea plugin?

**Comment by Shan1024** [comment]
I totally agree with @a5anka. This is significantly reducing the usability of the plugin.

@NipunaRanasinghe - I thought this is already implemented in the LS?

**Comment by NipunaRanasinghe** [comment]
@a5anka @Shan1024  I do agree with the point that this is one of the critical features required for a smooth developer experience. We had this implemented in our language server but we had to hold this feature until the next minor release (1.1.0) since there were few limitations and minor performance issues by the time we were hitting 1.0-alpha(It was decided to be focused on performance over features since 1.0 is supposed to be production-ready). 

Maybe @nadeeshaan could update us with the current progress and the ETA for the feature :)

**Comment by nadeeshaan** [comment]
Goto Definition support has been shipped with v1.1.0. Hence closing the issue
