### ISSUE TITLE
Unable to fetch a million record from DB : Java Heap Space error

### ISSUE THREAD

**Issue by dhananjay41996** [ballerina-platform/ballerina-lang#19448]
**Description:**

Running ballerina locally, I am creating a Data Service to query the Database.
However, I am getting 'Java heap space' error while I am trying to fetch around a million records.
From [#9806](https://github.com/ballerina-platform/ballerina-lang/issues/9806), I understand that there is a way to pass through the response back to the client but what if I want to do some filtering or operations on top of it? or as in the below code, fetching from the database itself throws the heap space error.

**Code:**

import ballerina/config;
import ballerina/http;
import ballerina/jsonutils;
import ballerina/log;
import ballerinax/java.jdbc;

jdbc:Client employeeDB = new ({
    url: config:getAsString("MYSQL_URL"),
    username: config:getAsString("MYSQL_USERNAME"),
    password: config:getAsString("MYSQL_PASSWORD"),
    dbOptions: {useSSL: false}
});

listener http:Listener employeeEP = new (9095);

@http:ServiceConfig {
    basePath: "/testing"
}

service dbTransactions on employeeEP {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/cat_extn/{offerid}"
    }

    resource function getEmployees(http:Caller caller, http:Request request, string offerid) {
        http:Response response = new;
        log:printInfo("The select operation - Select data from a table");
        var selectResult = employeeDB->select("SELECT * FROM prmrcusdb.prmr_catalog_attr_extn_tb limit 1000000;",()); // where offerid = ?", (), offerid);
        log:printInfo("The select operation - Query execution in progress...");  
        if (selectResult is table<record {}>) {
            json jsonConversionResult = jsonutils:fromTable(selectResult);
            log:printInfo(jsonConversionResult.toString());
            response.statusCode = http:STATUS_OK;
            response.setJsonPayload(jsonConversionResult);
        } else {
            log:printError("Error occurred in querying data");
            response.statusCode = http:STATUS_NOT_FOUND;
            json responseJson = {"Failed": selectResult.reason()};
            response.setJsonPayload(<@untainted>responseJson);
        }

        var result = caller->respond(response);

        if (result is error) {
            log:printError("Error sending response to the client", err = result);
        }
    }
}

**OS, DB, other environment details and versions:**
Ballerina version  = 1.0.1
I am running i5 on 8gb RAM.

**Comment by Manuri** [comment]
@dhananjay41996 

Ballerina inherently enforces the streaming behavior. 

Neither following line
```ballerina
var selectResult = employeeDB->select("SELECT * FROM prmrcusdb.prmr_catalog_attr_extn_tb limit 1000000;",()); 
```
nor this,
```ballerina
json jsonConversionResult = jsonutils:fromTable(selectResult);
```

Would load the data into memory.

When you send the response here,

```ballerina
var result = caller->respond(response);
```

Data will be streamed out of the database, converted json and sent to the client piece by piece(as a stream). 
Therefore passthrough scenario doesn't cause OOM as it won't really load the whole amount of data into memory at once.

However, in your code, you're printing the json value which results in OOM because its not streaming out the data(pass-through) but touching the content and loading it all to the memory.
```ballerina
log:printInfo(jsonConversionResult.toString());
```

To answer your question on how you'd perform some filtering operations on top of data, in other words - perform content-aware operations,
Well, you can't perform an operation and accumulate all the data - this would obviously cause OOM because the size of the data exceeds the available memory.
One thing you can do is have the size limitation at query level.

**Comment by dhananjay41996** [comment]
Understood the OOM and data pass-through issue. However, if I am to perform content-aware operations on some 300Mb of data (or let's say more than a million records), can I do that in batches in Ballerina(e.g. 100k at a time) because that won't be a burden on the memory either??

Since having a limit at the query level won't always be possible.

**Comment by Manuri** [comment]
ATM there is no such feature. You can create a feature request (Git issue) so that we can consider the possibility of doing this in a future version.

**Comment by dhananjay41996** [comment]
Okay, thanks for your assistance.
