### ISSUE TITLE
Not allowing authprovider config without secure socket config is incorrect

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#19549]
**Description:**
In real world there are situations where SSL connection is handle by an API stands in front of a service and SSL termination happens before reaching the service. In such cases secure socket config are unnecessary for a listener for authentication process, but auth configs should be allowed if user chooses to do the authentication thought the listener. Hence following condition[1] is blocker. 

[1] https://github.com/ballerina-platform/ballerina-lang/blob/adcd18f1ea722d5b06f4a2de9acf23848dd585c6/stdlib/http/src/main/ballerina/src/http/service_endpoint.bal#L99

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.2
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
It is the recommended way to have authentication with SSL. But in your case, since you are aware of the SSL connection, you can disable it with the setting the `mandateSecureSocket` as `false`. Please refer to [1] for more information.

[1] https://v1-0.ballerina.io/learn/how-to-write-secure-ballerina-code/#disable-https-enforcement

**Comment by chamil321** [comment]
Tested as per the above comment. Works fine. Thanks
