### ISSUE TITLE
Field based access for JSON not working

### ISSUE THREAD

**Issue by drrallen** [ballerina-platform/ballerina-lang#20049]
**Description:**
I am having difficulty accessing JSON values within a http req using field based access. E.g.
Error message says  that 'field based access is not supported for assignment'. I have tried 'dotted' and ["name"] notations and neither worked. Is this a bug or has the syntax needed been changed.

**Steps to reproduce:**

See example:
import ballerina/http;
import ballerina/log;
import ballerina/io;

listener http:Listener httpListener = new(9090);

// Order management is done using an in-memory map.
// Add some sample orders to 'ordersMap' at startup.
map<json> ordersMap = {};

// RESTful service.
@http:ServiceConfig { basePath: "/ordermgt" }
service orderMgt on httpListener {

    // Resource that handles the HTTP PUT requests that are directed to the path
    // '/order/<orderId>' to update an existing Order.
    @http:ResourceConfig {
        methods: ["PUT"],
        path: "/order/{orderId}"
    }
    resource function updateOrder(http:Caller caller, http:Request req, string orderId) {
        var updatedOrder = req.getJsonPayload();
        http:Response response = new;
        if (updatedOrder is json) {
            // Find the order that needs to be updated and retrieve it in JSON format.
            json existingOrder = ordersMap[orderId];

            // Updating existing order with the attributes of the updated order.
            if (existingOrder != null) {
                            // GET ERRORS FROM FOLLOWING CODE
                existingOrder.Order.Name = updatedOrder.Order.Name;
                existingOrder.Order.Description = updatedOrder.Order.Description;
                ordersMap[orderId] = existingOrder;
            } else {
                existingOrder = "Order : " + orderId + " cannot be found.";
            }
            // Set the JSON payload to the outgoing response message to the client.
            response.setJsonPayload(<@untainted> existingOrder);
            // Send response to the client.
            var result = caller->respond(response);
            if (result is error) {
                log:printError("Error sending response", err = result);
            }
        } else {
            response.statusCode = 400;
            response.setPayload("Invalid payload received");
            var result = caller->respond(response);
            if (result is error) {
                log:printError("Error sending response", err = result);
            }
        }
    }
  
}

**Error message:**
error: .::FieldAccess.bal:32:17: invalid operation: type 'json' does not support field access for assignment

**Affected Versions:**
Ballerina 1.04

**OS, DB, other environment details and versions:**
Windows 10 64bit

**Comment by MaryamZi** [comment]
@drrallen The `json` type in Ballerina is the union of (), int, float, decimal, string, and maps and arrays whose values are, recursively, json. A `map<json>` represents a JSON object while a `json[]` represents a JSON array. 

Setting a field in a JSON value can only be done if the value is a JSON object (which is a map<json> in Ballerina). Thus before you set the `Name` field in the nested JSON object with key `Order` in the `existingOrder` JSON object, you'll first have to check if it is a nested JSON object, and then use member access (`val[key]`).

Moreover, when accessing fields from a `json`-typed value (`j`), the resultant type is `json|error`, since `j` may not be a JSON object or `j` may not have a field by the specified key. Thus you may have to first check if `updatedOrder.Order.Name` is `json` and then use it on the RHS, or instead of `if (updatedOrder is json)` check if `if (updatedOrder is map<map<json>>)` which represents a nested JSON object and then use member access to access a field.

e.g.,
One way to do this is
```ballerina
if updatedOrder is map<map<json>> {
      // Find the order that needs to be updated and retrieve it in JSON format.
      json existingOrder = ordersMap[orderId];

      // Updating existing order with the attributes of the updated order.
      json|error orderJson = existingOrder.Order;
      if orderJson is map<json> {
            // GET ERRORS FROM FOLLOWING CODE
            orderJson["Name"] = updatedOrder["Order"]["Name"]; // sets () if no `Order` or `Name` key
            orderJson["Description"] = updatedOrder["Order"]["Description"];
            // updates should be reflected in the original map
      } else {
            existingOrder = "Order : " + orderId + " cannot be found.";
      }
....
```

You could potentially remove some of these type checks by updating `ordersMap` to be a `map<map<map<json>>>`, if it may only contain nested JSON objects.

**Comment by MaryamZi** [comment]
Pre-1.0.0 version allowed setting fields to a `json`-typed variable, without validating if it is a `map<json>` (JSON object), but this opened up room for errors at runtime.

The following resources could be helpful.
- [JSON objects BBE](https://ballerina.io/learn/by-example/json-objects.html)
- Blog - [Ballerina’s JSON type and lax static typing](https://medium.com/ballerina-techblog/ballerinas-json-type-and-lax-static-typing-3b952f6add01)

**Comment by drrallen** [comment]
Thank you @MaryamZi  for your guidance and  the helpful example code. I shall refer to the resources you suggest.
Closing this non-issue
