### ISSUE TITLE
[Interop] Returns java `null` value when function returns string?

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#20164]
**Description:**
When we have a function like below which returns string?, the function returns java `null` value. when we try to do any string operation(string concatenation) from the returned value, we get java.lang.NullPointerException.

```ballerina 
function externGet(Headers headerValues, handle headerName) returns string? =
@java:Method {
 class: "org.ballerinalang.net.grpc.nativeimpl.headers.Get"
} external;
```

**Steps to reproduce:**

**Affected Versions:**
1.0.4

**Comment by SupunS** [comment]
Since return type is a nillable type (`string|()`), it is correct to return java `null` which is the runtime representation of the ballerina `nil` value.

However since return type is a union-type, it should not allow to do any string-operations on top of a union type. Ideally should fail at compile time. Can you add a sample where it breaks?

**Comment by daneshk** [comment]
I would have attached the sample before. Below is the sample where it breaks.
```ballerina
io:println("Request Header: " + (headers.get("x-id") ?: ""));
```
even though we have nil shifting, it fails.

I am able to fix this by changing the API to return `handle?` and It works.
