### ISSUE TITLE
Map type is not getting recognized.

### ISSUE THREAD

**Issue by kaushikbiswas1984** [ballerina-platform/ballerina-lang#20275]
import ballerina/io;

public function main() {
    // Declares a "map" constrained by the type "string".
    ​map<string> m;    

}

Even simplest statement gives the below error:

ballerina run main.bal
Compiling source
        main.bal
error: .::main.bal:5:5: undefined symbol '?map'
error: .::main.bal:5:18: undefined symbol 'm

**Comment by rdhananjaya** [comment]
```ballerina
map<string> m; // map constrained by type `string`
```

**Comment by MaryamZi** [comment]
@kaushikbiswas1984, like @rdhananjaya mentioned a map type must have a constraint.

```ballerina
map<string> m;
```

However, I got similar errors like you've mentioned when I copied the exact source you've shared and added the constraint. The errors seemed to be due to a zero-width space character that was present at the start of the `map m;` line.

Can you try building the following please? 

```ballerina
public function main() {
    // Declares a "map" constrained by the type "string".
    map<string> m;
}
```

**Comment by hasithaa** [comment]
Tested with SLP3. The new parser is giving incorrect diagnostics, which is not helpful. @SupunS Shall you have a look into this?

**Comment by SupunS** [comment]
Seems there are three issues here:

1) Like @MaryamZi have mentioned, theres a zero-width whitespace character (U+200B) just before the map keyword. Since U+200B is not part of the ballerina [WhiteSpaceChar](https://ballerina.io/ballerina-spec/spec.html#WhiteSpaceChar), the entire `(U+200B)map` is read as a single token - resulting in an invalid token, as it is not a valid identifier. 
This is correct according to the spec. However it is debatable whether to treat these different whitespaces as ballerina whitespaces, which is also the case with https://github.com/ballerina-platform/ballerina-lang/issues/18987.

2) Whitespace after the invalid token `(U+200B)map` is not treated as a whitespace, resulting the next token also to be treated as an invalid token.

3) Even though the `(U+200B)map` is captured as an invalid token in the syntax-tree, a diagnostic does not added.

We need to fix 2) and 3) at the lexer.
