### ISSUE TITLE
Issues in variables shown while debugging

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#20299]
**Description:**
![debugger](https://user-images.githubusercontent.com/8376983/70435479-f1b3a200-1aac-11ea-8189-6dd6511621fb.png)

`a` is not even shown, while `f` which is not yet defined is shown with a default value.

**Steps to reproduce:**
```ballerina
string[] s = ["hi", "hello"];

public function main() {
    int[] i = [1, 2];

    int a = i[0];
    a = i[0];

    float f = 1.0;
}
```

**Affected Versions:**
1.1.0-alpha

**Comment by NipunaRanasinghe** [comment]
Closing since this is already fixed with recent runtime changes. However, there is a somewhat similar issue is reported, where the default value is shown only when the debugger is stopped at the declaration line. https://github.com/ballerina-platform/ballerina-lang/issues/28064. We'll be working on it and will update the progress in there.
