### ISSUE TITLE
Show the rest field in completions for record fields

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20314]
Refer to the following:
![Peek 2019-12-10 11-13](https://user-images.githubusercontent.com/6260009/70499081-608d0b80-1b3e-11ea-8f7f-13edfb0562cc.gif)

As it can be seen, the `address` field refers to an open record. But in the completion suggestions for the record, it only shows the non-rest fields. It would be good if we can come up with a way to show the rest field in the completions as well, if there is one.

**Comment by nadeeshaan** [comment]
We need to provide an intuitive way for the users. When a completion item is shown for the rest field then that particular completion Item can be mistaken as an existing field. If we make the field name (Which is shown as the label) distinguishable, it will be rare that the user will look for that particular field. 
Hence, I would suggest that we do not show a completion item for the users and instead of that users can hover over the record symbol and we can show that particular record is an open record or a closed c record. User should have the language knowledge to infer that he/she can add new fields.
@rasika @NipunaMarcus @NipunaRanasinghe @Kishanthan @pubudu91 
WDYT?

**Comment by rasika** [comment]
+1 to improve the dev exp. We can have a snippet completion for this. But since user types [.] dot to get completions we might need to remove it when accessing or assigning rest field value. @nadeeshaan is this possible with the current LSP protocol to remove the last dot?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1448489/93738241-ea582200-fc02-11ea-87ce-da8713fbf68c.gif)
