### ISSUE TITLE
Following code doesn't work

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#20530]
**Description:**

Consider following code it doesn't work:
```ballerina
    table<domain:ApplicationResponse> result = check <@untainted> connection->select(QUERY_SELECT_APPLICATION_BY_ID,  domain: ApplicationResponse, applicationId, userId);
``` 
in above connection is a `jdbc:Client`
@MaryamZi has more details :)
**Steps to reproduce:**

**Affected Versions:**
v 1.1.0
**OS, DB, other environment details and versions:**
MacOS
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ramith** [comment]
compile error is:
`
action invocation as an expression not allowed here
`

**Comment by MaryamZi** [comment]
This is basically because we are trying to use annotations in a type cast expression (`<@untainted>`) with actions.

Simpler code for demonstration

```ballerina
type Foo client object {
    public remote function bar() returns @tainted error? {
        
    }
};

error? x = (); // untainted var

public function main() returns error? {
    Foo f = new;
    x = <@untainted> f->bar(); // error: action invocation as an expression not allowed here
}
```

Since type-cast is an expression and we are using the cast (with the annotation) with an action, this is inline with the 2019r3 spec:

"An action cannot be nested inside an expression; it can only occur as part of a statement or nested inside other actions. This is because actions are shown in the sequence diagram in the graphical syntax."

This example can be fixed by first assigning the result of the remote method call and then untainting the value.
```ballerina
type Foo client object {
    public remote function bar() returns @tainted error? {
        
    }
};

error? x = ();

public function main() returns error? {
    Foo f = new;
    error? y = f->bar();
    x = <@untainted> y;
}
```

Similarly for the original issue with `check` we can do the following (missed this during the offline conversation),
```ballerina
table<domain:ApplicationResponse>|error origResult = connection->select(QUERY_SELECT_APPLICATION_BY_ID,  domain: ApplicationResponse, applicationId, userId);
table<domain:ApplicationResponse> result = check <@untainted> origResult;
```

**Comment by MaryamZi** [comment]
Btw, this is the general behaviour with any action in accordance with the spec. 

For example the following is also not allowed.
```ballerina
import ballerina/io;

type Foo client object {
    public remote function bar() returns @tainted int|error {
        return 1;
    }
};

public function main() returns error? {
    Foo f = new;
    io:println(f->bar()); //  action invocation as an expression not allowed here
}
```

The same would have to be written as
```ballerina
import ballerina/io;

type Foo client object {
    public remote function bar() returns @tainted int|error {
        return 1;
    }
};

public function main() returns error? {
    Foo f = new;
    int|error x = f->bar();
    io:println(x);
}
```

Closing this issue since the error is valid, and the requirement can be achieved. Please reopen if you have any concerns regarding the suggested approach.

**Comment by ramith** [comment]
Could I mark/annotate a resource ( in this example `connection`) as untainted?

**Comment by MaryamZi** [comment]
@ramith, sorry, missed responding to this.

> Could I mark/annotate a resource ( in this example `connection`) as untainted?

This is not supported atm, but we've created https://github.com/ballerina-platform/ballerina-lang/issues/20826 to track checking the feasibility of doing the same.
