### ISSUE TITLE
Need a better API to create ErrorValues

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-lang#20547]
**Description:**
$subject. Need an API to create ErrorValues https://github.com/ballerina-platform/ballerina-lang/blob/9582b76c4e6cc6042b9cd0e62e390984bc088acd/stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java#L1691

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
There is already a set of APIs: https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java#L75

Would that not be sufficient?

**Comment by SupunS** [comment]
Had a chat with @arukshani, the requirement here is to provide an API to create an error value in the https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java class, that is capable of creating an error value, using the `error` type defined in a given package. Such APIs are available for `records` and `objects`, but not for other user defined types.

**Comment by SupunS** [comment]
Further checking on this, I just realised that reason to provide an API [BallerinaValues.java](https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java) is because the value class implementations for `objects` and `records` are dynamic and there is no way for the [BValueCreator.java](https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValueCreator.java) class to know which class to use for value creation.

But this is not the case with other user defined types such as `error` and etc, where the value class is predefined. Hence we actually don't need that API, and [BValueCreator.java](https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValueCreator.java) can be used. 

No matter what API is used, it will required to mention  the org name, package name and the version of the type, from which we are creating a value.
