### ISSUE TITLE
Issue when specifying USERNAME as a variable name within ballerina.conf file

### ISSUE THREAD

**Issue by ashera96** [ballerina-platform/ballerina-lang#20612]
**Description:**

After creating a variable named "USERNAME" within the ballerina.conf file with a certain string value. Once the ballerina project is built and run, instead of reading the value stored within the variable, it reads the username found in the local machine. It would be better to allow variables such as username, etc. which are commonly used to not be regarded as special variables. Suggesting to access the system username in a more unique way.

**Steps to reproduce:**
Created a ballerina.conf file to store sensitive information such as username and password. After defining the "USERNAME" variable tried to access it within the main.bal file of a module. The username which is read within the main.bal file now is the username of the local machine.

**Affected Versions:**
1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
The behaviour you observed is due to the order of resolution of configurations when running a program. Configurations are looked up from (listed from lowest priority to highest), 
1) A config file
2) Environment variables
3) CLI params (`--key=val` pairs)

When resolving config values, if multiple sources contain the same config key, the value of the source with the highest priority is taken. So in your scenario, since `USERNAME` also happens to be an environment variable defined in the system, the priority goes to that value over the value you have defined in your config file. Can't you modify the config key to something else? Or else you can provide the user name as a CLI param. 

Note that the config API doesn't regard any config key as a special value. It's just a key-value pair storage which aggregates values provided by multiple sources. The behaviour you have observed is due to the config resolution order explained above.

**Comment by ashera96** [comment]
Yes, I did find a workaround for that issue by changing the config key.

What I was suggesting is to have a more unique environment variable to read the system username. So that such a common key that may be used within the config file often, will not be affected by the environment variable. (for example "sys.username"). 

Won't this prevent multiple sources having the same config key?

**Comment by pubudu91** [comment]
Multiple sources having the same config key is actually not a problem. That's intentional. The idea is if needed, you have a mechanism for overriding a config value. That's where the config source hierarchy I mentioned previously comes in: when two sources have the same key, precedence is given to the source higher up in the hierarchy. 

Let's say you have defined a value called `port=9090` in a config file, along with some other configurations. But when running the program you want to give a different value to `port`. You can do this by either setting `port` as an environment variable or by providing it as a CLI param. e.g.,
```bash
$ ballerina run program.bal --b7a.config.file=bal.conf --port=8080
```
And suppose the config file looks something like,
```toml
host="localhost"
port=9090
foo="bar"
```
When executing, the value the program looks up for `port` will be `8080`, since the value provided by the config file is overridden by providing `--port=8080` as a CLI param.

As for reading environment variables, as I mentioned earlier, the config registry is just a key-value pair store and when resolving config values, it **does not do any processing** to special case any of the keys (except replacing `.` with `_` when looking up env vars). If the user has looked up a particular key in the code, the config API will simply look it up, as-is, first in the config file, and then in env vars, and finally, in CLI params.

**Comment by ashera96** [comment]
As for the offline discussion with @pubudu91 this cannot be handled at the ballerina point of view. Hence, closing this issue.
