### ISSUE TITLE
Executable jar created with ballerina std lib module name gives CNF

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#20699]
**Description:**
When I create a executable jar with a b7a std lib module name (for ex: config.jar) it gives a CNF issue[1] when running that jar

[1]
```ballerina
error: java.lang.NoClassDefFoundError message=org/ballerinalang/stdlib/config/Contains cause=error java.lang.ClassNotFoundException message=org.ballerinalang.stdlib.config.Contains
	at ballerina.config:externContains(natives.bal:65535)
	   ballerina.config:contains(natives.bal:24)
	   ballerina:getAsInt(config.bal:58)
	   ballerina.http.PoolConfiguration:PoolConfiguration__init_(http_client_connection_pool.bal:27)
	   ballerina.http.ConnectionManager:__init(http_client_connection_pool.bal:35)

```

After changing the ballerina project name and creating the jar with different name it works
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This is a known issue which arises when a module has the same name as an imported module (with the presence of extern functions). The workaround is to use a different module name like you've mentioned. 

Closing this since the same is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/19562.
