### ISSUE TITLE
IntelliJ plugin reports "No ballerina SDK is found for project" even for non-ballerina projects

### ISSUE THREAD

**Issue by TomIsoGriv** [ballerina-platform/ballerina-lang#20718]
If the "Ballerina Home Auto-Detection" option is checked the Ballerina plugin will checks **every** opened project to in an attempt to determine the Ballerina SDK path ... even if it is another language (like Java).  It then reports failure in the IntelliJ event log.

This is Ballerina 1.1 running on OSX 10.14.6 with the 
**Affected Versions:**
1.1

**Comment by NipunaRanasinghe** [comment]
@TomIsoGriv As the ballerina plugin contains a low-cost sub-process to handle ballerina source files inside non-ballerina projects, we need to have this check when a project is being opened.  Anyway this log is supposed to be an internal/developer log for non ballerina projects and will be fixed with the next patch release. Thanks for reporting.

**Comment by NipunaRanasinghe** [comment]
@TomIsoGriv The plugin is supposed to wait until at least one ballerina file is opened, for non-ballerina project. Fixed with #21273. Thanks for reporting!
