### ISSUE TITLE
`destroy` method for tracing and metrics extensions

### ISSUE THREAD

**Issue by a5anka** [ballerina-platform/ballerina-lang#20863]
## Description

Different tracing and metric implementations can have different buffering mechanisms for data it generates. When the ballerina program is gracefully shutdown it will be better if the extension can get a method callback so that it can properly flush the collected data before shutting down.

1. https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.1.x/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/tracer/OpenTracer.java

## Affected Versions

1.1.0

**Comment by nadundesilva** [comment]
Once a ballerina allows a module to run code on shutdown (Spec Issue - https://github.com/ballerina-platform/ballerina-spec/issues/730), this requirement would be fulfilled.

Since all Observability Extensions are now Ballerina Modules. The module hosting the extension will be able to use the Ballerina Level callback and handle these gracefully. Hence closing this issue.
