### ISSUE TITLE
Incorrect formatting with service annotations

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#20913]
**Description:**
Refer the sample code below

**Steps to reproduce:**

Before formatting:

```ballerina
import ballerina/http;
import ballerina/io;

service wsService = @http:WebSocketServiceConfig {subProtocols: ["xml, json"]
                                         ,idleTimeoutInSeconds: 20} service {
    resource function onOpen(http:WebSocketCaller caller) {
        io:println("New WebSocket connection: " + caller.getConnectionId());
    }
};
```

After Formatting: Note that the `,` after the subProtocols array has moved to a new line.

```ballerina
import ballerina/http;
import ballerina/io;

service wsService = @http:WebSocketServiceConfig {
    subProtocols: ["xml, json"]
    ,
    idleTimeoutInSeconds: 20
} service {
    resource function onOpen(http:WebSocketCaller caller) {
        io:println("New WebSocket connection: " + caller.getConnectionId());
    }
};

```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaMarcus** [comment]
@anupama-pathirage  this is actually correct as to the rules. So there are two rules applied here. 

1. If a record literal is broken down into a new line it will break each field into a new line. That's why the fields are on new lines after format.
2. We preserve the new lines given by the user hence we preserve the new line that belongs to the `,` as the user has put a newline before the comma.

**Comment by sanjana** [comment]
Tested on version: **SLP5**. 
And this issue is fixed.
