### ISSUE TITLE
Ballerina Tool Returns Exit Code (0) In Failure

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#20967]
The Ballerina tool returns an exit code of 0 (success) even when the command fails. For example, if compilation fails, or test execution fails. These scenarios must return a proper exit code from the "ballerina" command execution. This is critical for other tools which executes the "ballerina" command and monitors it for success or failure, e.g. GitHub Actions. 

In bash, this can be tested with the following pattern:

$ ballerina test -a
$ echo $? # this prints the exit code of the previous process execution, this should be 0 for success or else, fail

**Comment by lafernando** [comment]
A similar issue was reported earlier, but seems, that scenario is also not working now: https://github.com/ballerina-platform/ballerina-lang/issues/20967.

**Comment by lafernando** [comment]
A related issue was reported earlier, but this also is not working now (in v1.1.1): #14276

**Comment by lafernando** [comment]
This issue is still there in Ballerina v1.1.4. I tried in a fresh installation, and not using "ballerina dist update". Please look into this ASAP.

**Comment by keizer619** [comment]
This is fixed in master and this will be available along with the next Ballerina Tool version. Currently 1.1.4 is using Tool 0.8.0. Next tool will be released along with upcoming 1.2.0 release.

**Comment by lafernando** [comment]
We should have fixed this in an earlier patch release (i.e 1.2,1.3,1.4) by doing a patch release of the Tool. Especially since this is a blocking issue.

**Comment by keizer619** [comment]
@lafernando It was there in the ballerina update tool 0.8.0 version. we did not release ballerina update tool along with 1.1.2-1.1.4 patches. 

We have fixed it in released it along with 1.2.0 release with a new version 0.8.5

In order to get that issue you need to run following command

`ballerina update`

This will bump tool version to 0.8.5. So even if you 1.1.0-1.1.4 or 1.2.0, if you have 0.8.5, the fix is there
