### ISSUE TITLE
Error when same name for method and variable

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [ballerina-platform/ballerina-lang#21030]
**Description:**

**Steps to reproduce:**
```
public function isAppSecurityOptional(string serviceName) returns boolean {
  return true;
}
boolean isAppSecurityOptional = isAppSecurityOptional("hello");
```
Error :
`
undefined function 'isAppSecurityOptional'
`

**Affected Versions:**
1.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
I get both the following errors for this code.

```cmd
error: .::qwe.bal:4:9: redeclared symbol 'isAppSecurityOptional'
error: .::qwe.bal:4:33: undefined function 'isAppSecurityOptional'
```

You cannot have both a function and a variable with the same name in the same scope and symbol space, so the "redeclared symbol" error here is expected.

However the "undefined function" error does seem odd since the compiler complains about the variable and not the function.

**Comment by hasithaa** [comment]
Not planning to fix this immediately. Hence this issue has been marked as "Deferred" and will be revisited in the future when resources are available.
