### ISSUE TITLE
Invalid reference in documentation issue

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#21527]
Please refer to the below function and its documentation.

![image](https://user-images.githubusercontent.com/9362271/76156637-3938e100-6123-11ea-8ced-b9070f358783.png)

This fails when compiled, but it compiles without any issues if the documentation is changed to below

```ballerina
#
# + stm - the stream
# + func - combining function
# + initial - initial value for the first argument of combining function
# + return - result of combining the members of `stm` using the combining function
```

**Comment by dulvinw** [comment]
The error given out by the compiler is correct. Because when you use the keyword function, the function should be a public function available in the given scope. Therefore i suggest to change the documentation to something like Initial value for the first argument of combining function given by the parameter `func`. 

But the error given by the compiler seems to be not sufficient. Hence I've created a new issue to track the improvement of the error message for BFM analysis.

#22672
