### ISSUE TITLE
A peek is shown for a variable declaration

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#21929]
Refer to the image below
![Peek 2020-03-18 14-53](https://user-images.githubusercontent.com/6260009/76945407-745bc100-6928-11ea-9da9-7785f43c6a63.gif)
When you press Ctrl and hover over a variable declaration, it shows a peek of itself. Shouldn't this peek be shown only for the references of that variable?

**Comment by nadeeshaan** [comment]
This happens because we jump to the definition even if the cursor is on the definition. We can avoid this by not providing a definition for self. If we do that, then the user will be prompted with no definition found while there is the definition. Since this is annoying in the user's perspective we are going forward with this. Also, every other plugin such as Typescript follows the same behaviour. 
Hope this answers your concern and closing the issue
