### ISSUE TITLE
When sorting imports during formatting comments belong to the import doesn't move

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#21953]
**Description:**
When sorting imports during formatting comments belong to the import doesn't move. 

**Steps to reproduce:**
* Format the following code

```ballerina 
// This example imports a module. You can only refer to the public symbols of
// an imported module.
import ballerina/math;

// Declare an explicit alias.
import ballerina/io as console;

public function main() {

    // Refer symbols of another module.
    // `math:PI` is a qualified identifier. Note the usage of the module alias.
    float piValue = math:PI;

    // Use the explicit alias `console` to invoke a function defined in the `ballerina/io` module.
    console:println(piValue);
}
```
* see the imports have sorted but the comments were not moved with the import

```ballerina
// This example imports a module. You can only refer to the public symbols of
// an imported module.
import ballerina/io as console;

// Declare an explicit alias.
import ballerina/math;

public function main() {

    // Refer symbols of another module.
    // `math:PI` is a qualified identifier. Note the usage of the module alias.
    float piValue = math:PI;

    // Use the explicit alias `console` to invoke a function defined in the `ballerina/io` module.
    console:println(piValue);
}

```

**Affected Versions:**
1.2.0

**Comment by IrushiL** [comment]
This issue is no longer applicable since the reordering of imports is not supported in the new Swan Lake formatter.

However, we have a new feature issue https://github.com/ballerina-platform/ballerina-lang/issues/26617 for the organization of imports. We should ensure this bug is not resurfaced during the new implementation.

Closing this issue since it is not applicable with the current implementation.
