### ISSUE TITLE
Bindgen tool not throwing error when there are jars version miss match. 

### ISSUE THREAD

**Issue by suhothayan** [ballerina-platform/ballerina-lang#22372]
**Description:**
The bindgen tool not throwing an error when different versions of the jars are added to the classpath. 

**Steps to reproduce:**
Added  ./javalibs/snakeyaml-1.26.jar to the classpath 
but add the following to the toml 
```
[platform]
target = "java8"

   [[platform.libraries]]
   path = "./javalibs/snakeyaml-1.25.jar"
   modules = ["yamlparser"]
```
and ran 
```
ballerina bindgen -cp ./javalibs/snakeyaml-1.25.jar -o src/yamlparser org.yaml.snakeyaml.Yaml java.io.FileInputStream java.io.InputStream java.util.Map
```
It didn't complain until I try to  build the project again.

**Affected Versions:**
1.2.0

**OS, DB, other environment details and versions:**
Mac 

**Suggested Labels (optional):**
Improvement 

**Suggested Assignees (optional):**
Jo

**Comment by IrushiL** [comment]
This issue is fixed through the following PRs:
* https://github.com/ballerina-platform/ballerina-lang/pull/22393
* https://github.com/ballerina-platform/ballerina-lang/pull/23883

The tool will now display the JAR files added to classpaths and the failed cases. 

Here, in this issue, the reason why the bindings are generated even though the correct jar is not picked, is because the tool allows the generation of bindings for classes available inside the Ballerina SDK without explicitly specifying a classpath The SnakeYaml JAR is loaded this way. This is mainly used to support the generation of standard Java library classes. 

However, since the output messages are now more detailed, a user is able to identify if a specified class is added to the classpath correctly or not.
