### ISSUE TITLE
Do we need to limit http status code to a int value

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#2276]
In current setStatusCode method, we are setting a int value as a status code, but when removing long and double from ballerina, we can set a long value as a status code. Do we need to do that?

**Comment by pubudu91** [comment]
In the implementation of `setStatusCode()`, there is a conditional check added for this. So, even if a long value larger than the maximum of an integer is passed, an exception is thrown. The cast to int is necessary because the underlying library we use (Netty) does not support long values as the status code. 

https://github.com/ballerinalang/ballerina/blob/8b725e19e2a1e740e48b09d0564d1ad1e858ef4d/modules/ballerina-http/src/main/java/org/ballerinalang/net/http/nativeimpl/response/SetStatusCode.java#L56

**Comment by nixel2007** [comment]
Why you ever need a long of a status code is limited to 599?

**Comment by pubudu91** [comment]
@nixel2007 this is because there's only one data type for integers in ballerina (called `int` which is a 64 bit integer type).

**Comment by pubudu91** [comment]
Closing this since this is no longer relevant nor applicable.
