### ISSUE TITLE
Need to be able to set http header values for OutboundOAuth2Provider

### ISSUE THREAD

**Issue by mghaigh** [ballerina-platform/ballerina-lang#22921]
**Description:**
Some Oauth2 authorization endpoints require specific values for Accept and Content-Type (e.g."application/json"). The configuration of an OutboundOAuth2Provider should allow setting those and possibly other http header values. See [ballerina-oauth2-authenticated-endpoint-returning-a-406](https://stackoverflow.com/questions/61391843/ballerina-oauth2-authenticated-endpoint-returning-a-406) for more details. [](url)
**Steps to reproduce:**
Use OutboundOAuth2Provider for an Oauth2 authorized endpoint where the authorization endpoint  expects specific http header values.

**Affected Versions:**
Ballerina 1.2.2
**OS, DB, other environment details and versions:**
N/A
**Related Issues (optional):**

**Suggested Labels (optional):**
Ballerina, Oauth2, Http header

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
Thanks for reporting the issue.

This is the summary as per the discussion had in Stack Overflow thread.
The Ballerina `oauth2:OutboundOAuth2Provider` prepare the access token request for password grant-type according to the RFC [1].

```
POST /token HTTP/1.1
     Host: server.example.com
     Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
     Content-Type: application/x-www-form-urlencoded

     grant_type=password&username=johndoe&password=A3ddj3w
```

The token endpoint used for 3rd party service by `https://developer.experian.co.uk/` expects the access token request according to the tutorial [2].

```
curl -X POST https://sandbox-uk-api.experian.com/oauth2/v1/token \
-H "Accept: application/json OR application/xml" \
-H "Content-Type: application/json OR application/xml" \
-H "grant_type : password" \
-d '{"username": "<USERNAME>","password":"<PASSWORD>",
"client_id":"<CLIENT_ID>", "client_secret": "<CLIENT_SECRET>" }'
```

[1] https://tools.ietf.org/html/rfc6749#section-4.3.2
[2] https://developer.experian.co.uk/tutorial/oauth-20-tutorial

**Comment by mghaigh** [comment]
Hi @ldclakmal. Thanks for looking at this.
Couple of points on your comment:

1. The RFC is just an example POST. I don't know what values the Ballerina `oauth2:OutboundOAuth2Provider` actually uses when it prepares the access token.
2. The documentation should identify what the default values are for key header keys used by the`oauth2:OutboundOAuth2Provider`
3. The `oauth2:PasswordGrantConfig` passed in should allow those default `oauth2:OutboundOAuth2Provider` values to be changed by the developer.
4. I am particularly interested in the  Password Grant case but the principles probably apply to other Oauth2 cases.

**Comment by mghaigh** [comment]
Hi @ldclakmal, I have now realised there are 2 different scenarios WRT API usage in a project and standards compliance:

1. **Provided API**; where an API, implemented in Ballerina, is being made available for others to use. In this case, Ballerina should enforce all applicable standards as far as possible. Making it’s APIs ‘good citizens’
2. **Required API**; where an API, possibly implemented by a third party, is being used by a Ballerina project. Here I think Ballerina’s default configuration should be compliant with applicable standards but, because the API being used may be outside the projects control (and may not be completely standards compliant), Ballerina should allow the default config(s) to be overridden. 
What do you think?

.

**Comment by mghaigh** [comment]
Closed by mistake

**Comment by ldclakmal** [comment]
@mghaigh Yes. Regarding this issues, it is categorized under **Required API**. Ballerina, as a programming language, provides the capability to do configurations w.r.t. the RFC provided and it is limited to the guidelines that RFC enforce. Providing ability to customize beyond the limitations/guidelines provided by RFC is not recommended. If there is any RFC violation, it should be definitely fixed in Ballerina.

But, there can be RFC deviated situations like this, where Ballerina need to provide flexibility to support custom mechanisms of authentication. In order to provide facility for that, we need to implement a custom outbound auth provider. Please refer the guide on ["Implementing-outbound-custom-authentication-mechanism"](https://ballerina.io/learn/how-to-write-secure-ballerina-code/#implementing-outbound-custom-authentication-mechanism).

In this scenario, most of the implementations are similar to what have done in [`oauth2:OutboundOAuth2Provider`](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal#L69). I assume, only the [`prepareRequest`](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal#L609) method need to be changed according to the 3rd party API [1] requirement. After implementing this, let's name it as `ExperianOAuth2Provider`, and you can use it with the same `http:BearerAuthHandler`.

```ballerina
public type ExperianOAuth2Provider object {

    *auth:OutboundAuthProvider;

    public function generateToken() returns string|auth:Error {
        // Custom logic to generate the token. 
    }

    public function inspect(map<anydata> data) returns string|auth:Error? {
        // Custom logic to inspect the data map received from the AuthHandler. 
    }
};

oauth2:PasswordGrantConfig passwordGrantConfig = {
    tokenUrl: config:getAsString("experian.authentication.tokenUrl"),
    username: config:getAsString("experian.authentication.username"),
    password: config:getAsString("experian.authentication.password"),
    clientId: config:getAsString("experian.authentication.clientId"),
    clientSecret: config:getAsString("experian.authentication.clientSecret"),
    credentialBearer: http:AUTH_HEADER_BEARER
};
ExperianOAuth2Provider oauth2Provider = new(passwordGrantConfig);

...
```

[1] https://developer.experian.co.uk/tutorial/oauth-20-tutorial

**Comment by ldclakmal** [comment]
Please reopen the issue if there are any concerns.
