### ISSUE TITLE
Empty string is not working, when we pass "" (empty quotations) as argument 

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-lang#2298]
Example :
[1] -
```ballerina
import ballerina/io;

function main (string[] args) {
    int a = 0;
    string x = args[0];
    if (x == "") {
        a = 1;
    }
    io:println(a);
}
```

[2]-
```
./ballerina run main sample.bal ""
```

**Comment by lankavitharana** [comment]
This seems to be a bug in jcommander as mentioned in [1]. According to that issue is fixed in the latest version, (we are using 1.60 and fix seems to be merged after 1.6 release)

so for time being can you use a space inside the double quotes? (" ") it was taken as a empty string.

[1] - https://github.com/cbeust/jcommander/issues/306

**Comment by uthaiyashankar** [comment]
Can we upgrade to latest jcommander (1.71)?

**Comment by MaryamZi** [comment]
Reopening since this seems to be broken.

```ballerina
import ballerina/io;

public function main(string arg) {
    io:println(arg);
}
```

None of the following work
```cmd
$ ballerina run test.bal
ballerina: insufficient arguments to call the 'main' function

$ ballerina run test.bal ""
ballerina: insufficient arguments to call the 'main' function

$ ballerina run test.bal " "
ballerina: insufficient arguments to call the 'main' function
```

**Comment by Kishanthan** [comment]
https://github.com/ballerina-platform/ballerina-distribution/pull/206 will fix this issue as well.
