### ISSUE TITLE
Version update fails

### ISSUE THREAD

**Issue by Dmunch04** [ballerina-platform/ballerina-lang#23184]
**Description:**
Whenever I try and install the new version using the `.deb` package, I get this error
![image](https://user-images.githubusercontent.com/30357821/81725559-4f964c80-9486-11ea-936c-0ab34219000c.png)
I tried removing the whole folder (`/usr/lib/ballerina`) but without any luck. And that also means that I no longer have access to the CLI, since I removed that folder. I'm unsure what to do from here?

**Steps to reproduce:**
None I suppose.

**Affected Versions:**
Latest (v1.2.3)

**OS, DB, other environment details and versions:**
Linux (Pop!_OS v19.10)

**Comment by keizer619** [comment]
After 1.1.0 release for version updates we always promote ballerina update tool [1].

If you need to install a specific installation you can use following command by specifying version

`ballerina dist pull jballerina-1.1.4`

if you want to update your distribution to latest patch version you can just execute 

`ballerina dist update`

In order to support above feature, we had to move installation to `/usr/lib/ballerina` where as it uses same shares in built JRE among multiple distributions. 

When you try to install new installers it will rewrite the whole installation and unfortunately in Ubuntu if you have a previous installation using same directory it will not rewrite.

To avoid that you need to remove previous version from dpkg (In your case its 1.1.4 as below)

`dpkg --remove ballerina-1.1.4`

and then use new install new version as follows (You can even use the wizard UI as well)

`dpkg -i ballerina-linux-installer-x64-1.2.0.deb`

Or else you can install forcefully by using following command

`dpkg -i --force-overwrite ballerina-linux-installer-x64-1.2.0.deb`

As i mentioned earlier to update ballerina now you don't need to download installer and install again, you can easily use ballerina update tool feature

[1] https://ballerina.io/learn/how-to-keep-ballerina-up-to-date/

**Comment by Dmunch04** [comment]
Thank you very much! And yeah, I first found the update command after I had deleted the old Ballerina folder. But this works. Thank you!
