### ISSUE TITLE
[IntelliJ Plugin] Highlighting issue in string literals

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#23532]
**Description:**
Please refer the following code sample.
![unnamed](https://user-images.githubusercontent.com/29032600/82988689-2db8d000-a017-11ea-9f7e-389b9bd21882.png)

**Steps to reproduce:**

**Affected Versions:**
plugin 1.2.4 and below

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vaughnbeanz** [comment]
I understand that this problem is related:

In the following code in IntelliJ (plugin 1.2.4), the characters from the first " on Line 6 to the last " inclusive are highlighted as "string".

```
public function main() {
    string? foo = "asd";

    io:println("hi foo:" + (foo ?: "()"));  // Line 6
    io:println("hi foo:"
     + (foo ?: "()"));
}
```

Also, when a line like line 6 is included in a service function and you try to run the service, the run configuration dialogue is displayed with an error message "Error: Service run kind is selected, but the file does not contain any services.". If I comment out line 17 then the service runs and functions correctly.
