### ISSUE TITLE
Update param and return types for clone, cloneReadOnly

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#23691]
**Description:**
Please refer https://github.com/ballerina-platform/ballerina-spec/issues/531#issuecomment-635739590

The clone, and cloneReadOnly should be changed to 
```ballerina
type Cloneable readonly|xml|Cloneable[]|map<Cloneable>|table<map<Cloneable>>;

@typeParam
type CloneableType Cloneable;

public function clone(CloneableType v) returns CloneableType = external;

public function cloneReadOnly(CloneableType v) returns CloneableType & readonly = external;
```
This depends on https://github.com/ballerina-platform/ballerina-lang/issues/23690

**Comment by KRVPerera** [comment]
`Cloneable` type is added and `clone` is also updated. `cloneReadOnly` is not yet updated because this requires creating new intersection from `TypeParamAnalyzer`. 
Since intersection with `readonly` creates a new type with effective types we cannot rely on bound types. 
The discussion lead to the idea of we must use consistent types to create a new type using their bound types first. Then use this type and take the intersection with readonly.

**Comment by MaryamZi** [comment]
Reopening this since https://github.com/ballerina-platform/ballerina-lang/pull/27909 only temporarily changed the signature of `cloneReadOnly` to 

```ballerina
public isolated function cloneReadOnly(CloneableType  v) returns CloneableType = external;
```

The return type needs to be changed to `CloneableType & readonly`.
