### ISSUE TITLE
Token minutiae modify only returns minutiae

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#24158]
**Description:**
I'm currently working on the formatter and using the token.modify() method to update minutiae and facing the below issue.
`token.modify(newLeadingMinutiaeList, newTrailingMinutiaeList)` method returns the updated token without the value. It only returns the minutiae.
![image](https://user-images.githubusercontent.com/16335290/84658438-88b55700-af33-11ea-86ea-34c1424ababe.png)

**Steps to reproduce:**

**Affected Versions:**
1.2.4

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by nadeeshaan** [comment]
@IrushiL can we check whether this particular issue is still there in the parser?

**Comment by sameerajayasoma** [comment]
Any update on this?  Please check the following test case for more details.
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/MinutiaeListAPITest.java

**Comment by IrushiL** [comment]
I went through the issue to verify if the problem still exists. Here the issue is actually seen when modifying a literal token. When modifying a token, the function given below is called.
https://github.com/ballerina-platform/ballerina-lang/blob/e29f3dcd344794e9c39d71a3cca6e5923b57016f/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/Token.java#L70
In an instance where the token is to be modified, the else section of the method given below is called to generate a new modified token.
https://github.com/ballerina-platform/ballerina-lang/blob/e29f3dcd344794e9c39d71a3cca6e5923b57016f/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/Token.java#L75
However, this generation creates a new Token without using the value of the existing token. This works fine for other SyntaxKinds such as keywords, types, etc. since they have defined string values. But in the case of literals, since the value is dynamic, the generated new token will be empty. AFAIU the following method could be called to generate the new token if the SyntaxType is of a literal type.
https://github.com/ballerina-platform/ballerina-lang/blob/e29f3dcd344794e9c39d71a3cca6e5923b57016f/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STAbstractNodeFactory.java#L95

This issue could be reproduced using the [MinutiaeListAPITest](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/MinutiaeListAPITest.java) that @sameerajayasoma mentioned by making the following adjustment to ensure that a literal token is modified.

Alter the https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/test/resources/tree/minutiae_test_04.bal test case to have a new line at the end of a literal token as follows. Since the test modifies all tokens to remove newline minutiaes from the tree, this literal will also be modified. The output will have something like `int x = ;`, dropping the integer value. 
```ballerina
function add() returns int {
    int x = 56
;
    int y = b;
    int z = a + b;
    return z;
}
```
