### ISSUE TITLE
Add before & after groups annotation

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#24925]
**Description:**
 Introduce another annotation to support running a configuration method before/after a defined set of test groups

**Steps to reproduce:**
N/A

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The suggested annotation for this would be `@BeforeGroups` and `@AfterGroups`. 
"Proposed Syntax:"
```ballerina
@BeforeGroups { 
     value : ["g1","g2"]
}
```

We have evaluated, two approaches for this:

1. Execute tests group-wise and run `@BeforeGroups` before the first test of the group is run and run the `@AfterGroups` after the last test of the group is executed.
**Limitation:** There can be a deadlock if the user adds `dependsOn` with a test belonging to another group.

2. Execute tests in the order defined in the file and run `@BeforeGroups` before the first test of the group is run and run the `@AfterGroups` after the last test of the group is executed.
**Limitation:** If the user defines tests in a random manner (where the groups are mixed up in terms of the order defined in the file), `@BeforeGroup` and `@AfterGroup` of another group may get executed before the tests of the one group has finished executed.

Both the limitations can be overcome if the user is careful enough, but IMO, we should adopt the second approach since resulting  in a deadlock will affect the performance where as mixing up the order will only result in the failure of tests which is acceptable. Also, since approach 2 is the way other test frameworks such as TestNG and Selenium has facilitated `@BeforeGroups`, the user would familiar with this approach and will have less chances of making mistakes.

**Comment by Dilhasha** [comment]
I'm +1 to following the 2nd approach too. IMO, user should have the ability to depend on tests belonging to other groups.

**Comment by Ibaqu** [comment]
+1 for the 2nd approach
