### ISSUE TITLE
Broken Link in the LDAP Module in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24985]
**Description:**
The "LdapConnection" link[1] below is broken in the LDAP module in API Docs when the link checker[2] is run.

<img width="1083" alt="Screenshot 2020-07-28 at 18 24 58" src="https://user-images.githubusercontent.com/11707273/88668010-b29b9500-d0ff-11ea-8ea0-34b93eb78db4.png">
<img width="1086" alt="Screenshot 2020-07-28 at 18 25 10" src="https://user-images.githubusercontent.com/11707273/88668015-b4fdef00-d0ff-11ea-9ebb-c0e59a7909c5.png">

- **For 1.2.x:** https://ballerina.io/learn/api-docs/ballerina/ldap/functions.html
- **For Swan Lake:** https://ballerina.io/swan-lake/learn/api-docs/ballerina/ldap/functions.html

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/ldap/records/LdapConnection.html
[2] https://www.brokenlinkcheck.com/broken-links.php#status

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
@praneesha Not sure, whether this is a bug in API doc generation tool. The referred record `ldap:LdapConnection` is an empty closed record, which has only native data.

```ballerina
# Represets the LDAP connection.
public type LdapConnection record {|
|};
```

So, the API docs for this record is not generated. That's the reason we get 401 here. Anyway I'll add the `instanceId` as a field of `ldap:LdapConnection` record, since it is the only field that can be useful.
