### ISSUE TITLE
Is there a way to check if a key exists inside a json object?

### ISSUE THREAD

**Issue by axewilledge** [ballerina-platform/ballerina-lang#24994]
**Description:**

I want to check if a key is exist in a JSON object. For an example

>     json[] exampleJson = 
>     [
>        {
>             "seat_count": 25,
>             "national_list_seat_count": 0,
>             "party_code": "Bar",
>             "party_name": "Bar bar"
>         },
>         {
>             "vote_count": 0,
>             "vote_percentage": "0.00%",
>             "seat_count": 18,
>             "national_list_seat_count": 0,
>             "party_code": "Foo",
>             "party_name": "Foo foo"
>         }
>     ]

>     io:println(exampleJson[0].vote_count)

Gives following error,

'error {ballerina/lang.map}KeyNotFound message=Key 'vote_count' not found in JSON mapping'

Is there a way to validate it. 

Example: 

> if(exampleJson[0].vote_count)
>   io:println(exampleJson[0].vote_count)

**Comment by MaryamZi** [comment]
Since you have a `json[]` each individual member may or may not be a JSON object (i.e., it can be a number, a string, an array, etc.). 

Once you validate that each member is indeed a JSON object (which is represented by a map of JSON `map<json>` in Ballerina) you can use the `hasKey` langlib method to check if the key exists.

For example,
```ballerina
    foreach json item in exampleJson {
        
        // Check if this member is a JSON object, if it is not, handle it. 
        // e.g., panic or return an error.
        if !(item is map<json>) { 
            // Handle non-JSON objects if needed.
            panic error("Expected a JSON object");
        }

        // We reach here only for a JSON object, so we can safely cast to a
        // `map<json>`
        map<json> mj = <map<json>> item;

        // Similar to a normal map, you can now check if the map contains
        // the key you need, and use the `get` langlib method to access the value.
        if mj.hasKey("vote_count") {
            json voteCount = mj.get("vote_count");

            // You can then check if `voteCount` is of the type you expect,
            // say `int`.
            if voteCount is int {
                // Here `voteCount` is an `int` and you can use it where an `int` 
                // is expected.
                int x = voteCount;
            }
        }
    }
```

The following examples explain JSON, JSON objects, JSON access, and maps.

- https://ballerina.io/learn/by-example/json.html
- https://ballerina.io/learn/by-example/json-objects.html
- https://ballerina.io/learn/by-example/json-access.html
- https://ballerina.io/learn/by-example/maps.html

**Comment by axewilledge** [comment]
Got it!!!
