### ISSUE TITLE
Address TODO's in the Lexer

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25147]
**Description:**

$subject

**Comment by lochana-chathura** [comment]
- Now there is only one TODO left in the lexer.

https://github.com/ballerina-platform/ballerina-lang/blob/a6a83619a98db093c66e1084ae43b668afab5cdb/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractLexer.java#L225

- Consider the following scenario also when fixing it. With PR #28752, the first character in the following example is parsed as a valid `isIdentifierInitialChar()`. I think it should be due to this remaining TODO.

![Screenshot from 2021-03-01 15-50-01](https://user-images.githubusercontent.com/39232462/109483935-d237d900-7aa5-11eb-8f47-3386907fb95d.png)
```bal
function foo() {
     int a;
}
```
