### ISSUE TITLE
Possible bug in `lock` statement support

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#25216]
**Description:**
Is this a bug in the lock support?  The variable `numbers` has a reference to the same array value referred by the variable `values`.

**Steps to reproduce:**
```ballerina
import ballerina/io;
int[] values = [];
int[] numbers = values;

public function main() {
    process();
    io:println("final array size - ", values.length());
}

function process() {
    @strand {thread: "any"}
    worker w1 {
        foreach var i in 1 ... 1000 {
            lock {
		        values[values.length()] = 1;
            }
        }
    }

    @strand {thread: "any"}
    worker w2 {
        foreach var i in 1 ... 1000 {
            lock {
		        values[values.length()] = 1;
            }
        }
    }

    @strand {thread: "any"}
    worker w3 {
        foreach var i in 1 ... 1000 {
            lock {
		        values[values.length()] = 1;
            }
        }
    }

    @strand {thread: "any"}
    worker w4 {
        foreach var i in 1 ... 1000 {
            lock {
		        // values[values.length()] = 1;
		        numbers[numbers.length()] = 1;
            }
        }
    }
    var result = wait {w1, w2, w3, w4};
}
```
Acutual output: 
```
final array size - 3728  // it should be 4000
```

**Affected Versions:**
Swan Lake Preview 2

**Comment by riyafa** [comment]
This issue is coming from the lock optimizer phase

**Comment by riyafa** [comment]
Earlier ballerina locks were global and one of the statement inside a lock needs to complete before proceeding to the next. This was overcome by the PR https://github.com/ballerina-platform/ballerina-lang/pull/22320 by which when two locks do not share the same global variables within them, they can then run parallely.

This is acheived by optimizing the previous global lock implementation. This optimization is done on the BIR and before the codegen phase. The equality of the global variables is determined in this phase by the equality of the java objects that represent these global variables. This has a flaw when the two global variables refer to the same object during runtime in the ballerina code. Because the references of two ballerina variables are not known till after code gen there is no simple way to solve this before runtime (as the references can be dynamically changed at runtime.)

Hence it is still unclear whether this is the expected behavior or if this is a bug in the implementations. What is the take on ballerina for references? References are manifested only at runtime so how should they be treated in the case of locks whereas locks are an inherent concept in Ballerina?
