### ISSUE TITLE
Revisit error recovery for function qualifiers 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25300]
**Description:**
Need to revisit error recovery for function qualifiers since

1. We have new qualifiers like `isolated` and the current model may not be scalable
2. There are several possibly related issues when there are errors
   - Bad, sad error on incomplete service source with `transactional function` - #25290 
   - Bad, sad error for duplicate function qualifiers - #25287 
   - Bad, sad error with missing `function` keyword and invalid qualifiers - #25261

**Comment by SupunS** [comment]
In the error handler, optional qualifiers are handled as: 
`{ REMOTE_KEYWORD, TRANSACTIONAL_KEYWORD,  ISOLATE_KEYWORD,  FUNCTION_KEYWORD }`. And then chained the next contexts as: `OBJECT_METHOD_WITHOUT_REMOTE`, `OBJECT_METHOD_WITHOUT_TRANSACTIONAL`, etc.

Problem with this is introducing a new qualifier requires adding many new alternative rules to tackle the all possible combinations. Also that increases the amount of paths to traverse.

We can avoid this if we can chain the contexts based on position of the qualifier rather than the qualifier itself.
eg:  starting context: `{ FIRST_QUALIFIER, FUNCTION_KEYWORD}`, and next context after the first qualifier is `{ SECOND_QUALIFIER, FUNCTION_KEYWORD}`

**Comment by lochana-chathura** [comment]
> Another concern with qualifier recovery is,
> 
> * Ideally, error handler should not perform INSERT action on qualifiers. (as qualifiers are always optional, there's always a better path).
> * But, if error handler pick such path as optimal path due to unprecedented reason that could lead to an infinite loop.
> * In order to avoid such scenario insert token for a qualifier context should always point to whatever the "end of qualifier parsing token". We have done this in many places. Need to check all places.

@rdulmina with fail safe mechanism, parser should not crash for above scenario right?

**Comment by rdulmina** [comment]
> > Another concern with qualifier recovery is,
> > 
> > * Ideally, error handler should not perform INSERT action on qualifiers. (as qualifiers are always optional, there's always a better path).
> > * But, if error handler pick such path as optimal path due to unprecedented reason that could lead to an infinite loop.
> > * In order to avoid such scenario insert token for a qualifier context should always point to whatever the "end of qualifier parsing token". We have done this in many places. Need to check all places.
> 
> @rdulmina with fail safe mechanism, parser should not crash for above scenario right?

Yes it will fail safe
