### ISSUE TITLE
Add an API to find the definition of a given symbol 

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25365]
**Description:**
Input is a cursor position/ text position

**Comment by pubudu91** [comment]
Had a chat with @nadeeshaan about this. It looks like this requirement is pretty much covered by the symbol at cursor API. If we add the position info to the public API of the symbol, then this requirement is covered I think.

**Comment by SupunS** [comment]
> Had a chat with @nadeeshaan about this. It looks like this requirement is pretty much covered by the symbol at cursor API. If we add the position info to the public API of the symbol, then this requirement is covered I think.

+1 for adding position info to the new symbol API

**Comment by nadeeshaan** [comment]
> Had a chat with @nadeeshaan about this. It looks like this requirement is pretty much covered by the symbol at cursor API. If we add the position info to the public API of the symbol, then this requirement is covered I think.

However, we have to reflect a couple of concerns with this definition API as well as the symbol API,
If we consider the type guard behaviour, then a symbol's effective type and similar information is different than it's definition's. Therefore IMHO, we have to address that differentiation with the APIs as well

**Comment by pubudu91** [comment]
For type narrowed symbols, the point of definition is still the same definition as the original symbol's definition right (since the type narrowed symbol is an internal implementation detail used to support type narrowing)? If we go by that notion, it's reasonable to set the position of the original symbol as the position of the type narrowed symbol. WDYT?

The effect of this on the API user would be that the user will not be able to distinguish between a symbol and its type narrowed counterpart except by checking the type of the symbol. I guess that's ok right?

**Comment by nadeeshaan** [comment]
As long as the APIs expose the relevant information this is OK to proceed, for an example,

Go to Definition will use the definition API and the origin of the request can be from the type narrowed counterpart, but the API user does not need to know the internal resolving and it output the original symbols position which is the expected. Hence this is OK to follow as long as the user APIs hides it.

**Comment by pubudu91** [comment]
This behaviour was implemented in PR #26072. Verified the above described behaviour for type narrowed symbols as well. Hence closing this issue.
