### ISSUE TITLE
Bug in nil type when initialed as a finite type

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#25371]
**Description:**
$subject. This affects the implementation of the match-stmt

**Steps to reproduce:**
```
import ballerina/io;
const CONST3 = ();

public function main() {
    any v = CONST3;
    if (v is CONST3) {
        io:print("Match"); // should match
    }
}
```

**Affected Versions:**
ballerina-slp3

**Comment by MaryamZi** [comment]
This happens because the runtime type checker's assignability rules for finite types is based on types rather than values - io.ballerina.runtime.internal.TypeChecker#checkIsFiniteType - https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L1556

The check needs to be updated to check by value.
