### ISSUE TITLE
Class not found when generating code coverage report

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#25399]
**Description:**
$subject
```
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/niveathika/WSO2/module-ballerina-java.jdbc/java.jdbc-ballerina/target/coverage/ballerina-java.jdbc-0.5.0-testable.jar/ballerina/java.jdbc
        at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:76)
        at org.ballerinalang.test.runtime.entity.CoverageReport.generateReport(CoverageReport.java:78)
        at org.ballerinalang.test.runtime.CoverageMain.main(CoverageMain.java:47)
Caused by: java.nio.file.NoSuchFileException: /home/niveathika/WSO2/module-ballerina-java.jdbc/java.jdbc-ballerina/target/coverage/ballerina-java.jdbc-0.5.0-testable.jar/ballerina/java.jdbc
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at org.ballerinalang.test.runtime.util.CodeCoverageUtils.copyClassFilesToBinPath(CodeCoverageUtils.java:96)
        at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:73)
        ... 2 more
```

The class seems to be generated under `/home/niveathika/WSO2/module-ballerina-java.jdbc/java.jdbc-ballerina/target/coverage/ballerina-java.jdbc-0.5.0-testable.jar/` and not under further directories of org & module as the error expects

**Comment by chamil321** [comment]
This is reproducible when the ballerina project contains multiple modules and run the following test command with code coverage.
```
src
│   ├── cors
│   │   ├── main.bal
│   │   ├── Module.md
│   │   ├── resources
│   │   └── tests
│   │       ├── main_test.bal
│   │       └── resources
│   ├── gtt
│   │   ├── main.bal
│   │   ├── Module.md
│   │   ├── resources
│   │   │   ├── MockClient_functions.json
│   │   │   └── ReceivedFile.txt
│   │   └── tests
│   │       ├── main_test.bal
│   │       └── resources
```
command
`ballerina test --all --code-coverage`

**Comment by Ibaqu** [comment]
I managed to reproduce the issue with the same exception under particular conditions when using the `--code-coverage` flag

From what I have tested, **the exception occurs when there are no '.bal' files in the module to generate the code coverage**.
The code-coverage flag is used to generate a code-coverage report on the '.bal' files we are trying to test in the **current module.**

In the current implementation
- **If a file doesn't exist in the module, it throws this exception.** 
This includes empty '.bal' files as well
It works if you simply add a `main.bal` file with some code in it, so that the code-coverage can pick it up and generate a report.
- **It does not generate a report if you have your code in one module and tests in another module**. 
For example, consider having 2 modules : `Module1` and `Module1_Test`. We can write tests in 'Module1_Test' by importing the 'Module1' in the tests folder and writing passable tests. 
However, if we include the '--code-coverage' flag, the report generated is going to be on a module basis. So the coverage report for `Module1_Test` will not include the code present in `Module1`.


From what I understand, a solution to this issue would be a check to see if the module we are trying to generate the code-coverage report for has '.bal' files to use as a reference, and if it doesnt exist to throw an error. @azinneera wdyt?

**Comment by azinneera** [comment]
@Ibaqu 

> I managed to reproduce the issue with the same exception under particular conditions when using the `--code-coverage` flag
> 
> From what I have tested, **the exception occurs when there are no '.bal' files in the module to generate the code coverage**.
> The code-coverage flag is used to generate a code-coverage report on the '.bal' files we are trying to test in the **current module.**
> 
> In the current implementation
> 
>     * **If a file doesn't exist in the module, it throws this exception.**
>       This includes empty '.bal' files as well
>       It works if you simply add a `main.bal` file with some code in it, so that the code-coverage can pick it up and generate a report.
> 
>     * **It does not generate a report if you have your code in one module and tests in another module**.
>       For example, consider having 2 modules : `Module1` and `Module1_Test`. We can write tests in 'Module1_Test' by importing the 'Module1' in the tests folder and writing passable tests.
>       However, if we include the '--code-coverage' flag, the report generated is going to be on a module basis. So the coverage report for `Module1_Test` will not include the code present in `Module1`.
> 
> 
> From what I understand, a solution to this issue would be a check to see if the module we are trying to generate the code-coverage report for has '.bal' files to use as a reference, and if it doesnt exist to throw an error. @azinneera wdyt?

@Ibaqu IMO, without throwing an error, we can print a warning saying there are no source files found in the module and continue the execution. So when the user runs the command with `-a` flag, the other modules will continue to execute and its just the report that would not have the code coverage info of the module that doesnt have any source files.

**Comment by niveathika** [comment]
I am getting this even when the above conditions are not there. There is only one module and it has a bal file.

Could we check this for module-ballerina-java.jdbc? 
https://github.com/ballerina-platform/module-ballerina-java.jdbc/blob/master/java.jdbc-ballerina/build.gradle#L175

**Comment by Ibaqu** [comment]
An improvement to the Code Coverage report which generates reports based on source files from other modules may be tracked in this issue : https://github.com/ballerina-platform/ballerina-lang/issues/25791

**Comment by niveathika** [comment]
@Ibaqu This issue is fixed, however when I try to generate the report, it shows as coverage as 0%
![Screenshot from 2020-09-15 19-27-00](https://user-images.githubusercontent.com/27669465/93220842-a7bdc200-f78a-11ea-99a7-77bbc817f905.png)
