### ISSUE TITLE
Bad sad error when specifying invalid key

### ISSUE THREAD

**Issue by bidalaka** [ballerina-platform/ballerina-lang#25443]
**Description:**
The bad sad error happens when compiling code which specifies an invalid field name for the table key. ballerina-internal.log is attached.

**Steps to reproduce:**

Specify a key which does not actually exist in the table record.

````
type TableRec record {
    readonly int a;
    string b;
    float c;
};

type TestTable table<TableRec> key(id);
````

**Affected Versions:** Observed when using slp3.

**OS, DB, other environment details and versions:** macOS Mojave 10.14.6, running `ballerina build` from the command line.

**Related Issues (optional):** None

**Suggested Labels (optional):** slp3

**Suggested Assignees (optional):**

[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/5131335/ballerina-internal.log)

**Comment by lasinicl** [comment]
This is fixed in the latest preview version SLP5. Hence closing the issue.
Additional information
```
type TableRec record {
    readonly int a;
    string b;
    float c;
};

type TestTable table<TableRec> key(id);

public function main() {
    TestTable tab = table [
      { a: 1, b: "B", c: 12.23 }
    ];
}
```
If you construct a `table` using the `TestTable` `table` type as given above, you'll get the following compilation error.
`field name 'id' used in key specifier is not found in table constraint type 'TableRec'`
