### ISSUE TITLE
Disable stdlib dependent bindgen tests

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25600]
**Description:**
As a part of stdlib migration(https://github.com/ballerina-platform/ballerina-lang/issues/21313), we had to disable the following bindgen tests which depend on stdlibs.

https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/2e88f2c62ae3b91a7368ca2a9eb642d66b20c624

**Comment by IrushiL** [comment]
This disabled integration test needs to be added inside the [ballerina-distribution](https://github.com/ballerina-platform/ballerina-distribution) repository since it depends on the [ballerina/jarrays](https://github.com/ballerina-platform/module-ballerina-java.arrays) standard library module. 

However, we could keep a simple integration test that does not require the [ballerina/jarrays](https://github.com/ballerina-platform/module-ballerina-java.arrays) module inside the [ballerina-lang](https://github.com/ballerina-platform/ballerina-lang) repository in order to immediately identify breaking changes that could happen inside the [ballerina-lang](https://github.com/ballerina-platform/ballerina-lang) repo.
