### ISSUE TITLE
Symbol at cursor not working for constant refs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#25841]
Consider the following snippet:
```ballerina
string s = foo:TRUE; 
```
In the above, the constant ref `foo:TRUE` gets replaced by the actual value of the constant (in this case, `"true"` literal) during the constant propagation phase. The result of this is that if we try to lookup the symbol at a position which falls within the `foo:TRUE` reference, the API returns `null`.

**Comment by SupunS** [comment]
This might work for ref-type constants (e.g: map constants), because IIRC those are used by the 'reference' rather than replacement, because the constants needs to be referring to the same value across the entire runtime. 
Probably we could do the same for the constants of basic types as well.

Theres a similar requirement in https://github.com/ballerina-platform/ballerina-lang/issues/26139 for preserving the original variable at the runtime.
