### ISSUE TITLE
A extra newline gets added every-time the code is formatted

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#26002]
**Description:**
Sample code
```ballerina
public function main() {
}
```
Output after formatting the code for five (5) times: 
```ballerina
public function main() {

}





```

Note the extra 5 newlines at the end of the file.

**Comment by SupunS** [comment]
Now a newline gets added and removed, with each format-all operation.

**Comment by sanjana** [comment]
The root cause for this issue is that, [`syntaxTree.rootNode().lineRange()`](https://github.com/ballerina-platform/ballerina-lang/blob/70c5342829156da8525211726b1548d2ad018271/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java#L530) is being incorrectly calculated in the initial call of following type of example:

```
public function main() {
}

```

Here the ending line number of the `lineRange` is miscalculated as **1**. 
This incorrect value is then preserved by caching, and the same incorrect value is being used within the subsequent calls to `.lineRange()`.
