### ISSUE TITLE
Multiple lines in Markdown parameters [Syntax tree]

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#26026]
**Description:**
When there are multiple lines in parameter documentation, the extra lines are identified as `MarkdownDocumentationLines` not `MarkdownParameterDocumentationLines` in the Syntax Tree.

**Steps to reproduce:**
Have the following code in a bal file
```
# Returns the next element in the stream wrapped in a record or () if the stream ends.
#
# + strm - The stream
#          next line.
# + return - If the stream has elements, return the element wrapped in a record with single field called `value`,
#            otherwise returns ()
public isolated function next(stream<int, string> strm) returns record {| int value; |}|string?|Person|int {
}
```
![Screenshot from 2020-09-23 13-41-00](https://user-images.githubusercontent.com/33398983/93985265-72286280-fda2-11ea-875c-458999d1b7ab.png)

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

@SupunS

**Comment by SupunS** [comment]
This is the expected behaviour. If you have something like below:
```ballerina
# + paramName - docLine1
#        docLine2
# docLine3
```
`MarkdownParameterDocumentationLines` refers to any line starts with a parameter name. e.g: `+ paramName - docLine1`.
`MarkdownDocumentationLines` refers to any line that starts with anything other than a paramter or the return type.
Syntactically, these are simply two structures that represent a line of code (rather a documentation line) in the syntax tree.

However, building a relationship between two lines, is up to the user makes use of the syntax tree.

**Comment by SupunS** [comment]
Adding some more context: 

We cannot merge these document lines at the parser level or at the syntax-tree level, because syntax-tree supposed to be a concrete representation of the source code, and should be able to reproduce the source-code from the syntax-tree. However, if we do any sort of merging at the syntax-tree level, then it no longer represents the source code as is, and becomes impossible to produce back the source-code.
