### ISSUE TITLE
Semantic API's visibleSymbol API drops function symbols

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#26317]
**Description:**
Consider the following source,

```
public function testFunction() {
    if <cursor>
}

function doSomeTask() {
    // todo: here goes a certain task
}

```

In the given cursor position, `doSomeTask` function should be visible

**Comment by pubudu91** [comment]
This turns out to be because of how the parser recovers the above incomplete program. It takes the `doSomeTask()` function and models it as a lambda function. That's why the `doSomeTask()` function's symbol is not visible at the given cursor position.

**Comment by lochana-chathura** [comment]
If we flip the order of `testFunction` and  `doSomeTask` it works.

The problem is when `testFunction` is followed by another top-level construct.  We go to recovery at the cursor position and find some matches within the next top-level construct. (In this case, find matches within `doSomeTask()`).

I think we have to special case this kind of scenario in the parser considering the user's point of view. 
Usually, when I write a function, I always write the `{ }` first and then start typing inside the block. I think LS snippet completion also does the same.

So we have to special case the `}` of `testFunction` when going to recovery.

**Comment by nadeeshaan** [comment]
> If we flip the order of `testFunction` and `doSomeTask` it works.
> 
> The problem is when `testFunction` is followed by another top-level construct. We go to recovery at the cursor position and find some matches within the next top-level construct. (In this case, find matches within `doSomeTask()`).
> 
> I think we have to special case this kind of scenario in the parser considering the user's point of view.
> Usually, when I write a function, I always write the `{ }` first and then start typing inside the block. I think LS snippet completion also does the same.
> 
> So we have to special case the `}` of `testFunction` when going to recovery.

Agree with the approach. Also, we have to consider the following usecase as well.

```
function testFunction2() r<cursor>

function testFunction1() {
}
```

The above cursor position also identified as a variable declaration. Shall we consider the above as well?WDYT? I feel like this is a similar issue.

**Comment by lochana-chathura** [comment]
> The above cursor position also identified as a variable declaration. Shall we consider the above as well?WDYT? I feel like this is a similar issue.

yeah. Let's fix that use case as well. Some tests are failing with this change. Have to go through them one by one. 
Will send a separate PR with #28736.
