### ISSUE TITLE
Document this action adds a completely new documentation for an already documented function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26509]
Refer to the following:
![Peek 2020-10-22 15-32](https://user-images.githubusercontent.com/6260009/96857285-6fda2680-147c-11eb-9159-6de4e83191ff.gif)

Also note how I had to place the cursor on the documentation string to get the code action for the second time.

**Comment by rasika** [comment]
Ideally in this case, you should get `Update Documentation` code-action but since it depends on the documentation warnings. Since here we have a semantic error in line3, documentation analyzer compiler phase is not executed. Thus, rather keeping user choice-less, we are showing `Add Documentation` code-action(even it already has docs) which results adding a new documentation. Hence, fix is blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/28872.

**Comment by IMS94** [comment]
This is fixed in master
