### ISSUE TITLE
Type info of a JSON object's field name missing when compile errors are present

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26628]
Consider the following:
```ballerina
function testStructuralConstructors() {
    json j = {name: "Jane Doe", age: 25};
}

function testMiscExprs() {
    int x = -20;
    int y = 10 * 20 / 5;
    int z = 10 + 20 - 5;
    boolean b = y >= z;
    anydata ad = "foo";

    string greeting = ad == "" ? "Hello" : "Hello " + ad; // error here
}
```
When checking the type of the `name` field in the above JSON, the type is `null`. But when you fix the compile error, it correctly gives the type as `string`.

**Comment by sanjana** [comment]
The type of the `name` is set at the Desugaring phase as an internal detail. And the type of the value of its field (`"Jane Doe"`) is set at the TypeChecker phase. 
When there's a compilation error at the TypeChecker phase, the compilation process halts and does not proceed through the other phases.
It would also not be best to consider the `name` JSON field as a symbol. 
Since the Desugaring phase is not needed to be visited in the Semantic API, this issue shall be closed.
