### ISSUE TITLE
Semantic model symbol returns empty for constant references

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#27152]
**Description:**
Semantic model symbol function returns empty for constant references.

**Steps to reproduce:**
1. Have the following code
```
public const TIME_DELTA_START = "TIME_DELTA_START";
public type TimeDeltaStart [TIME_DELTA_START, int];

public type Human record {|
    string HumanName;
    int age = 25;
    KeyAlgorithm algo;
|};
public type KeyAlgorithm RSA;
public const RSA = "RSA";

```

2. Get symbol of TIME_DELTA_START in TimeDeltaStart.
3. Get symbol of KeyAlgorithm in Human record.
4. Get symbol of RSA in KeyAlgorithm type.
5. All the above will return null.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
The issue here is that when you use a constant when defining a type, it is used as a type. For that usage, we internally create a new typedef with a finite type. When symbol entering the above type defs, it resolves the given constant refs and gets a finite type as the resolved type. We lose the access to the constant symbol.
