### ISSUE TITLE
Debug server connection is failing in vscode with latest update tool version 

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#27288]
**Description:**
We have observed that the vscode debug client is unable to connect with the ballerina debug server, only when using the latest ballerina update tool versions (SLP5 and SLP7).

This could be overcome by the following workarounds:
1. Use ballerina zip distribution.
2. Set ballerina home in VS Code settings after installing Ballerina via installers.

**Steps to reproduce:**
- Install Ballerina via installers(Linux, Windows or macOS).
- Create a simple `hello word` program.
- Add a debug point inside code.
- Run the program in debug mode.

**Affected Versions:**
```
Ballerina Swan Lake Preview 7
Ballerina Swan Lake Preview 5
```

**Comment by NipunaRanasinghe** [comment]
After some debugging, we found out that some of the java debugging library modules required to run the ballerina debug server are not bundled in the new platform JREs we are using (AdoptOpenJRE 11.0.8).

Therefore considering all the possible solutions we have right now,

1. Adding the missing library as a jar dependency
This seems not feasible with the new modular approach introduced for java 9+ versions, where the JDK standard library modules are now served in JMOD format instead of JARs.(In JDK8, these debugger libraries are bundled inside the JDK's tools.jar and therefore could be used as a jar dependency).

2. Modifying the distribution to use platform JDKs instead of JREs
This approach would be straightforward, but will also increase the distribution size. (11.0.2 JRE ~ 130MB and 11.0.2 JDK ~ 310MB)

3. Creating a custom modular runtime image for Ballerina, including the missing libraries
With the help of new in-built JLink tool and the java module system, developers are encouraged to build custom JREs which contain only the relevant standard libraries and external dependencies for their applications. These custom JIMAGEs are intended to be more time and space-efficient than the original legacy JAR format, reducing startup times(Even Oracle JDK11 has excluded the standard JRE they've been offering, enforcing the developers to create smaller custom runtimes). 

IMO option 3 might be the optimized solution, which also requires some effort as we'll need to create workflow to generate custom JREs for all the platforms that we currently support (Linux, Windows and macOS).

**Comment by NipunaRanasinghe** [comment]
Update: I'm currently working on creating release pipelines to generate custom ballerina runtime JREs as discussed with the team.

**Comment by NipunaRanasinghe** [comment]
Closing since this issue is fixed after introducing custom JRE to be bundled with ballerina distribution. The fix is shipped with Swan Lake Alpha release. (Ballerina custom JRE repository: ballerina-platform/ballerina-lang#27950)
