### ISSUE TITLE
Service Symbol is not visible in Semantic Model

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#27493]
**Description:**
Cannot retrieve compiler API Service Symbol details from the Semantic Model.

**Usecase:** List services details for the project packages API in LS. (Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/27488) 

**Steps to reproduce:**
`module.getCompilation().getSemanticModel()` cannot be used to retrieve Service and Resource details.

**Affected Versions:**
SLP 8

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
So we had an offline discussion regarding this yesterday. And the proposed solution for this was to rely on the syntax API instead to find out the service declarations and generate names for the services. Something like `service /path/to/service on someListener`. There won't be a symbol available for service declarations.

**Comment by rasika** [comment]
@pubudu91 thanks for the update. This issue is also related to the mail discussion with $subject "Missing Symbol representation for Services". Any idea on how to achieve below requirements?

1. Service is a documentable construct. Parsed documentation `MarkdownDocAttachment/BallerinaDocumentation` in Service Symbol ? - this is required for the CodeActions
2. [Type Descriptors](https://ballerina.io/spec/lang/master/#section_8.3.2) of the service level path parameters? - this is required for the code completion suggestions and code actions.

**Comment by rasika** [comment]
@pubudu91 can we prioritize this limitation for the the post-alpha?

**Comment by pubudu91** [comment]
Sure, will try to get the others' opinions as well before proceeding. Need to come to an agreement on what's the best possible path to take on this, as mentioned in https://github.com/ballerina-platform/ballerina-lang/discussions/27906
