### ISSUE TITLE
Incorrect file path while opening errors

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#27618]
**Description:**
Incorrect path is picked up for the files that are located inside modules (non default modules).
<img width="1160" alt="Screenshot 2020-12-21 at 16 58 19" src="https://user-images.githubusercontent.com/5234623/102773068-9f3ede00-43ae-11eb-8b56-1140fad38a6e.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SLP8

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
This issue is happening since the module compilation aggregate the diagnostics captured in the imported modules. Ideal solution for the language server is to use the `ProjectCompilation` and access the diagnostics from there. This has been blocked by https://github.com/ballerina-platform/ballerina-lang/issues/27231

**Comment by rasika** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/27925
