### ISSUE TITLE
Variables outside of a lambda function are not shown in debugger

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#27738]
**Description:**
$subject

<img width="1128" alt="Screenshot 2021-01-08 at 14 26 19" src="https://user-images.githubusercontent.com/4398820/104006228-36d46700-51cc-11eb-986f-ecb379880d6a.png">

**Steps to reproduce:**
Put a breakpoint inside a lambda function. You will see that the variables outside the lambda function are not shown.
[github-main.txt](https://github.com/ballerina-platform/ballerina-lang/files/5786693/github-main.txt)

**Affected Versions:**
SLP8

**OS, DB, other environment details and versions:**
Mac

**Comment by NipunaRanasinghe** [comment]
@riyafa Please note that this issue is still not resolved, as only the variables that are being used inside the lambda function are getting passed using the variable map. Therefore the rest of the variables are still not visible within the lambda function scope.

**Comment by riyafa** [comment]
@NipunaRanasinghe we had an internal discussion and we came to understand that this issue is not directly relevant to runtime. This can be fixed by saving the variables from before the lambda as readonly and providing a view of them later when debugging inside the lambda. It has to be done at the debugger end. The variables that are passed to the lambda functions can be changed, hence they are made available via the local variable table from my PR.  
I will removing the `Team/jBallerina` label from this issue, please let us know if required.

**Comment by praveennadarajah** [comment]
After having an internal discussion with the runtime team, it is decided to show only the lambda function's scope variables inside the lambda function. This behaviour is expected. If we want to see the variables outside the lambda function, we can simply click the respective stack frame on the call stack and see the visible variables.

This can be achieved after the improvement https://github.com/ballerina-platform/ballerina-lang/issues/31804.

Therefore closing this issue.
