### ISSUE TITLE
[Debugger] Variable declaration breakpoints get missed

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#27748]
**Description:**
Variable declaration breakpoints get missed as following screenshot where it has missed line 21 and 24 was hit. 
If i put a break point to 22 it will hit there.

<img width="574" alt="Screenshot 2021-01-07 at 15 43 07" src="https://user-images.githubusercontent.com/2918812/104026447-ecfb7900-51eb-11eb-8673-de9035800a33.png">

**Comment by NipunaRanasinghe** [comment]
Consider the below code sample.

```ballerina
L1 import ballerina/http;
L2 import ballerina/io;
L3
L4  public function main() returns error? {
L5      http:Client httpClient = 
L6                check new ("https://api.github.com/");
L7      http:Response resp = 
L8                check httpClient->get("/orgs/ballerina-platform/repos");
L9      io:println(resp.statusCode);
L10 }
```

When observing from the debugger side, it was found that the L5 and L7 are not added to the source line number table and therefore having a debug hit is not possible. However, considering a similar context in java (when LHS and RHS of an assignment statement are split into 2 lines), both of the lines are getting added into the source line number table so that both lines get hit. 

So is this current behaviour is expected in Ballerina runtime (by design) or could this be a potential runtime bug?

**Comment by warunalakshitha** [comment]
IMO both lines should have added to the line number table So I think we need to fix it.

**Comment by gabilang** [comment]
For these kind of scenarios, we don't need to add both lines to the line number table. The current behavior is expected since we are adding line numbers to the line number table based on the instructions (non-terminator or terminator) and for the compiler, these two-line variable assignment is considered as a single instruction. So IINM, we can't add both lines to line number table. For the similar contexts Java also not adding both line numbers to the line number table.

**Comment by warunalakshitha** [comment]
Remove the jballerina label as per last comment from @gabilang . @NipunaRanasinghe Please note.

**Comment by NipunaRanasinghe** [comment]
> For these kind of scenarios, we don't need to add both lines to the line number table. The current behavior is expected since we are adding line numbers to the line number table based on the instructions (non-terminator or terminator) and for the compiler, these two-line variable assignment is considered as a single instruction. So IINM, we can't add both lines to line number table. For the similar contexts Java also not adding both line numbers to the line number table.

@gabilang Somehow the vscode java debugger seems to be capable of capturing both of the lines in similar contexts (e.g. assignment statements which span over multiples lines).

https://user-images.githubusercontent.com/29032600/128661925-8d9d060b-5c3f-45eb-9ce6-acf31261828a.mov

**Comment by NipunaRanasinghe** [comment]
After the offline discussion with @gabilang, it was decided to keep the existing behaviour since otherwise, it will be too complicated to handle similar scenarios where a statement/expression is split into multiple lines (even vscode java debugger cannot provide reachable breakpoints for all the lines in similar contexts). 

However, we can check the feasibility of introducing `verified breakpoints`, where the breakpoint gets validated at the runtime and indicates if it's a reachable breakpoint. https://github.com/ballerina-platform/ballerina-lang/issues/34438 is created to track the progress and with this improvement, users will be able to verify whether their breakpoints are reachable or not beforehand.
