### ISSUE TITLE
[Semantic API] Type of enums returned as UNION

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#27804]
**Description:**
When we have reference to a enum, the semantic api returns the type as a UNION.
We have added enums to docs, and need this functionality to recognize enums in order to create links.

**Steps to reproduce:**
1. Have the following code
```
public enum LogLevel {
    DEBUG,
    ERROR,
    INFO,
    TRACE,
    # log level of warn
    WARN,
    ALL,
    # Turn off logging
    OFF
}
public type TestRecord record {
    boolean http2PriorKnowledge = false;
    LogLevel lvl;
};
2. Get the symbol of LogLevel in TestRecord.
3. TypeDescriptor.kind() returns `UNION`

```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
@shehan360 I had a look at this. This is actually by design. The spec defines enums as follows:
```
module-enum-decl :=
   metadata
   [public] enum identifier { enum-member (, enum-member)* }
```
The [spec also says](https://ballerina.io/spec/lang/master/#section_8.9) the following:

> The identifier is defined as a type in the same was as if it had been defined by a module-type-defn, with the type-descriptor being the union of the constants defined by the members.

So the above enum is actually the same as 
```ballerina
public const DEBUG = "DEBUG";
public const ERROR = "ERROR";
public const INFO = "INFO";
public const TRACE = "TRACE";
public const WARN = "WARN";
public const ALL = "ALL";
public const OFF = "OFF";

public type LogLevel DEBUG|ERROR|INFO|TRACE|WARN|ALL|OFF;
```

This is why when you call `typeDescriptor()` on an enum type ref you get a union type descriptor.

At the moment, to get the associated enum symbol, you look it up by passing the location in the type ref symbol to `symbol()`. I initiated a discussion on whether to add a back reference to the type def as well: https://github.com/ballerina-platform/ballerina-lang/discussions/27980

**Comment by shehan360** [comment]
There are several broken links in api docs due to this issue. It would be great if we can get a fix for this.

**Comment by pubudu91** [comment]
Doesn't the above mentioned approach work? You don't need to get the typedesc of the type ref of an enum right?

**Comment by pubudu91** [comment]
As mentioned in https://github.com/ballerina-platform/ballerina-lang/discussions/27980, we decided to add a method to `TypeReferenceTypeSymbol` to get the definition symbol associated with the type ref. This would solve this issue as well right?

**Comment by shehan360** [comment]
> As mentioned in #27980, we decided to add a method to `TypeReferenceTypeSymbol` to get the definition symbol associated with the type ref. This would solve this issue as well right?

Yes I think it will resolve the issue.
