### ISSUE TITLE
Code actions doesnt appear when there's an error

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#27936]
**Description:**
`Document this` and `Update document` code actions/lens don't appear when there's a compilation error in the source. Only the 'Document all' action is available leaving no way to add/update docs for a particular function.

Also, there's a small inconsistency with the code lens as it allows aggregated documents if we click on it multiple times before it disappears. This was only observed in a slow client setup.

**Steps to reproduce:**
```
# Description
#
# + c - Parameter Description
# + return - Return Value Description  
public function getMessage(string d) returns string {
    string a = "a";
    string b = "b"
    return "Hello, World!";
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**
SLP9

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rasika** [comment]
@prabushi this is due to a design decision of the compiler phase runner. When there's errors in CODE_ANALYZE phase it won't be continued to other phases such as DOC_ANALYZER...etc. Since update doc code-action is based on diagnostic messages in DOC_ANALYZER phase it won't appear. I raised this concern sometimes back. Will initiate a discussion on git as well.

**Comment by rasika** [comment]
Started a discussion https://github.com/ballerina-platform/ballerina-lang/discussions/2793

**Comment by IMS94** [comment]
Both code lens and code action is shown with a compiler error now. Used the following example:
```
public function getMessage(string d) returns string {
    string a = "a";
    string b = "b"
    return "Hello, World!";
}
```
