### ISSUE TITLE
Create variable code action not available for new expression

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#28088]
**Description:**
$subject.

![Screenshot from 2021-01-22 09-33-07](https://user-images.githubusercontent.com/39232462/105445461-009bea80-5c96-11eb-9fdf-98356e75b93c.png)

**Comment by nadeeshaan** [comment]
One issue we are having related to the developer experience here is how many options are we gonna suggest. If we have multiple class definitions with the same init signature, then it is not scalable.

**Comment by rasika** [comment]
This is not possible since we don't have any clue on what type will be returned or what really user want to be created. Create variable code actions only suggested on top of the `assignment required` diagnostic message. Thus closing this issue. Feel free to reopen if you need further clarifications.
