### ISSUE TITLE
No suggestion for variables when trying to use them inside records

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#28097]
**Description:**
When trying to refer to a function variable inside a record that is inside the function no suggestion is shown:
![suggestions3](https://user-images.githubusercontent.com/8238078/105436533-6633ab00-5c85-11eb-94f5-6b3db5244d7a.gif)
Here result is not suggested when typing

**Comment by nadeeshaan** [comment]
This is the default behaviour of VSCode editor itself for not triggering the auto-completion when a snippet is active. In order to override the behaviour, add the following config option to the user settings.

`"editor.suggest.snippetsPreventQuickSuggestions": false`

Hence closing the issue. If you observe this even after the config, please reopen
