### ISSUE TITLE
[Formatter] Formatting doesn't work properly when a part of the string is in a different line

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#28106]
**Description:**
Please consider the following scenario
![Screenshot from 2021-01-22 12-22-52](https://user-images.githubusercontent.com/19838787/105457309-993d6500-5cac-11eb-9c91-f9cbaa647e39.png)

When I format the above code snippet additional spaces are added to the string values as given below.
![Screenshot from 2021-01-22 12-24-06](https://user-images.githubusercontent.com/19838787/105457424-d0ac1180-5cac-11eb-8011-3053fafe45da.png)
 

**Steps to reproduce:**

**Affected Versions:**
SLP9-snapshot
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
The code snippet given in the above scenario is parsed into a syntax tree with diagnostics containing multiple missing tokens. In simple terms, this is considered an invalid code by the parser. In a scenario like this, the formatter will not be able to format the code as implied in the issue description since there could be multiple different approaches to how the code could actually be formatted. 

However, if the intention was to use multiline strings, the user could either use `\n` or a string template for this purpose.

On a separate note, there is an improvement that could be configured into the IDE to automatically add the additive operator and the respective quotes for string concatenation when pressing `Enter` in the middle of a string. This is available in IntelliJ and the following issue [1] is created to track this implementation in VSCode. 

[1] https://github.com/ballerina-platform/plugin-vscode/issues/215

**Comment by hasithaa** [comment]
I think Formatter shouldn't format this code because it is a syntax error.
