### ISSUE TITLE
[Query expression] Variable declared in from clause is not suggested in successive clauses

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28199]
**Description:**
![querySuggest](https://user-images.githubusercontent.com/15815199/105698451-e713d080-5f2b-11eb-8502-66d4e0991526.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
Currently we are having issues at the semantic API to capture such symbols since the parser generated symbol is not consistent.

**Comment by pubudu91** [comment]
Had a closer look at this. It looks like we have to handle these query expr related nodes the same way as we treat block stmt, function body node, match pattern etc. Since these nodes have their own scope, need a way to keep track of the symbols defined in these scopes. Typically we define symbols in another symbol's scope (e.g., var symbols in a function body gets defined in the enclosing invokable symbol's scope). There are couple of exceptions such as block stmt as I mentioned for which we define maintain the scope within that particular node itself, since there isn't a symbol associated with a block stmt. If we don't maintain the scope at the node, then, when we are rebuilding the symbol envs starting from the package symbol, we miss out on such symbols which have a scope which isn't associated with a symbol.

**Comment by pcnfernando** [comment]
Observing the same with Alpha 2. LS side improvement pending

**Comment by nadeeshaan** [comment]
Fixed by #29386. Hence closing the issue
