### ISSUE TITLE
BallerinaErrorHandler returns suboptimal solution

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#28256]
**Description:**
BallerinaErrorHandler returns a suboptimal solution for the solutions in which the number of fixes are the same. It only looks for the first fix of candidate solutions, hence bellow solutions will return a suboptimal solution

` Solution 1: Insert Delete`
` Solution 2: Insert Insert `

Error handler will return the first solution as the best match.

**Comment by lochana-chathura** [comment]
Not sure. But, I slightly remember we found this issue with a sample having 4 inserts and remove 1 which did not for the 5 inserts. 
This might be fixed in #28488. Refer to the https://github.com/ballerina-platform/ballerina-lang/pull/28488#discussion_r580885067.

Let keep this issue open and revisit if that's the case.

**Comment by rdulmina** [comment]
Closing this issue as discussed with @lochana-chathura offline since the results are not significant with respect to performance drawbacks. Please feel free to reopen if there is any concern.

**Comment by rdulmina** [comment]
Reopening this issue to get more accurate results with the change of lookahead limit from 5 to 4 in errorHandler.
