### ISSUE TITLE
[Query Expression] Erroneous recovery for on clause

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28380]
**Description:**
Refer the sample and the recovery

```ballerina
function test() {
    int [] arr1 = [1, 2, 3];
    int [] arr2 = [1, 2, 3];

    var res4 =  from int i in arr1
                join int j in arr2
                on i
}
```

MISSING[equals] MISSING[object] MISSING[{]}
 MISSING[select] MISSING[] MISSING[;] MISSING[}]

Should be 
MISSING[equals] MISSING[] MISSING[select] MISSING[] MISSING[;]

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Currently errorhandler looks ahead for 5 tokens only and pick the optimal path.
Therefore for above sample, 
[1]
`MISSING[equals] MISSING[object] MISSING[{]}
MISSING[select] MISSING[] MISSING[;] MISSING[}] `
means 4 fixes and 1 match.

[2]
`MISSING[equals] MISSING[] MISSING[select] MISSING[] MISSING[;]` 
means 5 fixes 0 matches.

Hence [1] is picked as the optimal path as it as less no of fixes.
This is the the expected behavior from the parser therefore closing this issue.
