### ISSUE TITLE
Concern regarding the unused import diagnostic message

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#28408]
**Description:**
Need to revisit the error message being displayed when there's no usages of an module import. We might need to revisit showing this as an error since the Ballerina spec doesn't emphasize such a thing.

<img width="751" alt="Screenshot 2021-02-03 at 10 51 18 AM" src="https://user-images.githubusercontent.com/1448489/106702199-f4a51680-660d-11eb-9bc1-16b90ec37eee.png">

**Affected Versions:**
2.0.0-alpha1

**Comment by MaryamZi** [comment]
The ["Import declaration" section](https://ballerina.io/spec/lang/master/#section_8.1) of the spec says
> It is an error for a source-part to import a module using a module-prefix and then not to use that module-prefix.

Related spec discussion - https://github.com/ballerina-platform/ballerina-spec/issues/241#issuecomment-505237301

**Comment by kdsuneraavinash** [comment]
For the shell as well, this check is very problematic. Bacause in the shell following is a valid session,
```
=$ import ballerina/io
=$ int v = 100
=$ io:println(v)
```
We have to selectively include imports to stop errors that can come from situations like this. This currently is an added complexity. If there is a flag on the compiler to toggle whether it gives an errors on imports or not, all those can be simplified.

**Comment by MaryamZi** [comment]
Closing this issue since the current behaviour is in-line with the current spec. However there is a spec issue to track the possibility of making this a warning instead, please see https://github.com/ballerina-platform/ballerina-spec/issues/738.

@kdsuneraavinash, let's create a separate issue for the shell requirement since this is a common requirement for certain other errors too (e.g., unused variable with inferred type including error).
