### ISSUE TITLE
[SessionSupport][Improvement] getAttribute method should return a meaningful error when an invalid attribute key is given

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#2854]
Current implementation: 
Returns the object bound with the specified name in this session in type any, or null if no object is bound under the name.

But, if the session passed is invalid in any of the other methods in this API, we give a meaningful error to the user.

So to maintain the consistency, getAttribute method should also return a meaningful error when an invalid attribute key is passed

**Comment by chamil321** [comment]
@dilinisg I understand the point you are making regarding the inconsistency. But the getAttribute is used to get the existing attributes from a valid session. If the session is invalid we throw an error as we can not continue the process. Because the entire context depends on the session. But should we stop the process if the user looks up for an attribute with an invalid key? I don't think that we should stop the process rather than returning a null. IMO we should allow user to handle it as follows.
```ballerina
        any attribute = Session.getAttribute("name");
        if (attribute != null) {
            myName, err = (string)attribute;
        }
```
We have gone through some referenced HTTP session APIs like Apache Tomcat when implementing session support for the ballerina. They adhere to the same behavior. 
Suppose a native function like "getHeader(string key)". Its behavior is quite similar to this as we return an empty string for a given invalid key rather than throwing an error to stop the whole process. WDYT?

@shafreenAnfar Can you please add your thoughts?

**Comment by afkham** [comment]
Session APIs were removed since we are going to tie the sessions with the service lifecycle
