### ISSUE TITLE
Langlib method call produces incorrect result when the method is called on the same variable as the first argument

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28580]
**Description:**
$title.

Could be a side-effect of the second check at https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-alpha2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L5315.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    int i = 1;
    int j = i.sum(i);
    io:println(i); // Prints 1, expected 2.
}
```

**Affected Versions:**
slalpha1

**Comment by grainier** [comment]
@MaryamZi I think we have to get rid of both the checks. Because;
`iExpr.argExprs.isEmpty()` will be false when there's at least 1 required param to the lang lib function, and `!iExpr.argExprs.get(0).equals(iExpr.expr)` will be error-prone in situations like you've mentioned. So, we should make the `expr` that lang-lib function gets called upon as the 1st arg w/o any checks.

**Comment by grainier** [comment]
> int j = i.sum(i);
Also @MaryamZi, In the above scenario, shouldn't `j` be 2 and `i` remains 1?

**Comment by MaryamZi** [comment]
Yes, sorry, my bad! It should have been `j`. This works as expected.

Debugged this a bit and I'm not sure if that second check is ever true actually. 

I guess this is no longer an issue with the changes in https://github.com/ballerina-platform/ballerina-lang/pull/28402 anyway.
