### ISSUE TITLE
Code action `Create variable and typeguard` does not consider return type of function

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#28684]
**Description:**

This code has the same problem mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/28663 also.

Since it is reported I tried a different code action for the case. Looks like variable type is correct but the user has not imported those modules here. So I think it is better to go with the return type of the method `sql:Error?`. Next issue is when we have this error another code action to try and cast adds a CompilationError cast `<$CompilationError$?> db:initializeLinksDb();`. May be an internal anonymous type.

![Links-1613538000577](https://user-images.githubusercontent.com/2173530/108158577-37d1b000-710b-11eb-82bb-ec6c6da177ea.gif)

Code is available here.
https://github.com/KRVPerera/Links/blob/bcd8767eae2e5bd66f4e2e8a4e2a10a338324f31/main.bal#L11

The project has a release with this issue https://github.com/KRVPerera/Links/releases/tag/0.2

**Steps to reproduce:**

**Affected Versions:**
SL Alpha 2

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/28663

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rasika** [comment]
The reason why you are not getting module prefixes for error types is already captured and it is a bug Semantic API and below layer https://github.com/ballerina-platform/ballerina-lang/issues/28654.

Secondly, having expanded types list instead of`sql:Error` is due to desugaring process of BIR loaded stdlibs. There's no way to get `sql:Error` back, what it sees is `DatabaseError|BatchExecuteError|ApplicationError|()` instead.

**Comment by KRVPerera** [comment]
Thank you for the explanation. I am keeping it open to discuss the desugaring process.
