### ISSUE TITLE
VisibleSymbols API does not capture certain symbols

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28702]
**Description:**
Consider the following source snippet,

```
type Student record {
    string firstName;
    string lastName;
    int intakeYear;
    float gpa;
};

public function main() {
    Student s1 = {
        firstName: "Michelle",
        lastName: "Sadler",
        intakeYear: 1990,
        gpa: 3.5
    };

    Student[] studentList = [s1];
    var reportList = from <cursor>
}
```

For the given cursor position, `Student` type symbol is not visible.

**Steps to reproduce:**
sl-alpha2 at least

**Comment by hasithaa** [comment]
`studentList` should be visible at the cursor point.

**Comment by nadeeshaan** [comment]
For the initial example, the visible symbols contains the Type descriptor in the latest master. Now we have an issue with the following cursor position where the `student ` variable is not visible

```
type Student record {
    string firstName;
    string lastName;
    int intakeYear;
    float gpa;
};

public function main() {
    Student s1 = {
        firstName: "Michelle",
        lastName: "Sadler",
        intakeYear: 1990,
        gpa: 3.5
    };

    Student[] studentList = [s1];
    var reportList = from Student student in studentList
                    where s<cursor>
}
```

**Comment by pubudu91** [comment]
Had a look at this. The issue is, for cases such as `where s<cursor>`, the where block ends right after the character "s". And the scoping for query exprs doesn't seem to be working like it typically does for nested block statements. In a nested block, any symbol defined in the outermost block will be visible anywhere within that nested structure. But in this particular case, such symbols are only visible within the expression/statement portion of the clauses. For example, consider the following valid query:
```ballerina
var reportList = from Student student in studentList
                    where student.gpa > 3<cursor_1>
                    se<cursor_2>lect {
                        name: student.firstName
                        intake: student.intakeYear
                    };
```
The illustrated cursor positions will be considered as out of scope because of the above described nature of how the scopes are modeled for query expr clauses. In a way, I guess this behaviour is ok since we only want to suggest the symbols in places where they are relevant. Maybe we should look at handling this at the semantic API level as @nadeeshaan suggested. Can look at adding some additional checks for query exprs 🤔

**Comment by IMS94** [comment]
@pubudu91 @nadeeshaan What's the effect on this issue with the merging of https://github.com/ballerina-platform/ballerina-lang/pull/29386/?

**Comment by nadeeshaan** [comment]
Checked in latest master and the issue has been resolved. The `student` variable is visible at the given context. Hence closing the issue.
