### ISSUE TITLE
'returns' is not suggested for function-typed fields

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28736]
**Description:**
`returns` keyword is not suggested for function typed field within a record.
<img width="1060" alt="Screenshot 2021-02-18 at 10 19 06" src="https://user-images.githubusercontent.com/5234623/108306835-07554900-71d3-11eb-8d45-9c7c36eb7e74.png">

**Steps to reproduce:**
```
type ObjectName object {
    string name;
    function getName() returns string;
};

```

**Affected Versions:**
SL Alpha2 

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
The issue here is that the `function getName() r<cursor>` segment is identified as an `ObjectFieldNode`. If we need to suggest the `returns` keyword it should be able to identify the function signature node.

@lochana-chathura @rdulmina Shall we have a look at this and check whether what's the feasibility doing so?
