### ISSUE TITLE
Support for spread operator

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28830]
The tracking issue for https://github.com/ballerina-platform/ballerina-spec/issues/52

Right now this only works in the function call and mapping constructor. But this should be supported for 
- function call (map or array)
- list constructor (map)
- mapping constructor (map)
- error constructor (map)

**Comment by MaryamZi** [comment]
Rest arguments are supported with function calls.

Spread fields are supported with mapping constructors and spread list members are supported with list constructors.

The spec doesn't allow spread fields in error constructors yet - https://ballerina.io/spec/lang/master/#section_6.17.

Closing this issue since everything allowed by the spec is allowed in the implementation.
