### ISSUE TITLE
[Debugger] `let` expression inner variables are visible outside the expression

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#28883]
**Description:**
Currently `let` expression variables are visible in debug mode. Those variables should not be visible.

**Steps to reproduce:**
- Consider the code segment:
```
public function main() {
    string greeting = let string hello = "Hello ",
                          string ballerina = "Ballerina!"
                      in hello + ballerina;
}
```
- Run the above program in debbubg mode.
- We can see the `greeting`, `hello` and `ballerina` are visible in the local variables panel.
- Expected behaviour is only `greeting` variable should be visible. Other variables (`hello` and `ballerina`) should not be visible

![image](https://user-images.githubusercontent.com/11292766/109098128-bc917f00-7746-11eb-8f84-e6bc411a7ec5.png)

**Comment by NipunaRanasinghe** [comment]
It seems like this is happening due to ballerina runtime representation of let expression inner variables.

**Comment by warunalakshitha** [comment]
Since this only happens for let expression, deprioritizing the issue.

**Comment by gabilang** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/32667

**Comment by gabilang** [comment]
The variables defined inside the `if` statements and, `while` and `foreach` loops are visible at the outside of the blocks and loops. Ideally they should not visible outside. 

Consider the following code example:
```
public function main() {
    int i = 1;
    if (i == 1) {
        int j = i;
    }
}
```
The variable `j` is visible outside the `if` block also.
 
![ifblock](https://user-images.githubusercontent.com/35595065/131451756-cd14bcce-8c1d-481b-bbd9-c35231d29b14.png)
This should be fixed in order to achieve above.
