### ISSUE TITLE
Ballerina build fails for larger methods

### ISSUE THREAD

**Issue by menakaj** [ballerina-platform/ballerina-lang#29137]
**Description:**
When compiling the code with a large main method, compilation fails with the error[1] 

`error: wso2/project1:3.2.0::main.bal:5:1: method is too large: 'main'`

This error occurred when building a microgateway project with several API definition files. (~150) Please find the sample project[1] and the generated main.bal file in [main.zip](https://github.com/ballerina-platform/ballerina-lang/files/6122593/main.zip)

[1]  https://drive.google.com/file/d/17EORfcAIwS6wgGf8axNVNFoMpD0XENPs/view?usp=sharing

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
This happens for HTTP resource functions as well, however at the code coverage process. The resource will compile without any issue.

The code coverage process is blocked in this regard since Jacoco throws a method too large exception as well for resource functions that have a large function. 

As a side test, a resource function with 100+ log lines also throws the same compilation error

```
Compiling source
        lakshan/test_testarina:0.1.0
ERROR [service.bal:(13:5,128:6)] method is too large: '$get$sayHello'
error: compilation contains errors
```

**Comment by warunalakshitha** [comment]
We do validation to check large methods since Java has a 64k limit on the size of methods. This is done after codegen phase. When compiling a program with observability on, there can be observability logic generated for each function call. So when we have more function calls, there can be a method too large issue. Hence after codegen we do a check and throw an error if the given method is large than 64k.

Since Jacoco also instrument code to generate bytecodes after compilation there can be cases above mention validation can be skipped as a normal method but when we run the tests with code coverage on. tests will fail with the method too large. We need to handle the error when we run the tests. ATM workaround would be to split the method. Long term we need to do more optimization on generated bytecode.

**Comment by warunalakshitha** [comment]
I am removing the blocker label since we can get rid of the method to a large error by split the method.

**Comment by warunalakshitha** [comment]
We have optimised the code avoid method too large issues with https://github.com/ballerina-platform/ballerina-lang/pull/32059. But there are few improvements to be done on observability codegen.

1) Remove unwanted try catches for non observable functions.
2) We can combine some multiple observability methods calls by single method.

**Comment by nadundesilva** [comment]
We have merged the fixes in Observability instrumentation for reducing the instructions count as well. Both fixes mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/29137#issuecomment-908048545 had been done.

**Comment by warunalakshitha** [comment]
I am closing this issue since we have fixed the identified codegen optimizations. Please reopen if you have further queries on this.
