### ISSUE TITLE
Packages pulled from `pull` and `build` command are stored in 2 different places.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#29141]
**Description:**
The packages that are pulled using the `pull` command and the packages that are pulled during `build` command are stored in 2 different locations.

![Screenshot 2021-03-11 at 7 48 44 PM](https://user-images.githubusercontent.com/4398820/110801017-d385b480-82a2-11eb-9856-87db01929dfb.png)

![Screenshot 2021-03-11 at 7 42 18 PM](https://user-images.githubusercontent.com/4398820/110800147-ed72c780-82a1-11eb-9927-e8b765a7aa19.png)

**Steps to reproduce:**
NOTE: Package `ballerina/io:0.6.0` is already pushed to DEV central. This was built by the pack.
I have created a pack for alpha3 - https://drive.google.com/file/d/1U4r9Q1aQ1vlRmC9C2pzhPutBXDuSebn-/view?usp=sharing

- Set env var for DEV central. i.e `export BALLERINA_DEV_CENTRAL=true`
- Using the above pack, invoke `bal pull ballerina/io`
- Using the above pack, build the hello world main by invoking `bal build`

**Affected Versions:**
Post Alpha2 pack

**OS, DB, other environment details and versions:**
Mac

**Comment by azinneera** [comment]
Similar to how 2 `platform` directories are created, the same will happen to compiler plugins as well. This is due to the bug in the BalaFiles util class where the platform libraries and compiler plugins are extracted from already extracted bala dir. The linked PR fixes the duplication of `platform` directory. We need to fix the duplication of compiler plugin.
