### ISSUE TITLE
Create function code action generates a new expr as the return value of the generated function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29225]
Consider the following:
```ballerina
object {
        string name;
        int age;
    } person = foo();
```
The above generates the following:
```ballerina
function foo() returns object {string name;int age} {
    
    return new();
}
```
Since the return typedesc is an object typedesc, I think we should refrain from adding a new expr as the return value. How about generating an object constructor expr instead?

**Comment by pubudu91** [comment]
Similar issue to #29222 when it's a class:
```ballerina
public function main() {
    Person p = bar();
}

class Person {
    string name;
    int age;

    function init(string name, int age) {
        self.name = name;
        self.age = age;
    }
}
```
The generated function:
```ballerina
function bar() returns Person {
    
    return new();
}
```
Note the semantically incorrect new expr.

**Comment by IMS94** [comment]
@pubudu91 This is how I thought of solving this. For classes, we create the `new()` expression with default values for its initializer's parameters. For `object` types, we let the user fill it -> That is, in VSCode we can specify a placeholder for places to be filled by the users. We can use that to allow the user to create the return value. WDYT?

Otherwise, I don't think the complexity of creating the object constructor expression by ourselves is not worth the effort we have to put given the complexity. @nadeeshaan @rasika

**Comment by nadeeshaan** [comment]
@pubudu91, @IMS94 agreed. We need to provide an object constructor expression. In this particular scenario, the things can get really complex given the signature of the construct. Therefore, Let's have `object {}` as the default generated object constructor expression and then the user can fill the internals there with the provided code suggestions and the code actions of the diagnostic.

**Comment by IMS94** [comment]
@nadeeshaan Did the implementation in #29565.
