### ISSUE TITLE
When pulling ballerinax/kafka an old version is getting pulled by default 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#29408]
**Description:**
The latest version of `ballerinax/kafka` is `2.1.0-alpha5`. `2.1.0-alpha3` is getting pulled by default. 
<img width="699" alt="Screenshot 2021-03-23 at 10 36 33" src="https://user-images.githubusercontent.com/39673615/112105228-267c3780-8bd2-11eb-80d8-3e22cc8030ff.png">

**Comment by hemikak** [comment]
There was an inconsistency of data for `ballerinax/kafka` and `ballerina/nats` packages in central. Please refer https://github.com/wso2-enterprise/ballerina-registry/issues/722 for fix. The inconsistency occurred due to a bug in central that was fixed by https://github.com/wso2-enterprise/ballerina-registry/pull/658. But the changes were not reflected to the already added packages in prod central.

**Comment by hemikak** [comment]
We have completed the fix mentioned in https://github.com/wso2-enterprise/ballerina-registry/issues/722.

`bal pull ballerinax/kafka` will now pull `2.0.5` version as it is the latest stable version available in central. If a pre-release version is required, you must mention it explicitly like `bal pull ballerinax/kafka:2.1.0-alpha5`.

Please reopen if required.
