### ISSUE TITLE
Debugging doesn't work in windows

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#29496]
**Description:**
This may have been cause by https://github.com/ballerina-platform/plugin-vscode/issues/322

**Affected Versions:**
SL Alpha3

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing since as per ballerina-platform/plugin-vscode#322, Ballerina vscode plugin 1.2.13 is not compatible with SL Alpha3 runtime and therefore debugger functionality cannot be guaranteed. Please use the vsix from the respective release and try again. Please reopen if you still get the above mentioned error with the SL vscode extension.
