### ISSUE TITLE
Compilation failure - Two incompatible versions exist in the dependency graph

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#29504]
**Description:**
Compilation error is thrown when building a sample application using Ballerina Swan Lake Alpha 3 (SL Alpha 3). The error message is shown below,

``
error: compilation failed: Two incompatible versions exist in the dependency graph: ballerina/http versions: 1.1.0-alpha4, 1.1.0-alpha5
``

**Steps to reproduce:**
- Create new Ballerina project (Need to use SL Alpha 3)
- Open the main.bal and paste the following code.

```
import ballerinax/googleapis_calendar;
import ballerina/http;

service on new http:Listener(8090) {
    resource function get sample(http:Caller caller, http:Request request) returns error? {

        googleapis_calendar:Client googleapis_calendarEndpoint = new ({oauth2Config: {
                clientId: "ddd",
                clientSecret: "dd",
                refreshToken: "https://oauth2.googleapis.com/token",
                refreshUrl: "dddddI"
            }});
        var getEventResponse = check googleapis_calendarEndpoint->getEvent("tempA31@gmail.com", "1");
    }
}
```

- Build the project using the command

``
bal build
``

**Affected Versions:**
Ballerina Swan Lake Alpha 3

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**
N/A

**Comment by azinneera** [comment]
@miyurud This happens because the `ballerinax/googleapis_calendar` has not been built with SLAlpha2 and you are trying to build with SLAlpha3. The version of `http` package is different in each release which are incompatible. For the same package,  we cannot have two prerelease versions in the dependency graph. 

To resolve this, you would need to migrate the `ballerinax/googleapis_calendar` to SLAlpha3.

**Comment by hevayo** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/29940
