### ISSUE TITLE
Incorrect order of fields in the record value created from an invocation of a function that has an included record param

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#29551]
I expected the order of fields to be in the same order as the function invocation. 

```
public type KeyVals record {|
    anydata ...;
|};

function foo(*KeyVals kvPairs) {
    io:println(kvPairs);
}

public function main() returns error? {
   foo(message = "This is a sample message", a = "foo", b = "bar", c = 100); 
}
```

Output:
```
{"a":"foo","bar":"sss","b":"bar","c":100,"message":"This is a sample message"}
```

**Comment by HindujaB** [comment]
This issue seems to be coming from compiler FE -Desugar phase.
https://github.com/ballerina-platform/ballerina-lang/blob/fc77bcd1d9407fd63da0975afd9b1002a08e0ab7/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java#L5829

The BIR contains the re-ordered version of parameters.
For the above case 
```
bb1 {
        %4 = newType KeyVals;
        %31 = ConstLoad a;
        %32 = ConstLoad foo;
        %33 = ConstLoad b;
        %34 = ConstLoad bar;
        %35 = ConstLoad c;
        %36 = ConstLoad 100;
        %37 = ConstLoad message;
        %38 = ConstLoad This is a sample message;
        %30 = NewMap %4;
        %39 = test(%30) -> bb2;
    }
```
Please note that the parameter order is loaded as `a`, `b`, `c`, `message`.
And, at runtime, we use a `LinkedHashMap` to store values, in order to preserve the order of fields.

**Comment by MaryamZi** [comment]
Just to clarify, this is the preferred behaviour, but not a must, right? Because mapping values in Ballerina are unordered collections, we cannot rely on an order?

The spec does say 
> The order of the iteration sequence is implementation-dependent, but implementations are encouraged to preserve and use the order in which the fields were added.

So +1 to fix this to preserve the order.

Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/27447
