### ISSUE TITLE
Compiler Prints Duplicate Compilation Error Message 

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#29627]
**Description:**
When there is an `unused variable '<variable name>' with inferred type including error` error occurs, the error message duplicates in the stderr. 

<img width="816" alt="Screenshot 2021-03-26 at 13 10 01" src="https://user-images.githubusercontent.com/40016057/112607693-7a3f8880-8e3f-11eb-8435-e52a251009e1.png">

**Steps to reproduce:**
Build the GraphQL module (commit:  https://github.com/ballerina-platform/module-ballerina-graphql/commit/64375e5befbb8b0e354ebc4be625af65d0bbdae4)

**Affected Versions:**
Ballerina lang 2.0.0-alpha7-SNAPSHOT

**Comment by MaryamZi** [comment]
Seems to happen when the module has tests. 

In the dataflow analyzer we seem to be directly calling [visit](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java#L312) instead of analyze for testable packages. This results in the unused var map being shared causing errors to be duplicated.
