### ISSUE TITLE
"Create variable" code action doesn't work as expected with intersection types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29738]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    int[] x = [1, 2];
    x.cloneReadOnly(); // returns `int[] & readonly`

    func(); // returns `int[] & readonly`
}

function func() returns int[] & readonly => [1, 2];
```

Using the create variable code action with both the `x.cloneReadOnly()` and `func()` calls add a variable of type `int[]` even though the actual type is `int[] & readonly`.

**Affected Versions:**
slalpha4-SNAPSHOT

**Comment by MaryamZi** [comment]
Adds invalid code for an error intersection

```ballerina
public function main() {
    func();
}

type ErrorOne error<record { boolean fatal; }>;
type ErrorTwo error<record { int code; }>;
type ErrorIntersection ErrorOne & ErrorTwo;

function func() returns ErrorOne & ErrorTwo => error ErrorIntersection("error!", code = 1234, fatal = false);
```

adds

```ballerina
$anon/.:0.0.0:$anonIntersectionErrorType$_174 funcResult = func();
```

**Comment by IMS94** [comment]
Had a look into this. We rely on the `Diagnostic` information to determine the expected type of the created variable. `Diagnostics` depend on the `TypeChecker` to get the type. The `TypeChecker` returns the `effectiveType` of a `BType` which cause the diagnostics to include only the effective type instead of the `intersection type`. If we write a method like: 

```function func() returns record {| string key; |} & readonly => [1, 2];``` 

the `TypeSymbol` will only have the `record type symbol` and miss the `intersection type`.

The concrete implementation of a `TypeSymbol` contains the `BType` which has the readonly flag. But, there's no API for us to get that information. What approaches do we have? @nadeeshaan @pubudu91 @MaryamZi

**Comment by IMS94** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/29984.
