### ISSUE TITLE
Isolated variables can escape isolated functions via closures

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#29771]
**Description:**
It seems below paragraph from the spec is not yet implemented. Hence $title.
```
Captured variables are restricted as follows: if the body is part of an anonymous-function-expr, 
then any captured variable references must refer to variables that are both final 
(either explicitly or implicitly) and have a static type that is a subtype of readonly|isolated object {}.
```

Sample:
```ballerina
import ballerina/io;

final C c = new();

public function main(){

    foo();

    var a = c.get();
    if !(a is ()) {
        map<int> mapResult = a(); // mapResult is allocated in foo();
        io:println(mapResult);
        mapResult["hi"] = 1;
    }

    a = c.get();
    if !(a is ()) {
        io:println(a());
    }
}


isolated function foo() {
    map<int> m = {};
    lock {
        // `m` escape via closure
        c.set(() => m);
    }
}

isolated class C {
    private int i = 0;
    private (function () returns map<int>)? m = ();

    public isolated function set(function () returns map<int> f) {
        lock {
            self.m = f;
        }
    }

    public function get() returns (function () returns map<int>)? {
        lock {
            return self.m;
        }
    }
}
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This restriction applies only when the body is part of an anonymous-function-expr and the function is declared as `isolated`. https://ballerina.io/ballerina-spec/spec.html#isolated_functions

In the case of `foo`, with the implicit anonymous function expression the relevant function type (the contextually-expected type of `C.set`'s parameter) is not `isolated`, so this restriction does not apply here, right? But if you change `C.set` to accept an `isolated` function `() => m` in `foo` will result in a compilation error.

```ballerina
isolated function foo() {
    map<int> m = {};
    lock {
        c.set(() => m); // error: invalid access of mutable storage in an 'isolated' function
    }
}

isolated class C {
    private int i = 0;
    private (function () returns map<int>)? m = ();

    public isolated function set(isolated function () returns map<int> f) {
        lock {
            self.m = f;
        }
    }

    public function get() returns (function () returns map<int>)? {
        lock {
            return self.m;
        }
    }
}
```

Also, in the original example, calling the function returned by `c.get()` is also not an issue since the `main` function is not `isolated`. But if you make the `main` function `isolated`, the function returned by `c.get()` cannot be called there.

Only `isolated` variables and `isolated` objects are considered to be isolated roots (https://ballerina.io/ballerina-spec/spec.html#section_5.1.3). An `isolated` function only provides a guarantee regarding the mutable state it accesses; quoting from the spec

> Ballerina guarantees that a call an isolated method or function will only result in access to mutable state if at least one of the following conditions applies:
>
>- the mutable state is freely reachable from an argument passed to the function or method and the access happens on the strand on which the function is called; the object on which a method is invoked is considered as an argument for this purpose;
>- the mutable state is freely reachable from an isolated variable or an isolated object;
>- the mutable state is part of a new value created by the call.


So, IMO, this is okay.
