### ISSUE TITLE
Improve readonly record `toString()` method 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#29824]
**Description:**
Consider the following code in module `foo`,
```ballerina
type Person record {|
    readonly string name;
    readonly string address = "default address";
    readonly int age?;
|};
public function main() {
    io:println(Person);
}
```
The output : 
```bash
typedesc foo:Person
```
Note that the string didn't include the `readonly` part even though the record contains only readonly fields. 
It would be better if the output is more detailed instead of the name given at type definition.

**Steps to reproduce:**

**Affected Versions:**
alpha3

**OS, DB, other environment details and versions:**
ubuntu 20.04, jdk 11.0.9

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
As discussed in https://ballerina-platform.slack.com/archives/CAXS256RX/p1617351617034600, IMO this is okay and is usually what the user expects when there is a type definition.

The issue is when there is an intersection type as a type definition, that should use the name of the type definition too. I've created https://github.com/ballerina-platform/ballerina-lang/issues/30097 to track the same.
