### ISSUE TITLE
Cannot get the type of a Node when there is Compilation error

### ISSUE THREAD

**Issue by sajeerAhamed15** [ballerina-platform/ballerina-lang#29903]
**Description:**
`semanticModel.type(<node>)` does not give the type information in the below scenario (There is a compilation error).

**Steps to reproduce:**
```
import ballerina/http;

service on new http:Listener(8090) {
    resource function get .(http:Caller caller, TestClass testClass) returns error? {
        int temp = **<cursor>**testClass.testFn();
    }
}

class TestClass{
    function testFn() returns int|error  {
        return 1;
    }
}

```

Below image is the response for `semanticModel.type(<node>)` (here `<node>` corresponds to `node` of `testClass.testFn()`)

![image](https://user-images.githubusercontent.com/26720235/113880179-df4c9400-97d8-11eb-8c35-6404c981ddeb.png)

**Comment by pubudu91** [comment]
What's the actual requirement here? The above behaviour is due to how the type checker works. If the assessed type of an expression is not compatible with the contextually expected type, it sets the expression's type as compile error.

**Comment by nadeeshaan** [comment]
> What's the actual requirement here? The above behaviour is due to how the type checker works. If the assessed type of an expression is not compatible with the contextually expected type, it sets the expression's type as compile error.

The issue here is, when invoking the `type` API in `SemanticModel` this gives the `CompilationErrorType`. If we consider the diagnostic at this particular error, it shows the type difference, in the sense we have earlier captured the actual type of the expression. Then we somehow drop that and return the `CompilationErrorType`. For analyzers, we have this requirement to capture the actual type of the expression, which is not a `CompilationErrorType`.

**Comment by pubudu91** [comment]
Had an offline discussion with the others regarding this and came to a conclusion that we need to figure out how we can support the above. To support this we can introduce a new field to `BLangExpression` which holds the determined type for an expression. This field would then be the one used to create the type symbol in the `type()` method, instead of the `type` field. This would avoid compile error being returned in cases such as the above.

There was also another suggestion to figure out a way to expose the contextually expected type as well. This is a bit trickier since this may not make sense for all contexts (e.g., in the above case, it doesn't make sense)

**Comment by pubudu91** [comment]
We may not be able to get rid of the compile error type completely since for some scenarios it makes sense to return it as the type. e.g., getting the type of `y` in the below program
```ballerina
public function main() {
    int x = y;
}
```

**Comment by kaviththiranga** [comment]
@pubudu91 will this be available in beta?

**Comment by pubudu91** [comment]
> @pubudu91 will this be available in beta?

Planning on adding this for beta2

**Comment by pubudu91** [comment]
Been looking in to this and while making the changes, noticed that changing the behaviour of `type()` may result in a lot of breaking changes (a number of semantic API tests broke). So instead of change `type()` itself, how about deprecating `type()` and introducing a new replacement for it? Say, `typeOf()`? @hasithaa @nadeeshaan @mohanvive

**Comment by nadeeshaan** [comment]
> Been looking in to this and while making the changes, noticed that changing the behaviour of `type()` may result in a lot of breaking changes (a number of semantic API tests broke). So instead of change `type()` itself, how about deprecating `type()` and introducing a new replacement for it? Say, `typeOf()`? @hasithaa @nadeeshaan @mohanvive

I think that would be the viable option at the moment. Also, @pubudu91 when the test cases are failing, the output of the `type` is correct right? In the sense, we have tolerated the wrong behaviour in the old implementation?

**Comment by pubudu91** [comment]
> > Been looking in to this and while making the changes, noticed that changing the behaviour of `type()` may result in a lot of breaking changes (a number of semantic API tests broke). So instead of change `type()` itself, how about deprecating `type()` and introducing a new replacement for it? Say, `typeOf()`? @hasithaa @nadeeshaan @mohanvive
> 
> I think that would be the viable option at the moment. Also, @pubudu91 when the test cases are failing, the output of the `type` is correct right? In the sense, we have tolerated the wrong behaviour in the old implementation?

Yes, exactly. Certain wrong usages currently give correct results in `type()`. Correct as in what the user expects the API to do in the context. When fixed correctly, those usages fail.

**Comment by mohanvive** [comment]
> Been looking in to this and while making the changes, noticed that changing the behaviour of `type()` may result in a lot of breaking changes (a number of semantic API tests broke). So instead of change `type()` itself, how about deprecating `type()` and introducing a new replacement for it? Say, `typeOf()`? @hasithaa @nadeeshaan @mohanvive

I don't see any other options to avoid failures rather introducing another method as you suggested @pubudu538

**Comment by nadeeshaan** [comment]
> > Been looking in to this and while making the changes, noticed that changing the behaviour of `type()` may result in a lot of breaking changes (a number of semantic API tests broke). So instead of change `type()` itself, how about deprecating `type()` and introducing a new replacement for it? Say, `typeOf()`? @hasithaa @nadeeshaan @mohanvive
> 
> I don't see any other options to avoid failures rather introducing another method as you suggested @pubudu538

Let's proceed with this approach then,
+1
