### ISSUE TITLE
Return BPackageSymbol instead of ServiceDeclarationSymbol in compiler plugin

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#29919]
**Description:**
I tried the following during the compiler plugin development with a gRPC negative use case. Here, I want to validate a service annotation.

```java
// SyntaxNodeAnalysisContext syntaxNodeAnalysisContext
ServiceDeclarationNode serviceDeclarationNode = (ServiceDeclarationNode) syntaxNodeAnalysisContext.node();
Optional<Symbol> serviceDeclarationSymbol = syntaxNodeAnalysisContext.semanticModel().symbol(serviceDeclarationNode);
```

When I have a correct gRPC service with annotations like below, this optional symbol works fine.
```ballerina
@grpc:ServiceDescriptor {
    descriptor: ROOT_DESCRIPTOR,
    descMap: getDescriptorMap()
}
service "HelloWorld" on ep {...}
```

However, when I removed the annotations like below, this optional symbol returns a `BPackageSymbol` instead of a `ServiceDeclarationSymbol`.
```ballerina
service "HelloWorld" on ep {...}
```

**Steps to reproduce:**
Run the `testCompilerPluginServerStreamingWithoutAnnotations` test in this branch:
https://github.com/ballerina-platform/module-ballerina-grpc/tree/annot-issue

**Discussion**
https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1617808028083300

**Affected Versions:**
- Swan Lake Alpha 4

**OS, DB, other environment details and versions:**
- macOS
- Java11

**Comment by pubudu91** [comment]
Had a look at this. It seems since the old compiler plugin is also there, the annotation still gets injected to the service. So for the following code,
```ballerina
service "HelloWorld" on ep {...}
```
this still becomes the following:
```ballerina
@grpc:ServiceDescriptor {
    descriptor: ROOT_DESCRIPTOR,
    descMap: getDescriptorMap()
}
service "HelloWorld" on ep {...}
```
And the starting position of this injected annotation is also the same as the `service` keyword. And since this is at the beginning of a module prefix, you are getting the module symbol for the gRPC module instead of the service decl symbol. 

Had a chat with Buddhi and Danesh regarding this and decided to remove the old compiler plugin from the gRPC module. Closing this since this is not an issue in the semantic API.
