### ISSUE TITLE
Bad, sad error

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30041]
I got another bad, sad with slalpha4. No idea what is causing this.

[semtype.zip](https://github.com/ballerina-platform/ballerina-lang/files/6330432/semtype.zip)

I tried a few workarounds without success, so I am blocked.

**Comment by MaryamZi** [comment]
This seems to be happening when attempting to log errors for member access on `ListSubtype[]` (since an `int` value is expected) at

1. L391 of semtype.bal

```ballerina
SemType[2] [t0, t1] = tc.listDefs[b.atom]; // `b.atom` here seems to be of type `Atom`
```

2. L405 of semtype.bal

```ballerina
SemType[2] [t0, t1] = tc.listDefs[neg.first]; // `neg.first` here seems to be of type `Atom`
```

Fixing these should fix the crash.

The stacktrace seems to be similar to https://github.com/ballerina-platform/ballerina-lang/issues/29971#issuecomment-818445527.

**Comment by jclark** [comment]
But Atom is defined in bdd.bal as

```
type Atom int;
```

**Comment by jclark** [comment]
I changed these into e.g.:

```
int i = neg.first;
SemType[2] [t0, t1] = tc.listDefs[i];
```

and I still get a Bad, Sad.

**Comment by jclark** [comment]
Whoops, looks like I attached the wrong file.

**Comment by jclark** [comment]
This is user error on my part: I didn't save all the files before trying to build.  Sorry. I think we can treat this as a dup of #29971.
