### ISSUE TITLE
Invalid Completions within the function in a class

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30081]
**Description:**
Consider the following source snippet
```
class Student {
    *Person;

    private string school;

    function init(string name, string age, string school) {
        s<cursor>
        self.school = school;
    }

    function getSchool() returns string {
        return self.school;
    }

    function getName() returns string {
        return self.name;
    }

    function getAge() returns int {
        self.age;
    }
}
```
Invalid completions are provided at the cursor position

**Affected Versions:**
sl-alpha4 at least

**Comment by IMS94** [comment]
When investigated, 
```
    function init(string name, string age, string school) {
        s<cursor>
        self.school = school;
    }
```
the node at the cursor is identified as `s self[MISSING;]` in the syntax tree. This cause another variable of type `self` to be available within the scope and visible symbols doesn't return `self` because the `self` variable in the function is defined after cursor position. Seems like this cannot be handled at the parser side. We are still discussing a proper approach.

**Comment by pubudu91** [comment]
We had an offline chat about this. The conclusion was that we need to add some additional meta info to var symbols about the compilation state of them. e.g., is this a redeclared symbol? 

Need to think about how to capture these info and how to expose them through `VariableSymbol`.
