### ISSUE TITLE
Incorrect code coverage reports are generated for native code

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#30093]
**Description:**
This is related to the code coverage reports generated for the [WebSocket module](https://github.com/ballerina-platform/module-ballerina-websocket).

Please refer to the following report.
https://app.codecov.io/gh/ballerina-platform/module-ballerina-websocket

In those reports, I could see couple of issues like,
1. Shows method signatures are not covered while the body of the method is covered.
![image](https://user-images.githubusercontent.com/11239305/115356348-30955400-a1d9-11eb-8750-4cbfd1f3d3fc.png)
![image](https://user-images.githubusercontent.com/11239305/115357888-b82f9280-a1da-11eb-9d61-f1f70954e1cc.png)

2. Shows part of a code line is covered when the code line is separated into more than one line because the line exceeds the limit of 120.
![image](https://user-images.githubusercontent.com/11239305/115356771-9da8e980-a1d9-11eb-8c41-500494f5c614.png)

3. Shows commented lines are not covered.
![image](https://user-images.githubusercontent.com/11239305/115357212-0a23e880-a1da-11eb-98a6-e2152aa209f3.png)
![image](https://user-images.githubusercontent.com/11239305/115357784-a0580e80-a1da-11eb-8ccd-f45c36ac4357.png)

4. Shows empty lines are not covered
![image](https://user-images.githubusercontent.com/11239305/115357441-43f4ef00-a1da-11eb-8903-7554da2e6f84.png)

5. Shows imports are not covered
![image](https://user-images.githubusercontent.com/11239305/115358035-e319e680-a1da-11eb-94ba-c9911b4098e2.png)

Can this be resolved as this has an impact on the final code coverage percentage?

**Comment by Dilhasha** [comment]
The issue happens due to the presence of duplicate class and source file elements for 'WebSocketException' and 'WebSocketUtil' in the coverage XML. The reason is having classes with the same name in both the packages. 

```
org.ballerinalang.net.http.websocket.WebSocketUtil 
org.ballerinalang.net.websocket.WebSocketUtil 
org.ballerinalang.net.http.websocket.WebSocketException
org.ballerinalang.net.websocket.WebSocketException
```

When investigating this, I found a bug in the filtering i.e. even though specific includes for code coverage are provided that information is not used when constructing the XML. This will avoid adding the http related classes to the coverage XML, so this issue will be solved.

But we need to investigate on the following.

Even though the classes and source files are grouped correctly with different packages in the coverage bundle at [1], the generated XML contains the source file under the wrong package name leading to this issue. This seems to be a bug in jacoco XML Formatter. 

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/CodeCoverageUtils.java#L461
