### ISSUE TITLE
Inline values passed to http:Caller->respond() method get compilation failed due to type ambiguity

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#30131]
**Description:**
```ballerina
type Person record {|
    int id;
    string name;
|};

type RetEmployee record {|
    readonly int id;
    string name;
|};

type PersonTable table<RetEmployee> key(id);
type PersonTableArr PersonTable[];

resource function get callerInfo17(@http:CallerInfo {respondType: Person}http:Caller abc) returns error? {
    error? a = abc->respond({id:123, name:"hele"}); // type is considered as map<json>
}
   
resource function get callerInfo32(int xyz, @http:CallerInfo {respondType: PersonTableArr} http:Caller abc) {
    PersonTable tbPerson = table [
        {id: 1, name: "John"},
        {id: 2, name: "Bella"}
    ];
    checkpanic abc->respond( [tbPerson, tbPerson]); // type is considered as table<map<json>>[]
}
```
`http:Caller->respond()` method param type is 
```
public type ResponseMessage Response|string|xml|json|byte[]|int|float|decimal|boolean|map<json>|table<map<json>>|
                            (map<json>|table<map<json>>)[]|mime:Entity[]|stream<byte[], io:Error?>|();
```

**Describe your task(s)**
This works fine when you pass a particular type to the method
```
Person p = {id:123, name:"hele"};
error? a = abc->respond(p);
```

**Comment by pubudu91** [comment]
I think the issue here is that if a type is not explicitly specified, it'll infer the type to be the type it's compatible with in the param's type. In this case, `map<json>`. So I think this behaviour is correct. If you need to be explicit about the type inferred for the inline value, a cast can be used. @hasithaa @MaryamZi please verify.

**Comment by MaryamZi** [comment]
> I think the issue here is that if a type is not explicitly specified, it'll infer the type to be the type it's compatible with in the param's type. In this case, `map<json>`. So I think this behaviour is correct. If you need to be explicit about the type inferred for the inline value, a cast can be used. @hasithaa @MaryamZi please verify.

Yeah, this is the expected behaviour. The compiler does not know of/make use of any additional restrictions the library has.

If you really want to allow this maybe the specific validation can do some additional checks for constructor expressions (mappings, lists, tables) before logging the `incompatible respond method argument type` error.

**Comment by chamil321** [comment]
I'm not sure I had the sufficient additional details to figure out the exact type when the values is passed inline to improve the error message. As mentioned in the description, the record which passed inline was considered as type `map<json>`. Also, matching the record structure with the param values could cause a significant delay when the number of fields are higher.

I think it makes sense to either cast the value or pass a typed value.

**Comment by MaryamZi** [comment]
@chamil321, since this is the expected behaviour, shall we close this issue?

**Comment by chamil321** [comment]
> @chamil321, since this is the expected behaviour, shall we close this issue?

+1
