### ISSUE TITLE
Configurable related error messages do not required contextual information

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#30164]
Case 1)
When I value is not provided for a mandatory configurable variable, I get the following error. It doesn't say anything about the module name or the package name.

```
error: value not provided for required configurable variable 'name'
```

**Comment by sameerajayasoma** [comment]
Case 2) When there are multiple required configurable variables and values are not provided for all of them, I get the error only for the first such variables. I expect to get errors for all such variables.

**Comment by sameerajayasoma** [comment]
Case 3) I get a different error when a value is not provided for a required configurable variable in a sub module.

```
error: [Config.toml:(1:1,16:16)] invalid module structure found for module 'config1.log'. Please provide the module name as '[config1.log]'
```

I should get the same error for case 1 and case 2.

**Comment by warunalakshitha** [comment]
@sameerajayasoma  We already have a https://github.com/ballerina-platform/ballerina-lang/issues/29826 to add variable contextual information to error message with location info. PR already sent and we hope to merge it with beta. I hope case 1 is covered with that.

Please refer to the following sample.
**Ballerina Project**

main.bal

```ballerina
import project2.mod1;

configurable int a = ?;
configurable string[] & readonly array = ?;
configurable table<mod1:Person> & readonly managerTable = ?;
```

mod1:mod1/bal

```ballerina
public type Person record {|
    int id;
    string name;
|};

configurable Person & readonly person = ?;
```

With the above improvement, the error message willl be output as below.

**Output**

```
error: value not provided for required configurable variable 'a'
        at waruna/project2:0.1.0(main.bal:3)
error: value not provided for required configurable variable 'array'
        at waruna/project2:0.1.0(main.bal:5)
error: value not provided for required configurable variable 'managerTable'
        at waruna/project2:0.1.0(main.bal:7)
error: value not provided for required configurable variable 'person'
        at waruna/project2.mod1:0.1.0(mod1.bal:1)
```

case 02: This should be already be fixed in alpha5. Can you provide an example case where error messages missing for the all required configurable variable? 

case 03 : @HindujaB will work on fixing that.
