### ISSUE TITLE
Provide a way to force use packaged stdlibs in the Ballerina distribution

### ISSUE THREAD

**Issue by Mirage20** [ballerina-platform/ballerina-lang#30230]
**Describe your problem(s)**

We are currently using Ballerina SL Alpha4. After the release of SL Alpha5, the Alpha4 distribution started to pull new versions of stdlibs from ballerina central. This can break the existing builds due to incompatible versions. For example, builds which use Alpha4 connectors. As a workaround, we are using `Dependencies.toml` to specify the required stdlib versions. 

**Describe your solution(s)**

It would be good to have a way (maybe a flag?) to force the Ballerina to use packaged stdlibs when building. 
Another option is to give priority to packaged libs unless the user specified to pull new stdlib versions.

**Comment by azinneera** [comment]
We have added a fix to only show compatible packages to a given distribution. This ensures the distribution does not pull the latest if it is not compatible. Therefore, we are closing the issue since the mentioned issue is resolved. Feel free to reopen if there are any other use cases for forcing the versions from the distribution for standard libraries.
