### ISSUE TITLE
Conditional expression not parsed correctly because mistaken for qualified name

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30321]
In slalpha5, the compiler rejects this correct program:

```
function foo(boolean b, int x) returns int {
  return b ? x : bar();
}

function bar() returns int {
   return 0;
}
```

with the errors:

```
ERROR [condqualambig.bal:(4:14,4:23)] undefined function 'bar'
ERROR [condqualambig.bal:(4:14,4:23)] undefined module 'x'
ERROR [condqualambig.bal:(4:23,4:23)] missing colon token
ERROR [condqualambig.bal:(4:23,4:23)] missing identifier
```

**Comment by lochana-chathura** [comment]
@jclark When parsing, we give the higher precedence to the `qualified-identifier` over `conditional-expr`. That's why this is parsed as a function call. (`return b ? x:bar() MISSING[:] MISSING[identifier];`)

So, if one wants to get the above worked, they have to use parenthesis `return b ? (x) : bar();`
Shouldn't that be the expected behavior?

**Comment by jclark** [comment]
Precedence rules tell you how to resolve an ambiguity. For example, the grammar allows `x * y + z` to be parsed in two ways: precedence tells you which is the right one.

In this case, there is no ambiguity. If you try to parse `x : bar` as a qualified identifier, you won't get a valid parse, so you need to backtrack and try other possible parses.

**Comment by rdulmina** [comment]
This issue still exists for the following examples

```bal
int a = b ? c : d.a;
int a = b ? c : d.a();
int a = b ? c : d[1];
```
All the expressions which can contain a qualified name reference in LHS affected by this issue.
