### ISSUE TITLE
Failing to compile Ballerina code(Swan Lake Alpha5) with pulling balas from Ballerina central 

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-lang#30521]
**Description:**
Ballerina build fails time to time with different errors. (The followings were for sequential 3 builds the same code) sometimes, it builds the code successfully. Even the cache is cleared same thing happens most of the time. Tried after reinstalling Ballerina, still the following errors are there.
1] Error 01
``` Compiling source
        ballerinax/gmail_new_attachment_to_drive:0.1.0
WARNING [modules/listener/util.bal:(213:1,221:2)] function 'getAllMetaData' can be marked as an 'isolated' function

Running executable

ballerina: Oh no, something really went wrong.

The `ballerina-internal.log` file located in the current directory
will indicate what the problem is.
We really appreciate it if you can share with us, the code
that broke Ballerina, together with this log file by creating a
bug report in https://github.com/ballerina-platform/ballerina-lang/issues.

```
2] Error 02

```
Compiling source
        ballerinax/gmail_new_attachment_to_drive:0.1.0
Exception in thread "main" java.lang.NullPointerException
        at io.ballerina.cli.launcher.Main.main(Main.java:63)
```
03 Error 03
```
Compiling source
        ballerinax/gmail_new_attachment_to_drive:0.1.0
ERROR [modules/listener/Dispatcher.bal:(18:1,18:45)] cannot resolve module 'ballerinax/googleapis.gmail as gmail'
ERROR [modules/listener/Dispatcher.bal:(30:13,30:25)] undefined module 'gmail'
ERROR [modules/listener/Dispatcher.bal:(30:13,30:25)] unknown type 'Client'
ERROR [modules/listener/Dispatcher.bal:(32:71,32:83)] undefined module 'gmail'
ERROR [modules/listener/Dispatcher.bal:(32:71,32:83)] unknown type 'Client'
ERROR [modules/listener/Dispatcher.bal:(67:23,67:47)] undefined module 'gmail'
ERROR [modules/listener/Dispatcher.bal:(67:23,67:47)] unknown type 'MailboxHistoryPage'
ERROR [modules/listener/Dispatcher.bal:(69:13,69:31)] undefined module 'gmail'
ERROR [modules/listener/Dispatcher.bal:(69:13,69:31)] unknown type 'HistoryEvent'
ERROR [modules/listener/Dispatcher.bal:(70:13,70:31)] undefined module 'gmail'
```

**Affected Versions:**
Ballerina Swan Lake Alpha5

**OS, DB, other environment details and versions:**
Ubuntu, JDK 11, Ballerina SLAlpha5

**Comment by azinneera** [comment]
The issue lies in the dependency graph resolution. When sorting the packages, we also sort the modules in all packages considering the dependencies within a package. This does not seem to work as intended for dependencies.

The mentioned case occurs for the package `ballerinax/googleapis.gmail` where the `googleapis.gmail.listener` has a dependency to `googleapis.gmail` but it is not captured in the module dependency graph.

The `module.dependencies()` returns an empty collection for `googleapis.gmail.listener` module.
https://github.com/ballerina-platform/ballerina-lang/blob/c4499641597a452077f1ca6c0269d8e82f11bb6d/compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java#L247-L252

**Comment by azinneera** [comment]
The root cause is a bug in the way the module name is constructed for resolving module dependencies from the `.bala` file. The following method is used for constructing the module name which does not handle the hierarchical packages properly. 
https://github.com/ballerina-platform/ballerina-lang/blob/1a0e90b51cb393311cd5b7b82e12961939232d1d/compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleName.java#L52

This resulted in showing zero module dependencies (all modules in the package are independent) for the dependant module causing the `moduleDependencies.topologicallySortedList()` to return the module with the wrong order intermittently.
