### ISSUE TITLE
Test fails with failed to load init class runtime error when using interop

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#30679]
**Description:**
A Runtime exception occurs when running a particular Ballerina project using interop. It is a unit test that makes use of a particular java class to test dependently typed variables. Class `VariableReturnType` resides in testerina-integration-test and the interop paths to the `build/libs/integration-test.jar`
The project can be found [here](https://github.com/Ibaqu/ballerina-lang/tree/master_COPY).

Test fails with :

```
Compiling source
        intg_tests/object_mocking:0.0.0

Running Tests with Coverage

        object_mocking
error: failed to load init class :intg_tests.object_mocking.0_0_0.$_init
```

Generated module jar and Testable jar do not contain any classes. Only the manifest.mf file. 

**Steps to reproduce:**

**Affected Versions:**beta 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This happens due to the java dependency not being added in the `Ballerina.toml`. This is supposed to be a compilation failure since the InteropValidator should complain about the missing interop classes and functions.But due to aa bug in the diagnostic reporting in `InteropValidator` these errors are not captured during compilation. As the fix, the module that the diagnostic is related to should be set when reporting the diagnostic.
