### ISSUE TITLE
[Testerina] When mocking a client and using `getMember()`, the functions of the client do not work

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#30893]
**Description:**
When mocking a client and using `getMember()`, a case is registered in the mock registry only for the member variable and not the functions of the client. 

This causes a `case not registered` error when attempting to use getters or setters of the client that happen to use that particular member variable. 

```
// Sample client that we can use for member access
public client class exClient {
    public int id;
    private string[] values = ["A", "B", "C", "D"];

    public function init(int id) {
        self.id = id;
    }

    public function getValue(int id) returns string {
        return self.values[id];
    }
}
```

In this case, calling `getValue()` does not work and the object mocking functionality throws an error since the function is not stubbed. 

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Like we discussed, 
Let's improve this to use the original function definitions when cases are not registered. WDYT?

**Comment by azinneera** [comment]
We can introduce `callOriginal`  to object mocking as a solution

**Comment by Dilhasha** [comment]
After evaluating the ROI on implementing the `callOriginal`, the existing behavior seems more useful. We improved the documentation with a note emphasizing the requirement to stub all the used member functions with the PR https://github.com/ballerina-platform/ballerina-dev-website/pull/6660

Decided to check the access modifiers before allowing to stub member variables allowing to mock only public member variables. So, if you need to mock a member variable that is private, you need to stub the accessor functions of the variable. This avoids the confusion caused by the example mentioned in this issue.
