### ISSUE TITLE
Improve error message related to http:Client get method

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#30934]
**Description:**

Related to following code segment

```
import ballerina/http;
http:Client clientEndpoint = check new ("http://postman-echo.com"); 
string v = clientEndpoint->get("/get?test=123");
```
Above code segment raise following error 

```
| error: action invocation as an expression not allowed here
| 	string v = clientEndpoint->get("/get?test=123");
| 	           ^
| Compilation aborted due to errors.
```
Need to improve above error message.

**Comment by pubudu91** [comment]
The issue here is that the above error message can be confusing in the context of the Shell since `not allowed here` doesn't really convey the context. The issue here is that in the above case the variable is actually in the module scope. So the error message needs to be more specific as to what's meant by "here".
