### ISSUE TITLE
[Formatter] formatting improvements

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#30942]
**Description:**
When formatted returns statement and the check line does not format properly

Here is the sample code before formatting:

![Screenshot from 2021-06-02 00-31-21](https://user-images.githubusercontent.com/46120162/120377235-7d249100-c33a-11eb-94da-8232381657e5.png)

Here is what I get after using the Format Document:

![Screenshot from 2021-06-02 00-31-37](https://user-images.githubusercontent.com/46120162/120377270-8a418000-c33a-11eb-88bb-ff2ca3bc6d42.png)

**Steps to reproduce:**

```
import ballerina/io;
class File {
string path;
string contents;
function init(string p)
returns error? {
self.path = p;
self.contents =
check io:fileReadString(p);
}
}
```

**Comment by IMS94** [comment]
More valid example is:
```
import ballerina/io;
class File {
    string path;
    string contents;
    function init(string p)
    returns error? {
        self.path = p;
        self.contents =
        check io:fileReadString(p);
   }
}
```
which gets formatted to (almost same):
```
class File {
    string path;
    string contents;
    function init(string p) 
    returns error? {
        self.path = p;
        self.contents = 
        check io:fileReadString(p);
    }
}
```
1. `check` expression should be indented right
2. `returns error?` should be indented right

**Comment by IrushiL** [comment]
This is the expected behavior as of now since the formatter preserves user-defined new lines while aligning them to the closest tab. 

The intention is to prevent the formatting from being opinionated. For instance, one user might want to indent the returns statement with a single tab whereas another would want to indent it with two tabs. Essentially, we are trying to support this by aligning the user-defined new lines to the closest tab. Since the new line is defined by the user, we can assume that they would have an opinion as to where their new line should start.

However, we could explicitly specify the indentation settings by making it configurable through the editor based on user preference during the implementation of https://github.com/ballerina-platform/ballerina-lang/issues/28234.
