### ISSUE TITLE
Jar files required for execution contains duplicate names

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#30995]
**Description:**

At the c2c module, we are executing the thin executable jar file with dependency jars copied to the Docker image. 
When coping the dependency jars to the folder, we noticed that jar files have duplicate names.  Therefore some dependency jar files are getting overridden. Can we generate the jar files with unique names?

**Steps to reproduce:**

**Affected Versions:**
Swan-Lake Beta 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Currently if a module name is equal the generated thin jar will have the same name. For Project API this is not an issue since we keep the thin jar in a directory structure which capture the orgname, package and version of the module. 

Conceptually it make sense to have a unique name for the jars we generate so shall we name the generated jar files as follows.
orgname-package-name-version-platform.jar

**Comment by anuruddhal** [comment]
+1 for orgname-modulename-version-platform.jar
