### ISSUE TITLE
CLI parameter help menu

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31000]
**Description:**
When an error happens CLI should print the expected input format
eg:
```
error: all operand arguments are not matched
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
**A suggestion for usage syntax**
Here `bal run [--experimental] [--offline] [<executable-jar | ballerina-file | package-path>]` is omitted because it is lengthy and wants to highlight the expected arguments. Only `[-- program-args...]` are displayed in the usage message as shown below.
```
usage: [--long-option1] [--long-option2]... [--long-option3=int] [--long-option4=string|error] [--long-option5[=float|int]] [--long-option6=float]... operand1 operand2 operand3...
    operand1: string
    operand2: float
    operand3: int
```
Or instead of “`operand3…`”, “`[operand3]`” can be there.

Here I have omitted the “`--`” in the usage line. I think if I am running a _file.bal_ it should be before the “`[--long-option1]`” and if I am running a _file.jar_ it should be before the “`operand1`”. If so, please suggest a suitable way to depict that in the usage line.

**Comment by Nadeeshan96** [comment]
**Example for the above suggestion**

Say we have the following main function.
```
public type GrepOptions record {|
    int 'after\-context = 0;
    int 'before\-context = 0;
    boolean 'ignore\-case;
    boolean 'line\-number;
    boolean recursive;
    string? file;
|};

public function main(string pattern, string fileName, 
    *GrepOptions grepOptions) returns error? {
```
So the usage line is like
```
usage: [--after-context=int] [--before-context=int] [--ignore-case] [--line-number] [--recursive] [--file=string] pattern fileName
    pattern: string
    fileName: string
```
