### ISSUE TITLE
Browser back button doesn't work in coverage report

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31201]
Browser back button doesn't work in the coverage report, and the icon you have to click on is too small.

<img width="526" alt="Screenshot 2021-06-16 at 12 48 49 PM" src="https://user-images.githubusercontent.com/1686124/122175469-54a3a780-cea1-11eb-8838-c33f9978aa81.png">

**Comment by ShammiL** [comment]
- As this is a single-page application, only the components within the page changes and browser history doesn't change.
- The component changing happens according to state changes and these state changes could not be added to browser history. 
- Best approach to fix the issue will be to use routes instead of states for changing components.
- It is also recommended to upgrade the entire code to newer versions of React before the fix.

**Comment by azinneera** [comment]
Since the change will significantly change the current template, we do not have to prioritize this. Let's increase the size of the button for now.
