### ISSUE TITLE
Get an error by `fromJsonString()`

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#31289]
**Description:**
$Subject
Error: ```error: {ballerina/lang.value}FromJsonStringError {"message":"expected " or } at line: 1 column: 2"}```

**Steps to reproduce:**
To reproduce, run the following code
```ballerina
public function main() returns error? {
    string jsonObject =  "{name: \"issue\", label: \"team/ballerina\"}";
    json convertedQuery = check jsonObject.fromJsonString();
    io:println(convertedQuery);
}
```
But the following casting worked.
```ballerina
public function main() {
    string jsonObject =  "{name: \"issue\", label: \"team/ballerina\"}";
    json convertedQuery =  <json>jsonObject;
    io:println(convertedQuery);
}
```
**Affected Versions:**
SLBeta1

**Comment by MaryamZi** [comment]
`value:fromJsonString()` parses a string in JSON format. The string value in the example is not in JSON format.

If the string is in the JSON format (`"{\"name\": \"issue\", \"label\": \"team/ballerina\"}"`) the parsing will succeed.

```ballerina
import ballerina/io;

public function main() returns error? {
    string jsonObject =  "{\"name\": \"issue\", \"label\": \"team/ballerina\"}";
    json convertedQuery = check jsonObject.fromJsonString();
    io:println(convertedQuery); // {"name":"issue","label":"team/ballerina"}
    io:println(typeof convertedQuery); // typedesc map<json>
}
```

Casting doesn't panic, but it doesn't create a JSON object either (which IIUC is your requirement), the value held by `convertedQuery` will continue to be the string value. This cast will always succeed because any `string` value belongs to `json`.

```ballerina
import ballerina/io;

public function main() {
    string jsonObject =  "{name: \"issue\", label: \"team/ballerina\"}";
    json convertedQuery =  <json>jsonObject;
    io:println(convertedQuery); // {name: "issue", label: "team/ballerina"}
    io:println(convertedQuery is string); // true
    io:println(convertedQuery is map<json>); // false
}
```
