### ISSUE TITLE
Removing an import statement cause completions to not work in vscode

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#31354]
**Description:**
$subject

Consider the following code:
```
import ballerina/http;
import ballerina/test;

function test() {
    http:<cursor>
}
```
If you type `ctrl+space` at cursor, you will get completions. Now, remove the import statement,
```
import ballerina/test;
```
and try for the completions at `<cursor>`. No completions will be provided. And from this point onward, no completions are provided for external modules (std libs, etc).

**Steps to reproduce:**
See description:

**Cause**
When investigated, compiler (SymbolEnter) look at the `packageCache` for the `http` package. And removal of a import statement cause the `packageCache` to be cleared. Afterward, when we do a text edit, the `http` module is no longer in the `packageCache`. 

A package is added to `packageCache` when that external module is compiled. But, an already compiler `http` module's module compilation state is set to` MODULE_SYMBOLS_LOADED`. At this state, when we invoke `compile()` on module context, package symbols are not added to the `packageCache` (which is now empty).

**Affected Versions:**
Up to SL beta 1

**Comment by azinneera** [comment]
The reason is that we wipe out the symbols in the compiler package cache and assume that they will be added again in the next compilation. 
https://github.com/ballerina-platform/ballerina-lang/blob/289db963ff993b6d6c25b44d6b7fa09f4b709180/compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java#L429

But for the next compilation, when resolving packages at the package resolution phase, the dependencies are loaded from the Project API package cache which contains moduleContexts with `MODULE_SYMBOL_LOADED` state. 
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java#L86

Therefore, the symbols are not added to the compiler packageCache
