### ISSUE TITLE
[LS] Detail for `BLangRecordTypeSymbol` completions show the signature instead of name

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#31426]
**Description:**
Consider the following code:
```
type PositionRec record {|
    int line;
    int offset;
|};

type Position readonly & PositionRec;

type Range record {|
    Position startLine;
    Position endLine;
|};

function test() {
    Range range = {
        <cursor>
    };
}

```
At `<cursor>` when we get completions, `startLine` and `endLine` will have the signature in the `detail` instead of the name `Range`.

Ex: Got `(record {| Position startLine; Position endLine; |}).endLine`, but expected `Range.endLine`

![Screenshot from 2021-06-25 12-51-35](https://user-images.githubusercontent.com/11285165/123386289-1f3f3e00-d5b4-11eb-925b-0ef39645f5cd.png)

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 2 Snapshot

**Comment by malinthar** [comment]
Consider the record type definition below. 
```
type Range record {|
    Position startLine;
    Position endLine;
|};
```

The raw type of the above definition is `RecordType` and it does not have a name. Therefore, current implementation uses the signature instead of the name. 

One solution is to use name of the original type(broader type/type reference) in this instance. However, accessing the type reference is not possible as  per the [current implementation](https://github.com/ballerina-platform/ballerina-lang/blob/ba8aaa60af12a2ca140f2a7acc18e1392a22551d/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java#L460). 

Therefore, have to think of a better approach to solve this problem.
