### ISSUE TITLE
Type Alias for Builtin Types Cannot be Retrieved at Runtime

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#31649]
**Description:**
When we define a type as follows:

```ballerina
type Foo string;

Foo foo = "foo";
```

The type name of the `foo` is `string`. But this should be `Foo`. This is a blocker for [GraphQL ID type Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/1272).

Related issue: #26284

**Comment by warunalakshitha** [comment]
Blocked on #26284

**Comment by HindujaB** [comment]
As we handle the value `"foo"` at runtime instead of the variable `foo`, the type of the value is expected to be `string`.
And, we keep the simple basic typed values as java primitives in jballerina instead of specific java objects. 
Therefore, it will be not possible to keep the type-name information for those types without creating wrapper objects (that will impact the runtime performance).  

As per the offline discussion, this will be handled in the graphQL implementation. Hence, closing this issue. 
Please reopen if there's a requirement.
