### ISSUE TITLE
Invalid access of mutable storage in an 'isolated function' 

### ISSUE THREAD

**Issue by slahirucd7** [ballerina-platform/ballerina-lang#31676]
**Description:**

Visual Studio Code's problem pane (problem tab) displays  `Invalid access of mutable storage in an 'isolated' function (BCE3943)`  after opening the auto generated balleina gRPC stub `_pb.bal` file.

**Describe your problem(s)**

After generating stubs from the proto file (using ballerina gRPC compiler), if we open the `_pb.bal` file, above message appears on the problem tab of Visual Studio Code. Even though there are problems as per the below image, it compiles the code and generates relevant JAR(s).

![image](https://user-images.githubusercontent.com/40932779/125329148-c7018d80-e362-11eb-8683-f0a872f23c3b.png)

**Describe your solution(s)**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by MaryamZi** [comment]
Is it possible to share the proto file? Or the relevant bal code?

Please also let us know the version with which this was observed.

**Comment by slahirucd7** [comment]
Proto file for service 1

```
syntax = "proto3";
package test.apis;
service MyService1 {
    rpc LimitStatus(LimitMessage) returns (LimitMessage) {
    }
}
message LimitMessage {
  string data = 1;
}
```
Proto file for service 2

```
syntax = "proto3";
package test.apis;
service MyService2 {
    rpc LocationStatus(LocationMessage) returns (LocationMessage) {
    }
}
message LocationMessage {
  string data = 1;
}
```

ballerina version details:
```
Ballerina Swan Lake Beta 1
Language specification 2021R1
Update Tool 1.3.5
```

**Comment by MaryamZi** [comment]
Thanks @slahirucd7. 

The following needs to be done to reproduce this.

Add two files in a package.

In one file (say one.bal) add
```ballerina
public function main() {
    
}
```

In the other file (say two.bal) add
```ballerina
public isolated client class Client {

    isolated remote function LimitStatus() returns LimitMessage|error {
        anydata result = getTuple();
        return <LimitMessage>result;
    }
}

isolated function getTuple() returns anydata => 0;

public type LimitMessage record {|
    string data;
|};
```

When one.bal is modified (e.g., add or remove a new line), the error appears for two.bal. But this error goes away when two.bal is modified (similarly adding/removing lines with no change to the actual content).

When one.bal is modified again, the error reappears in two.bal.

Looping in @nadeeshaan also.

Tested with:
Swan Lake Beta2
VSCode Plugin 2.1.0

**Comment by nadeeshaan** [comment]
@MaryamZi This could be due to the subsequent compilations as we observed earlier.

**Comment by IMS94** [comment]
I put a comment in https://github.com/ballerina-platform/ballerina-lang/issues/32650#issuecomment-919697019 regarding why this happens. Then further investigated the root cause with @pubudu91 .Within `TypeChecker.visit(BLangTypeConversionExpr conversionExpr)` method, we do the following:
```java
BType exprCompatibleType = checkExpr(nodeCloner.cloneNode(expr), env, targetType);
```
where a clone of the node is passed just for type checking. It's within `checkExpr` where we create the new symbol and set it to the `varRef`. Since we don't use the cloned `expr` and continue using the original `BLangTypeConversionExpr.expr`, we have 2 different symbols; 
1. Newly created variable symbol will be added to `env`
2. `BLangTypeConversionExpr.expr` which is a `simpleVarRef` will continue to have an old `symbol`.
This cause the equality check in `IsolationAnalyzer#isReferenceToVarDefinedInSameInvokable()` to fail.

Easy hack will be to implement `equals()` for variable symbols only and use that to check equality. But, there can be other similar places which we haven't discovered yet. @MaryamZi WDYT?

**Comment by MaryamZi** [comment]
@IMS94, @pubudu91, and I discussed this offline and it seems to be happening due to a forced clone of the expression in a type cast expression. Removed this in https://github.com/ballerina-platform/ballerina-lang/pull/32775 since it was redundant anyway with the changes in https://github.com/ballerina-platform/ballerina-lang/pull/30966.
