### ISSUE TITLE
Validate properties in resourceConfig

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3193]
We need to validate the property values in resourceConfig section, For example following cases seem to be valid,

Should not allow other than defined HTTP verbs
```
 @http:resourceConfig {
        methods:["ABCDEF"],
        path:"/gettopost1"
    }
```
Should not allow to add duplicate paths
```
@http:resourceConfig {
        methods:["GET"],
        path:"/gettopost1",
        path:"/gettopost2"
    }
```
Should not allow to add duplicate methods
```
@http:resourceConfig {
        methods:["POST"],
	methods:["POST"],
        path:"/gettopost1"
    }
```

Should not allow invalid characters for path
```
@http:resourceConfig {
        methods:["POST"],
        path:"/!@#$%^*&*()"
    }
```
If we allow this the behavior should be documented. 
```
@http:resourceConfig {
    }

```

**Comment by yasassri** [comment]
Some of the above are applicable to http:configuration section as well :)

**Comment by samgnaniah** [comment]
Assign to Shafreen.

**Comment by uthaiyashankar** [comment]
This problem is there yet.

**Comment by riyafa** [comment]
Let me explain each of these use cases and why they are valid:
```
@http:ResourceConfig {
        methods:["ABCDEF"],
        path:"/gettopost1"
    }
```
It is allowed in HTTP for a user to define any method name in their server. There is not a set of _allowed methods_.
Currently `ResourceConfig` is a record and there is a bug #9171 in records that allow duplicate declaration of fields. This is not an issue in `ResourceConfig` but a bug in compilers and needs to be fixed. 
```
@http:resourceConfig {
        methods:["POST"],
        path:"/!@#$%^*&*()"
    }
```
It is okay for a resource to have invalid characters for a path in server because in the url the client has to escape it properly before calling the server. The above path is validated now and resource fails in compilation because of the `%` sign.
