### ISSUE TITLE
Misleading error message when a tuple has a cyclic type reference

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#31976]
**Description:**

I found the error message to be a little misleading because initially I thought the it was referring to `[int, recursivetype]` from the tuple.

![Screenshot from 2021-08-02 11-07-46](https://user-images.githubusercontent.com/27485094/127813174-787b81cb-8024-45ac-ac82-412713e379a7.png)

But then I found it being the same for the sample below. 

![Screenshot from 2021-08-02 11-10-31](https://user-images.githubusercontent.com/27485094/127813191-ae87d8cd-1291-41c3-8a1a-26c36e47e4e3.png)

Thought it could be improved.

**Steps to reproduce:**

`type recursivetype [int, recursivetype];`

`type recursivetype [int, recursivetype, float];`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
The error message tries to convey the cycle.

For example
```ballerina
type Bar [int, Baz];
type Baz Bar;
```

results in
```cmd
invalid cyclic type reference in '[Baz, Bar, Baz]'
```

IMO, this is not misleading, but can be improved for direct references. Therefore, marked this as an improvement as opposed to a bug.

**Comment by KRVPerera** [comment]
I think this may not be a direct reference scenario. Since in this area, we compare undefined types identifier (`recursivetype`) using string comparison to identify cycles we may be comparing duplicate identifiers below in the ballerina source. Don't think the cyclic algorithm is enhanced for this specific scenario.

We may need a way to make the cyclic path more clear to the user. As an example, if direct reference like proposed we can improve the message. If not a direct reference we may need to incorporate starting and end line numbers in the ballerina source.
