### ISSUE TITLE
Type test expression gives incorrect result for `map<anydata>` check when extern function returns `anydata`

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#32052]
**Description:**
Ballerina:
```
import ballerina/jballerina.java;
import ballerina/io;

public function main() {
   anydata h = anydataReturn();
   io:println(h is map<anydata>); // prints false
}

function anydataReturn() returns anydata = @java:Method {
   name: "app",
    'class: "javalibs.app.App"
} external;
```
Java:
```
public class App {
    public static Object app() {
        BMap<BString, Object> mapValue = ValueCreator.createMapValue(PredefinedTypes.TYPE_ANYDATA);
        mapValue.put(StringUtils.fromString("a"), 5);
        return mapValue;
    }
}
```
The above check should result `true`.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Team/jBallerina

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Here `io:println(h is map<anydata>); // prints false` because `ValueCreator.createMapValue(PredefinedTypes.TYPE_ANYDATA)` creates an `anydata` object, but not a `map<anydata>` object. In order to create a map value, for this function we should pass the `MapType`, not the constraint type to which a particular map is bound.

So the correct java code would be,
```java
public class App {
    public static Object app() {
        BMap<BString, Object> mapValue = ValueCreator.createMapValue(
                TypeCreator.createMapType(PredefinedTypes.TYPE_ANYDATA));
        mapValue.put(StringUtils.fromString("a"), 5);
        return mapValue;
    }
}
```
and that would make `io:println(h is map<anydata>);` prints `true`.

As a warning to the user, the existing `createMapValue` methods with `Type` parameter in the ValueCreator API will be deprecated and new ones with `MapType` parameter will be introduced.
