### ISSUE TITLE
[Testerina] `AfterGroups` fails to execute when a particular test case fails

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#32062]
**Description:**
`AfterGroups` function is supposed to execute regardless of which test cases have failed. However, for the SQL module, if the first test case fails, all the other dependent test cases are skipped, and the `AfterGroups` fails to execute. 

When executing the build, normally the following logs can be seen

```
Test suite initiated (BeforeSuite)
Docker container for Database 'transaction' created. (BeforeGroups)
Docker container for Database 'transaction' initialised with the script. (BeforeGroups)
.
.
.
Cleaned docker container 'sql-transaction'. (AfterGroups)
Test suite finished (AfterSuite)
```

However, after executing the suite with the first test case marked to fail the following logs can be seen
```
Test suite initiated (BeforeSuite)
Docker container for Database 'transaction' created. (BeforeGroups)
Docker container for Database 'transaction' initialised with the script.
Test suite finished (AfterSuite)

                [fail] testLocalTransaction:

                    Purposeful test fail

                        at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
                        ballerina.test.0_8_0:assertFail(assert.bal:236)
                        ballerina.sql.0_6_0-beta_3.tests.local-transaction-test:testLocalTransaction(tests/local-transaction-test.bal:60)


                0 passing
                1 failing
                9 skipped
```

**Steps to reproduce:**
For `module-ballerina-sql`, execute `./gradlew clean build -Pgroups=transaction`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Able to reproduce this locally. 

It seems that when there are test cases that depend on each other, if even one fails the `AfterGroups` function is added to the skipped list and fails to execute

**Comment by Dilhasha** [comment]
The current behaviour of beforeGroups and afterGroups is as follows.
- `beforeGroups` runs before the first test that belongs to the group is executed
- `afterGroups` runs after the last test that belongs to the group is executed.

So, when a test in the group is skipped, the check for `last test is executed` is always false. This results in skipping the `afterGroups` function.

**Comment by Dilhasha** [comment]
The current test execution behaviour is inconsistent for some scenarios. So, following is the expected behaviour and we would fix any cases that are not adhering to the below behaviour. Appreciate your input @hevayo @azinneera 

This is the expected order of execution for tests in a test suite.
![expected_order](https://user-images.githubusercontent.com/5234641/130068420-e0a3c86e-b690-4bec-a61b-cb8065239996.png)

- If `BeforeSuite` fails, 
every other following function is skipped. 

![testerina1](https://user-images.githubusercontent.com/5234641/130068500-c29cf4d1-e05e-4b4e-a06c-3f5d93b6b0f2.png)

- If `BeforeGroups` function fails,  

For that group, the tests will be skipped including the before, after functions.
`beforeEach` and `afterEach` will be executed anyway. The afterGroups function will be skipped.
Tests belonging to other groups will not be affected.

![testerina2](https://user-images.githubusercontent.com/5234641/130068586-a9d3aa2c-d876-47ea-bc06-1f6bfec6aae4.png)

- If `BeforeEach` function fails, 
Every test function will be skipped. Since beforeSuite is already executed afterSuite will be executed. If the beforeGroups was executed prior to beforeEach, then the afterGroups will be executed. If not they will be skipped.
![testerina3](https://user-images.githubusercontent.com/5234641/130068623-745159a5-8c5c-4e1d-9a34-91e50c046277.png)

- If a test function fails, none of the other functions get skipped.

- If the before test function fails, the test function and the after function for that test will be skipped

- If a test function is skipped (due to a failure of a function it depends on), even then the `AfterGroups` function will not be skipped

![testerina4](https://user-images.githubusercontent.com/5234641/130068702-e2c92aa6-1dfd-4c31-8a6d-0e04e2ffcda9.png)

- If the `AfterEach` function fails, every following beforeEach, afterEach and test functions will get skipped.

- If the `AfterGroups` function fails, it won’t affect any other functions.

- `AfterGroups` & `AfterSuite` will run if ‘alwaysRun’ is enabled irrespective of the status of other functions
