### ISSUE TITLE
Shell stuck on same error even for valid code proceeding invalid code 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#32086]
**Description:**

```shell
=$ var t = int.typeIds();                                                                                            took 103 ms

=$ t                                                                                                                 took 509 ms
| error: unknown type 'TypeId'
|       var 't = <TypeId[]? & readonly> __recall_any("'t");
|                 ^----^
| Compilation aborted due to errors.

=$ type R record {};                                                                                                  took 89 ms
| error: unknown type 'TypeId'
|       <TypeId[]? & readonly> __recall_any("");
|        ^----^
| Compilation aborted due to errors.
```
**Steps to reproduce:**

**Affected Versions:**
Swan Lake Beta-2
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

Found this error just after https://github.com/ballerina-platform/ballerina-lang/issues/32085

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by DamithaSenevirathne** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/32085

**Comment by DamithaSenevirathne** [comment]
In Ballerina shell implementation, user input is discarded only if that particular user input contains an error. In this case `var t = int.typeIds();` user input is a valid user input. And shell accepts the user input and shell updates the template `bal` file. But due to a bug in the shell/ compiler (compiler in this case) it raises an error and error is propagating with the `bal` template file.

Need to identify and fix the related to bug avoid this type of cases.

**Comment by rdhananjaya** [comment]
If you mean #32085 then I don't think that can be fixed from compiler side.

**Comment by DamithaSenevirathne** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/32085 will be fixed by PR https://github.com/ballerina-platform/ballerina-lang/pull/32746

issue was in the `ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java` file

Had to change

**Comment by DamithaSenevirathne** [comment]
> If you mean #32085 then I don't think that can be fixed from compiler side.

If I'm not mistaken, Issue https://github.com/ballerina-platform/ballerina-lang/issues/32085 will be fixed by the PR https://github.com/ballerina-platform/ballerina-lang/pull/32746

Issue was in the line https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L1275 
 
Had to change `pkgSymbol.owner` to `pkgSymbol`.

Tested above changes in the ballerina shell and I didn't get the expected error.

**Comment by rdhananjaya** [comment]
Ah awesome, same thing happens in VSCode when we convert a `var` to a concrete type, hopefull that will also be solved with this fix.

**Comment by pubudu91** [comment]
> Ah awesome, same thing happens in VSCode when we convert a `var` to a concrete type, hopefull that will also be solved with this fix.

Coupld of such issues were reported recently. The underlying issue with these was as Damitha mentioned the owner being incorrectly set in the type symbols. There were a couple of places in `BIRPackageSymbolEnter` where the owner seems to have been blindly set as `pkgSymbol.owner`. This causes the owner to be recognized as the `lang.annotations` module. Symbols in the `lang.annotation` module are assumed to be builtin symbols. Hence we drop the module prefix from them when referring to them. I think we have to go through the `BIRPackageSymbolEnter` and see if there are any other places where this happens. For now, can close this issue. Will open a separate one for checking the `BIRPackageSymbolEnter`.
