### ISSUE TITLE
Method is too large in `init` method

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#32096]
I intermittently get following when compiling nballerina project

```
Compiling source
        wso2/nballerina:0.1.0
ERROR [nballerina.front:(1:1,1:1)] method is too large: '.<init>'
error: compilation contains errors
```

**Comment by warunalakshitha** [comment]
We have optimised the generated code specially related to init function by properly splitting the large functions and moving some utility methods to separate class.  We have removed some duplicate code generation for union types. Please refer the following PRs for more information.

https://github.com/ballerina-platform/ballerina-lang/pull/32059
https://github.com/ballerina-platform/ballerina-lang/pull/32325

I am closing this issue since above fixes will solve the method too large issue with init. Please reopen the issue if you have further queries on this.
