### ISSUE TITLE
Design the specification for the semvar enforcing tool for Ballerina APIs

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#32373]
**Description:**
$subject

Task 1 of the related issue. Once an initial draft is designed it can be reviewed and the final version could be derived iteratively.

**Related Issues (optional):**
#32368

**Comment by IrushiL** [comment]
Link to the initial design specification: https://docs.google.com/document/d/1YowcycsEcO0K67sYBAb_Gz1slFVf5CnCkgkOnMMKcSo/edit?usp=sharing

**Comment by NipunaRanasinghe** [comment]
Closing since the proposed specification is available at https://docs.google.com/document/d/1STs91QTXrvivfcowGltOtoYCRlgJheGPay56G3cWuxM/edit?usp=sharing. Created https://github.com/ballerina-platform/ballerina-spec/issues/1070 to review to track the progress on reviewing and adding to the ballerina-spec repository.
