### ISSUE TITLE
Test failure in Salesforce connector daily build 

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/ballerina-lang#32417]
**Description:**

SFDC connector default module test cases are failing in the daily build since last few days due the following error. 
Build Action -https://github.com/ballerina-platform/module-ballerinax-sfdc/runs/3439272150?check_suite_focus=true

```Running Tests
sfdc
Aug 27, 2021 2:46:58 AM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @3106ms to org.eclipse.jetty.util.log.Slf4jLog
Aug 27, 2021 2:46:59 AM org.ballerinalang.sf.EmpConnector connect
INFO: EmpConnector connecting
>>>>
[2021-08-27 02:46:59.776] Success:[/meta/handshake]
{ext={replay=true, payload.format=true}, minimumVersion=1.0, clientId=hl4gkqbqgtr6ze1tpk5safqyecn, supportedConnectionTypes=[Ljava.lang.Object;@1b87f76c, channel=/meta/handshake, id=1, version=1.0, successful=true}
<<<<
error: Test module invocation for test suite failed due to error("java.lang.NullPointerException")
```
Able to reproduce it locally with the latest pack.
One test case related to SFDC listener uses java dependency causes these test failures. Other test cases can pass without this listener [test case](https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/master/sfdc/tests/listener_test.bal).

**Affected Versions:**
SL Beta3 Daily Build

**Comment by LakshanSS** [comment]
There is also a slack thread created related to this issue
https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1630053651008800

**Comment by Ibaqu** [comment]
The issue seems to originate from the SFDC side due to an error stemming from the java class `ListenerUtils`. The following function `getTopic()` throws a NPE when trying to access a string value from `channelConfig` map. The `channelConfig` in this case resolves to a Null value

```
private static String getTopic(ObjectValue service) {
        MapValue<BString, Object> channelConfig = (MapValue<BString, Object>) service.getType()
                .getAnnotation(StringUtils.fromString(Constants.PACKAGE + ":" + Constants.SERVICE_CONFIG));       
        return channelConfig.getStringValue(Constants.CHANNEL_NAME).getValue();
    }
```
https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/master/emp-wrapper/src/main/java/org/ballerinalang/sf/ListenerUtil.java#L161 
The error thrown from this end causes the interop to simply return the NPE. 

Testerina can be improved to display the stacktrace for such a scenario however, it can only display information that fails from the Ballerina side and not the actual java interop error. 
<img width="900" alt="Screenshot 2021-09-08 at 14 09 51" src="https://user-images.githubusercontent.com/43578935/132508048-089edd90-a748-4246-8a9c-10565e1cea07.png">

**Comment by LakshanSS** [comment]
The root cause of this issue is [this breaking change](https://github.com/ballerina-platform/ballerina-lang/commit/ceb2009fa81162ce7c6640c38f1237706d032bae) happened in ballerina-runtime-api/Module 

In salesforce connector, we were hardcoding the Module version in java code.
Now this issue is fixed after merging https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/169
