### ISSUE TITLE
Invalid coverage for return statement when there's a if condition

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#32411]
**Description:**
For the following sample code:

`main.bal`

```
public function intAddd(int a, int b) returns int {
    if (true) {
        return a + b;
    } 
    return a - b;
}
```
`tests/main_test.bal`

```
import ballerina/test;

@test:Config{}
function testFunc() {
    test:assertEquals(intAddd(1,2), 3);
}
```

Execute bal test --code-coverage

Even though the final return  is never hit by the test, this code gives 100% coverage in Testerina report.

**Steps to reproduce:**
As discussed above

**Affected Versions:**
Swan lake beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
The issue https://github.com/ballerina-platform/ballerina-lang/issues/31061 has been fixed, but the current issue is still there.

**Comment by gabilang** [comment]
The issue is occurring when the function have multiple return statements. If do not have a test to cover the last return statement and have a test to cover one of the above return line, code coverage tool shows that the last return statement statement line also covered partially by the test. It can happen some of the bytecode branches related to the last return statement also covered by the tests which are written to cover the previous return statements. Making the positions regarding those instructions didn't work as far as I checked.
