### ISSUE TITLE
Incorrect member types for union type definition

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#32569]
**Description:**

Consider the scenario,

```
type t "0"|"1"|t1;
type t1 "a"|"b"|"c";
```
In `memberTypeDescriptors()`,  we get `"0|1"` as a union type.

Refer to https://github.com/ballerina-platform/ballerina-lang/pull/32540#discussion_r701611819

![image](https://user-images.githubusercontent.com/27485094/131980729-a7aa026a-d401-41c4-8fe0-83c3bd8b6c07.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
The issue here seems to be that in cases such as the above where we have a mix of singleton types and other types in the union, we seem to be modelling it as a union of a finite type node and the other type nodes. We are synthesising a new type def for the finite type and then use it in the user given type def. Ideally, this should be modelled as written: a single union type consisting of 2 singleton types and a type ref.

**Comment by dulajdilshan** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/32760
