### ISSUE TITLE
Update type checking to use exact singleton type for expressions whenever all their operands have a singleton type

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#33090]
**Description:**
$title so that unreachability is based on whether the type is singleton true or singleton false. 

Related discussion
https://github.com/ballerina-platform/ballerina-spec/issues/902

**Comment by lasinicl** [comment]
Checking unreachability based on similar scenarios as follows will be handled through this.
```ballerina
if 1 == 1 {
   int a = 10;
} else {
   int a = 20; // unreachable
}
```

**Comment by lochana-chathura** [comment]
Once fixed something like `5 n = 3 + 2;(applying gsingleton typing rules on top of additive-expr)` should work.

**Comment by lochana-chathura** [comment]
When fixing this, will the error messages in the following cases change to the singleton type instead of int?

[1] `string s = 1; // @error incompatible types: expected 'string', found 'int'`
[2] `1 n = -1; // @error incompatible types: expected 'string', found 'int'`

for [1], `found 'int'` is more appropriate whereas for [2], `found '-1'` is more appropriate.

**Comment by lasinicl** [comment]
> When fixing this, will the error messages in the following cases change to the singleton type instead of int?
> 
> [1] string s = 1; // @error incompatible types: expected 'string', found 'int'
> [2] 1 n = -1; // @error incompatible types: expected 'string', found 'int'
> 
> for [1], found 'int' is more appropriate whereas for [2], found '-1' is more appropriate.

yes! the error messages will contain the singleton type for [2]
