### ISSUE TITLE
Invalid node/ context identified by the parser

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33205]
**Description:**
```
import ballerina/io;

type Person record {
 string first;
 string last;
};

public function main() {
    Person[] persons = [
        {first: "Melina", last: "Kodel"}
    ];

    string[] names = from var {first, last} in persons
                    let int len1 = first.length()
                    <cursor>
 }
```

**Steps to reproduce:**
If we get the node at the cursor position shown, we get the block node, instead of the let clause.

**Affected Versions:**
SwanLake-Beta4-SNAPSHOT at least

**Comment by lochana-chathura** [comment]
cp - cursor position
[1]
```bal
public function main() {
    string[] names = from var {first, last} in persons
                    let int len1 = first.length()
<cp1>               <cp2>
}
```

Recovered as,
[2]
```bal
public function main() {
    string[] names = from var {first, last} in persons
                    let int len1 = first.length()
 MISSING[select] MISSING[] MISSING[;]<cp1>                    <cp2>
}
```

Here by design(trailing trivia ends at the newline. whitespace after that will be leading trivia of next token), the whitespace between `<cp1>` and `<cp2>` belongs to leading minutiae of `}` token.

Therefore for the cp2, node at the cursor position is  block node.

We need to think of a way to handle this scenario.

**Comment by lochana-chathura** [comment]
One possible solution from the parser side would be to make the recovered tree as,
```bal
public function main() {
    string[] names = from var {first, last} in persons
                    let int len1 = first.length()
 <cp1>                    <cp2>MISSING[select] MISSING[] MISSING[;]
}
```

Basically, when inserting the missing token at the error handler, we transfer the leading whitespace minutiae (until first newline) of the `peek()` token to the missing token's leading minutiae.

But this introduces some complications in the implementation.
1.  There are places we ignore the recovered missing token. Those cases have to be handled in a way we will not lose any whitespaces.
2. Once we transfer the whitespaces we have to cash the new `peek()` which does not include leading whitespace minutiae.

If we consider the C# recovery may have done kind of similar thing. (Ref: https://github.com/ballerina-platform/ballerina-lang/issues/29418#issuecomment-871638412 - Note that missing semicolon has leading whitespaces)

**Comment by lochana-chathura** [comment]
From LS side if we can detect and transfer the cursor position from `<cp2>` to `<cp1>` for this kind of scenario (assuming we do the fix for #33224) then we can get the correct node from `findNode()`.

**Comment by nadeeshaan** [comment]
> From LS side if we can detect and transfer the cursor position from `<cp2>` to `<cp1>` for this kind of scenario (assuming we do the fix for #33224) then we can get the correct node from `findNode()`.

@lochana-chathura from the LS side we cannot transfer the cursor position since we keep the cursor position immutable throughout the operation in order to maintain the consistency

**Comment by lochana-chathura** [comment]
Adding more to the original issue. Completions work when the user types "s" at the cursor position.

The only problem is when a user tries to get completions without typing anything. Also if they try for completions while keeping the cursor in-line with let-clause still completions work.

Since the proposed fix https://github.com/ballerina-platform/ballerina-lang/issues/33205#issuecomment-971301979 introduces a lot of complications to the parser, both I and @rdulmina are thinking of not fixing this for the GA.

@nadeeshaan what is your take on this? would that be okay?

**Comment by nadeeshaan** [comment]
@lochana-chathura yes, when we type at least a single character, the context is properly identified. And based on the gravity of the fix, +1 for not including it in the GA.
