### ISSUE TITLE
VSCode Plugin Shows Invalid Errors when Two Files Exists with Same Name

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#33258]
**Description:**
If there are two files with the same name inside a Ballerina project, the VSCode plugin shows invalid errors such as,
- `Redeclared Symbol`: For functions that are defined inside such a file
- `Undefined function`: In places where the functions are being called

This can be reproduced by having the following file structure:

```
- sample
  |
  |- utils.bal
  |- tests
     |- utils.bal 
```

Functions in the `tests/utils.bal` file are marked as redeclared symbols. When we call these functions from another file, it shows an undefined function error. But this project builds without an error.

**Comment by nadeeshaan** [comment]
As per the initial debugging, this is happening due to the following code segment.
https://github.com/ballerina-platform/ballerina-lang/blob/010b62093347642402b95b07771cb4ebf0e55177/compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java#L181-L196

When we try to access a documentId given the path, we first check on the default sources and then we check the test sources. If we have two files with the same name, then we get the default source.
Another reason for that, is we compare just the file name instead of the relative path. 

In order to fix this, it seems we have to consider the relative path name.

@azinneera @pramodya1994 thoughts?

**Comment by azinneera** [comment]
@nadeeshaan correct. We have sent a fix for this.
