### ISSUE TITLE
`lineRange` is not set when parsing multiple statements with syntax API

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#33323]
**Description:**
When I parse multiple statements using `parseStatements()`, The `lineRange` hasn't been set in each `StatementNode` except the first `StatementNode`.

eg:
```java
String x = "string fName = \"Ted\"; string lName = \"Mosby\";";
NodeList<StatementNode> s = NodeParser.parseStatements(x);
s.get(1).lineRange();
```
Above will throws the below IOOB exception.
```
java.lang.IndexOutOfBoundsException: Index: '36', Size: '19'
```

**Affected Versions:**
2.0.0-beta.4-SNAPSHOT

**Comment by lochana-chathura** [comment]
The reason for IOOB is the `ExternalTreeNodeList` created for the statement list does not have a parent.

If we consider a similar sample,
```java
TextDocument textDocument = TextDocuments.from("import foo; import bar;");
ModulePartNode s = SyntaxTree.from(textDocument).rootNode();
LineRange lineRange = s.imports().get(1).lineRange(); // Here the parent of imports().get(1) is ModulePartNode
```

```java
String y = "int a = 1; a = 2;";
NodeList<StatementNode> s = NodeParser.parseStatements(y);
LineRange lineRange = s.get(1).lineRange(); // Here the parent of s.get(1) is null.
```

When the parent of a `StatementNode` is null, `LineMap` is populated for the `StatementNode`, not for the whole input. Therefore, when trying to derive the `LineRange` from `TextRange` it causes IOOB.

In summary, we need to have a parent node for the `NodeList<StatementNode>`. It cannot exist alone.

**Comment by rdulmina** [comment]
+1 for the approach

**Comment by lochana-chathura** [comment]
[1] https://github.com/ballerina-platform/ballerina-lang/blob/8adfc0ac5b12d60c70d33893a15e49e7eba2920e/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NonTerminalNode.java#L200

[2] https://github.com/ballerina-platform/ballerina-lang/blob/8adfc0ac5b12d60c70d33893a15e49e7eba2920e/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/syntax/ExternalTreeNodeList.java#L56

One thing that I do not understand is the reason for not making `ExternalTreeNodeList` a parent.
 
At [2], we consider `this.parent` as the parent instead of `this`. We will not have the issue if `ExternalTreeNodeList` can become a parent.

**Comment by sameerajayasoma** [comment]
Do we have the same problem with `parseStatement` method?

**Comment by lochana-chathura** [comment]
> Do we have the same problem with `parseStatement` method?

You mean `parseExpression`? No. 
The problem only exists for `parseStatements` where we create an unlinkedFacade for a nodeList and expose.

**Comment by sameerajayasoma** [comment]
My gut feeling: we should `parserStatements` method. There is no parent that can represent a set of statements in the language. I don't think adding a random parent node solves this problem. Instead, we should be adding `parseStatementBlock` or something.
