### ISSUE TITLE
Cannot Retrieve Information from SingletonTypeSymbol

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#33577]
**Description:**
There is no way to retrieve the name or documentation of a `SingletonTypeSymbol` in Package APIs. (SingletonTypeSymbol does not have any APIs as it seems).

**Comment by pubudu91** [comment]
Do you have an example on what you were trying to do? Generally type symbols don't have metadata associated with them. e.g.,
```ballerina
# A type def for a singleton type
type Foo 10;

Foo f = 10;
20 s = 20;
```
In the above use of `10` in the type def, that's a singleton type. But the documentation in the line above that is not a part of that singleton type. That documentation is a part of the type def `Foo`. 

To better understand the difference, consider the second case, where `20` is used as a type. That's also a singleton type, but it's directly used as a singleton type. Which means no meta data for it.

**Comment by pubudu91** [comment]
Had an offline chat with @ThisaruGuruge regarding this. So the requirement was something like the following:
```ballerina
# This is a constant
const FOO = "foo";

# This is a type
type Bar <cursor>FOO;
```
So previously, if we looked up the symbol at the illustrated cursor position, it returned a singleton type IINM, due to #26284. But now, when we look up the symbol, it returns the constant symbol for `FOO`, from which the documentation is accessible. This addresses the above concern right?

**Comment by ThisaruGuruge** [comment]
Thank you, @pubudu91. This will solve the issue.
