### ISSUE TITLE
Constant with type-descriptor `byte` cannot be defined with an expression

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#33889]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
const byte a = 1 + 2; // output: incompatible types: expected 'byte', found 'int'
byte b = 3 + 2; // output: incompatible types: expected 'byte', found 'int'
byte c = 3;
byte d = 7;
byte e = c + d; // output: incompatible types: expected 'byte', found 'int'
```

**Affected Versions:**
SL Beta4 RC2

**Comment by MaryamZi** [comment]
According to the 2021R1 spec getting errors for the non-const scenarios is expected.

> It is required that either
> - **the static type of both operand expressions is a subtype of the same basic type, in which case this basic type will be the static type of the result**
> - the static type of one operand expression must be a subtype of xml and of the other operand expression must be a subtype of string, in which case the static type of the result is xml

So the static type of the additive-expr is `int` when the operands are of static types that are subtypes of `int`, which is the reason for the errors here.

But with https://github.com/ballerina-platform/ballerina-lang/issues/33090, the following will work since the static type will be a singleton type that belongs to `int`.

```ballerina
byte b = 3 + 2;
```

But the following will continue to result in an error.

```ballerina
byte c = 3;
byte d = 7;
byte e = c + d;
```

This is correct since we don't know what `c` and `d` are and the addition of `c` and `d` may result in an `int` value that does not belong to `byte`.

e.g.,
```ballerina
byte c = 255;
byte d = 1;
byte e = c + d; // 256 does not belong to `byte`
```

Will change the title to reflect the `const` scenario.
