### ISSUE TITLE
Ballerina package resolution issue with minor version of dependent packages

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#33951]
**Description:**
We bumped all SQL packages to minor versions in beta4(1.1.0 - in beta3 it was 1.0.0). Since this is a minor version upgrade, when we build an existing project which was built in beta3, the latest minor version of the JDBC package is not pulled from the central. but the latest minor version of its dependent SQL package is picked because it is coming from the distribution.

When we try to build the project it gives an error due to the version mismatch in the dependent packages.
Related issue: ballerina-platform/ballerina-standard-library#2428

**Steps to reproduce:**
* Build and run [JDBC Query Sample](https://ballerina.io/learn/by-example/jdbc-query-operation.html?is_ref_by_example=true) with beta3 first. It will pull the JDBC 1.0.0 version.
* Upgrade Ballerina distribution to beta4
* Try to build and run the same sample again.

Build will fail with the following error,

```
Compiling source
        test2.bal
ERROR [ballerinax/java.jdbc/1.0.0::client.bal:(65:5,69:16)] mismatched function signatures: expected 'public function queryRow(ballerina/sql:1.1.0:ParameterizedQuery sqlQuery, typedesc<anydata> returnType) returns (returnType|ballerina/sql:1.1.0:Error)', found 'public function queryRow(ballerina/sql:1.1.0:ParameterizedQuery sqlQuery, typedesc returnType) returns (returnType|ballerina/sql:1.1.0:Error)'
WARNING [test2.bal:(37:5,39:8)] unused variable 'e'
WARNING [test2.bal:(57:5,57:39)] unused variable 'er'
WARNING [test2.bal:(77:5,81:41)] unused variable 'result'
WARNING [test2.bal:(95:5,96:63)] unused variable 'result'
error: compilation contains errors
```

**Affected Versions:**
SL beta4

**Comment by azinneera** [comment]
Automatic update of dependency versions are only supported for patch level. To get a minor version update, please delete the Dependencies.toml if this is a package. Single files should work since the versions aren't locked

**Comment by niveathika** [comment]
This is now failing because the central pull of `ballerinax` modules is not working correctly.
<img width="904" alt="Screenshot 2021-11-26 at 13 31 49" src="https://user-images.githubusercontent.com/27669465/143547198-5729f440-cf96-415c-a78f-6e731961fa50.png">

Currently I cannot build the samples since jdbc module is not pulled properly.

Looping in @pramodya1994

**Comment by azinneera** [comment]
@niveathika there are two issues here: 
1. Some APIs in Ballerina Central has not implemented the restriction to avoid getting packages pushed from newer distribution
2. Bug is hierarchical name resolution logic 

This issue will address the 2nd point and the first one will be fixed by the Ballerina Central team.
