### ISSUE TITLE
Showing diagnostics of lang/std libs in problems tab of vscode is misleading

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34005]
**Description:**
From end users' perspective, showing errors related to std libs or lang libs in the problems tab is misleading and confuses the user. It gives the impression that "my project has this much more errors".
![Screenshot from 2021-11-25 23-10-36](https://user-images.githubusercontent.com/11285165/143484319-b9b874c4-2140-487e-b1a2-01a8e6fb4a42.png)

**Describe your problem(s)**
See description

**Describe your solution(s)**
Need to filter unrelated diagnostics at LS level or from project API level.

**Comment by IMS94** [comment]
@mohanvive @nadeeshaan WDYT

**Comment by mohanvive** [comment]
Yes, it creates unnecessary confusion. I have seen @nadeeshaan has raised this concern and Sameera yet to reply to that. Let's see.

**Comment by nadeeshaan** [comment]
@azinneera please note this

**Comment by mohanvive** [comment]
Related current behaviour - https://github.com/ballerina-platform/ballerina-lang/issues/31582

**Comment by azinneera** [comment]
This is partially fixed with https://github.com/ballerina-platform/ballerina-lang/pull/42627. Except for the errors, all other diagnostics of dependencies are now hidden by default. Suppressing the errors is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/32985. Hence closing this issue.
