### ISSUE TITLE
[Debugger] Update the debugger guide with new breakpoints features 

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#34021]
**Description:**
The current debug guide has documentation for 
- Conditional Breakpoints
- Logpoints

It would be better if we can add documentation for the rest of the breakpoints features as well
- Conventional Breakpoints (Hit count)
- On-the-fly breakpoints (adding) and (removing)

**Comment by NipunaRanasinghe** [comment]
After the discussion with @lnash94 and @praveennadarajah, closing this since it was decided not to add documentation for conventional breakpoints and for adding/removing on-the-fly breakpoints, since these can be considered as primitive capabilities experience therefore should be intuitive for the user.
