### ISSUE TITLE
Rename error "unused import module"

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#34071]
Spec says, `It is an error for a source-part to import a module using a module-prefix and then not to use that module-prefix.`

The error message should say, "unused module prefix"

**Comment by nadeeshaan** [comment]
Just to clarify, in this particular scenario, what should be the diagnostic range? Should we only capture the prefix part or the whole import statement? With the latest changes, it highlights only a part of the import statement which seems to be misleading because the part which is not highlighted as an error, can be considered as valid. Refer the following screenshot

<img width="323" alt="Screenshot 2021-12-08 at 13 30 21" src="https://user-images.githubusercontent.com/1329674/145170881-22d870fa-47ea-4302-9588-253f5a8ce1dd.png">

This gives the user an idea that `import ballerina/` part is valid but the module name.
