### ISSUE TITLE
VSCode suggestions for streams did not appear with check statement

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#34104]
**Description:**
When I tried to iterate a stream, the following suggestions were given correctly when I only used stream without `check`.

<img width="721" alt="Screenshot 2021-12-02 at 14 36 16" src="https://user-images.githubusercontent.com/18663444/144392104-5a88df99-94ab-4e65-8e95-bc2d980fd4fa.png">

However, when I tried the same with a `check` statement, I didn’t give the previously given suggestions.

<img width="600" alt="Screenshot 2021-12-02 at 14 36 38" src="https://user-images.githubusercontent.com/18663444/144392157-8bb6e3fa-02a8-4946-a545-6d1e9e4ba06a.png">

**Steps to reproduce:**

Follow the aforementioned steps.

**Affected Versions:**
- Ballerina Swan Lake Beta 05
- VSCode Ballerina plugin `v2.1.1`
- VSCode version: 1.62.3
- macOS

**Comment by nadeeshaan** [comment]
In the case where we do not have the check keyword, the `myStream.` will be identified as a field access expression while in the case of having the `check` keyword, the node at the cursor is identified as the `CheckExpressionNode` it self. Hence we cannot route to the field access completion resolver. I think the parser itself avoid having a field access expression on this particular scenario, since we expects  a call expression.

@lochana-chathura @rdulmina thoughts?

If we are to fix this, we might need to have it fixed from the parser. Hence adding the parser label

**Comment by lochana-chathura** [comment]
We fixed the following scenario recently for issue #33940
```
public function abc() {
    check mod1:<cursor>
}
```
yeah we can do the same for `check myStream:<cursor>` as well. Small fix. Will do.
