### ISSUE TITLE
Debug hit failure for object init() method inside language and standard libraries

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#34258]
**Description:**
Incorrect line number table generation for `lang.query` module's `types.bal` class.

**Steps to reproduce:**

- Consider the following code segment:

```
1. public function main() {
2.     int[] nums = [1, 2, 3, 4];
3.     int[] numsTimes10 = from var i in nums
4.                         select i * 10;
5. }
```

- Add a debug point in line number `3`.
- Once the debug point is hit, `STEP_IN` at line number 3.
- This will step into the first line of `createPipeline` method. This method is situated in `lang.query` module's `helpers.bal` class.
- Now again `STEP_IN`. This will step into the first line of `init` method of `_StreamPipeline` class. This method is situated in `lang.query` module's `types.bal` class.
- Now add a debug point inside the `init` method of `_StreamPipeline` class. 
- Start the debug session again.
- Now we could able to observe that the debug point will not get hit.
- The reason for this is `referenceType` does not contain all the necessary line locations.
<img width="548" alt="Screen Shot 2021-12-10 at 1 36 38 PM" src="https://user-images.githubusercontent.com/11292766/145539622-980ee55a-75c7-429f-9cbd-e48e2339ce5d.png">

**Comment by praveennadarajah** [comment]
The above issue is **not** reproducible for single ball files. The issue is only reproducible in ballerina projects.

**Comment by gabilang** [comment]
The line number table generated for `types.bal` class in the `lang.query` module seems correct and the generated byte codes are same (except the module name references) in the single bal file case and ballerina project. Since single `bal` file is also considered as a ballerina project with default module (`.`), the code generation for both cases are similar and the generated line number tables are same. It looks like nothing needed to be done from code generation side.

**Comment by gabilang** [comment]
As per the offline discussion, removed the jBallerina label.

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/34697
