### ISSUE TITLE
Cannot call in the module `init` function a function that is not a function in the same module when there are uninitialized module-level variables

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#34400]
**Description:**
$subject

**Steps to reproduce:**
```
final readonly & map<int> m1;

function init() {
    map<int> m2 = { "i1": 2 };
    m1 = m2.cloneReadOnly(); // error uninitialized variable `m1`
}

public function main() {
}
```

**Affected Versions:**
swan-lake beta6

**Comment by MaryamZi** [comment]
The related spec issue was https://github.com/ballerina-platform/ballerina-spec/issues/424.

See https://github.com/ballerina-platform/ballerina-spec/issues/424#issuecomment-617511275.

We seem to have disallowed any function call rather than those calling module-level functions of the particular module.

**Comment by MaryamZi** [comment]
Also, the following doesn't result in a compilation error. Prints false instead.

```ballerina
import ballerina/io;

int[] x;

class Foo {
    int[] m = x;

    function init() {

    }
}

function init() {
    Foo f = new;
    int[] v = f.m;
    x = [1, 2];
    io:println(v is int[]); // prints false
}
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/35823.
