### ISSUE TITLE
Constant type members are added as `SingletonypeSymbol`s in union types

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34448]
**Description:**
Consider the following code:
```
const VAN = "VAN";
const CAR = "CAR";

function func() {
     CAR|VAN i = getVehicleType();
}
```
Here, when we look at members of union type `CAR|VAN`, the members are of type `SingletonTypeSymbol` instead of `ConstantTypeSymbol`.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta6

**Comment by pubudu91** [comment]
The issue here is that due to the way we have modelled constants in the compiler, there's a loss of association info when the constant is used in type contexts. For a constant we create two module-level AST nodes:
- A `BLangConstant` instance for representing the constant
- A `BLangTypeDefinition` instance. Generated to provide a type when the constant is used in type contexts.

Had an offline discussion with @hasithaa, @mohanvive, @MaryamZi, @nadeeshaan, @IMS94 etc.  on how best to handle this. Discussed the following approaches:

1. Keep track of the constant symbol in the `BFiniteType` for finite types created for constants. 
        - Pros: No/minimal intrusion to the compiler
        - Cons: Basically a hack, not a proper design. 
2. Instead of using the constant's value in the value space of the finite type, use a reference to the constant instead. i.e., a `BLangSimpleVarRef` to the constant. 
        - Pros: More in-line with the spec's definition of singleton types and can preserve the link to the constant from the finite type.
        - Cons: Impacts the compiler since we may have assumed the value space of constant types to be literals.
<img width="497" alt="Screenshot 2022-03-07 at 17 13 54" src="https://user-images.githubusercontent.com/6260009/157030692-1cb32d7d-093c-4377-99c8-3ce87cf29dd6.png">

3. The other option is of course to remodel how constants and singleton types are represented in the compiler. This would be ideal, but the most complex option as well since this would mean a complete overhaul of `BFiniteType`.

**Comment by pubudu91** [comment]
Related issues: #34640, #34808
