### ISSUE TITLE
[Query Expressions] Possible improvements related to completions

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#34528]
**Description:**
Came across a few cases that we could improve the completions/suggestions for query expressions. Most of them are minor improvements that we could consider.

1. Suggest only the iterator variables as input in `from` clause

<img width="786" alt="iterator-value-suggestion" src="https://user-images.githubusercontent.com/7523274/148317532-ef9ac8ec-17f9-43c8-9cb4-c93cc126e6b9.png">

2. Avoid suggesting imports within record declaration

<img width="703" alt="Import-suggestion-record" src="https://user-images.githubusercontent.com/7523274/148318045-1ed67f81-9c17-4490-add9-934a764ca30d.png">

3. Could suggest field names of the `Person` type in select clause

<img width="628" alt="Slect-clause-suggestion" src="https://user-images.githubusercontent.com/7523274/148318339-76af6458-8f46-494a-b7a5-daf44d2bdf82.png">

4. Expression in `join` clause snippet does not produce accurate code
It seems, in `join` clause all the `expr` considered as identical. Shall we improve this?

https://user-images.githubusercontent.com/7523274/148319699-e333babb-8c75-48fd-b161-4a78cea0cf06.mov

5. Suggestions are not provided for regular key press but works for option+ESC (in mac).
What is the reason for this behavior?

https://user-images.githubusercontent.com/7523274/148320945-3a44e177-86d8-4cdb-9df1-4b192de2475a.mov

working.....

**Affected Versions:**

ballerina-swan-lake-2201.0.0-SNAPSHOT (December 23rd build)

**Comment by nadeeshaan** [comment]
@mohanvive,
If we consider
case 2:
- We can refer types coming from other modules, hence we suggest the modules.

Case 5: 
- If we consider the context `join Person person in personArray on i<cursor>` we currently have a limitation identifying the context from the syntax tree and we haven't implemented the workaround in order to reduce the complexity. Now if you consider `join Person person in personArray on <cursor>`, we can identify the proper context in this scenario. That is why you can see the completion items when you press `cmd + space`. Once these completions appear and if you continue typing, the editor will not send the completion request to the server and instead it will filter from the list (intellisense) available at the moment. That is why we can see the completions are working while typing

**Comment by IMS94** [comment]
`Case 1`
We have improved the sorting order to suggest iterable variables and functions that return iterables first.

`Case 2` - is valid because, a user may define a record like this:
```ballerina
type Data record {|
    http:Ok status?;
    string name;
    string id;
|};
```
For such cases, `http` module import should be provided so that user can continue to write `http:Ok status?;` field.

`Case 3`
We are now suggesting the field names inside the `select` clause

`Case 4` is now fixed

`Case 5` won't fix at this time due to the associated complexity. Will reconsider if the same issue is reported in the future.

Closing this issue since all the cases have been addressed (or provided reasons to not fix at this time).
