### ISSUE TITLE
Code Action not appearing when the cursor is inside the service

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#34542]
**Description:**
Wrote a code action to add a code snippet for the TCP service. When I keep the cursor inside the service as follows, it doesn't show the code actions.
<img width="464" alt="Screenshot 2022-01-06 at 15 07 10" src="https://user-images.githubusercontent.com/11239305/148362116-dfe6a6f3-3e99-4209-a736-959e87541a9e.png">

Code actions are only appearing at line 3 and line 5.

<img width="376" alt="Screenshot 2022-01-06 at 16 00 05" src="https://user-images.githubusercontent.com/11239305/148369173-6a6fbaf8-1e3a-4b90-b57c-b09877510247.png">

<img width="352" alt="Screenshot 2022-01-06 at 16 00 22" src="https://user-images.githubusercontent.com/11239305/148369190-5d975cf4-d9e7-4169-8c5e-efbbf62398d4.png">

Appears when there are other members inside the function.
<img width="381" alt="Screenshot 2022-01-06 at 16 01 55" src="https://user-images.githubusercontent.com/11239305/148369304-f6bc36a4-5f55-4652-8d43-a83026c23344.png">

Is there a way to overcome this?

**Comment by TharushiJay** [comment]
The issue here is that code actions are not triggered for empty lines. Therefore, what can be done instead is to publish a visible diagnostic (a diagnostic severity which is not `INTERNAL`) from the compiler plugin that would trigger the code actions.

**Comment by Bhashinee** [comment]
> The issue here is that code actions are not triggered for empty lines. Therefore, what can be done instead is to publish a visible diagnostic (a diagnostic severity which is not `INTERNAL`) from the compiler plugin that would trigger the code actions.

When writing code actions, we cannot change the severity from `INTERNAL` to something visible. can we?

**Comment by nadeeshaan** [comment]
> > The issue here is that code actions are not triggered for empty lines. Therefore, what can be done instead is to publish a visible diagnostic (a diagnostic severity which is not `INTERNAL`) from the compiler plugin that would trigger the code actions.
> 
> When writing code actions, we cannot change the severity from `INTERNAL` to something visible. can we?

This actually depends on how we are going to guide the user.  Basically, this particular behaviour for the code actions are universal. The code actions typically triggers for the lines having tokens.
On the other hand, if we show a diagnostic to cover the particular range that would not be better user experience when comparing the look and feel. This is because, once the user knew how to execute the code action and where it appears, then the diagnostic become annoying since it is not an error. So I'm -1 for adding the diagnostic. IMHO, we should train the user via proper documentation on how to trigger the code action. 
The way, the IDEs/ code editors have defined the code action experience leverage this. This is one of the reasons that the VSCode IDE triggers the code actions requests once we move the cursor in between lines with tokens.

PS: Also, we can try to move the code action to the context menu. But, we have to check whether it will honour for the empty line.

**Comment by IMS94** [comment]
Agree with what @nadeeshaan has mentioned. Since we cannot improve this scenario in a non-invasive manner to the user, LS cannot fix this case. 

The stdlib can decide if it's ok to show a visible diagnostic that will surely go away once the code action is applied (or if the user follows the mandatory steps of the given service). Therefore closing this issue. Please reopen if there's any concern.
