### ISSUE TITLE
Too many arguments compilation error for a function with included record param

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#34572]
**Description:**

**Steps to reproduce:**
Run the below sample.
```
public type Value anydata|Valuer;

public type Valuer isolated function () returns anydata;

public type KeyValues record {|
    never msg?;
    never 'error?;
    error:StackFrame[] stackTrace?;
    Value...;
|};

public isolated function printDebug(string msg, error? 'error = (), *KeyValues keyValues) {
    
}
public function main() {
    error err = error("bad sad");
    printDebug("something went wrong", 'error = err, stackTrace = err.stackTrace(), username = "Alex92", admin = true, id = 845315,
    attempts = isolated function() returns int {
        return 3;
    });
}
```

Getting the below error.
```
Compiling source
	log.bal
ERROR [log.bal:(17:85,17:104)] too many arguments in call to 'printDebug()'
ERROR [log.bal:(17:106,17:118)] too many arguments in call to 'printDebug()'
ERROR [log.bal:(17:120,17:131)] too many arguments in call to 'printDebug()'
ERROR [log.bal:(18:5,20:6)] too many arguments in call to 'printDebug()'
error: compilation contains errors
```

**Affected Versions:**
Latest Master build

**OS, DB, other environment details and versions:**
MacOS

**Comment by MaryamZi** [comment]
The errors are observed for the arguments specified corresponding to the record rest descriptor (`Value`) - `username`, `admin`, `id`, and `attempts`. 

For included record parameters the [spec](https://ballerina.io/spec/lang/master/#function_call) says

> The arg-name of every named-arg must be distinct. Each named-arg must correspond to either a parameter that is not a rest-param or to a field of an included-record-param. In the latter case, there are two possibilities.
> 
> - The field is described by an individual-field-descriptor with a type that is not never.
> - The field is described by a record-rest-descriptor, either explicitly as part of an exclusive-record-type-descriptor or implicitly as part of an inclusive-record-type-descriptor. In this case:
>   - for every parameter name and every individual-field-descriptor of an included-record-param with a type that is not never, the record-type-descriptor must include an individual-field-descriptor that has type never and is optional, and so disallows a field with that name;
>   - **the record-type-descriptor must not include any other individual-field-descriptor;** and
>   - there must be no other included-record-param with a record-rest-descriptor.

I believe compilation errors for this function call are expected according to the spec since these additional arguments correspond to the record-rest-descriptor of an included record parameter but the record-type-descriptor includes an individual-field-descriptor for `stackTrace`.

Looping in @jclark and @hasithaa. Would appreciate your input.

To specifically solve the log module's issue, should we consider making making `error:StackFrame[]` part of the record-rest-descriptor instead of an individual-field-descriptor? This may also help reduce backward compatibility issues for when the stack trace is passed with a different key (named argument) at the moment.

```ballerina
public type KeyValues record {|
    never msg?;
    never 'error?;
    Value|error:StackFrame[]...;
|};
```

**Comment by jclark** [comment]
I agree that the highlighted bullet point makes it an error. But I don't remember why it does that. Is it just to keep things simple or is there a more fundamental reason? Need to think.

If we do `Value|err:StackFrame`, won't we get back to the same problem we had before?

How about adding `stackTrace` as an defaultable argument (`error:StackFrame[]? stackTrace = ()`)?

**Comment by MaryamZi** [comment]
> If we do `Value|err:StackFrame`, won't we get back to the same problem we had before?

Yes, sorry, my bad. What I had suggested is what we had originally.

> How about adding `stackTrace` as an defaultable argument (`error:StackFrame[]? stackTrace = ()`)?

+1. 

Looping in @daneshk also.

**Comment by MaryamZi** [comment]
Closing this since the log module was updated to use a defaultable parameter as suggested in https://github.com/ballerina-platform/ballerina-lang/issues/34572#issuecomment-1008570710.

https://github.com/ballerina-platform/ballerina-spec/issues/1021 has been created regarding the restriction in the spec disallowing the original solution.
