### ISSUE TITLE
Duplicate field name error for wildcard assignments at module level

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#34610]
**Description:**
```ballerina
decimal _ = 3600 * 24;
decimal _ = 3600; 
```

Getting
`
Error: LinkageError occurred while loading main class $_init
        java.lang.ClassFormatError: Duplicate field name "_" with signature "Lio.ballerina.runtime.internal.values.DecimalValue;" in class file $_init
`

**Steps to reproduce:**

**Affected Versions:**
SL Beta 6

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
In the above examples, both global variables are passed as `_` from compiler FE, that results in a duplicate naming error in the bytecode. 
This can be fixed by having a specific generated name for these (same typed `_` variables) variables such as `$ignoreVar1` .
IMO, It is preferred to do it in compiler FE , because this is reflected in the BIR and not specific to jballerina.
BIR dump
```
================ Emitting Module ================
module hinduja/foo v 0.1.0;

import ballerina/io v 1.1.0;
import ballerinai/observe v 0.0.0;

$annotation_data map<any>;
_ decimal;
_ decimal;


public .<init> function() -> error{map<Cloneable>}|() {
 }
```

**Comment by MaryamZi** [comment]
Tracked in https://github.com/ballerina-platform/ballerina-lang/issues/38978
