### ISSUE TITLE
Port SemType Tests from nBallerina to lang repo Tests

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34629]
$Subject.
No of people: 2

**Comment by KavinduZoysa** [comment]
As per the discussion had with @hasithaa, @rdhananjaya, @gimantha, @chiranSachintha, 
our plan is,
- write semtype test runner to check all subtype relations for given test file
- split the test available [here](https://github.com/ballerina-platform/nballerina/tree/main/compiler/testSuite/semtype) into small pieces and change the comment to include all possible relations in order to test against semtype test runner.

**Comment by KavinduZoysa** [comment]
We have to write separate tests for type tests available in [here](https://github.com/ballerina-platform/nballerina/tree/main/compiler/testSuite/semtype). 
Let's restrict each test file to having a maximum of four relations. 
Any failing test case should be present in a single bal file and it should be renamed as `-f.bal`


- [ ] anydata-tv.bal   
- [ ] fixed-length-array-t.bal        
- [ ] not1-tv.bal   
- [ ] proj2-tv.bal  
- [ ] table-t.bal    
- [ ] tuple2-tv.bal  
- [ ] tuple4-tv.bal          
- [ ] xml-complex-rw-tv.bal  
- [ ] xml-readonly-tv.bal  
- [ ] xml-te.bal
- [ ] bdddiff1-tv.bal  
- [ ] fixed-length-array-tuple-t.bal  
- [ ] proj1-tv.bal  
- [ ] table2-t.bal  
- [ ] tuple1-tv.bal  
- [ ] tuple3-tv.bal  
- [ ] xml-complex-ro-tv.bal  
- [ ] xml-never-tv.bal       
- [ ] xml-sequence-tv.bal

**Comment by KavinduZoysa** [comment]
@chiranSachintha, let's do our changes in this branch https://github.com/ballerina-platform/ballerina-lang/tree/semtype-tests

**Comment by KavinduZoysa** [comment]
Identified issues:
https://github.com/ballerina-platform/ballerina-lang/issues/34696

**Comment by chiranSachintha** [comment]
As discussed with @rdhananjaya We are going to ignore the following two kinds of test cases which are in the semtype test suite

1. [Intersection](https://github.com/ballerina-platform/nballerina/blob/f1560e776a3a3944e2a019c2f12678e22ce8e815/compiler/testSuite/semtype/fixed-length-array-t.bal#L40) related tests(Because ballerina doesn't support these kinds of scenarios)

Example 
```ballerina
type IntArray int[];
type ArrayExcept5 IntArray & IntArray;
```

2. kind of [array](https://github.com/ballerina-platform/nballerina/blob/f1560e776a3a3944e2a019c2f12678e22ce8e815/compiler/testSuite/semtype/fixed-length-array-t.bal#L29) related test cases

Example
```ballerina
type IntArray int[];
// @type IntArray = Array5OfIntArray[4]
type Array5OfIntArray int[5][];
```
In this test case, generate a value related to `Array5OfIntArray` and get the type related to the fourth element of the value. (But there's no way to generate it in jballerina) 

Any idea to port this kind of test cases? @gimantha @MaryamZi @hasithaa @KavinduZoysa

**Comment by KavinduZoysa** [comment]
@chiranSachintha, I think,
in case 1:
since we support `&` operator with readonly and error we can ignore that test case.
in case 2:
Sometimes we will be able to find test cases that can be rearranged to support our implementations.
ex:
Let's say we have to test something like this.
```ballerina
type IntArray int[];
// @type IntArray <: Array5OfIntOrFloatArray[4]
type Array5OfIntOrFloatArray (int|float)[5][];
```
Even we can't test this as it is, we can rearrange this as follows.
```ballerina
type IntArray int[];
// @type IntArray <: IntOrFloatArray
type IntOrFloatArray (int|float)[];
```

**Comment by MaryamZi** [comment]
> As discussed with @rdhananjaya We are going to ignore the following two kinds of test cases which are in the semtype test suite
> 
> 1. [Intersection](https://github.com/ballerina-platform/nballerina/blob/f1560e776a3a3944e2a019c2f12678e22ce8e815/compiler/testSuite/semtype/fixed-length-array-t.bal#L40) related tests(Because we doesn't support these kinds of scenarios)
> 
> Example
> 
> ```ballerina
> type IntArray int[];
> type ArrayExcept5 IntArray & IntArray;
> ```

Depending on the effort, can't we migrate these also and keep them disabled and enable them as and when we add support for other kinds of intersections?

> 
> 2. kind of [array](https://github.com/ballerina-platform/nballerina/blob/f1560e776a3a3944e2a019c2f12678e22ce8e815/compiler/testSuite/semtype/fixed-length-array-t.bal#L29) related test cases
> 
> Example
> 
> ```ballerina
> type IntArray int[];
> // @type IntArray = Array5OfIntArray[4]
> type Array5OfIntArray int[5][];
> ```
> 
> In this test case, generate a value related to `Array5OfIntArray` and get the type related to the fourth element of the value. (But there's no way to generate it in jballerina)
> 

When you say value, do you mean a runtime test?
