### ISSUE TITLE
Need to decide on for which scenarios we should provide Language Server options (e.x: rename, code-actions) 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34706]
**Description:**
The user is provided with the options even for errored ballerina codes.

Sometimes code-actions are suggested where we don't need to suggest.
Ex: 
```ballerina
type DataRecord record {|
    string date;
    string state;
    int death;
    int positive;
|};

type DataRow record {|
    time:Utc dateTime;
    string state;
    int death;
    int positive;
|};

function sortTable(table<DataRecord> a) returns table<DataRow> {
    table<DataRow> aa = a.map(function(drecord) returns DataRow {
        return {
            dateTime: [0, 0],
            death: 0,
            positive: 0,
            state: ""
        };
    });
}
```
Here code-actions are suggested even though we don't have meaningful diagnostic

**Related Issues (optional):**
- https://github.com/ballerina-platform/ballerina-lang/issues/34694

**Comment by nadeeshaan** [comment]
When we consider the way we utilise the diagnostic information through the diagnostic API, we have to ensure that we do a second layer of safety validation as well. It seems sometimes, there are semantically ambiguous information captured in the diagnostic properties.

**Comment by dulajdilshan** [comment]
Another scenario: https://github.com/ballerina-platform/ballerina-lang/issues/34787

**Comment by dulajdilshan** [comment]
Another scenario:
Case 1: 
```
type TypeMap map<>;

public function main() {
    TypeMap tt = {};
}
```

Case 2:
```ballerina
type TypeTable table<>;

public function main() {
    TypeTable tt = table [];
}
```
Here the type-descriptor in the type definition is missing. However, We can't perform rename, go-to-def, find-references on this code.

**Comment by TharushiJay** [comment]
Invalid `change variable type` code action (on the issue description) has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35709.

Before :
<img width="720" alt="Screenshot 2022-05-19 at 11 25 06" src="https://user-images.githubusercontent.com/27485094/169220332-9ecac0c1-41c8-40ce-8aae-ac59e708b14b.png">

After :
<img width="720" alt="Screenshot 2022-05-19 at 11 28 31" src="https://user-images.githubusercontent.com/27485094/169220612-a76d12ad-43da-4992-bc2e-eb0940d804c5.png">
