### ISSUE TITLE
Compiler gives incorrect error related to var assignment

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#34735]
**Description:**

Consider following example

```ballerina
import ballerina/io;

public function test() {
    string[] s = [x,x];
    io:println(s);
}

var x = "str";
```

above code segment outputs following error

```Compiling source
balTest.bal
ERROR [balTest.bal:(4:19,4:20)] incompatible types: expected 'string', found 'other'
ERROR [balTest.bal:(4:21,4:22)] incompatible types: expected 'string', found 'other'
error: compilation contains errors
```

But if we change the var assignment position as shown below, it is working as expected

```ballerina
import ballerina/io;

var x = "str";

public function test() {
    string[] s = [x,x];
    io:println(s);
}
```

**Comment by pubudu91** [comment]
This is an issue in how the module level decls are ordered. During symbol entering, we set `x`'s type as no type since there's no type node and therefore, we cannot determine its type at that point. We come back to this in semantic analyzer, determine its type and overwrite it. The issue in the first of these cases is that since the var decl is after the function it's used in, we see no type as `x`'s type since the compiler hasn't yet updated its type.
