### ISSUE TITLE
Re-evaluate quick fix Code Actions 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34787]
**Description:**
Suggesting code-actions which doesn't solve the error. If we keep executing the code-action it will repeatedly do the same even though it doesn't solve the error in the code
![Adding_check_repeatedly_Peek 2022-01-21 16-50](https://user-images.githubusercontent.com/25485997/150518606-9b0e61d2-9651-48fa-89bc-f2c8413653b1.gif)

**Steps to reproduce:**
1. Execute the Code action suggested on `readBinaryMessage`
```ballerina
import ballerina/websocket;

public function main() returns error? {
    websocket:Client cl = check new ("ws://localhost:8808");
    byte[]|websocket:Error readBinaryMessage = cl->readBinaryMessage();
    byte[]|websocket:Error response = wait readBinaryMessage;
}
```

**Affected Versions:**
VSCode v3.0.0-preview-m9, Ballerina v2201.0.0-rc1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Given the code snippet, this behaviour is expected. In order to fix the diagnostic, the `readBinaryMessage` variable should be a `future`. Even though we add the `check`, the issue does not get resolved. The intension of this particular code action is to do a thin validation against the type of the expression. We do not perform an explicit semantic validation against the enclosing expression.

**Comment by gayalkuruppu** [comment]
https://docs.google.com/document/d/10LCUNwRZY3IRX0zmokyWn7W364XeCOqG8Xx4cSDYVUA/edit?usp=sharing
