### ISSUE TITLE
[Debugger] Support for evaluating function calls of imported modules

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#34875]
**Description:**
```ballerina
import ballerina/lang.value;
public function main() {
    int a = name();
    string balString = value:toBalString("hr");
}

function name() returns int {
    return 1;
}
```

Evaluating `name()` returns 1 
Evaluating `value:toBalString("hr")` causes 
```
Failed to evaluate.
Reason: Failed to load the required classes to execute method: 'toBalString'

```

**Steps to reproduce:**

**Affected Versions:**
SL GA

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
@pcnfernando We already support qualified function evaluations and the issue is not reproducible for me when trying the latest RC pack on mac. 
<img width="742" alt="Screenshot 2022-01-28 at 09 44 54" src="https://user-images.githubusercontent.com/29032600/151486409-28e628f0-1af7-4d22-8801-8c3aa6df630f.png">

May I know your Ballerina version and the OS if possible?

**Comment by pcnfernando** [comment]
SL GA RC3 in Mac OS
Seems this is only happening when debugged on a single file run.
