### ISSUE TITLE
Child nodes are missing when paste a code

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#34953]
**Description:**
```ballerina
import ballerina/http;

service / on new http:Listener(8090) {
    resource function get say\-hello(http:Request req) returns json|error {
        http:Client clientEP = check new ("https://postman-echo.com/post");
        json clientResponse = check clientEP->forward("/", req);
        return clientResponse;
    }
}

```
The node visitor is giving an empty function body for the above code. This is happening only when we paste a code or redo/undo the code. Its giving the correct ST when we did a manual code change  (Ex: add a new line to EOF)
![Screenshot from 2022-02-07 10-33-30](https://user-images.githubusercontent.com/16335290/152728003-dea542be-e03e-4727-88bb-979cef1e00af.png)

**Steps to reproduce:**
Copy Paste the above code

**Affected Versions:**
Ballerina: Swan Lake
Plugin : 3.0.0

**OS, DB, other environment details and versions:**
Ubuntu

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Once analysed, it seemed that the plugin emit the performance analyser event before the didChange event emitted and notifying the language server. Since the language server sync the document content upon the didChange and didOpen notifications, in order to get the up to date syntax/ semantic information, the document synchronising events should come before any other event which depends on the latest content.

@gigara shall we create a plugin issue to track this?

**Comment by gigara** [comment]
Since the didChange event fires through vscode, we don't have a way to synchronize the other LS API calls. The best way we can achieve is to implement a notifier from LS side. Then we can await for the LS notification for didChange event before sending other LS API calls.

**Comment by nadeeshaan** [comment]
Currently we are working on the following in order to facilitate a similar behaviour.
https://github.com/ballerina-platform/ballerina-lang/issues/35057

**Comment by IMS94** [comment]
The project update notifications is now implemented with https://github.com/ballerina-platform/ballerina-lang/issues/35057 and can be used for this kind of scenarios.

Plugin can now listen for project updates and get notified via the `LanguageClient` and act accordingly.

Closing this issue since the rest of the development have to be done at the plugin side and in LS extensions.
