### ISSUE TITLE
Mapping constructor expression fails to determine the correct type based on field type

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#34987]
```
const A = "A";
const B = "B";
type Name A|B;

type TA record {|
    int i;
    A name = A;
|};

type TB record {|
    int i;
    B name = B;
|};

type T TA|TB;

public function main() {
    Name name = nameFn(1);
    T t = { i: 1, name };
}

function nameFn(int i) returns Name {
    if i==0 {
        return A;
    }
    return B;
}

```
Above code fails with error `incompatible mapping constructor expression for type 'T'` while if we use an explicit type check as fallows it works
```
const A = "A";
const B = "B";
type Name A|B;

type TA record {|
    int i;
    A name = A;
|};

type TB record {|
    int i;
    B name = B;
|};

type T TA|TB;

public function main() {
    Name name = nameFn(1);
    T t;
    if name is A {
        t = { i: 1, name };
    }
    else {
        t = { i: 1, name };
    }
}

function nameFn(int i) returns Name {
    if i==0 {
        return A;
    }
    return B;
}

```

**Comment by MaryamZi** [comment]
Right now, type checking for constructor expressions with union contextually-expected types works as follows.

For `A|B _ = E;` we check if `E` is a valid constructor against each member of the expected union type (i.e., first `A` and then `B`). Basically we check `A _ = E;` and `B _ = E;`.
- if `E` is compatible with only one of `A` or `B`, we use the single type to determine the inherent type
- if `E` is compatible with more than one of `A` and `B`, we log an ambiguous type error
- if `E` isn't compatible with any member, we log an incompatible types error

In this particular example, neither of the following is valid

```ballerina
TA _ = {i: 1, name};
TB _ = {i: 1, name};
```

Therefore, `T _ = {i: 1, name};` is also considered invalid.

I don't think we should be allowing this, since we wouldn't know at compile-time what the inherent type of this constructed value is.

The spec actually doesn't allow even what jBallerina allows atm.

>  If the applicable contextually expected type is a union type descriptor, then any members of the union that are inconsistent with the field names specified in a specific-field in the mapping-constructor-expr will be ignored; it is a compile-time error if this does not leave a single mapping type descriptor, which is then used as the inherent type.

jBallerina does some additional checks and these are being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/33056 and https://github.com/ballerina-platform/ballerina-spec/issues/962.

We will revisit this with the spec changes.
