### ISSUE TITLE
Support resolution of packages built with patch distributions of the same major release

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#35069]
**Description:**
We have the rule that a package built with newer distributions will not be compatible with older distributions. This has to be refined to add this restriction to only Update releases (i.e. minor version releases of the distribution). Packages built with a patch distribution of the same major release should be supported.

**Comment by Dilhasha** [comment]
We need to check whether the distribution versions are pre-release versions when comparing the major and minor versions.

Otherwise, a package built with a lower pre-release version (e.g.`2201.0.0-beta1`), will be evaluated as compatible for a patch update.(e.g. `2201.0.5` ).
The same applies to pre-release distributions.

**Comment by azinneera** [comment]
> We need to check whether the distribution versions are pre-release versions when comparing the major and minor versions.
> 
> Otherwise, a package built with a pre-release version (e.g.`2201.0.6-beta1`), will be evaluated as compatible for a patch distribution version.(e.g. `2201.0.5` ).

AFAIK, there won't be any pre-release for patch releases. By any chance, if we decide to release a pre-release for Updates, then the minor version will be different. (e.g 2201.0.5 vs 2201.1.0-beta.1). So this should not be an issue.
