### ISSUE TITLE
Integration test support for stdlib packages

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#35062]
**Description:**
Compiler plugin tests and ballerina package tests are run in separate gradle sub modules. When the ballerina tests are run, the compiler plugin is not engaged. Hence the logic should be tested separately. If a dev misses to write the compiler logic, the issue is found only when running the distribution. Each stdlib should be self contained, hence there should be a way to test both compiler plugin logic and the ballerina src together.

**Solution**
1. Language provide support to write integration test to test the package as a whole (Preferred)
2. Stdlibs write gradle submodule and integrated both tests to run together

**Related issue**
https://github.com/ballerina-platform/ballerina-standard-library/issues/2047

**Comment by ThisaruGuruge** [comment]
Writing Gradle submodule for the compiler plugin is not an ideal solution. There are a couple of drawbacks.

1. There's no way to get the code coverage for the compiler plugin tests
Since the compiler plugin tests are a separate set of tests written using TestNG, we cannot get the code coverage for the compiler plugins. This is an issue we are facing currently. All the standard library code coverage values are calculated without the compiler plugins, which is somewhat misleading.

2. There's more room for human errors
When the ballerina package tests run, the compiler plugin is not applied. Therefore, all the unit tests are run without validation from the compiler plugin. This can lead to issues where the developers may write tests that are passing as unit tests, but the functionality actually does not work due to a compiler plugin issue. 
This is true for the other way around as well. Currently, the compiler plugin tests are written using a separate Gradle submodule, but we only test them by compiling them. Not by running them. So, there can be instances where the compiler plugin test is passing (as we only test them by compiling), but the runtime functionality is not working as expected. 

Therefore, I think having the integration tests inside the ballerina package is the ideal solution. It would be great if there's a way to test compilation errors as well using integration tests (or some other way) to calculate the code coverage for the compiler plugin.

**Comment by ThisaruGuruge** [comment]
Any update on this? With the [code coverage issue occurred recently](https://github.com/ballerina-platform/ballerina-standard-library/issues/4107), the importance of integration tests is increased. Without integration tests, testing a package with compiler plugins is becoming harder.
