### ISSUE TITLE
[Semantic API] Lang lib methods with multiple type params missing in table type's lang lib methods

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35271]
The issue with the above is that we don't seem to consider lang lib methods with multiple type params properly. The result is that methods like `filter()` and `remove()` are missing in table type's lang lib methods.

**Comment by dulajdilshan** [comment]
Had a discussion with @gimantha @pcnfernando @MaryamZi @pubudu91 on this. Here the bug is that the tables are defined without specifying a key are not assignable to the type of the first-param of the `remove()` and `filter()` lang-lib functions.
```ballerina
public isolated function filter(table<MapType> key<KeyType> t, @isolatedParam function(MapType val) returns boolean func)
```
https://github.com/ballerina-platform/ballerina-spec/blob/e8a25f6ebdb03a3eb110f162c7a06b58777a9375/lang/lib/table.bal#L105

```ballerina
public isolated function remove(table<MapType> key<KeyType> t, KeyType k) returns MapType = external;
```
https://github.com/ballerina-platform/ballerina-spec/blob/e8a25f6ebdb03a3eb110f162c7a06b58777a9375/lang/lib/table.bal#L125

Fix:
`table<MapType>` should be assiginable to `table<MapType> key<KeyType>`

**Comment by dulajdilshan** [comment]
Further clarification on the issue:
```ballerina
public function main() {
    table<record {|readonly int id;|}> tb = table key(id) [{id: 12}];
    tb.<cursor>
}
```

Here we are not getting `filter()` and `remove()` as lang-libs because we have implemented such that  `table<MapType> key<KeyType>` is not assignable `table<MapType>`. Shoudl we special case this?
![Screenshot from 2022-06-01 15-31-24](https://user-images.githubusercontent.com/25485997/171380546-4f147a71-07f4-4a63-a936-c9cdbf970c00.png)
![Screenshot from 2022-06-01 15-31-48](https://user-images.githubusercontent.com/25485997/171380560-4ac110df-64c2-4787-8af3-3005e6ef13bd.png)

**Comment by dulajdilshan** [comment]
Closing this. Reason: https://github.com/ballerina-platform/ballerina-lang/issues/35576#issuecomment-1178554744
