### ISSUE TITLE
Create function code action is not suggested with record/object field default values

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#35347]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Department record {|
    string name;
    int id = fn();
|};

// Or
// class Department {
//     int id = fn();
// }
```

**Affected Versions:**
2201.0.1

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/35325

**Comment by nadeeshaan** [comment]
In order to provide the particular code action, we capture the possible return type of the function. In this particular scenario `int`. This is captured with the `typeOf` api by providing the `fn()` as the argument. In this scenario the returned type is captured as `CompilationErrorType` which we need to fix.

**Comment by pubudu91** [comment]
> In order to provide the particular code action, we capture the possible return type of the function. In this particular scenario `int`. This is captured with the `typeOf` api by providing the `fn()` as the argument. In this scenario the returned type is captured as `CompilationErrorType` which we need to fix.

This is not something that can be fixed at the Semantic API level though.
