### ISSUE TITLE
HTTP compiler plugin is not working inside `tests` directory

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#35413]
**Description:**

HTTP compiler errors and code actions are not shown for files in `tests` directory. 

**Steps to reproduce:**

1. Create a Ballerina package with the `bal new` command 
2. Create a directory in the root directory of the package named `tests` and create `test.bal` inside this directory
3. Add the following service in the `main.bal` file :
```ballerina
import ballerina/http;

service /hello on new http:Listener(9090) {
    resource function get . (http:Caller caller) returns string {
        return "Hello World!";
    }
}
```
This will give a compiler error : `invalid resource method return type: can not use http:Caller and return string from a resource : expected error or nil (HTTP_118)`
4. Add the same service in the `test.bal` file. This did not give any compiler error.

**Affected Versions:**
2202.0.1 (Swan Lake)

**Comment by pramodya1994** [comment]
Seems this issue is happening due to the following code block in the [`SyntaxNodeAnalysisTaskRunner`](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/SyntaxNodeAnalysisTaskRunner.java#L57)
```java
   private void runTasks(ModuleContext moduleContext, List<Diagnostic> reportedDiagnostics) {
        for (DocumentId srcDocumentId : moduleContext.srcDocumentIds()) {
            DocumentContext documentContext = moduleContext.documentContext(srcDocumentId);
            runTasks(documentContext.syntaxTree(), moduleContext.moduleId(),
                    srcDocumentId, reportedDiagnostics);
        }
    }
```
In `runTasks` method we only consider `srcDocumentIds`.
@sameerajayasoma Can we improve this code for test documents as well or this has been done on purpose?

**Comment by sameerajayasoma** [comment]
I think we missed adding test documents AFAIR.
