### ISSUE TITLE
How to override an existing session

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3555]
HTTP package only has a function to create a session if not exist. How can we override an existing session?

**Comment by chamil321** [comment]
HTTP package basically has two methods to retrieve session. 

1. **createIfAbsent()** - This method creates a new session when the user has not provided with a valid BSESSION ID. Otherwise it returns the existing session correspond to the BSESSION ID. So this method gurantee a session.
2. **getSession()** - This method only returns the existing session for a valid BSESSION ID. Otherwise returns a null. BSESSION ID is sent as a cookie in the request. 

Once the user gets the session, session attributes can be changed based on their requirements.

**Comment by chamil321** [comment]
Closing the issue as the requirement will not be available in the session API.
