### ISSUE TITLE
Improve error diagnostics for conversion errors

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#35665]
**Description:**
Consider the following `main.bal`

```

type TestRow record {|
    int employeeId;
    string name;
|};

public function myFunc() returns error? {
    json val = {employeeId:7238, name:"dil", val:"hdjd"};
    _ = check val.cloneWithType(TestRow);
}

public function main() returns error? {
    check myFunc();
}
```

This throws a conversion error due to the missing field in record.

```
Compiling source
        dilhashanazeer/mytests1:0.1.0

Running executable

error: {ballerina/lang.value}ConversionError {"message":"'map<json>' value cannot be converted to 'mytests1:TestRow': 
                field 'val' cannot be added to the closed record 'mytests1:TestRow'"}
```
We can improve the diagnostics for this with line numbers etc.
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Line numbers are shown when there is a panic. For example if the `check myFunc();` is replaced with `checkpanic myFunc();`, they are shown. In the given sample, since the error value is returned from the `main` function, `toString()` of that error value is shown. Stack trace can be obtained by calling `stackTrace()` on the error value. Hence closing the issue.

Please reopen if you have further queries.
