### ISSUE TITLE
IllegalStateException when binding json to record from non ballerina thread via FromJsonWithType

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#35780]
**Description:**

Getting `java.lang.IllegalStateException: strand is not accessible from non-strand-worker threads`[1] exception when trying to bind a json payload to a record. This is done in the HTTP transport thread and not in the ballerina thread. 

Stdlibs are in the process of introducing data binding for may modules, and this is a major requirement to bind data and start ballerina thread. Earlier we used `CloneWithType` which worked fine. 

What is the solution for this or an alternative?

Update: If you give same record as an array, it works fine. :) Looks like a bug

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java#L208

**Steps to reproduce:**

**Affected Versions:**
2201.0.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Sample code
```
type Person record {|
    string name;
    int age;
|};

resource function post body6(http:Caller caller, http:Request req, @http:Payload Person person) returns error? {
    string name = [person.name](http://person.name/);
    int age = person.age;
    check caller->respond({ Key: name, Age: age });
}

resource function post body8(http:Caller caller, @http:Payload Person[] persons) returns error? {
    var jsonPayload = persons.cloneWithType(json);
    if (jsonPayload is json) {
        check caller->respond(jsonPayload);
    } else {
        check caller->respond(jsonPayload.message());
    }
}
```

**Comment by HindujaB** [comment]
This happens because the implementation calls the `fromJsonWithType()` before starting a scheduler thread while passing a `typedesc`. 
In `cloneWithType` usage, we use the `CloneWithType.convert()` API without passing the `typedesc` value. 
To solve this, 
1. We can check whether the strand is available inside `fromJsonWithType()`, and use the non-typedesc method to create the record.
2. Have a new API in `FromJsonWithType` that does not require a `typedesc` value. Similar to, https://github.com/ballerina-platform/ballerina-lang/blob/ec9174e926e0f2a62ecd3e7cb83bffb12032ef98/langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneWithType.java#L80
