### ISSUE TITLE
Getting an ambiguous error when creating a field with a number union type

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#35855]
**Description:**
Even if the number union field has an array with a specific number type, the ambiguous error returns by this function.

**Steps to reproduce:**
``` ballerina
import ballerina/io;

type Movie record {
    string title;
    int[]|decimal[] year;
    string released;
    Person writer;
};

type Person record {
    string fname;
    string lname;
    int age;
};

public function main() returns error? {
    json inceptionJ = {
        title: "Inception",
        year: [2010.0d, 2011.0d],
        released: "16 Jul 2010",
        writer: {
            fname: "Christopher",
            lname: "Nolan",
            age: 30
        }
    };

    Movie cloneWithType = check inceptionJ.cloneWithType(Movie);
    io:println(cloneWithType);
}
```

**Affected Versions:**
Ballerina 2201.0.3

**Comment by HindujaB** [comment]
The above code will give the following error.
```
error: {ballerina/lang.value}ConversionError {"message":"'map<json>' value cannot be converted to 'foo:Movie': 
                value '[2010.0,2011.0]' cannot be converted to '(int[]|decimal[])': ambiguous target type"}
```

The [spec](https://lib.ballerina.io/ballerina/lang.value/0.0.0/functions#cloneWithType) for `cloneWithType()` function mentions that the function will do the numeric conversions to clone the value to a target type. 
In that case, for the above example, the target type contains a union of numeric-based types (`int[]|decimal[]`).
Even though, the value provided here is a `decimal[]`, it still can be converted to `int[]` through `cloneWithType()`. That's why it is providing an ambiguous type error here. 

IMO, this behavior is expected.
