### ISSUE TITLE
Allow the user to change variable name(rename popup) in create variable code action

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36139]
**Description:**
$Title

**Describe your problem(s)**
We automatically suggest a variable name when using  create variable code action. Provide the ability to change the suggested name at that moment for a user preferred name(a pop up box like in rename symbol). Thus giving higher flexibility for the code action.

**Describe your solution(s)**
Check out the RedHat java plugin for how they provide this. RedHat java plugin uses the Eclipse language server (https://github.com/eclipse/eclipse.jdt.ls) to provide this functionality. We might want to look at both of those implementations.

**Comment by mindula** [comment]
The eclipse language server provides this feature by providing a command `RENAME_COMMAND` with create variable code action [1].
They have registered their own rename command, `java.action.rename`, instead of using the built-in command of the vscode plugin `editor.action.rename`.
When the `create variable` code action is used, the text edits are applied first followed by the `RENAME_COMMAND`. (For code actions we can pass a text edit and a command) and when the `RENAME_COMMAND` is executed, the inbuilt rename command of the editor is executed for the provided cursor position [2].
We can follow the same approach to provide a rename popup for our create variable code action.

[1]https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java#L140
[2]https://github.com/redhat-developer/vscode-java/blob/master/src/refactorAction.ts#L16

**Comment by mindula** [comment]
We will be using the resolve support https://github.com/ballerina-platform/ballerina-lang/issues/34935 for the implementation of this rename popup feature and for the implementation of the resolve support we will have to implement a set of APIs for several interfaces.

**Comment by IMS94** [comment]
I had a look at how `eclipse jdt ls` has done this implementation (see https://github.com/eclipse/eclipse.jdt.ls/commit/d198055a2ea6655e968e3f2db3994e4088162924#diff-b3ca2d7c5aa1c579c738fd3e8921b7a2a292570e8c3a66fb1c453ce15655debaR563)

They are calculating the rename position as part of the code action request and the returned command contains the rename position. The line pointed above is the place where they specifically check for the new position of a node.

We have to follow a similar approach. This wont be a performance impact for diagnostic based code actions since there's a filtering by the diagnostic. For the range based code actions, we have to improve the validations.

@mindula we should move that rename position calculating logic to the `getCodeActions()` method. The logic should calculate the offset from which the added variable name will be offset. And determine the rename position based on that.

**Comment by mindula** [comment]
Rename command registered in ballerina-plugin-vscode https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/493

**Comment by IMS94** [comment]
Lang side changes were merged. Waiting for the plugin side changes to be merged https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/493
