### ISSUE TITLE
Provide a better error message when validating the `ballerina.home` property

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#36222]
In the Project API, we require a system property called `ballerina.home`. This property is expected to be set to a specific ballerina distribution. This is not the typical `BALLERINA_HOME` env var we set. 

It'd be better if we can provide some sort of additional validation here other than checking if it's `null` and throw an exception if the property is not set correctly (e.g., it's set to the directory pointed by `BALLERINA_HOME`). 
https://github.com/ballerina-platform/ballerina-lang/blob/a30f2bf87c11257ab46190946ff0e686e5591134/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/BallerinaDistribution.java#L49

Otherwise we get an NPE at a later stage, when trying to load the lang libs. That NPE is not user friendly and would be hard to debug for a person who is not that familiar with the Project API.

**Comment by Ibaqu** [comment]
Adding a validation at this point would not work as it would interfere with the normal build process IMO. I have tried this but the distribution used at various build phases means the `validateBallerinaHomeDir` cannot be consistently validated. 

It must be noted that the existing validation simply checks if the path given exists and if it is a directory which is why errors can occur down the line. This can happen when the ballerina.home get set to the root of the distributions folder instead of the actual distribution


What we can do is use a separate property for scenarios like this OR we would have to derive the proper path when we notice that the path is not set properly. 

@sameerajayasoma @azinneera I believe we might need to discuss this further to implement a better solution. Wdyt?
