### ISSUE TITLE
Failed to identify the type in a type checking block

### ISSUE THREAD

**Issue by AyeshW** [ballerina-platform/ballerina-lang#36237]
**Description:**

Unable to identify the type in a type checking block. Following code block explains the issue. Expected behavior is, the else block should identify `value` as a type `B` object.

**Steps to reproduce:**
```
type A record {
    string a;
};
type B record {
    string b;
};
type C record {
    string c;
};

function typeCheck(A|B value) returns B|C {
    if value is A {
        C valueC = {c: "hello"};
        return valueC;
    } else {
        return value;
    }
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Since `A` and `B` are open records, according to the current semantic typing rules, a value of a type like `record { anydata a; anydata b; }` is valid for `A|B` here, even though jBallerina doesn't allow it yet. So we can't say the value belongs to `B` in the else block, which is why the type is not narrowed. 

The current behaviour is in-line with the current spec. Please reopen the issue if you have further concerns.
