### ISSUE TITLE
Update LS simulator to simulate addition of import declarations nodes

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36322]
**Description:**
$subject

With #36031 we introduced ability to add random import statements the editor. Now we need to simulate removal as well.

**Describe your problem(s)**
See description

**Describe your solution(s)**
See description

**Comment by mindula** [comment]
In addition to the above mentioned scenario, we should revisit this issue because now the ballerina developers are experiencing more OOMs frequently. However, the LS simulator hasn't reported any errors recently.  We should improve the LS simulator to use a project involving health care packages, which has been known to produce OOMs frequently.

**Comment by malinthar** [comment]
> In addition to the above mentioned scenario, we should revisit this issue because now the ballerina developers are experiencing more OOMs frequently. However, the LS simulator hasn't reported any errors recently. We should improve the LS simulator to use a project involving health care packages, which has been known to produce OOMs frequently.

This is addressed with https://github.com/ballerina-platform/ballerina-distribution/pull/4739
