### ISSUE TITLE
Completions and goto def are not working in annotation value context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#36351]
**Description:**
Consider the following scenario where I'm trying to define the annotation value. 
![image](https://user-images.githubusercontent.com/35211477/170914803-4579bc44-e975-4a18-8f6a-9705e0790771.png)

The goto def feature is not working for the `@hhtp:ResourceConfig` and the completions are not accurate at the depicted cursor position.  

**Steps to reproduce:**
```ballerina
service /conversionRates on new http:Listener(9090) {

    function init() {
        task:JobId result = check task:scheduleJobRecurByFrequency(new Job(), 60, maxCount = 30);
    }

    @http:ResourceConfig {
        <cursor>
    }
    resource function post register( ) {
        
    }
}
```

**Affected Versions:**
2201.1.0

**Comment by IMS94** [comment]
Had a look at this. Here the `SemanticModel` fails to find the symbol for the annotation on top of the resource function. Detailed explanation below:
1. In this case, the `withinBlock()` check inside `lookup(BLangCompilationUnit unit, LinePosition cursorPos)` method of SymbolFinder returns false because the `cursor` is outside (in the metadata node) the function definition node.
2. When looked at where the `pos` for resource functions are set, `transform(FunctionDefinitionNode funcDefNode)` method of `BLangNodeBuilder` is the one setting the `pos`. There, it set the `pos` without metadata explicitly.

@dulajdilshan What is the reason to ignore the metada when calculating position of the `BLangResourceFunctionNode`? Is this intended?

**Comment by IMS94** [comment]
See the slack thread https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1655971048193769 for more details

**Comment by lochana-chathura** [comment]
Blocked by #36731

**Comment by KavinduZoysa** [comment]
Even If we do the changes as mentioned in #36731, this original issue will not be resolved because we have not visited annotation attachments in https://github.com/ballerina-platform/ballerina-lang/blob/9d24b34069680336d075602d52cf8cb403f06bde/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java#L285

In order to fix this issue, we need both changes. (Locally tested)

**Comment by IMS94** [comment]
@KavinduZoysa we can get that updated from the semantic API side. We can proceed with the compiler FE changes right?

**Comment by KavinduZoysa** [comment]
> @KavinduZoysa we can get that updated from the semantic API side. We can proceed with the compiler FE changes right?

We will do the necessary changes from compilerFE side. Please check the progress under https://github.com/ballerina-platform/ballerina-lang/issues/37404

**Comment by IMS94** [comment]
@KavinduZoysa @dulajdilshan  even though fixing #37404 has fixed the references and completions issue, the goto definition issue is still there. What happens is that the `SymbolFinder.lookupNodes(List<? extends BLangNode> nodes)` method's `PositionUtil.withinBlock(this.cursorPos, node.pos)` check fails due to the `node.pos` (resource function's `pos`) doesn't include the annotation attachment's line range.

**Comment by KavinduZoysa** [comment]
@IMS94 we will prioritize the goto definition issue from our side.

**Comment by IMS94** [comment]
Thanks. @KavinduZoysa thanks. Created #38053 to track that.

Marking this as blocked by #38053

**Comment by IMS94** [comment]
Blocker has been fixed and now the goto definitions are working for resource function annotations as expected. LS should add a test case for this scenario
