### ISSUE TITLE
No error when assigning `{a: "A", b: [1, 2]}` to `value:Cloneable`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#36595]
**Description:**
$subject.

```bal
value:Cloneable v = {a: "A", b: [1, 2]};  // no error given
value:Cloneable w = [1, 2]; // error given
```

**Affected Versions:**
2201.1.0 at least.

**Comment by lochana-chathura** [comment]
With `public type Cloneable readonly|xml|Cloneable[]|map<Cloneable>|table<map<Cloneable>>;` definition,
I'm not sure whether first one becomes `map<readonly>`.
If it is the case, then the second one should also work with no compilation error treating it as `readonly[ ]`?

**Comment by lochana-chathura** [comment]
@MaryamZi appreciate any input on this.

**Comment by MaryamZi** [comment]
Right now, how we type check mapping/list constructors with union types is by checking the constructor against each member type of the union. If there is only one type with which the constructor is valid we use that as the type to type check the constructor. If there's none or more than one, it will result in an error.

When we consider `value:Cloneable w = [1, 2]`, `[1, 2]` could be used when both `readonly` is the contextually-expected type (CET) and `value:Cloneable[]` is the CET. So there's two possible types making it ambiguous.

```ballerina
import ballerina/lang.value;

public function main() {
    readonly a = [1, 2]; // OK
    value:Cloneable[] b = [1, 2]; // OK

    readonly|xml|value:Cloneable[]|map<value:Cloneable>|table<map<value:Cloneable>> x = [1, 2]; // error
}
```

With the mapping constructor example, `{a: "A", b: [1, 2]}` is valid with `readonly` but not `map<value:Cloneable>`, because it has a member expression that is a list constructor and for that we get an ambiguous type error against the map's member type `value:Cloneable`. So in this particular case, `{a: "A", b: [1, 2]}` is valid only for `readonly`, making it non-ambiguous.

```ballerina
import ballerina/lang.value;

public function main() {
    readonly a = {a: "A", b: [1, 2]}; // OK
    map<value:Cloneable> b = {a: "A", b: [1, 2]}; // error for `[1, 2]`

    readonly|xml|value:Cloneable[]|map<value:Cloneable>|table<map<value:Cloneable>> x = {a: "A", b: [1, 2]}; // OK
}
```

Please note these rules are kinda implementation-dependent since this is something additional we do atm (https://github.com/ballerina-platform/ballerina-lang/issues/33056).

**Comment by lochana-chathura** [comment]
Got it. Thank you.
