### ISSUE TITLE
Fix AST node positions to include metada and add another property to keep position without medatadata

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#36731]
**Description:**
$subject. 

Please refer to the discussion at [https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1655971048193769](https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1655971048193769).

**Comment by KavinduZoysa** [comment]
As per the offline disussion had with @hasithaa, we decided that the suggested approach will become an extra overhead to the compiler. In order to fix the original issue mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/36351, a different approach was suggested in https://github.com/ballerina-platform/ballerina-lang/issues/37404.

Hence closing this issue. We will https://github.com/ballerina-platform/ballerina-lang/issues/36351 under #37404
