### ISSUE TITLE
Getting html tags in ballerina shell `/help` (BBE help)

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36750]
**Description:**
When we get `/help isolated variables` in bal shell, we get `html` tags which we need to remove.
<img width="744" alt="Screenshot 2022-06-28 at 17 55 07" src="https://user-images.githubusercontent.com/46120162/176177860-c4920fcc-2f09-4ea1-98c7-a62640673fa8.png">

**Steps to reproduce:**
`/help isolated variables`

**Affected Versions:**
2201.1.1 RC2

**Comment by MaryamZi** [comment]
@gayalkuruppu, was this intentionally marked as a Compiler FE issue? The behaviour is because how the BBE is written, right? I believe this should go away with the BBE change to MD format.

https://github.com/ballerina-platform/ballerina-distribution/blob/bbe-generation-v2/examples/isolated-variables/isolated_variables.md 

Even without that though, I think if at all, it should be handled on the shell side? We couldn't have gotten rid of them in the BBE?

**Comment by gayalkuruppu** [comment]
@MaryamZi its a mistake, Intention was to tag FETools

**Comment by mohanvive** [comment]
It is fixed now.
