### ISSUE TITLE
List literal compilation errors for recursive type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#36809]
```ballerina
public type Type "int" | List;
public type List ["list", Type[]] | ["list", Type[], int] |  ["list", Type[], int, Type];
public function main() {
    List intPair = ["list", ["int"], 2]; // works
    List intSingleton = ["list", ["int"]]; // error "ambiguous type 'user/bal_sexp.sexpr:0.1.0:List'"
}

```

**Comment by MaryamZi** [comment]
> ```ballerina
> public type Type "int" | List;
> public type List ["list", Type[]] | ["list", Type[], int] |  ["list", Type[], int, Type];
> public function main() {
>     List intPair = ["list", ["int"], 2]; // works
>     List intSingleton = ["list", ["int"]]; // error "ambiguous type 'user/bal_sexp.sexpr:0.1.0:List'"
> }
> ```

When a constructor expression is used with a union as the contextually-expected type, the compiler checks if that expression is valid with each member type of the union. If it is valid with only one we use that, if there isn't at least one or if there's more than one it'll result in an error.

In this example, since `["list", ["int"]]` is valid with both `["list", Type[]]` and `["list", Type[], int]` (with the filler value), this is considered ambiguous.

Related lang issue - https://github.com/ballerina-platform/ballerina-lang/issues/33056 (https://github.com/ballerina-platform/ballerina-lang/issues/33056#issuecomment-953919836)
Spec issue for the current behaviour - https://github.com/ballerina-platform/ballerina-spec/issues/962

Also related to https://github.com/ballerina-platform/ballerina-lang/issues/33129

**Comment by MaryamZi** [comment]
> ```ballerina
> public type Type "int" | List;
> public type List ["list", Type[]] | ["list", Type[], int] |  ["list", Type[], int, Type];
> 
> function f(List l) {
>     Type t = l; // error "incompatible types: expected 'user/rectypeliterror:0.1.0:Type', found 'user/rectypeliterror:0.1.0:List'(BCE2066)"
> }
> ```

Shall we create a separate issue for this?

**Comment by manuranga** [comment]
Thanks for the explanation. I forgot about the filler value. Found a workaround for this by factoring the type as 

```ballerina
public type SimpleList ["list", Type[]];
public type List SimpleList | ["list", Type[], int] |  ["list", Type[], int, Type];
```

I'll create a separate issue for the other.

**Comment by manuranga** [comment]
Looks like cloneWithType can handle this case though, not sure how it deals with filler value ambiguity.

**Comment by MaryamZi** [comment]
> 

I believe the behaviour should be the same (https://github.com/ballerina-platform/ballerina-spec/issues/890#issuecomment-987511226).

The following results in an error, so probably leads to not being detected as ambiguous when used with the union.

```ballerina
public function main() returns error? {
    [string, [string]] x = ["list", ["int"]]; 
    ["list", Type[], int] _ = check x.cloneWithType(); // error: "'[string,[string]]' value cannot be converted to '["list",Type[],int]'"
}
```

Seems like filler values aren't handle properly with tuples: the following results in an error.

```ballerina
public function main() returns error? {
    [int, int] intTuple = [1, 2];
    int[3] _ = check intTuple.cloneWithType(); // OK
    [int, int, int] _ = check intTuple.cloneWithType(); // error: '[int,int]' value cannot be converted to '[int,int,int]'
}
```

Shall we create an issue for this too?
