### ISSUE TITLE
NPE during nballerina nightly build

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#36848]
```
java.lang.NullPointerException
	at io.ballerina.runtime.internal.types.BFiniteType.toString(BFiniteType.java:161)
	at io.ballerina.runtime.internal.types.BUnionType.computeStringRepresentation(BUnionType.java:507)
	at io.ballerina.runtime.internal.types.BUnionType.toString(BUnionType.java:351)
	at io.ballerina.runtime.internal.TypeChecker.checkIsLikeRecordType(TypeChecker.java:2663)
```

```
java.lang.NullPointerException
	at io.ballerina.runtime.api.values.BError.<init>(BError.java:37)
	at io.ballerina.runtime.internal.values.ErrorValue.<init>(ErrorValue.java:92)
	at io.ballerina.runtime.internal.values.ErrorValue.<init>(ErrorValue.java:82)
	at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:52)
```

https://github.com/ballerina-platform/nballerina/runs/7180608429?check_suite_focus=true

**Comment by manuranga** [comment]
Any update on this? build has been failing due to this for 10 days. This can be covering other issues in the build.

**Comment by warunalakshitha** [comment]
As per error log, It seems the same issue https://github.com/ballerina-platform/ballerina-lang/issues/36664 which is already  fixed in master and 2201.2.x branches.

Error log still provide the old code line (With new fix we cannot have NPE in BFiniteType.java:161). https://github.com/ballerina-platform/ballerina-lang/blob/2201.2.x/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFiniteType.java#L161. 

So fix seems not applied in jblalerina lang version use in nballerina build. What is the jballerina version we use in nballerina build?

**Comment by manuranga** [comment]
We use latest build from https://github.com/ballerina-platform/ballerina-distribution/actions/workflows/main.yml
It should be updated if its in the master, @keizer619

**Comment by manuranga** [comment]
I tested on 2201.2.x, this is not there. So it looks like master is ether lagging or not sync.

**Comment by manuranga** [comment]
@warunalakshitha 
>  already fixed in master and 2201.2.x branches.
You mean 2201.1.x ? there is no 2201.2.x in https://github.com/ballerina-platform/ballerina-distribution/actions

**Comment by warunalakshitha** [comment]
No. I mean ballerina lang 2201.2.x branch. BTW fix has been merged to master, 2202.1.x and 2201.2.x. so respective distributions should include the fix if we are using the latest ballerina lang.

**Comment by warunalakshitha** [comment]
But it seems master daily build has been failing for two weeks.

**Comment by warunalakshitha** [comment]
I am closing this since fix is merged to the master. Please reopen if you have further queries on this.
