### ISSUE TITLE
Function mock fails when a function assigned to a module-level variable is being mocked

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#36854]
**Description:**

$title

**Steps to reproduce:**
```ballerina
float f = floatAdd(2, 3);

public function floatAdd(float a, float b) returns float {
    return (a + b);
}

public function floatAdd2(float a) returns float {
    return a + f;
}
```
at test.bal
```ballerina
import ballerina/test;

public function mockFloatAdd(float a, float b) returns (float) {
    return 5;
}

@test:Mock {
    functionName: "floatAdd",
    moduleName: "function_mocking"
}
test:MockFunction mock_floatAdd = new();

@test:Config {}
function testFloatAdd() {
    test:when(mock_floatAdd).call("mockFloatAdd");
    test:assertEquals(floatAdd(2, 3), 5.0);
}
```
output:
```
Running Tests

        function_mocking
error: Dependant module initialization for test suite failed due to java.lang.NullPointerException
        at org.function_mocking.0:$MOCK_floatAdd(function_mocking:1)
           org:.<init>(function_mocking:3)
           org:$moduleInit(function_mocking:-1)
           jdk.internal.reflect.NativeMethodAccessorImpl:invoke0(NativeMethodAccessorImpl.java:-2)
           jdk.internal.reflect.NativeMethodAccessorImpl:invoke(NativeMethodAccessorImpl.java:62)
           jdk.internal.reflect.DelegatingMethodAccessorImpl:invoke(DelegatingMethodAccessorImpl.java:43)
           java.lang.reflect.Method:invoke(Method.java:566)
           org.ballerinalang.test.runtime.entity.TesterinaFunction:lambda$runOnSchedule$0(TesterinaFunction.java:108)
           io.ballerina.runtime.internal.scheduling.SchedulerItem:execute(Scheduler.java:610)
           io.ballerina.runtime.internal.scheduling.Scheduler:run(Scheduler.java:316)
           io.ballerina.runtime.internal.scheduling.Scheduler:runSafely(Scheduler.java:283)
           java.lang.Thread:run(Thread.java:834)
error: there are test failures
```

**Affected Versions:**
2201.0.x, 2201.1.x

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
This is a known issue. I have looked into this after the runtime changes however it is not possible to mock functions that initialise global variables. 

This is inherently due to how function mocking is designed. Function Mocking happens in 2 stages : 

     1. Replacing the function calls with a Desugared Mock Handler function (stubbing)
     2. When a test runs, we instruct the Desugared Mock Handler function to perform certain action; either call another function, return a specific value or call the original function 
     
Both these steps are required to execute for Function Mocking to work. 


For initialising global variables with functions, this happens **before** the Mock Handler function receives instructions on what to do. Ie the mock handler doesn't know what to do when the function is called, which is why the exception occurs. Essentially, for these types of functions, stage 2 doesnt run. 

To get this to work, we would have to have a function on the test suite that executes the mock instructions before global variables are initialised. However this would mean that the mocking would happen only once.

**Comment by Ibaqu** [comment]
A workaround for this would be to use the legacy function mocking that is still in-built to the test framework. This type of function mocking is an older version that replaces all calls before any global initialization. However it lacks the nuance of the existing newer function mocking which lets us return values and call original functions. 

```
@test:Mock {
    functionName : "floadAdd"
}
public function mockFloatAdd(float x, float y) returns (float) {
    return x - y;
}
```
