### ISSUE TITLE
Enable `testMultipleDynamicListenersWithAsyncCall` jballerina integration test case

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#36929]
**Description:**
Above test case is disabled with #  due to intermittent failures. 

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gabilang** [comment]
It's not failing locally even with multiple runs. It's observed intermittently failing due to the PR builds due to timeouts. 
One possibility for timeout is, the error message is not being logged due to the server shutdown happened before registering any listener. But it seems the already written tests gave enough time for that. 
It's waiting for the error message to be logged but it didn't happen within the timeout. The error message should be logged within that time, no reason for extra time, it looks like the graceful shutdown of listener is not happening, it can be happen the listener is not registered. So server interruption is happening sometimes before the listeners are registered. It can be the reason for the intermittent failures.

**Comment by gabilang** [comment]
It seems there can be a possibility for intermittent failures due to the way of the test has been written. The server interruption expected to be happen during the program execution. If it happens after the program execution, the messages is not going to be logged and the port is going to wait for the message is to be logged. So there's a possibility for timeouts.
