### ISSUE TITLE
Runtime error when trying to create a readonly value

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#37031]
I have following module level variable.
```ballerina
final readonly & jwt:ValidatorConfig jwtConfig = {
    issuer: JWT_ISSUER,
    audience: JWT_AUDIENCE,
    clockSkew: 60,
    signatureConfig: {
        jwksConfig: { url: JWKSENDPOINT }
    }
};
```

it gives:

```
error: {ballerina/lang.map}InherentTypeViolation {"message":"invalid value for record field 'clientConfig': expected value of type '(jwt:ClientConfiguration & readonly)', found 'jwt:ClientConfiguration'"}
        at ballerina.jwt.2.$anonType$_18:$anonType$_18$gen$.<init>(jwt_validator.bal:59)
```

If I remove `readonly`, it runs.

**Comment by MaryamZi** [comment]
This is expected atm since the [default value specified for the `clientConfig` field in the record descriptor](https://github.com/ballerina-platform/module-ballerina-jwt/blob/v2.3.1/ballerina/jwt_validator.bal#L59) is mutable.

The behaviour will most likely change with https://github.com/ballerina-platform/ballerina-spec/issues/544.

**Comment by warunalakshitha** [comment]
I am closing this since it is not bug based on current spec. Please reopen if you have further queries on this.
