### ISSUE TITLE
On fail should only be allowed with regular-compound-stmt

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#37315]
**Description:**
Ref https://ballerina.io/spec/lang/master/#stmt-with-on-fail

**Steps to reproduce:**

**Affected Versions:**
2201.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gayalkuruppu** [comment]
For now `TransactionStatementNode` and `RetryStatementNode` has an `Optional<OnFailClauseNode> onFailClause()` and the on fail is allowed.

**Comment by pcnfernando** [comment]
Original impl based on https://github.com/ballerina-platform/ballerina-spec/issues/337#issuecomment-660922407

**Comment by buehlefs** [comment]
What is the reason `on fail` support is removed for transactions? Updating the spec to specifically support it for transaction blocks could also be an option here, as there is a clear use case for this feature.

For example, I use this extensively to streamline error handling of transaction blocks (since all my database calls are wrapped in transactions anyway). The alternatives to this are:
* Checking every single result for errors -> ~1 extra if statement per result
* Wrapping the transaction in a `do` block with `on fail` -> one extra level of nesting
* Refactoring the transactions into individual functions -> the best choice but creates many single-use functions just for better error handling

The `on fail` of transaction blocks could also be interpreted as syntactic sugar for `do { transaction {...} } on fail ...`. This could be useful to simplify defining the semantics in combination with retry of transactions.

**Comment by SasinduDilshara** [comment]
Had a chat with internal team and decided to allow on fail for transaction and retry statements
