### ISSUE TITLE
Function pointers are not equal when the same pointer is passed as two different parameters

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#37379]
**Description:**
If the same function pointer is passed as two different parameters to a function, then there are not equal under the `===` operator.

**Steps to reproduce:**
The output of the following program returns false where it should be true.
```ballerina
function func() {}
function twoFunctionsEqual(function f, function g) returns boolean => f === g;

public function main() {
    io:println(twoFunctionsEqual(func, func));
}
```

**Affected Versions:**
2201.2.0-RC1

**Comment by HindujaB** [comment]
This happens because we load two different temporary variables for each function pointer parameter of the `twoFunctionsEqual` function.
The BIR for the above function call looks like this. 
```ll
public main function() -> () {
    %0(RETURN) ();
    %1(TEMP) any;
    %2(TEMP) function() -> ();
    %3(TEMP) function() -> ();
    %4(TEMP) boolean;
    %5(TEMP) ();

    bb0 {
        %2 = fp hinduja/foo:0.1.0::func;
        %3 = fp hinduja/foo:0.1.0::func;
        %4 = twoFunctionsEqual(%2, %3) -> bb1;
    }
    bb1 {
        %1 = <any> %4;
        %5 = println(%1) -> bb2;
    }
    bb2 {
        %0 = ConstLoad 0;
        GOTO bb3;
    }
    bb3 {
        return;
    }

}
``` 

Note that the `%2`, `%3` are created to load the same function pointer `func`. 
The function invocation contains two required args with different temporary variables at compilation.

![Screenshot from 2022-08-16 10-24-55](https://user-images.githubusercontent.com/28644893/184800910-5a160b05-ed73-4dec-a826-6d3daeaca5c6.png)

The temporary variable creation for the same function pointer needs to be optimized here.

**Comment by HindujaB** [comment]
This one works. 
```ballerina
public function main() {
    function func = function() => ();
    io:println(twoFunctionsEqual(func, func));
}
```

**Comment by nipunayf** [comment]
The equality returns false for functions with parameters while it worked for others.
```ballerina
import ballerina/io;

function func() {}
function func_with_params(string param) {}
function func_with_return() returns error? {}

function twoFunctionsEqual(function f, function g) returns boolean => f === g;

public function main() {
    io:println(twoFunctionsEqual(func, func)); // returns true
    io:println(twoFunctionsEqual(func_with_params, func_with_params)); // returns false
    io:println(twoFunctionsEqual(func_with_return, func_with_return)); // returns true
}
```
