### ISSUE TITLE
[Bug]: typeOf() in Ballerina Semantic Model gives incorrect typeSymbol for basic literal type

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37613]
### Description

Please check the below example. This is happening in all extract to features due to the semantic models behaviour. 

https://user-images.githubusercontent.com/46120162/188084634-66ef3eca-b572-4b62-a340-a676284bb387.mov

This happens because when trying to access the type of the node `9090`, the `typeOf()` in `SemanticModel` identifies it as `ballerina/module1:0.1.0:Listener` instead of `int`.

### Steps to Reproduce

```
import ballerina/module1;

service on new module1:Listener(9090) { // select the range for `9090`
    
}
```
Use the config format in `extractIntRangeToConstant.json` and change the ballerina file `extractToConstant.bal` to debug. There you can include a range as the input. Else you will get the same behaviour when you have the cursor on `9090`.

### Affected Version(s)

2201.2.x

### Labels

CompilerFETools

**Comment by DamithaSenevirathne** [comment]
This was fixed in 2201.2.x with the fix https://github.com/ballerina-platform/ballerina-lang/pull/37838. 
In master and 2201.3.x.this was fixed by the PR : https://github.com/ballerina-platform/ballerina-lang/pull/37493

Since we decided to revert the fix(https://github.com/ballerina-platform/ballerina-lang/pull/38304) in the master, need to send the fix in 2201.2.x to the master.
