### ISSUE TITLE
[Improvement]: Generate a main method for the testable jar

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#37739]
### Description

ATM, the test runner has to handle the initialization of the module, and configurations, and stop them when executing tests. This is currently done by invoking the required methods through Reflection APIs in Java. This imposes limitations on the following features: 
1. Migrating the test framework completely to Ballerina
    - The execution still has to be done using reflection since init, start and stop methods has to be handled by the test runner
2.  Supporting `bal test` with GraalVM native image
     - The GraalVM native image needs an entrypoint

### Suggested solution(s)

When performing the code generation, the testable jars should also be generated with a main which will handle the initialization, test execution and stopping of the module.

**Comment by azinneera** [comment]
This is not a blocker for GraalVM implementation since we decided to use the main method in the test runner as the entrypoint.

**Comment by gabilang** [comment]
Having Java main methods for each testable JARs as the entry points of execution (each testable jar needs to be run separately through `java -cp` command using separate Java processes) may have some limitations on test native image build and test debugging:

- When build native images of tests, multiple images going to be generated (images will be generated per testable packages).

- Debugging with test packages will be affected since debugger going to connect and disconnect to the port per execution of testable JARs - needs to start debugging manually through IDE/code editor each time upon one jar's completion.

So we need to have a single Java main to execute all of the testable JARs. We can keep the `BTestMain.java` for that as currently it's being used and use reflections to invoke main methods of testable JARs.
