### ISSUE TITLE
[Improvement]: Format complex records with nested record types

### ISSUE THREAD

**Issue by axewilledge** [ballerina-platform/ballerina-lang#37881]
### Description

When we try to convert a complex JSON with multiple models it gives record types in single lines. Need to get it formatted correctly.

![image](https://user-images.githubusercontent.com/12099227/191664193-316db142-fad7-4bf4-bc66-72d48b69a148.png)

**Comment by NipunaRanasinghe** [comment]
@axewilledge Please note that it'll be the expected behaviour for the above scenario, as the current formatter is designed in a way that it'll always try to preserve the user's preference when it comes to lists related scenarios (e.g. function parameter list, record field list). Therefore, 

- if the user has kept all the inline record fields in a single line, the existing formatting will be preserved.
- if the user has kept fields in 2 or more lines, the rest of the record fields will be formatted into multiple lines.

Please refer to the below example for which demonstrate the above 2 cases for an inline record.
https://user-images.githubusercontent.com/29032600/192258641-d3b2ee53-03f0-45a1-9370-2cb3edef98e5.mov

**Comment by axewilledge** [comment]
Above format is only needed for JSON to Record conversion endpoint only. `jsonToRecord/convert`

**Comment by AzeemMuzammil** [comment]
Reopening with the PR #37984

**Comment by AzeemMuzammil** [comment]
Reopening with the PR https://github.com/ballerina-platform/ballerina-lang/pull/37984
