### ISSUE TITLE
[Bug]: LS API to convert record to JSON does not work properly

### ISSUE THREAD

**Issue by tharindulak** [ballerina-platform/ballerina-lang#38440]
### Description

Please refer $subject.

### Steps to Reproduce

I am trying to convert below json and create a record. I am giving Person as the name of the Record. (Note there's a nested field with same name).

```
{
    "person":{
        "id": 1001,
        "firstName": "Vinnie",
        "lastName": "Hickman"
    },
    "course": [
        {
            "id": "CS6002",
            "title": "Computation Structures",
            "credits": 4
        },
        {
            "id": "CS6003",
            "title": "Circuits and Electronics",
            "credits": 3
        },
        {
            "id": "CS6004",
            "title": "Signals and Systems",
            "credits": 3
        }
    ]
}
```

### Affected Version(s)

ballerina-2201.2.2

### Related area

-> Other Area

**Comment by AzeemMuzammil** [comment]
This issue can be resolved with 2 options,

1. If the JSON string contains a field with the same name as user provided Record name, the tool would give a diagnostics and fail.
2. We can treat a such scenario as below given example and generate the Record,

```json
{
    "person":{
        "id": 1001,
        "firstName": "Vinnie",
        "lastName": "Hickman"
    },
    "course": [
        {
            "id": "CS6002",
            "title": "Computation Structures",
            "credits": 4
        },
        {
            "id": "CS6003",
            "title": "Circuits and Electronics",
            "credits": 3
        },
        {
            "id": "CS6004",
            "title": "Signals and Systems",
            "credits": 3
        }
    ]
}
```

```ballerina
type Person record {
    Person person?;
    CourseItem[] course?;
    string id?;
    string firstName?
    string lastName?
};

type CourseItem record {
    string id;
    string title;
    int credits;
};
```

Note: Here the Person record got a field of Person as optional which is a cyclic reference to it self.

Here we can't change the field name `person` to some other, as it would cause the JSON schema to change. and can't change the User defined name as well because it's obvious.

@hevayo Can you give your inputs as well?

**Comment by hevayo** [comment]
We should go with option 1 and ask user to put a meaningful name.
