### ISSUE TITLE
[Improvement]: Improve native-image build-time memory usage for transaction scenarios

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#38826]
### Description

Ballerina examples with transactions seems to be consuming a lot of memory when building the native-image.  Need to investigate on this and do any improvements to reduce the memory usage. 

### Describe your problem(s)

When trying to add GraalVM Native Test workflow in `SQL` module,  we observed OOM issue. The workflow runners only have 7GB of RAM.

The tried running about 3/4 transaction tests of sql module locally(with 16GB RAM) using `bal test --native` and observed that the `Peak RSS` for the build is larger than 10GB. Even a single transaction test run with native build reported more the 8GB as the `Peak RSS`.

Since the GitHub workflow runner has only 7GB of RAM, this is a blocker to deploy native test workflow in `SQL` module

### Describe your solution(s)

Need to investigate on this high memory usage and check whether there can be any improvements done from ballerina runtime side

### Related area

-> Runtime

### Suggested assignee(s) (optional)

@warunalakshitha @HindujaB

**Comment by NipunaMadhushan** [comment]
Similar issue happens with prometheus as well. when we try to build native image for a simple http service with observability metrics enabled via prometheus, I'm getting the following error.

```
=== Memory statistics (in MB):
=== Used heap size: 8094
=== Free heap size: 3974
=== Maximum heap size: 11652
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
Error: Image build request failed with exit status 1
nipunal@nipunal native-issue % native-image -jar target/bin/native_issue.jar  --no-fallback -H:MaxDuplicationFactor=40.0 -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
```

**Comment by Nadeeshan96** [comment]
High memory usage during graalvm native image build is due to the high complexity of the desugared Ballerina code, which is consisting of high no. of basic blocks and jumps. Here the issue is observed when we have database access methods inside the retry transaction blocks, and usually when the code is complex, high memory usage is observed. Until we come across a possible way to reduce the memory usage, we can follow the following workaround. We need to simplify our Ballerina functions such that higher order loops and jumps are inside them minimised. For retry transaction blocks we can move complex operations such as database access inside them to separate functions. In that way the graalvm native image builder will be able to use less memory to analyse and optimise the Ballerina functions. 

@TharmiganK @kaneeldias, shall we refactor the sql-module transaction test code like this? I have sent a draft PR which shows possible refactoring, and I was able to successfully build the native image with the Peak RSS of 7.45GB and run all the tests without any problem. You may be able to further improve that, and reduce the memory usage.
```
nadeeshand@nadeeshand ballerina % module-ballerina-sql/target/ballerina-runtime/bin/bal test --native
Compiling source
        ballerina/sql:1.7.0
WARNING [tests/local-transaction-test.bal:(100:5,100:70)] unused variable 'ignore'
WARNING [tests/local-transaction-test.bal:(208:5,208:83)] unused variable 'ignore'
WARNING [types.bal:(1429:63,1429:72)] invalid reference in documentation 'close()' for type 'function'
WARNING [types.bal:(1440:43,1440:52)] invalid reference in documentation 'close()' for type 'function'
========================================================================================================================
GraalVM Native Image: Generating 'sql' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (10.1s @ 0.24GB)
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC
 2 user-specific feature(s)
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.ballerina.stdlib.crypto.svm.BouncyCastleFeature
[2/7] Performing analysis...  [*************]                                                          (101.5s @ 7.29GB)
  28,297 (94.95%) of 29,803 classes reachable
 102,053 (82.37%) of 123,895 fields reachable
 172,103 (76.50%) of 224,970 methods reachable
   1,414 classes,   784 fields, and 2,674 methods registered for reflection
      91 classes,    94 fields, and    66 methods registered for JNI access
       6 native libraries: -framework CoreServices, -framework Foundation, dl, pthread, stdc++, z
[3/7] Building universe...                                                                              (37.5s @ 7.93GB)
[4/7] Parsing methods...      [*****]                                                                   (28.7s @ 2.98GB)
[5/7] Inlining methods...     [***]                                                                      (5.7s @ 1.91GB)
[6/7] Compiling methods...    [*****************]                                                      (299.2s @ 5.51GB)
[7/7] Creating image...                                                                                 (10.2s @ 6.12GB)
 135.59MB (60.58%) for code area:   125,447 compilation units
  72.97MB (32.60%) for image heap:  539,735 objects and 98 resources
  15.25MB ( 6.81%) for other data
 223.81MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
  24.13MB ballerina.sql$test/1.tests                          22.68MB byte[] for code metadata
  16.60MB ballerina.http/2                                    13.18MB byte[] for embedded resources
   4.84MB ballerinai.transaction/0                             7.59MB java.lang.Class
   4.03MB ballerina.http/2.types                               5.77MB byte[] for java.lang.String
   3.02MB ballerina.sql/1                                      5.33MB java.lang.String
   2.82MB ballerina.io/1                                       4.02MB byte[] for general heap data
   2.78MB org.hsqldb                                           2.59MB com.oracle.svm.core.hub.DynamicHubCompanion
   2.63MB ballerina.test/0                                     1.49MB byte[] for reflection metadata
   1.59MB sun.security.ssl                                     1.09MB java.lang.String[]
   1.41MB ballerina.file/1                                     1.03MB c.o.svm.core.hub.DynamicHub$ReflectionMetadata
  71.00MB for 923 more packages                                7.07MB for 3712 more object types
------------------------------------------------------------------------------------------------------------------------
                       62.3s (12.3% of total time) in 135 GCs | Peak RSS: 7.45GB | CPU load: 3.62
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
module-ballerina-sql/ballerina/target/native/sql (executable)
module-ballerina-sql/ballerina/target/native/sql.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'sql' in 8m 24s.

Running Tests

        sql
Test suite initiated
Docker container for Database 'Transaction' created.
Docker container for Database 'Transaction' initialised with the script.
Test suite finished


                13 passing
                0 failing
                0 skipped
```

**Comment by TharmiganK** [comment]
@Nadeeshan96 thank you for the update. The 7.45GB memory usage is still too high to run the workflow. And this is only to run the sql transaction test cases. If possible we need to improve it further.

@kaneeldias / @niveathika can you review the above PR and check whether it is possible to improve it further?

**Comment by Nadeeshan96** [comment]
> IMO this is not a valid workaround, you have refactored by moving 2 database query call to separate function. From ballerina code perspective, we cannot call these as complex code that requires its own function.

Yes, we will search for a way to reduce the memory usage by looking at the graalvm features. We had looked at the possibility to split the retry transaction blocks to separate functions, but could not find a way due to variable scope problems, debugger functionalities, and closures. We will check this further if a solution cannot be found from the former.

>  How much is the memory usage for one test case?

Peak RSS during native image generation is mentioned below. Data during consecutive runs are comma separated. We can see at different times, it takes different memory usage and no clear pattern with increasing no. of tests.

|                                                                     | 1 test (testLocalTransaction)    | 2 tests (+ testTransactionRollbackWithCheck) | 3 tests (+ testTransactionRollbackWithRollback) |
|---------------------------------------------------------------------|--------------------------------|----------------------------------------------|-------------------------------------------------|
| Before refactoring (here when running tests, they crashed in MacOS) | 5.19GB, 5.57GB, 5.93GB, 6.04GB | 6.30GB, 7.06GB                               | 7.43GB, 7.11GB                                  |
| After refactoring (tests ran fine)                                  | 5.97GB, 5.94GB, 6.19GB         | 5.19GB, 4.84GB                               | 5.51GB, 4.50GB                                  |

We previously removed the database access code inside the tests and the code relevant to docker container and built the image. The peak RSS were as follows.
- 3 tests - 5.21 GB
- 8 tests - 5.51 GB
- All tests - 5.07GB

Then when we built the image with all the tests without the database access code, the Peak RSS was 5.35GB. That's why we thought to move those to separate functions.

**Comment by Nadeeshan96** [comment]
We have checked the Graalvm features such as native image options and found out we cannot mitigate the high memory usage using them. Hence we will look at a way to change how the byte code is generated such that it takes less memory during native image generation.
