### ISSUE TITLE
[Bug]: Extract code actions extract negative int literals incorrectly

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38860]
### Description

Consider

```ballerina
public function demo() {
    int a = -1<cursor>;
}
```
On `-1` we get `extract to constant`, `extract to local variable` and `extract to function` code actions. When applied, 
```ballerina
const int CONST = 1;
public function demo() {
    int a = -CONST;
}
```
Note the `-` sign being left behind. Same for other 2 code actions as well.

If cursor is like `-<cursor>1`, then this extracts correctly

### Steps to Reproduce

See description

### Affected Version(s)

2201.3.0-rc3

### Related area

-> Editor

**Comment by gayalkuruppu** [comment]
@IMS94  For the case, `int a = -1<cursor>;` the parser identifies the node at cursor as `1` (the numeric literal). And for the case `int a = -<cursor>1;` the parser identifies the node at cursor as `-1` (the unary expression). So this was intentional in the implementation. If you check by highlighting the two scenarios, the code actions are coming as expected. 

But in this scenario, if we need to improve the code actions to expect to extract the unary expression, we will have to special case this when `range.startPosition() == range.endPosition()`. 

But then for the scenario, when we have `int a = -12<startPos>34<endPos>56;` what do you expect to be extracted?

**Comment by IMS94** [comment]
Agreed that it may not be straightforward to identify the node to be extracted. Hence closing this.
