### ISSUE TITLE
[Bug]: GraalVM native image generation failed when we use prometheus

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-lang#38968]
### Description

native-image build fails with the following error when we include prometheus. 
```
=== Memory statistics (in MB):
=== Used heap size: 8094
=== Free heap size: 3974
=== Maximum heap size: 11652
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
Error: Image build request failed with exit status 1
nipunal@nipunal native-issue % native-image -jar target/bin/native_issue.jar  --no-fallback -H:MaxDuplicationFactor=40.0 -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
```

### Steps to Reproduce

The sample code is given below.

```ballerina
import ballerina/http;
import ballerinax/prometheus as _;

service /srvc on new http:Listener(8090) {
    resource function get success() returns string|error {
        return "successful";
    }
    resource function get failure() returns error? {
        return error("Failure");
    }
}
```

### Related area

-> Runtime

**Comment by HindujaB** [comment]
This seems to be due to the nested loops used inside a resource function defined in the `init` function of the Prometheus module.
https://github.com/ballerina-platform/module-ballerinax-prometheus/blob/689f06c69b28d7178a9a7d63addc96255a7a6d9f/prometheus-extension-ballerina/metric_reporter.bal#L66

We can move the loop into a separate function and call the function. This will solve the issue.
