### ISSUE TITLE
[Bug]: `typeOf()` API returns incorrect result for simple name ref in xml attribute access expr

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#39015]
### Description

Consider the following code:
```ballerina
    xml x5 = xml `<para id="greeting">Hello</para>`;
    string|error id = x5.io:;
```
Here, when we perform `semanticModel.typeOf()` on `x5` in `x5.io:` expression, the result is `string|error`, not `xml`.

When investigated seems like the relevant BLangNode's derivedType is also set to `string|error` in this case.

### Affected Version(s)

2201.3.0

### Related area

-> Editor

**Comment by IMS94** [comment]
In #38958, xml attribute access related test cases were disabled due to this

**Comment by dulajdilshan** [comment]
Checked this in 2201.3.1,

We get `XMLTypeSymbol` in `typeOf` for `x5`
<img width="690" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/25485997/d6d5d12c-8111-421a-90b2-ead3de2ad50a">

And, 
in later versions it gives `null` for `null` which is correct since `x5` in `x5.io:` is not a complete expression (x5 here is a var-ref).

The original issue LS had was solved with `expectedType` API in Semantic Model. 

Closing this as invalid
