### ISSUE TITLE
[Bug]: LS does not recover from bad sad error

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#39014]
### Description

Consider https://github.com/ballerina-platform/ballerina-lang/issues/39012.

In the above scenario, although the code snippet that generates the bad, sad error is removed, the subsequent compilation requests keep showing the bad sad error. 

### Affected Version(s)

Update 3

### Related area

-> Editor

**Comment by malinthar** [comment]
Did some investigation and figured that the LS becomes unresponsive due to the OOM caused by subsequent Bad Sad errors. Therefore removing the code snippet does not do anything.

**Comment by malinthar** [comment]
![image](https://user-images.githubusercontent.com/35211477/208636540-6e8ac306-c523-4f44-a12a-79338fb19dca.png)

When I investigated the Bad Sad error figured out that it occurs multiple times due to multiple invocations of the method `lookupLanglibMethod`.  

https://github.com/ballerina-platform/ballerina-lang/blob/8fb5b5deb75d3fee6d248f1b7498ff35b71aecc9/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java#L752-L755

It seems that the used memory grows rapidly after throwing the unhandled exception each time as depicted in the above image. Need to further investigate this to check what is causing the memory growth.

**Comment by IMS94** [comment]
@hasithaa @mohanvive @gimantha It's better if we start looking into this. It's the fact that LS (ultimately the compiler) not recovering forever is the concern here. Can we investigate into this? IMO this is critical.

**Comment by mohanvive** [comment]
I believe we could start looking at this issue since it is a blocker.

**Comment by pcnfernando** [comment]
Debugging the scenario in https://github.com/ballerina-platform/ballerina-lang/issues/39012; observed the below

1. When the user adds the mentioned code snippet, it causes the compiler to throw a Bad Sad error.
2. When the compiler crashes, the compilation is marked as crashed https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java#L318 and the project's caches are cleared https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java#L319
3. To clear the cache, we remove the references from the project cache so that it would be cleared during GC.
4. In the meantime LS receives continuous compilation requests for building up the semantic model from different operation contexts(eg: hover, code action, etc)
5. For each of these requests, it compiles, crashes, and builds up an unreferenced object
6. When this happens until GC is performed, these objects take up memory and cause it to go OOM
7. If we perform GC manually right after clearing the project cache, it would not go OOM

Hence, as the solution, the successive requests to compile after a Bad Sad will proceed only for source changes.
The fix is added in https://github.com/ballerina-platform/ballerina-lang/pull/39190
