### ISSUE TITLE
[Bug]: java.lang.ArrayIndexOutOfBoundsException from asm visitMaxs when compiling

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#39050]
### Description

Compile time error when compiling
```ballerina
import ballerina/io;

function ticks(string l) returns int[] {
    int[] result = [];
    int startPos = 0;
    while true {
        int? tickPos = l.indexOf("`", startPos) + 1;
        if tickPos == () {
            return result;
        }
        startPos = tickPos;
        result.push(tickPos);
    }
}

public function main() {
    io:println(ticks("a`b`c"));
}

```

It does work when I rename `result` to something else.

### Affected Version(s)

Ballerina 2201.3.0 (Swan Lake Update 3)

**Comment by gabilang** [comment]
This issue is observed when we have a structured type variable named with `result`. It can be reproduced with the following code as well.
```ballerina
public function main() {
    int[] result = [];
    int? a = foo(0) + 1;
}

function foo(int i) returns int? {
    if (i == 0) {
        return ();
    } else {
        return i;
    }
}
```
The BIR generated for above case and for one with just the variable name change (rename the variable `result` to something else) are different. It's probably due to a clash with naming in the desugar phase since we are desugaring the array with the name `$result$` (with the variable name) and also creating a variable with the name `$result$` for desugaring `foo(0) + 1`.

Since it is needed to be fixed from desugar phase, moved it to compilerFE team and removing `Team/jBallerina` label.
