### ISSUE TITLE
[Improvement]: Improve completion item sorting in statement context

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#39330]
### Description

Consider:
```ballerina
import ballerina/http;

public function main() {
    h<cursor>
}
```
Here the completion list looks like this:
![Screenshot from 2023-01-23 14-51-10](https://user-images.githubusercontent.com/11285165/214004905-7e6ed7c7-7df1-4e83-9d88-d10f58cb10fb.png)

Note that the `http` module prefix is not at the top due to the items provided by the types coming from already imported modules takes precedence. In this context, `http` module prefix should come first. Then the types coming from already imported modules (should be sorted accordingly).

### Describe your problem(s)

See description

### Related area

-> Editor

**Comment by malinthar** [comment]
This is related to https://github.com/ballerina-platform/ballerina-lang/issues/40617.  Here the completion context is type descriptor node context. So type completion items are sorted to the top. It is true that the users are more likely to select the `http' module completion item. However, since http has only four characters users can simply type it. We are deprioritising this issue for the moment.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
