### ISSUE TITLE
[Bug]: Code coverage reduced after the lang version update

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#39609]
### Description

Code coverage in some of the standard libraries reduced significantly after the lang version update PR.
- HTTP : 81% -> 79%
- gRPC : 80% -> 72%
- graphQL : 87% -> 26%

Sample coverage reports in HTTP :
Before the lang update - https://app.codecov.io/gh/ballerina-platform/module-ballerina-http/commit/29d780823e9f6a6a80fa63aac7c69b5cd8ecdcf4/tree
After the lang update commit - https://app.codecov.io/gh/ballerina-platform/module-ballerina-http/commit/1263712dd41f727ecb3cb07aa12839fa0d1d35f4/tree

Incase of HTTP, the entire codecov of `ballerina` directory is missing

Due to this codecov reduction, currently the PRs are blocked on merging

### Steps to Reproduce

See a sample PR in the above repositories

### Affected Version(s)

SwanLake Update 2201.4.0

### Related area

-> Test Framework

**Comment by chiranSachintha** [comment]
When the dependencies were reverted to RC1, the code coverage issue persisted. Therefore, it appears that the issue is not related to the lang, but rather to Codecov.
When dependencies are updated to RC1: https://github.com/ballerina-platform/module-ballerina-graphql/pull/1223

**Comment by Thevakumar-Luheerathan** [comment]
We created few PRs(with reverted dependencies https://github.com/ballerina-platform/module-ballerina-grpc/pull/1171 https://github.com/ballerina-platform/module-ballerina-graphql/pull/1223 https://github.com/ballerina-platform/module-ballerina-http/pull/1446) for those affected repos to check the impact of those dependencies. Still we couldn't get any improvement on coverage. Then We compared the xml reports generated from graphql-tests for the affected timestamped versions (`2201.4.0-20230213-151200-6d175fd1` vs `2201.4.0-20230206-091900-3d0899b2`).  There were differences between those xml reports. After we observed similar differences between xml reports generated with some other timestamped versions (`2201.4.0-20230130-171600-b819386a` vs `2201.4.0-20230206-091900-3d0899b2`) and they haven't contributed to any coverage changes. We concluded that the issue is from `Codecov` side not from Ballerina side .

**Comment by Dilhasha** [comment]
We have raised the issue to Codecov and waiting on a resolution.

https://community.codecov.com/t/coverage-dropped-by-60-after-merging-a-commit/4129

**Comment by Dilhasha** [comment]
Based on the observations,
I tried to reproduce the same issue with a simple project https://github.com/Dilhasha/MyHTTPTest/tree/main

In this project,
- `proj1` contains all the ballerina source
- both `proj1` and `proj2` contain tests

Based on the coverage for this project, we identified that the issue is in the path fixes. Unless we specify the exact path fix, it doesn't get picked. With PRs sent to `graphql` module, I was able to confirm this behavior.

So, I have communicated this to the codecov team in the issue https://community.codecov.com/t/coverage-dropped-by-60-after-merging-a-commit/4129/13 and awaiting their response.
