### ISSUE TITLE
Type narrowing fails for specific cases 

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#39630]
### Description

Consider the following code snippet
```ballerina
import ballerina/http;

public function main() {
    map<GitHubInstallationRepos>|http:InternalServerError result = foo();

    if result is http:InternalServerError {
        return;
    }

    map<GitHubInstallationRepos> repos = result; // Compile error here
}

function foo() returns map<GitHubInstallationRepos>|http:InternalServerError {
    return {foo: {id: 1, orgName: "ballerina", repos: ["ballerina-lang"]}};
}

public type GitHubInstallationRepos record {|
    int id;
    string orgName;
    string[] repos;
|};
```

### Affected Version(s)

2201.2.3
2201.3.2

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
This is not a bug. This is the expected behaviour according to the current specification because the union has an open record (the map is effectively an open record) and the values are mutable.

See https://github.com/ballerina-platform/ballerina-lang/issues/35704#issuecomment-1091067067 for more details.

Narrowing will work if the values were immutable.

```ballerina
public function main() {
    readonly & (map<GitHubInstallationRepos>|http:InternalServerError) result = foo().cloneReadOnly();

    if result is http:InternalServerError {
        return;
    }

    map<GitHubInstallationRepos> repos = result; // OK
}
```

There are some proposed changes to this, but the behaviour is in-line with the current spec.
