### ISSUE TITLE
[Bug]: Formatter incorrectly formats expressions

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#39813]
### Description

Most of the time, the formatter performs incorrect formatting when I try to format expressions.

ie:
original source:
```ballerina
population - infantCount
```

formatted source:
```ballerina
 population- infantCount
```
--

original source:
```ballerina
age > 18 ? "Adult" : "Child"
```

formatted source:
```ballerina
age> 18 ? "Adult" : "Child"
```

Once use case of this is the Ballerina Statement Editor where it performs formatting the snippets before rendering.

### Affected Version(s)
Ballerina 2201.3.2

**Comment by AzeemMuzammil** [comment]
Since we are trying to format syntax erroneous code snippets, the erroneous code snippet gets mapped to a valid Syntax Node with missing Nodes. and the mapped valid syntax node is formatted. In the above-mentioned examples, 
1. `population - infantCount` gets mapped to `FunctionDefinitionNode` as `MISSING[function]population  MISSING[(]-  MISSING[]infantCount MISSING[)] MISSING[{] MISSING[}]`

3. `age > 18 ? "Adult" : "Child"` gets mapped to `ModuleVariableDeclarationNode` as `MISSING[map] MISSING[<]age >  MISSING[] MISSING[=]18 ? "Adult" : "Child" MISSING[;]`.

And formatting works as expected with the erroneous code snippets. And the fix is not possible from the Formatter side.

**Comment by AzeemMuzammil** [comment]
Actually, this can be done, we can use `NodeParser` to achieve the result. @madushajg
