### ISSUE TITLE
[Improvement]: Suggest regexp template expressions snippets in function body and module part ctxs

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#39837]
### Description

```
r<cursor>

function test() {
 r<cursor>
}

```

### Related area

-> Compilation

**Comment by IMS94** [comment]
In the body block node context, we suggest a subset of expression context completions since the users tend to first write the RHS of the expressions and then create variables (fill the LHS). When it comes to `regex` snippets, can we expect such a trend?

IMO, regex is a feature used by only a subset of language users. And those who use it knows that they need a regex in the given line. If that's the case, I believe they will write `string:RegExp regexp = <cursor>` and get the completions. WDYT?

**Comment by LakshanWeerasinghe** [comment]
> In the body block node context, we suggest a subset of expression context completions since the users tend to first write the RHS of the expressions and then create variables (fill the LHS). When it comes to `regex` snippets, can we expect such a trend?
> 
> IMO, regex is a feature used by only a subset of language users. And those who use it knows that they need a regex in the given line. If that's the case, I believe they will write `string:RegExp regexp = <cursor>` and get the completions. WDYT?

yes. If you look at our langlib example we use the regex expression to call the langlib functions. Then users can use the create variable code action to generate the L.H.S.

**Comment by mindula** [comment]
@LakshanWeerasinghe In both of these contexts we're not suggesting `string` or `xml` templates. Hence, i think it is not necessary to suggest `regexp` template expressions in these contexts.

**Comment by LakshanWeerasinghe** [comment]
We can close this improvement by considering the comments given by @mindula and @IMS94.
