### ISSUE TITLE
Need a function to round values to the given decimal places

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3986]
Currently, we have only math:round() function which converts a float to a int. But, if we want to convert a value to lets say two decimal places we cannot do so directly. This is a very useful function when it comes to converting monetary values in real world scenarios. Hence, pls support this.

**Comment by pubudu91** [comment]
There's the question of whether we should be supporting this OOTB. Currently, we don't have support for high precision floating point numbers. Without such support, it seems pointless to provide a `round()` function since the result given by it will be inaccurate. It's definitely not the type of function you'd want for handling monetary values.

**Comment by pubudu91** [comment]
Closing this since a rounding function cannot be provided due to the above mentioned issue.
