### ISSUE TITLE
[Bug]: Inconsistent behavior in HTTP client resource suggestions

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#40007]
### Description

I get suggestions when there are no statements below the resource invocation line. See the following image:
<img width="1137" alt="Screenshot 2023-03-27 at 12 54 44 PM" src="https://user-images.githubusercontent.com/2637328/228052227-f4b0cb67-2d52-47b8-a9fb-4bf8b1eadfb3.png">

But I don't get suggestions when there are statements below the resource invocation line:
<img width="948" alt="Screenshot 2023-03-27 at 12 55 21 PM" src="https://user-images.githubusercontent.com/2637328/228052508-7c756706-336b-4040-a4cc-71b725212dd2.png">
 

### Affected Version(s)

2201.4.1

### Related area

-> Editor

**Comment by IMS94** [comment]
@malinthar #39958 won't fix this right?

**Comment by malinthar** [comment]
> @malinthar #39958 won't fix this right?

@IMS94 No it doesn't fix this case. 

@sameerajayasoma We will be focusing on providing a fix for this. The reason for the above behaviour is a limitation implementation. 

To be more specific, the syntax tree that we get for the above case considers `io:println(products)` statement as part of the resource path as depicted in the figure below. 
![image](https://user-images.githubusercontent.com/35211477/228135064-0b0cafc8-5d41-4b14-b7ac-5008255c22f0.png)


Therefore, the completion context is as follows. 

i.e:  `check productSvc-> /<cursor>io[Missing_SEMICOLON] [Missing]:println(products)`

The partial resource path is `io`

Since there are no completable(matching) resource paths with the above incomplete(partial) resource path it doesn't suggest any completion items. 

We have to figure out a way to special case this scenario from the LS as we can't change the behaviour of the parser atm. We will provide the fix with #39958

**Comment by rdulmina** [comment]
If we have the `;` this works because the parser recovers as expected by the LS. Since we cannot handle this from the parser side my suggestion is to check whether the previous `/` contains a new line in its trailing trivia, if so consider the resource path only up to that point and provide suggestions. The issue with this approach is this may provide wrong suggestions when the resource path is purposely written in multiple lines.

**Comment by malinthar** [comment]
> If we have the `;` this works because the parser recovers as expected by the LS. Since we cannot handle this from the parser side my suggestion is to check whether the previous `/` contains a new line in its trailing trivia, if so consider the resource path only up to that point and provide suggestions. The issue with this approach is this may provide wrong suggestions when the resource path is purposely written in multiple lines.

Added a fix from the LS side with https://github.com/ballerina-platform/ballerina-lang/pull/39958/commits/6b79da4bd67cc14a7c5240032c22ba9cf2297569

![image](https://user-images.githubusercontent.com/35211477/228646054-cc9b4a5b-1d90-451c-a6e8-1ab73a25fca9.png)
