### ISSUE TITLE
[Bug]: Can't use the configs defined in a submodule.

### ISSUE THREAD

**Issue by sumedhe** [ballerina-platform/ballerina-lang#40356]
### Description

When using configurations in the ballerina config model, we are defining types that correspond to the configs in the toml file. I have encountered the following issue with configuration usage.

### Steps to Reproduce

1. Create a new ballerina app and create two modules named `mymodule`.
2. Create the `Config.toml` file in the root of the project.
    ```toml
    [myconfig]
    port = 8005
    ```
3. In the `myconfig` file, define a config type as below.
    ```bal
    public type ServerConfig record {
        int port;
    };

   public configurable ServerConfig myconfig = {
        port: 8081
   };
    ```
4. in the `main.bal` file use the config initialized in the `mymodule` as below.
    ```bal
    public function main() {
        io:print(mymodule:myconfig.port);
    }
    ```
5. Start with `bal run` and it will show the following error.
    ```bash
    Running executable
    
    error: [Config.toml:(11:1,12:12)] unused configuration value 'myconfig'
    error: [Config.toml:(12:1,12:12)] unused configuration value 'myconfig.port'
    ```

### Affected Version(s)

Ballerina 2201.5.0 (Swan Lake Update 5)
Language specification 2022R4
Update Tool 1.3.14

### OS, DB, other environment details and versions

Linux

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Since myconfig.bal is just another file in the same module, you don't have to use `mymodule:` to access the `myconfig` variable.

```ballerina
import ballerina/io;

public function main() {
    io:print(myconfig.port);
}
```

To move this to a different module, you need to add the module with 

```
bal add myconfig
```

This will add the module in `modules/myconfig`. Once you move the config code to that module, you'll have to update the main.bal file to import the module.

```ballerina
import mymodule.myconfig;

import ballerina/io;

public function main() {
    io:print(myconfig:myconfig.port);
}
```

Note that you'll also have to update the Config.toml file.

```toml
[mymodule.myconfig]
myconfig.port = 8005
```

Also see https://ballerina.io/learn/organize-ballerina-code/
