### ISSUE TITLE
[Bug]: Key become null in for loop if use filtering within the loop

### ISSUE THREAD

**Issue by ruks** [ballerina-platform/ballerina-lang#40379]
### Description

If we write a loop to iterate map<json>, its key becomes null if we use a filter within this loop. In this case, if we use an array to filter within the loop and if we use `key` to filter the data, this issue happens. 

### Steps to Reproduce

Consider this code:
```
import ballerina/io;

public function main() returns error?{
    string[] values = ["a","b","c"];
    json data = {
        key_001:"value_001",
        key_002:"value_002"
    };
    io:println(data);
    map<json> dd = check data.ensureType();
    foreach [string, json] [key, value] in dd.entries() {
        string name = key;
        io:println(name);
        io:println(value);
        string[] fValues = values.filter(item => item == key);
        io:println(fValues);
    }
}
```

Its output is followed and the key has become null.
```
{"key_001":"value_001","key_002":"value_002"}

value_001
[]

value_002
[]
```

### OS, DB, other environment details and versions

Bal version: 
Ballerina 2201.2.3 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10

### Related area

-> Compilation

**Comment by HindujaB** [comment]
This happens due to the `println` statements referring to a wrong desugared map to read the `key`. 
Seems like a bug in desugaring the `foreach` body. 

<img width="1385" alt="Screenshot 2023-10-10 at 12 22 00" src="https://github.com/ballerina-platform/ballerina-lang/assets/28644893/93a586f1-6ff9-459e-bc4f-dfbf2fba18d2">


Note that the map updated with the iterator call is `$map$block$_8`. But the `println` statement refers to another map `$map$block$_4`. This returns `null` as the map does not contain the key.

**Comment by MaryamZi** [comment]
This seems to be fixed now. @poorna2152 can you please check?

**Comment by poorna2152** [comment]
Yes this has been fixed with this. https://github.com/ballerina-platform/ballerina-lang/pull/41894

**Comment by poorna2152** [comment]
A test case which demonstrates a similar scenario to this where a usage of a variable defined in a binding pattern in a closure has been added [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal#L895-L901). 
Thus closing this issue.
