### ISSUE TITLE
[Task]: Finalize the design for runtime types representation with semtypes

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#40512]
### Description
$subject.

**Comment by lochana-chathura** [comment]
Functionality wise using the same sem-type representation and the subtyping algorithms at runtime would work.
However, performance-wise we could improve the runtime type checking.

Let's see the nBallerina way of handling runtime type checking.

There are only a limited number of scenarios that we require a runtime type checking. 
For example: type test, adding a new member to an array, etc

The thing is we know the types related to such operations at compile-time.
Let's say the types t1, t2, t3, ..., tn are involved. So once we know the involved types, we can derive all the subtyping relationships among them. Basically, for every type pair from the list of n types, we check for `isSubtype(ti, tj)` (nC2 combinations) and make a table out of all the relationships.

Since we have already derived and created a table from all the subtyping relationships at compile-time, we don't need to perform expensive subtyping checks at runtime. We can simply refer to the table.

Question: Why do we compute all these relationships at compile-time while we can do it at runtime? That way we don't need to check all combinations. Instead, we can directly check for the required subtype relationship only.

Answer: We only compile a program once. But, we run it many times. Therefore, additional overhead at compile time would serve its price.

An optimization on top of the aforementioned strategy:
As the n grows the number of combinations grows rapidly. The subtype checking overhead gets heavier as the types become complex. Therefore, we could go for a hybrid approach where for the simple types we do the subtype checking at runtime, while for the complex types only, we derive the subtyping relationship table at compile-time. Drawing the line between what is a simple type and what is a complex type is up to us. In nBallerina, we consider type's having simple BDDs (single atoms) as simple types. However, the member types within them, themselves have to be simple types.

**Comment by lochana-chathura** [comment]
Based on today's discussion. We would revisit the runtime implementation.
Would give priority to fully complete the compile time implementation.

**Comment by heshanpadmasiri** [comment]
General design we came up with (see #40511 for more details) is as fallows,

1. There will be a sealed base class called `SemType`, instead of a marker interface like we have in the compiler side. This is so that we can do direct field access to get `all`, `some` and subtype data, without having to do type checks or virtual function calls. For the time being there will be a single class instead of two (BasicTypeBitSet and ComplexSemType) this means we are wasting 12 bytes in the case of `BasicTypeBitSet` but this means we don't have any runtime overhead with type checking when we try to access fields
2. There will 2 direct implementations of this class called "PureSemType" and "BSemTypeWrapper". "PureSemType" will be just a SemType similar to what we have in nBallerina. All results from SemType APIs (`union`, `intersect` etc) will be of this type and will give us  a light weight representation.
3. All existing `BTypes` will extend from either `BSemTypeWrapper` or implement a SemType supplier. This means as far the type checker is concerned it can treat any type it get's as a semtype  while current runtime API users can treat them as "BTypes"  (for more details on see the next section)
4. Since these are different classes from the once used by the compilers semtype API there will be a correspondingly separate API. While in compiler side we have faithfully reproduced the same API as the nBAllerina there may be few deviations in the runtime mostly to better exploit JVMs performance profile. However both of these will use the same test suite (in semtype port tests) so in theory they are drop in replacements

Problem with computing all the possible runtime type check relations is unlike nBallerina jBallerina has the ability to create new types at runtime using [`TypeCreator`](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/TypeCreator.java) API. But still we can cache type check results (that is we have check if given type pair `T1` and `T2` to be subtypes and this is the result in `T1` (we can't say the result for `T2` to be inverse since `T2` could be equal to `T1` and to check that we need to do an extra type TypeCheck which is not worth it)

# BSemTypeWrapper and type supplier
+ For simple basic types (`int`, `boolean` etc) there will be direct implementations that will use a delegate to support current BType implementations.  This is because for type checking we don't have a way to attach the type to the value which means we have to create these types again and again. This should give us more room to optimize these things by being able to share the inner BType part and caching the creation of these types where applicable. Also these
+ For others where we have a type attached to the value I decided to treat that type as a semtype supplier. This is because these types can have recursive types. Also we don't have a clear break point where the type has finished initializing since they can be modified after construction.

# Handline BTypes during the transition period
While we have only a part of the type space implemented as semtypes I'll introduce a new (temporary) basic type called BType which will hold the the part of the type type currently not implemented as a semtype. Most type operations will not be supported for this BasicType.
