### ISSUE TITLE
[Bug]: NPE when formatting Ballerina code that includes regular expressions

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#40541]
### Description

Occurred this NPE errors[2] while formatting the below ballerina code[1] using `bal format` command

[1] sample Ballerina code
```ballerina
import ballerina/constraint;

@constraint:String {pattern: re `[A-Z]{1}`}
public type FlightClass string;

@constraint:String {pattern: re `[a-zA-Z0-9]{3}`}
public type Code string;

public function main() {
    Code code = "A380";
    FlightClass flightclass = "A";
}

```
[2] Error stack
```
May 30, 2023 8:57:24 PM org.ballerinalang.formatter.core.FormattingTreeModifier formatNode
SEVERE: Error while formatting [kind: RE_SEQUENCE] [line: 3] [column:33]: java.lang.NullPointerException
May 30, 2023 8:57:24 PM org.ballerinalang.formatter.core.FormattingTreeModifier formatNode
SEVERE: Error while formatting [kind: RE_SEQUENCE] [line: 6] [column:33]: java.lang.NullPointerException
modified files:
/Users/hansaninissanka/Documents/Ballerina Projects/pattern_connector/main.bal

format successful.
``` 

### Affected Version(s)

2201.5.0
2201.6.0-rc1

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
The issue seems to be at the `TreeModifier` when we have a single quantifier. The optional `mostTimesMatchedDigit` is not handled correctly in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java#L3612
```ballerina
_ = re `[a-zA-Z0-9]{3}`;
```

The below works as expected where the optional nodes are available
```ballerina
_ = re `[a-zA-Z0-9]{3,5}`;
```

We'll consider this a priority and take this up in the next sprint.
