### ISSUE TITLE
[Bug]: Bal build command pulling deprecated packages even without having a dependencies.toml

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#40566]
### Description

It seems like `bal build` command pulls some of the deprecated packages, even if the particular dependency is not locked in the `dependencies.toml`. Also not getting any warnings to notify that the package is deprecated. 

### Steps to Reproduce

1. use the below simplified sample which uses the deprecated sfdc package.

```ballerina
import ballerinax/sfdc;

public function main() {
    string empty = sfdc:EMPTY_STRING;
}
```

2. Run `bal build` and notice that the package is getting pulled without any warnings and result in compilation errors.

### Affected Version(s)

2201.6.0, 2201.5.0

### Related area

-> Other Area

**Comment by Dilhasha** [comment]
> It seems like bal build command pulls some of the deprecated packages, even if the particular dependency is not locked in the dependencies.toml

This behavior is expected. Based on the current design, if there is no non-deprecated package version available to satisfy a dependency, the deprecated version gets pulled. Among the compatible packages the latest version is pulled. So, sfdc https://central.ballerina.io/ballerinax/sfdc 3.0.1 is pulled.

> not getting any warnings to notify that the package is deprecated.

This looks like a bug.
The same behavior works fine for deprecated packages if they are pushed with swan Lake stable versions. 
We need to confirm that this is due to the latest version being `slbeta3`. I'll verify and update this issue.

Before we deprecate the other packages in prod central, shall we do the deprecation in dev Central and verify the behavior?

**Comment by Dilhasha** [comment]
@NipunaRanasinghe I was able to find the bug. Unfortunately, it affects all packages that use compiler plugins.
So, sfdc, azure_functions, awslambda will be affected. I'll send a fix for this ASAP.
