### ISSUE TITLE
[Improvement]: Improve sorting of trie completion items

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#40617]
### Description

Consider the following capture

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/38db1105-a79d-4d4e-a53d-74caaaa0f35a)

The `log: setOutput()` completion item depicted above should not be given the highest priority in the above context. basic types and other user-defined types should be given the highest priority. 

### Describe your problem(s)

```ballerina
import ballerina/log;
import ballerina/http;

final http:Client clientEP = check new ("http://localhost:9090/");

type Person record {|
    string name;
    int age;
    s<cursor>
|};

type Params record {|

|};

public function main() returns error? {
    // http:Response res = check clientEP->/test;
    // log:printInfo("response obtained", statuscode = res.statusCode, payload = check res.getTextPayload());
    test("hello", 1, 2);
    testIncludedRecordParams();
}

public function test(string arg1, int... restArg) {

}

public function testIncludedRecordParams() {

}

```

### Related area

-> Editor

**Comment by mindula** [comment]
This was happening due to the filter text of each completion item. In the above screen capture `log:setOutput()` completion item is shown at the top of the list because it has a filter text whereas other completion items such as type descriptors and module types don't. 
The filter we get for `log:setOutput()` now is `setOutput`, and to prfioritize the basic types, we've decided to modify the filter text of `log:setOutput()` to include the module name along with the type (log_setOutput).
