### ISSUE TITLE
[Bug]: Bal commands are not executing after pulling bal health tool

### ISSUE THREAD

**Issue by Isuruni** [ballerina-platform/ballerina-lang#40677]
### Description

In windows environment, after bal health tool is pulled using "bal tool pull health" command other bal commands are not getting executed. It's showing an error as mentioned below;

![Capture](https://github.com/ballerina-platform/ballerina-lang/assets/62780506/c1b1ee99-9b6c-442a-8650-da23843e0871)

### OS, DB, other environment details and versions

Windows

### Related area

-> Compilation

**Comment by gayaldassanayake** [comment]
Seems like the issue is not related to bal tool, but a general issue related to the windows command prompt maximum character size. A similar issue is reported on discord for `bal dist` command. https://discord.com/channels/957996897782616114/1017493204326686860/threads/1116289477615304759
One suggestion would be to use `powershell` instead where the max character size is higher.
