### ISSUE TITLE
[Bug]: Incorrect type name for the error values created via `ErrorCreator.createError()` API

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#41025]
### Description

```bal
public type ResourceDispatchingError RequestDispatchingError;
public type RequestDispatchingError distinct error;
```

When we use `ErrorCreator.createError()` API to create `ResourceDispatchingError` it will correctly creates the error value but if we do `.getType().getName()` on the value it gives `RequestDispatchingError` instead of `ResourceDispatchingError`

### Related area

-> Runtime

**Comment by HindujaB** [comment]
This happens due to the wrong type getting passed from the `BLangTypedefinition`. 
At the code generation, the type of the error type definition is provided as `RequestDispatchingError` even though the expected type should be type-reference type `ResourceDispatchingError`. 
This type is populated from the `symbol.type` from the `BLangTypedefinition` instance generated at compilation. 

<img width="992" alt="Screenshot 2023-10-03 at 17 30 03" src="https://github.com/ballerina-platform/ballerina-lang/assets/28644893/5e74c9d0-c422-4a4d-8d18-3b39da7e0e21">

Note that the `type` field contains the wrong type `RequestDispatchingError` for both `BLangTypedefinition.type` and `symbol.type`.
