### ISSUE TITLE
[Bug]: `incompatible types` compiler error for pulled bal package

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#41332]
### Description

$subject

### Steps to Reproduce

Error is shown when building a bal package using `2201.8.0` with the following package import.
https://lib.ballerina.io/ims/billionairehub/1.0.0

```ballerina
import ims/billionairehub;

type Billionaire billionairehub:Billionaire;

public function main() {
}
```
Error : 
```
ERROR [ims/billionairehub/1.0.0::client.bal:(53:53,53:65)] incompatible types: expected 'ballerina/http:2.10.0:ClientConfiguration', found 'ims/billionairehub:1.0.0:ClientConfig'
```

### Affected Version(s)

2201.8.0. test pack

### Related area

-> Compilation

**Comment by Dilhasha** [comment]
Due to the client config record in the `ims/billionairehub` module no longer being a subtype of the http record.

**Comment by MaryamZi** [comment]
`ims/billionairehub:ClientConfig`is not a subtype of `http:ClientConfiguration` in v2.10.0. There are additional fields now and the type of the `httpVersion` field has changed.

So this module is not compatible with newer HTTP versions and a newer version will have to be released.

Closing this issue since it is not a lang bug.
