### ISSUE TITLE
[Improvement]: Can we prioratize ballerina lang code actions over github copilot code actions? 

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#41497]
### Description

$subject.

It is really annoying that github copilot code actions come first. Always has to go down in the action list to pick the right action. The affects the developer experience when coding with ballerina with copilot on. 

<img width="357" alt="Screenshot 2023-10-10 at 10 08 35" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/ab681fbc-4b2b-4ec5-8055-a5e86feb8358">

**Comment by nadeeshaan** [comment]
Please refer.
https://github.com/microsoft/vscode/issues/152845

This cannot/ should not be handled by the Language Server, since it does not relate to the language semantics. This is something we should handle from the plugin itself, which is also an existing concern in the current VSCode editor releases.

**Comment by mindula** [comment]
This has been fixed now.
<img width="448" alt="Screenshot 2024-02-01 at 12 09 45" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/4776b786-33a4-4c42-87e0-44754d22b8df">
