### ISSUE TITLE
Unsafe conversion to boolean never throws an error

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#4172]
**Steps**
1. Follow the below code segment
```
boolean isValid;
TypeConversionError err123;
string q = "hgygiugi76567hgh";
isValid, err123 = <boolean>q;
println(err123);
```

**Issue**
Unsafe conversion never throws an error. So, all the time err123 will be null. isValid will be false for invalid conversion

**Comment by afkham** [comment]
string q = "hgygiugi76567hgh";
isValid = <boolean>q;
io:println(isValid);


Above code prints false.

**Comment by hasithaa** [comment]
Right now string to boolean conversion is a safe operation. It always returns a boolean, not a boolean/error. 
eg: 
    string s = "dddd";
    boolean b = <boolean> s;

Hence this is not a bug in the current implementation.

**Comment by afkham** [comment]
That doesn't look correct though!

**Comment by hasithaa** [comment]
In future, we are planning to remove this behavior. There will be no casting from string to boolean. Hence we kept this behavior as it is for now.

Rather than providing casting operation, the correct way of doing this is to provide a utility function to do the conversion. This is how other languages like Java, Go, etc do string to boolean conversion.
