### ISSUE TITLE
[Bug]: Typecast error occurs with string array

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-lang#41842]
### Description

```ballerina
function func() returns string[]|error {
    any|error val = ["q"];
    if (val is error) {
        return val;
    }
    return <string[]>val;
}

public function main() {
    string[]|error funcResult = func();
    if funcResult is string[] {
        io:println("str array");
    } else {
        io:println("error");
    }
}
```

I am getting below error with above code
```
Running executable

error: {ballerina}TypeCastError {"message":"incompatible types: '(any|error)[]' cannot be cast to 'string[]'"}
        at luheerathan.test1.0:func(main.bal:25)
           luheerathan.test1.0:main(main.bal:29)
```

### Related area

-> Runtime

**Comment by MaryamZi** [comment]
The type cast expression checks if the value belongs to the target type (the type it is being cast to).

> a value belongs to a type if it looks like the type, and it will necessarily continue to look like the type no matter how the value is mutated.

The array constructed with `["q"]` is an `(any|error)[]` since the expected type is `any|error`. Since it is mutable, it can be updated to have any value, including non-string values. So the cast will fail. If the array was immutable, the cast will succeed. 

```ballerina
    readonly & any|error immutableArr = ["q"];
    any|error val = immutableArr;
    if val is error {
        return val;
    }
    return <string[]>val; // succeeds now
```
