### ISSUE TITLE
[Bug]: Project API load() method is not correctly resolving dependencies

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#41866]
### Description

SQL testcase failing to resolve dependency time module

https://github.com/ballerina-platform/ballerina-lang/actions/runs/7170430688/job/19523715953

### Related area

-> Compilation

**Comment by niveathika** [comment]
Here the resolution happens sucessfully after the first attempt. 

https://github.com/ballerina-platform/ballerina-lang/actions/runs/7172073878/job/19541598996?pr=41867

This is after disabling one test. Another is failing

**Comment by ShammiL** [comment]
This failure in resolving the time module, which is a dependency of the sql module, is due to the time module not been detected when creating the `dependencyGraph`. 

Further investigating revealed that the time module is not added to the `dependency-graph.json` of `ballerina/sql:1.11.2` pack as the `scope` of the time module dependency is taken as `TEST_ONLY` during the dependency resolution test.
