### ISSUE TITLE
[BUG]: Config Generation fails to add the name of Readonly Records to the Config Schema

### ISSUE THREAD

**Issue by chalindukodikara** [ballerina-platform/ballerina-lang#41906]
**Description:**
Config generation should include the record name in the config schema. However, when the record is read-only, it fails to include the record name.

**Steps to reproduce:**
- Create two records with read only and without read only.
- Generate config schema (bal build --generate-config-schema)

Sample Code: https://github.com/chalindukodikara/ballerina-codes/tree/master/config-generation-name-issue

Config Schema: https://github.com/chalindukodikara/ballerina-codes/blob/master/config-generation-name-issue/target/bin/config-schema.json

**Related Issues (optional):**
This issue affects Choreo Console for Ballerina components.
https://github.com/wso2-enterprise/choreo/issues/25862

**Suggested Labels (optional):**
Priority/High

**Comment by Dilhasha** [comment]
The type converter in config schema generation fails to add the name at https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/configschema/TypeConverter.java#L185

The reason for this issue is a compiler bug which is reported at https://github.com/ballerina-platform/ballerina-lang/issues/41912

**Comment by MaryamZi** [comment]
> The reason for this issue is a compiler bug which is reported at #41912

Please see https://github.com/ballerina-platform/ballerina-lang/issues/41912#issuecomment-1863883793.
