### ISSUE TITLE
[Bug]: A variable declared as an explicit readonly record does not include a reference type as one of its constituent types

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#41912]
### Description

$subject.

### Steps to Reproduce

Consider the below code snippet.

```
public type ReadOnlyRecord readonly & record {
    string readOnlyValue;
};

public type NormalRecord record {
    string normalValue;
};

configurable ReadOnlyRecord record1 = ?;
configurable NormalRecord record2 = ?;
```

The constituent types of record2 has reference type.
But, record1 does not have reference type.

### Affected Version(s)

2201.8.4

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/41906

**Comment by MaryamZi** [comment]
Looping in @HindujaB, since this is an issue specific to configurable variables. 

Is your expectation to get `readonly` and `ReadOnlyRecord` as constituent types? The current behaviour may be because `ReadOnlyRecord` is already `readonly`.

The spec requirements is 

> The static type of a variable declared as configurable is implicitly readonly: the type specified in the type-descriptor is intersected with readonly. 

So IMO, we don't really have to create an intersection type that is `readonly & ReadOnlyRecord` for `record1`, which is effectively `readonly & (readonly & record { string readOnlyValue; })`.

Also note that even if you did get `readonly` and `ReadOnlyRecord` as constituent types, `ReadOnlyRecord` will be an intersection type where one of it's constituent types will be an anonymous record type. The behaviour won't be the same as for `NormalRecord`, since with

```ballerina
public type NormalRecord record {
    string normalValue;
};
```

the name `NormalRecord` is specified for the record, whereas with

```ballerina
public type ReadOnlyRecord readonly & record {
    string readOnlyValue;
};
```

the name is for the intersection type.

**Comment by HindujaB** [comment]
I agree with the comment from @MaryamZi. We can't depend on the `getConstituentTypes()` to return a type-reference type for the first element. It can vary depending on the record descriptor. At runtime, we use a recursive method called `getImpliedType()` to extract the underlying record type. 
There is a relevant compiler FE API, which we can use. 
https://github.com/ballerina-platform/ballerina-lang/blob/07161023cd419af86e84d47109fa1ec57a6fed2f/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java#L421
(Need to move this API to a proper class.)
And, we may need to check the `anonymous` flags to identify the record name.

**Comment by Dilhasha** [comment]
Agree with the comments. We'll check on a proper implementation for the initial requirement.
