### ISSUE TITLE
[Improvement]: Support for HTTP resources with trailing slashes

### ISSUE THREAD

**Issue by slahirucd7** [ballerina-platform/ballerina-lang#41927]
### Description

Considere a scenario where there are two HTTP resources as `/abc` and `/abc/`
In ballerina those two resources are considering as the same.
But in other languages those are considered as two different resources.

### Describe your problem(s)

```
import ballerina/http;


service on new http:Listener(9092) {

    resource function get rsc() returns string {
        return "without trailing slash";
    }

    resource function get rsc\/() returns string {
        return "with trailing slash";
    }
    resource function get rsc/[string a]() returns string {
        return "with trailing slash and path param " + a;
    }
    // This is not allowed to have in ballerina
    // resource function get rsc/[string a]\/() returns string {
    //     return "with trailing slash and path param" + a;
    // }
}
```

![image](https://github.com/wso2-enterprise/internal-support-ballerina/assets/40932779/1b69e3be-6e5f-480f-b714-4370b6657cd6)

### Describe your solution(s)

Provide the support to consider resource with trailing slash as a separate API resource.

### Related area

-> Compilation

**Comment by TharmiganK** [comment]
Here the actual requirement is to differentiate the business logic in two different resources for requests coming in paths `/abc` and `/abc/`. Even though it is not recommended to have both resources, other languages like spring boot support this.

```bal
service /api on new http:Listener(9090) {

    resource function get abc() returns http:Response {
        // Logic for requests with path `/api/abc`
    }

    resource function get abc/() returns http:Response {
        // Logic for requests with path `/api/abc/`
    }
}
```

This is not supported in Ballerina since the Ballerina specifications does not allow trailing slashes in path segment. The slash should be followed by either a `path-segment` or a `path-rest-parameter`.

So to support this, we should have a single resource and then access the raw path to execute the logic
```bal
service /api on new http:Listener(9090) {

    resource function get abc(http:Request req) returns http:Response {
        string rawPath = req.rawPath;
        if rawPath.endsWith("/") {
            // Logic for requests with path `/api/abc/`
        } else {
            // Logic for requests with path `/api/abc`
        }
    }
}
```

Adding @MaryamZi and @shafreenAnfar for their insights

**Comment by MaryamZi** [comment]
There is an open spec issue related to this - https://github.com/ballerina-platform/ballerina-spec/issues/677

**Comment by MaryamZi** [comment]
Closing this since there is an open spec issue to track this.
