### ISSUE TITLE
[Bug]: Runtime NPE with elvis operator and filter() function

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-lang#41921]
### Description

In the example below using `filter()` triggers `NullPointerException` but using `map()` doesn't. The examples will compile fine.

### Steps to Reproduce

```
$ cat bug.bal 
import ballerina/io;

public function main() {
    int[]? x = ();
    int[] x2 = (x ?: [])
        .filter(n => n > 2)
    ;
    io:println(x2);
}
$ bal run bug.bal
Compiling source
        bug.bal

Running executable

error: java.lang.NullPointerException {"message":"Cannot invoke "io.ballerina.runtime.api.types.Type.isReadOnly()" because "elemType" is null"}
        at ballerina.lang.array.0:filter(array.bal:133)
           bug:main(bug.bal:5)
```

### Affected Version(s)

```
$ bal version
Ballerina 2201.8.3 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.2
```

### OS, DB, other environment details and versions

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

### Related area

-> Runtime

**Comment by MaryamZi** [comment]
As a workaround, we can explicitly specify a type for the list constructor (e.g., `<int[]>[]`) within the nil conditional (elvis) expression.

```ballerina
int[] x2 = (x ?: <int[]>[]).filter(n => n > 2);
```

Also reproducible with

```ballerina
public function main() {
    var x = [];
    anydata[] y = x;
    anydata[] _ = y.filter(v => v is int);
}
```

The execution path of the original example may change with https://github.com/ballerina-platform/ballerina-spec/issues/1050. Therefore, we need to also add a test with the second sample when this issue is being fixed.

**Comment by MaryamZi** [comment]
This seems to happen because in `org.ballerinalang.langlib.array.utils.ArrayUtils#createEmptyArrayFromTuple` (at https://github.com/ballerina-platform/ballerina-lang/blob/v2201.8.4/langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/utils/ArrayUtils.java#L118), via https://github.com/ballerina-platform/ballerina-lang/blob/v2201.8.4/langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Filter.java#L58, the flow seems to have assumed that there will be at least be one member in a tuple, which is not correct.

`[]` (tuple with no members) is equivalent to `never[]` (also empty list since there can't be a `never` member). Therefore, we should be able to handle this by creating a `never[]` to correspond to empty tuples.
