### ISSUE TITLE
[Bug]: The code coverage shown less but the whole file is covered

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#42141]
### Description

The code coverage of the native java files is shown as covered less(1.32%) although the executable code is covered. 

<img width="1394" alt="Screenshot 2024-02-11 at 22 43 27" src="https://github.com/ballerina-platform/ballerina-lang/assets/39673615/cbd8573f-a2e2-4afd-86b4-38455c6bbc50">
<img width="506" alt="Screenshot 2024-02-11 at 22 43 21" src="https://github.com/ballerina-platform/ballerina-lang/assets/39673615/d2cab2ba-18e5-4965-a8d2-1720fe400a25">

### Affected Version(s)

module-ballerinax-aws.redshift:1.0.0
ballerinaLangVersion=2201.8.0

### Related area

-> Other Area

**Comment by gayaldassanayake** [comment]
This is due to an issue in jacoco code coverage.  the aws.redshift uses ballerina/sql as a dependency. Both sql and redshift contains the below 3 classes with the same class name.
```
CallProcessor
QueryProcessor
ExecuteProcessor
```

This results in the coverage data getting mixed up. A similar issue has been found in websocket where http and websocket share the same class names - [issue](https://github.com/ballerina-platform/ballerina-lang/issues/30093).

This can be fixed by adding a --include filter to the bal test command. Will introduce this as a fix to the `aws.redshift` module.

**Comment by aashikam** [comment]
Thank you for looking into this!
