### ISSUE TITLE
[Bug]: Create variable for dependently typed functions add `targetType` as variable type

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#42591]
### Description

I have a dependently typed function in a client. When I call a that function and try to create the variable using the `Create variable` code action in VS code, it creates a variable with type `targetType` which is incorrect.

### Steps to Reproduce

Use the following code with Ballerina SwanLake Update 9 in VS code:

```bal
import ballerina/http;

type Album record {|
    string name;
    string artist;
    int year;
|};

type ErrorMsg record {|
    string message;
|};

type AlbumOk record {|
    *http:Ok;
    Album body;
|};

type AlbumNotFound record {|
    *http:NotFound;
    ErrorMsg body;
|};

client class AlbumClient {
    resource function get albums/[string id](typedesc<AlbumOk|AlbumNotFound> targetType = <>)
        returns targetType = external;
}

public function main() returns error? {
    AlbumClient albumClient = new;
    albumClient->/albums/["1"];
}
```

Try the `Create Variable` code action for the client call:

https://github.com/ballerina-platform/ballerina-lang/assets/63336800/5c4961b8-5d81-4920-aedb-f663877fc5dc

Expected something like this:
```bal
public function main() returns error? {
    AlbumClient albumClient = new;
    AlbumOk|AlbumNotFound targetType = albumClient->/albums/["1"];
}
```

### Affected Version(s)

Ballerina SwanLake Update 9

### OS, DB, other environment details and versions

Mac OS

### Related area

-> Compilation

**Comment by nipunayf** [comment]
There are two concerns with this scenario. The first one is a bug which produces the `Create variable` code action in place of the `create variable with type` code action. This only occurs when the type consists solely of record type caused by the following code.

https://github.com/ballerina-platform/ballerina-lang/blob/2b9e2332af7adcf91ed148ad437a5c1ae6abbd09/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java#L276

Ideally, it should produce the following code actions:
1. Create variable with 'AlbumOk'
2. Create variable with 'AlbumNotFound'

The second concern is an improvement in which the user expects the union type as a code action as well. One solution would be to provide the respective code action along with the already existing ones, i.e.:

1. Create variable with 'AlbumOk|AlbumNotFound'
2. Create variable with 'AlbumOk'
3. Create variable with 'AlbumNotFound'
