### ISSUE TITLE
[Bug]: Compiler Plugin not identifies the transitive dependencies

### ISSUE THREAD

**Issue by samithkavishke** [ballerina-platform/ballerina-lang#42592]
### Description

When using the Compiler Plugin built in the `dev` branch of [module-ballerinax-wso2.mi](https://github.com/ballerina-platform/module-ballerinax-wso2.mi), the user-code throwing the following error:
```
error: compilation failed: The compiler extension in package 'ballerinax:ballerina:0.1.0' failed to complete. org/antlr/v4/runtime/Recognizer
```

### Steps to Reproduce

clone the following repo with specific branch:
[https://github.com/ballerina-platform/module-ballerinax-wso2.mi/tree/dev](https://github.com/ballerina-platform/module-ballerinax-wso2.mi/tree/dev)

build the project:
```./gradlew clean build -x test -x check```

Create new ballerina project:
```bal new project1```

Add the following compiler plugin dependency in `Ballerina.toml` file:
```
[[dependency]]
org = "ballerinax"
name = "ballerina"
version = "0.1.0"
repository="local"
```

Use the following sample ballerina code for the ballerina new project:
```
import ballerinax/ballerina as _;

public function foo(string i, string j) returns string {
    return i + j;
}
```

build the new ballerina-project
```bal build```

### Affected Version(s)

ballerina 2201.9.0

### Related area

-> Compilation

### Suggested assignee(s) (optional)

@gayaldassanayake

**Comment by KavinduZoysa** [comment]
Once we manually add the missing jar (antlr) into bre/lib in the ballerina pack, this issue is resolved.

**Comment by gayaldassanayake** [comment]
The issue here is due to the missing `antlr` dependency. 

In 8.x, the graphql-tool has used `antlr` as a dependency. Furthermore `handlebars` has been used in multiple places in `lang`, `openapi`, `distribution` etc. (https://github.com/search?q=org%3Aballerina-platform%20handlebars&type=code). As a result, despite specifying `handlebars`, `antlr` in the CompilerPlugin.toml or not, they will be picked from the distribution and used.

When moving into U9, the graphql-tool has removed `antlr` as a dependency. Therefore, `antlr` is not packed with the distribution anymore. However, `handlebars` is still packed in the distribution. 

In compiler plugins, if the same class is available from both the bal distribution and as a URL in CompilerPlugin.toml, priority is given to the bal distribution, due to the nature of the URLClassLoader used. As a result, `handlebars` is still picked from the bal dist. However, `handlebars from the distribution do not have access to the `antlr` dependency added in the CompilerPlugin.toml. Hence the below error.

```
java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStream
        at com.github.jknack.handlebars.Handlebars.<init>(Handlebars.java:294)
        at com.github.jknack.handlebars.Handlebars.<init>(Handlebars.java:332)
        at io.ballerina.stdlib.mi.plugin.Utils.generateXml(Utils.java:52)
        at io.ballerina.stdlib.mi.plugin.model.Component.generateInstanceXml(Component.java:56)
        . . .
```

**Comment by gayaldassanayake** [comment]
The first solution from the [above comment](https://github.com/ballerina-platform/ballerina-lang/issues/42592#issuecomment-2068968567) can be done. `handlebars` has been added to bre/lib from the `ballerina-lang`. However, it is not used in runtime. So we can safely remove `handlebars` from `bre/libs`. With that, `handlebars` from the CompilerPlugin.toml is picked.
