### ISSUE TITLE
High error rate for HTTPs loadtests with 200 concurrent users

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#42628]
**Description:**
$Subject.
This works fine for the 60 user case.
Applies to both passthrough and transformation usecase we have.

https://github.com/ballerina-platform/ballerina-performance-cloud/actions/runs/8782386068/job/24096556961
https://github.com/ballerina-platform/ballerina-performance-cloud/blob/1d735a28d62a06265a7ccad3c72bfa78764b476a/load-tests/https_passthrough/results/summary.csv#L2609

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
I was able to reduce the reproducer code with this:
```bal
import ballerina/http;

listener http:Listener securedEP = new (9090);

final http:Client nettyEP = check new ("http://localhost:8688");

service /passthrough on securedEP {
    resource function post .(http:Request clientRequest) returns http:Response|error {
        return nettyEP->/'service/EchoService.post(clientRequest);
    }
}
```

But in order to reproduce, I have to use **1000 users with 5s ramp-up period**. (I checked the similar configuration with update 8 service and it was working without any hanging.)

If I remove the `clientRequest` from the resource signature then it is working without any hanging issue. So this might be related to the previous memory issue: https://github.com/ballerina-platform/ballerina-lang/issues/42566. The difference here is there is no memory increase now but some strands used to populate the default values seems to be in runnable state.

Please note that I have removed SSL here, so not 100% sure that both of these are related. (With SSL also the service is hanging). But I think with SSL, the probability of this issue occurrence is high.
