### ISSUE TITLE
[Task]: Fix fixed length array size overflowing

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#42684]
### Description

$subject.  The following tests fail at the moment. It is included in the [fixed-length-array-large-t.bal](https://github.com/ballerina-platform/ballerina-lang/pull/42663/files#diff-87ab02f714b6d462ba9d8b324e08273142201619435b0062e766bdcd0ce7c757) added by PR #42663.

```bal
public const int MAX_VALUE = 9223372036854775807;

public const int MAX_VALUE_M_1 = MAX_VALUE - 1;

// @type LargeArray < IntArray
type LargeArray int[MAX_VALUE];

// @type LargeArray <> LargeArray2
type LargeArray2 int[MAX_VALUE_M_1];
```

**Comment by heshanpadmasiri** [comment]
This is caused by an integer overflow [here](https://github.com/ballerina-platform/ballerina-lang/blob/c3e489da1369147cc8453f403e618d1bfd4f35d8/tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java#L233). But in general I think this indicate fixed length must be a `long` not an `int` to have the same behavior as nBallerina. Will send a fix

**Comment by heshanpadmasiri** [comment]
After an offline chat we decided not support this and instead give a proper error for such overflow. This is because our lists are internally backed by java arrays and their indices have an upper limit enforced by `int` not `long`. Note this is consistent with the existing behavior of jBallerina

**Comment by lochana-chathura** [comment]
Closing with #42701
