### ISSUE TITLE
[Bug]: Intermittent compilation failure for dependently typed functions

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#43007]
### Description

```
public isolated client class Client {
    final http:Client clientEp;

    public isolated function init() returns error? {
        self.clientEp = check new http:Client("http://localhost:9090");
    }

    remote function getTaskCodeOfTaskCodeText(string TaskCodeGroup) returns TaskCode|error {
        return self.clientEp->get("/TaskCode/" + TaskCodeGroup);
    }
}
```

Here the `TaskCode` type is not correctly binding.

```log
ERROR [client.bal:(68:153,68:161)] a function with a non-'external' function body cannot be a dependently-typed function
ERROR [client.bal:(68:153,68:161)] invalid parameter reference: expected 'typedesc', found 'string'
ERROR [client.bal:(72:16,72:57)] incompatible type for parameter 'targetType' with inferred typedesc value: expected 'typedesc<(ballerina/http:2.11.2:Response|anydata)>', found 'typedesc<other>'
```

### Steps to Reproduce

Build this ballerina client generated from openapi.

https://github.com/HabeebaMinhar/module-ballerinax-sap.s4hana.qm/tree/test/ballerina/taskcode_0001

`TaskCode` type is defined in the types.bal.

Note, when I try to reproduce this in a simple scenario as I have given above, the issue was intermittent. For this project it was not

### Affected Version(s)

2201.9.0

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
The problem here is with the generated remote method signatures. Parameter names are in scope for the return type, to support dependently-typed functions.

E.g., to support something like 

```ballerina
remote isolated function getTaskCode(
    string TaskCodeGroup, typedesc<anydata> td, 
    map<string|string[]> headers = {}, *GetTaskCodeQueries queries) 
        returns td|error = external;
```

In the lines you get the errors for (e.g., https://github.com/HabeebaMinhar/module-ballerinax-sap.s4hana.qm/blob/test/ballerina/taskcode_0001/client.bal#L67), a parameter name (`TaskCode`) is the same as the name of the type you're using in the return type, so the analysis happens as for a dependently-typed function.

The errors go away if you change the parameter names to something else.

**Comment by niveathika** [comment]
Ack @MaryamZi
