### ISSUE TITLE
No possibility to exit program

### ISSUE THREAD

**Issue by werner468** [ballerina-platform/ballerina-lang#5311]
Seems there is no possibility to exit program as e.g. in Java with System.Exit(0)
https://stackoverflow.com/questions/49289064/how-to-terminate-ballerina-program/49289209#49289209

**Comment by afkham** [comment]
I think there is no need for a System.exit sort of function in Ballerina. This is because, if you started your process via a main function, then getting that function to complete will result in the program exiting. If there are services running, then it is a bad idea to have a System.exit in service code.

**Comment by shafreenAnfar** [comment]
@werner468 Will you be able to explain your use-case a bit ? Maybe we can achieve the same without using System.exit(0).

**Comment by Kishanthan** [comment]
@werner468, could you share your use case in detail for us to analyse?

As mentioned above, currently we don't see a concrete use case to have like system.exit functionality in ballerina.

**Comment by ayomawdb** [comment]
Hi @werner468, I am closing this issue for now. However, please feel free to reopen the issue with the use case you are trying to address, so that we can see if the same can be addressed without System.exit sort of a function.
