### ISSUE TITLE
Examples are hard to recreate

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6417]
<a href="https://github.com/robbla"><img src="https://avatars2.githubusercontent.com/u/11582659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [robbla](https://github.com/robbla)**
_Wednesday Nov 29, 2017 at 10:38 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4757_

----

When we look at the examples, e.g. the JMS producer it is quite hard to figure out the steps as to get to the sample, in other words rebuilding it. 

This is particularly so in:

1. which function first (dependencies)
2. use of predefined sub functions
3. dependencies and errors (e.g. the return statement needs a return value)

For instance how do we create this function from the graphical overview?

```ballerina
function getConnectorConfig () () {
     // We define the connection properties as a map. 'providerUrl' or 'configFilePath' and the 'initialContextFactory' vary according to        //the JMS provider you use.
     // In this example we connect to the WSO2 MB server.
    jms:ClientProperties properties = {   initialContextFactory:"wso2mbInitialContextFactory",
                                          configFilePath:"C:/ballerina-tools-0.95.0/bre/conf/jndi.properties",
                                          connectionFactoryName: "QueueConnectionFactory",
                                          connectionFactoryType : "queue"};
    return properties;
```

**Comment by hevayo** [comment]
Sorry for taking so long to reply. 

At the time of this issue is reported we had a drag and drop graphical editor. As of now, we have moved away from considering the graphical editor as a fully fledge program editor. Now the focus is that graphical editing will only allow you to create an initial flow of the program. ie. add the connectors, defining the basic flow of the code etc. 

We will be closing this issue since it is no longer relevant, please do try new editing capabilities in Ballerina VSCode plugin and give us your feedback.
