### ISSUE TITLE
Condition check, null == CustomType results in NullReferenceError

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#6806]
**Description:**
if(null == CustomType) { // this line throws a NullReferenceError

**Comment by sanjiva** [comment]
Chatted with Azeez. He got the error from here:
https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-builtin/src/main/ballerina/transactions/2pc_transaction.bal#L40

Line 40 was not there and the L33 declaration doesn't say state is optional. However we don't currently check at compile time whether all non-optional fields are initialized by the initializer.

So the fix is to make that work correctly .. then there would've been a compile time error saying "state was not initialized so you need to init or mark it optional".
