### ISSUE TITLE
Add Annotation to provide XML/JSON schema location

### ISSUE THREAD

**Issue by srinathperera** [ballerina-platform/ballerina-lang#72]
This is schema used to describe the qualifier attached to xml, json etc via < ..> e.g. xml<http://foo/Foo

**Comment by hasithaa** [comment]
Language has evolved a lot since this issue is created. The current plan is to add this support to the language itself. This is captured in Spec in different issues & hence I am resolving this issue, in favor of following:
XML:
- https://github.com/ballerina-platform/ballerina-spec/issues/177
- https://github.com/ballerina-platform/ballerina-spec/issues/249

JSON:
- https://github.com/ballerina-platform/ballerina-spec/issues/363
