### ISSUE TITLE
Cannot validate the type of the variable given for an annotation

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#7516]
**Description:**
If a annotation configuration record takes a `typedesc` variable it cannot be validated during compile time. That is we if it is to be of `WebSocketService` type we need to make sure it is of that type and not allow user to set any other type there. For example WebSocket config for upgrade resource is as follows:
```
@http:ResourceConfig {
        webSocketUpgrade:{
            upgradePath:"/ws",
            upgradeService:simpleProxy
        }
    }
```
`upgradeService` can only be of type ` WebSocketService` which cannot be validated at compile time.

**Comment by hasithaa** [comment]
@MaryamZi Please verify this.

**Comment by MaryamZi** [comment]
@riyafa IINM, this is related to service typing, and not specifically an annotation field? 

The current WebSocketUpgradeConfig has the following structure, so I'm assuming the requirement is to validate that the service is a WebSocket service?

```ballerina
public type WebSocketUpgradeConfig record {|
    string upgradePath = "";
    service upgradeService?;
|};
```

Quoting from the spec, 
```
It is planned that a future version of Ballerina will provide a mechanism that allows 
more precise typing of services. In the meantime, implementations can use 
annotations on type definitions to support this.
```

Since we don't have the concept of service typing atm, we would have to use an annotation to identify that a service is of a particular type, and validate at runtime that the service is of the expected type, based on the annotation. I don't think there is a straightforward way to do this at compile time atm.

**Comment by hasithaa** [comment]
Related to https://github.com/ballerina-platform/ballerina-spec/issues/329

**Comment by hasithaa** [comment]
This issue will be fixed with the new service type design. We will use the spec issue to track this requirement.
