### ISSUE TITLE
[HTTP] Fix Data binding negative test case

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#7859]
**Description:**
Due to language limitation, JSON to Record conversion does not fail when there are no equivalent record fields in the JSON.
Fix https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/services/dispatching/DataBindingTest.java

**Comment by riyafa** [comment]
The following code runs without any issue but in reality it should throw an error:

```
import ballerina/io;

type event record{
    boolean ^"left";
    boolean ^"right";
    boolean up;
    boolean down;
};
function main(string... args) {
   json val = {"hello":"world"};
   event data = check <event>val;
    io:println(data);
}
```

**Comment by riyafa** [comment]
This [issue](https://github.com/ballerina-platform/ballerina-lang/issues/9343) need to be fixed before this test case can be fixed.

**Comment by sanjiva** [comment]
This issue is now solvable properly with the improve record type descriptor syntax. 

If a record has a field x and its not an *optional field*, then its a required field and it MUST be in the JSON. Records are open by default but if the person said !...; at the end then its closed .. meaning ONLY the fields in the record must be in the JSON.

If this is not clear lets meet and I can clarify.
