### ISSUE TITLE
Syntax highlighting issues

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8342]
**Description:**
Syntax highlighting issues
![56](https://user-images.githubusercontent.com/1845370/39515556-1d4a192a-4e18-11e8-9fd8-e0918ec1ae78.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by roonyh** [comment]
@dilinisg If you could also post the code in text, its easier to reproduce.

**Comment by dilinisg** [comment]
It is the http client endpoint sample

**Comment by roonyh** [comment]
The outermost variable decs like `http:Request req` is a little difficult to highlight at the moment. We need to figure out a way to highlight them without breaking other stuff. The rest is fixed by #8797. I'll close this and add a separate issue for the above.
 
![screenshot from 2018-05-31 15-40-26](https://user-images.githubusercontent.com/3872221/40824189-d716df02-6590-11e8-9830-184cd1a6e60e.png)
