### ISSUE TITLE
[Docerina] Union type function parameters cannot document.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#8490]
**Description:**
Union type parameters such as [1] gives following error.

WARNING: ballerina/sql/actions.bal:28:9:: no such documentable attribute 'parameters' with doc prefix 'P'

Code to reproduce the issue:See P{{parameters}}

```
documentation {
        The call action implementation for SQL connector to invoke stored procedures/functions.

        P{{sqlQuery}} SQL statement to execute
        P{{recordType}} Array of record types of the returned tables if there is any
        P{{parameters}} List of parameters for the query
        R{{}} A `table[]` if there are tables returned by the call action and else nil,
                `error` will be returned if there is any error
    }
    public native function call(@sensitive string sqlQuery, typedesc[]? recordType, Param... parameters)
        returns @tainted table[]|()|error;

```

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-database/src/main/ballerina/sql/actions.bal#L31

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
This is fixed in the latest master, hence closing this issue. 

[https://ballerina.io/learn/api-docs/ballerina/sql.html#CallerActions-call](https://ballerina.io/learn/api-docs/ballerina/sql.html#CallerActions-call)

**Comment by anupama-pathirage** [comment]
The issue is no way to give a description for union types. Issue is still there, hence re-opening the issue

**Comment by praneesha** [comment]
This is fixed in the new design. For example, if we consider the union type in L61 of [1], the API docs will be generated with the description of the union type displayed as follows in [2]:

<img width="985" alt="Screenshot 2019-12-10 at 15 48 30" src="https://user-images.githubusercontent.com/11707273/70521160-c1c7d580-1b64-11ea-8613-cbe887113753.png">
<img width="1204" alt="Screenshot 2019-12-10 at 15 48 46" src="https://user-images.githubusercontent.com/11707273/70521206-d310e200-1b64-11ea-8338-5ca5c240fa1e.png">

Therefore, closing this as the issue doesn't prevail in the new API Docs.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/jdbc/src/main/ballerina/src/java.jdbc/client.bal
[2] https://ballerina.io/learn/api-docs/ballerina/java.jdbc/clients/Client.html
