### ISSUE TITLE
[Docerina] New lines in doc comments are not rendered properly

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#8527]
**Description:**
Even we have used new lines for the parameter descriptions, in the generated html page, they are not displayed. But empty lines are taken as the new line separator in the html page.

Refer the doc comment [1] for details.
[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-database/src/main/ballerina/sql/types.bal#L45:L82
Refer [2] for the generated html page.

[2] https://ballerina.io/learn/api-docs/ballerina/sql.html#TypeDefinitions

**Affected Versions:**

0.979.1

**Comment by praneesha** [comment]
For example, if we consider L189-L191 in [1] that are all added as new lines, it will be displayed in API docs without the new lines as follows in [2].

<img width="984" alt="Screenshot 2019-12-10 at 15 14 59" src="https://user-images.githubusercontent.com/11707273/70518270-1452c300-1b60-11ea-8919-7eeb046cd443.png">
<img width="1240" alt="Screenshot 2019-12-10 at 15 15 11" src="https://user-images.githubusercontent.com/11707273/70518295-216fb200-1b60-11ea-882d-67a1596c6a11.png">


[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/jdbc/src/main/ballerina/src/java.jdbc/types.bal
[2] https://ballerina.io/learn/api-docs/ballerina/java.jdbc/index.html#types

**Comment by shehan360** [comment]
This issue seems to be fixed in the latest master branch.
![Screenshot from 2020-08-18 10-43-21](https://user-images.githubusercontent.com/33398983/90473230-079b5b80-e140-11ea-819e-2c36dff717cd.png)
![Screenshot from 2020-08-18 10-44-43](https://user-images.githubusercontent.com/33398983/90473236-0a964c00-e140-11ea-9779-801c73a35cb3.png)

**Comment by praneesha** [comment]
The issue still prevails in [1] as shown below.

<img width="1128" alt="Screenshot 2020-08-18 at 10 53 45" src="https://user-images.githubusercontent.com/11707273/90473741-42ea5a00-e141-11ea-841d-bf9794176d6e.png">

[1] https://dev.ballerina.io/learn/api-docs/ballerina/java.jdbc/types.html#Direction

**Comment by shehan360** [comment]
To achieve the desired formatting effect, the documentation text should be formatted as follows.
![Screenshot from 2020-08-20 11-36-50](https://user-images.githubusercontent.com/33398983/90722962-74962900-e2d9-11ea-932b-5f25bed68bef.png)


That is, a blank line should be placed where a new line is desired. When formatted like above, the output will be as follows.
![Screenshot from 2020-08-20 11-32-25](https://user-images.githubusercontent.com/33398983/90722919-61835900-e2d9-11ea-9ef4-d858de745107.png)

Documentation has to be formatted like above because in some instances a line extends to the next line. This can be seen in many places due to the 120 character limit.
![Screenshot from 2020-08-20 11-39-53](https://user-images.githubusercontent.com/33398983/90723168-e4a4af00-e2d9-11ea-9140-35ab1f5308c2.png)

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/25356 and https://github.com/ballerina-platform/ballerina-dev-website/pull/1191.
