### ISSUE TITLE
[WINDOWS] Ballerina program run issue

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#8654]
**Description:**

Consider the following project structure.
```
project-root
   |-test
       |- main.bal
```
If we set the source root and run a file using the relative path using the following command -
```
C:\Users\Shan\IdeaProjects\TestBallerina>C:/Users/Shan/Desktop/Ballerina-SDKs/ballerina-platform-0.970.1\bin\ballerina.bat run --sourceroot C:\Users\Shan\IdeaProjects\TestBallerina test\main.bal
```

We get the following error -

```
ballerina: cannot find file 'test\main.bal'
```

This works without any issue in MacOS and Ubuntu.

Also this causes issues when running Ballerina main programs in IDEA (https://github.com/ballerina-platform/ballerina-lang/issues/8636).

**Comment by NatashaWso2** [comment]
A ballerina project can be executed as : ballerina run package-name. It would be determined as a project if there's a .ballerina folder. A single ballerina program can be executed as : ballerina run bal-file. Closing this issue as it is not valid.

**Comment by manuranga** [comment]
@TylerJewell - The issues is, running something in a package as a file is inconsistent, it works only if there are no relative imports.

We _could_ search the file system to see if there is a `.ballerina` and resolve the relative imports accordingly. This is one of the feature we have planed (in the spreadsheet as "Auto detect.ballerina (eg: when giveing abs path)") but hasn't started yet.

Even then it's debatable if this the correct thing to do, since the compiler's POV files are not first class, packages are. Shall we discuss this in Thursday meeting.

**Comment by hevayo** [comment]
The implementation has deviated hence closing the issue
