### ISSUE TITLE
Verify and remove setting auto-committing false in executing batch update

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#8675]
**Description:**
$subject at [1]. Doing [1] and committing later seems unnecessary. We are not trying to perform a transaction and have only one execute statement. Whether the batch update is transactional or not is up to the driver and we have no control over it.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/v0.971.0/stdlib/ballerina-database/src/main/java/org/ballerinalang/database/sql/actions/AbstractSQLAction.java#L262

**Comment by anupama-pathirage** [comment]
This is done so that all the Batch statements execute in a single transaction and no operation in the batch is committed individually. This way, it is possible to rollback the batch operation in case one of the updates fail for any reason.

From the JDBC 4.1 spec [1] :

The auto-commit mode is disabled to prevent the driver from committing the transaction when Statement.executeBatch is called. Disabling auto-commit allows an application to decide whether or not to commit the transaction in the event that an error occurs and some of the commands in a batch cannot be processed successfully. For this reason, auto-commit should always be turned off when batch updates are done. The commit behavior of executeBatch is always implementation-defined when an error occurs and auto-commit is true.

[1] http://download.oracle.com/otn-pub/jcp/jdbc-4_1-mrel-spec/jdbc4.1-fr-spec.pdf
