### ISSUE TITLE
Add support for Blowfish/AES/RSA encrypt / decrypt to Crypto API

### ISSUE THREAD

**Issue by crognon** [ballerina-platform/ballerina-lang#9054]
**Description:**
I would like to use Blowfish encrypt to have a symetric encode decode capability to obuscate json content
.
Or a way to call some Java code that already is capable of such encryption.

**Affected Versions:**
Latest

**OS, DB, other environment details and versions:**
linux 64b ou win32 64b

**Suggested Labels (optional):**
JSON  ENCRYPT

Thanks
Cyril

**Comment by Shan1024** [comment]
Hi @crognon, thank you vey much for reaching out to us. We don't have built in support for blowfish encryption as of now. But you can easily implement it by writing native functions which exposes some java codes for encrypting and decrypting. Since Ballerina is open source, you can write this and send a PR to Ballerina if you like as well.

Please refer following links where you can get an idea about how to implement native functions.

https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-builtin/src/main/ballerina/crypto/natives.bal

https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-builtin/src/main/java/org/ballerinalang/nativeimpl/crypto/Hash.java

Also please refer the [contributing guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md) as well.

Please join our [Slack](https://ballerina-platform.slack.com) channels so you can ask any question you have from Ballerina developers.

**Comment by ayomawdb** [comment]
Hi @crognon! I agree with you that we need to have encryption / decryption capabilities exposed through [Ballerina Crypto API](https://ballerina.io/learn/api-docs/ballerina/crypto.html). Currently the API is limited to HMAC generation and hashing. We are considering this as an improvement to the Crypto API. 

If this is blocking your work and you need an immediate solution, you may use [package-crypto written by in2group](https://github.com/in2group/package-crypto) as a reference to implement a native function that expose Blowfish encryption to Ballerina. Native functions are written in Java as of now. 

Here are the updated new reference links @Shan1024 provided: 

https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/crypto/src/main/ballerina/crypto/natives.bal

https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Hash.java
