### ISSUE TITLE
Ensure Java 9 compatibility

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#9184]
**Description:**
When trying to run ballerina in Java9u4; it fails with the "**ballerina: Oh no, something really went wrong. Bad. Sad.**" error message.

**Steps to reproduce:**
Set JDK9 as the JAVA_HOME and try to run following code snippet with the command `ballerina run helloWorld.bal`;

```
import ballerina/io;
      function main(string... args) {
        io:println("Hello, World!");
      }
```

**Comment by bjansen** [comment]
Also, ballerina won't even start if `JAVA_HOME` points to an Oracle JDK 9 on Windows, because `ballerina.bat` assumes the version is `1.9` instead of just `9`.

Here's the result of `"%JAVA_HOME%\bin\java" -version`;
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

I believe the [regex](https://github.com/ballerina-platform/ballerina-lang/blob/master/distribution/zip/ballerina/bin/ballerina.bat#L114) should be fixed like this:

```
"%JAVA_HOME%\bin\java" -version 2>&1 | findstr /r "[1.8|9]" >NUL
```

A better approach would be to check system properties instead, like [commons-lang does](https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/SystemUtils.java#L1692):
* if the substring you are looking for appears somewhere else in the output of `java -version`, that won't lead to a false positive
* you will also be able to target Java 10, 11 etc.

Note: once I fix `ballerina.bat`, I also get the exception found in the original post.

**Comment by rasika** [comment]
@bjansen, We'll be more than happy If you could send your fix in a separate PR so we can review and merge. And also, can you try the fix I have suggested along with your regex fix in your windows environment?

**Comment by bjansen** [comment]
I tried the fix in https://github.com/rasika/ballerina-1/commit/b23da220219f00fb7b4e9610f6a5b56017e75eab and it works very well: no more error message, and no log file are created either.

I'm surprised you were able to run the script though, because every JDK 9 I've tried so far returns version `9`, not `1.9`.

I'll open a PR soon for the regex.

**Comment by bjansen** [comment]
Done: https://github.com/ballerina-platform/ballerina-lang/pull/9269

**Comment by rasika** [comment]
I couldn't test the fix with the Windows environment; because of that reason, this PR is not merged yet. Thanks for the contribution and will check your PR ASAP.
