### ISSUE TITLE
Composer not starting in windows

### ISSUE THREAD

**Issue by kasvith** [ballerina-platform/ballerina-lang#9430]
**Description:**
When tried to open up ballerina composer in windows environment it fails to start with 
`Error: Could not find or load main class org.ballerinalang.composer.server.launcher.ServerLauncher`

**Steps to reproduce:**
- Install ballerina
- Initialize a project
- Run composer on this folder
![image](https://user-images.githubusercontent.com/13379595/42319984-5444f3ba-8071-11e8-9779-3111b52678cc.png)

> PS : I ve renamed composer.bat to bal-composer due to the conflict with PHP composer. Renaming the composer name would reduce these kind of issues as PHP Composer is pretty popular among devs and ballerina should not make a conflict 👍 

> When I started composer directly in the bin dir of the ballerina with Windows CMD it worked

**Affected Versions:**
- Ballerina 0.975.1

**OS, DB, other environment details and versions:**
- Windows 10 Education version 1803 (build 17134.112)
- used [Cmder](http://cmder.net/) as console emulator on windows (v180206)

**Related Issues (optional):**

**Suggested Labels (optional):**
bug

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@kasvith It seems that the Ballerina class path issue is arising in this scenario. Can you try replacing the following line in composer.bat
`FOR %%C in ("%BALLERINA_HOME%\lib\resources\composer\services\*.jar") DO set BALLERINA_CLASSPATH=!BALLERINA_CLASSPATH!;".\lib\resources\composer\services\%%~nC%%~xC"`
with
`FOR %%C in ("%BALLERINA_HOME%\lib\resources\composer\services\*.jar") DO set BALLERINA_CLASSPATH=!BALLERINA_CLASSPATH!;"%BALLERINA_HOME%\lib\resources\composer\services\%%~nC%%~xC"`

this has been fixed in the latest ballerina version.

Please reopen if the issue exist further.

**Comment by nadeeshaan** [comment]
Rename related issue has been addressed at https://github.com/ballerina-platform/ballerina-lang/issues/9442
