### ISSUE TITLE
Having "\." in a string will result in parser errors

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#9540]
**Description:**

Compiling following program results in parser errors:
```
function main(string... args) {
    string example = "\.";
}
```

```
error: ./test.bal:2:22: token recognition error at: '"\.'
error: ./test.bal:2:25: token recognition error at: '";\n}\n'
error: ./test.bal:4:1: invalid token '<EOF>'
compilation contains errors
```

**Steps to reproduce:**
Compile the example form the description.

**Affected Versions:**
0.975.1

**OS, DB, other environment details and versions:**
N/A. Tested on Ubuntu

**Suggested Labels (optional):**
Priority/High Component/Compiler Type/Bug

**Comment by Shan1024** [comment]
We cannot use `"` , `\` within strings without escaping them first. Also note that we can only escape `b`, `t`, `n`, `f`, `r`, `"`, `'`, `\` characters in a string (`.` is not supported). So the compiler does not recognize `\.` as valid escaped character which causes this issue.

So you have to escape `\` first.  E.g.- `\\.`

**Comment by ayomawdb** [comment]
@Shan1024 noted. @hasithaa Should we keep the issue open or open a new issue so that we can improve the error? The error be something like "illegal escape character".  Three errors we generate can be very confusing for an end user.

**Comment by Shan1024** [comment]
@ayomawdb - We already have a issue opened for improving syntax issues related error messages at https://github.com/ballerina-platform/ballerina-lang/issues/3673.

We cannot improve these error messages as it is now. What we can do is, we need to allow any character to be escaped in the grammar, and then in the compile time we can check and throw more meaningful error. Otherwise we might not be able to improve error messages at all.
