### ISSUE TITLE
[Suggestion]build and Push processes could be put in the composer 

### ISSUE THREAD

**Issue by jayamaljayamaha** [ballerina-platform/ballerina-lang#9583]
**Description:**
Currently, run the package, building the package and push to the GitHub happen through the command line but we can integrate that into the composer and we can do that all processes using the composer

in the current process, we have to work with multiple windows
            1) command line for open the composer
            2) command line for build and push processes
            3) browser for access the composer 
We can reduce that to the two windows when we put above processes to the composer itself then no need to shift between composer and command line we can do that both processes using the composer, workflow becomes easy and reduced  

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
@jayamaljayamaha thanks for the suggestion.

Actually, now (since 0.980.0) composer is packed and distributed with Electron and if you use the installer to install ballerina tools, you should get it. After installation, you can launch composer from start menu shortcut (on windows) or from Applications folder (on Mac). However for linux, still you should launch it from command line (in future we will create shortcuts for linux too, during installation). The need to open a browser window is no longer there as composer will now be launched in its own window once started. 

Still, the second point is valid - which is the need for an integrated terminal or the ability to build/push etc. This is in our backlog already and we are looking into the possibility to base Composer tooling on [Theia IDE](https://github.com/theia-ide/theia), which has an integrated terminal. Hopefully this will resolve the need to maintain basic IDE features on our own.

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina

**Comment by nadeeshaan** [comment]
This has been captured with #13562 hence closing the issue.
