### ISSUE TITLE
Fix testerina behavior

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#9652]
**Description:**
Earlier testerina behavior was that if you are testing a package "ab" and if that package has some services you need to test, then you had to specifically start those services before testing. But with a recent change https://github.com/ballerina-platform/ballerina-lang/pull/9615 this was changed so that if you are testing package "ab" then you don't specifically need to start services of that package, the rationale was that it was consistent with ballerina run behavior, for example, if you run a package with both services and main, then you don't specifically say to run services but those will get started automatically, (this is true for dependant package as well)

But there is a counter-argument to this saying, the user should have the control over which services to run when testing a package, hence creating this issue to track the progress

**Comment by yasassri** [comment]
IMV, testerina execution flow doesn't have to be consistent with the ballerina run flow. When it comes to tests the user should have the control over which component or the service they need to test. For e.g. I might have a ballerina package which has a service, but due to unavailability of a proper backend for testing I might only do unit tests on the package. In this case I don't need to start the service at all. Also there can be cases where the developers need to perform prerequisites before starting the services. E.g : Configuring the backends etc. Also there can be cases where the developer needs to restart the service several times for executing different test cases. E.g : Changing the input value sets etc. So I'm in favor of the original behavior of Testerina.
