### ISSUE TITLE
[Proposal] Refining the type system to use type inference

### ISSUE THREAD

**Issue by conradwt** [ballerina-platform/ballerina-lang#9676]
**Description:**

Add some support for type inference.  For example, Ballerina Language currently requires one to do the following:

Given

```ballerina
type Person record {     
  string firstName,
  string lastName
};
```

Now, one can use the above record by doing the following:

```ballerina
Person person = { firstName: 'Conrad', lastName: 'Taylor'};
```

Finally, I would like to propose using type inference throughout the type system:

```ballerina
[constant | con] person1 = Person{ firstName: 'Conrad', lastName: 'Taylor'};
[variable | var]  person2 = Person{ firstName: 'Conrad', lastName: 'Taylor'};
``` 
**Steps to reproduce:**

N/A

**Affected Versions:**

N/A

**OS, DB, other environment details and versions:**

N/A

**Related Issues (optional):**

N/A

**Suggested Labels (optional):**

Type/Task

**Suggested Assignees (optional):**

TBD

**Comment by hasithaa** [comment]
@conradwt , This is similar to, `Explicitly typed expression`. (see page 44 in Ballerina-Language-Specification-WD-2018-07-12.pdf). Instead of saying `Person{ firstName: 'Conrad', lastName: 'Taylor'}` we say `<Person> { firstName: 'Conrad', lastName: 'Taylor'}`.

Please reopen this issue, if there is any deviation from what you suggest. 

Spec : https://ballerina.io/res/Ballerina-Language-Specification-WD-2018-07-12.pdf
