### ISSUE TITLE
[Proposal] Helm Chart Support

### ISSUE THREAD

**Issue by conradwt** [ballerina-platform/ballerina-lang#9677]
**Description:**

Add support for building Helm Charts with the Ballerina.  Why?  One tends to want to take all the Kubernestes artifacts and manage them as a cohesive whole so one doesn't need to perform `kubectl apply -f ...`.   As a next step, it would be really cool to create a Helm Chart. Thus, simply use something like the following at the end of the output during the build process:

```
'helm install --name example ./mychart'.
```

**Steps to reproduce:**

N/A

**Affected Versions:**

N/A

**OS, DB, other environment details and versions:**

N/A

**Related Issues (optional):**

N/A

**Suggested Labels (optional):**

Component/Kubernetes
Component/Helm[Chart]

**Suggested Assignees (optional):**

None

**Comment by anuruddhal** [comment]
Hi @conradwt, 
thank you very much for reaching out to us. We don't have built-in support for Helm Charts as of now. But this can easily implement it by writing a compiler extension. Since Ballerina is open source, you can write this and send a PR to Ballerina if you like as well.

Please refer following links where you can get an idea about how to implement a compiler extension.
https://ballerina.io/learn/how-to-extend-ballerina/#create-custom-annotations-builder-extensions

Refer kubernetes and docker extensions as well.
https://github.com/ballerinax/kubernetes
https://github.com/ballerinax/docker

Also please refer the [contributing](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md) guide as well.

Please join our [Slack](https://ballerina-platform.slack.com/messages) channels so you can ask any question you have from Ballerina developers.

**Comment by hemikak** [comment]
This support is added with https://github.com/ballerinax/kubernetes/pull/177
