### ISSUE TITLE
persistent intellij warning 

### ISSUE THREAD

**Issue by rabbah** [ballerina-platform/ballerina-lang#9922]
**Description:**
i have several ballerina files in an intellij project
and the ide reports properly that my assets are not in a ballerina module but the warning is persistent and cannot be dismissed.

<img width="567" alt="screen shot 2018-08-06 at 9 21 34 am" src="https://user-images.githubusercontent.com/4959922/43718899-21e3c228-995a-11e8-8902-e748ddee078b.png">

**Steps to reproduce:**
the project i'm working with imports the following code https://github.com/apache/incubator-openwhisk-runtime-ballerina 

**Affected Versions:**

**OS, DB, other environment details and versions:**
mac osx, IJ ultimate 2018.1 and ballerina 0.975

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
This may occur when your IntelliJ project is not opened as an `IntelliJ ballerina project`. Could you please share a screeenshot of your project structure shown in IntelliJ, as shown by the example below?

**Example:**
![screenshot from 2018-08-07 10-42-14](https://user-images.githubusercontent.com/29032600/43755671-9f280efe-9a2e-11e8-8adc-d1c5f9ed0add.png)

**Comment by rabbah** [comment]
Sure I can do that but maybe this is enough: the project is a scala project that also includes some Ballerina artifacts.

**Comment by NipunaRanasinghe** [comment]
Yeah, that should be the reason. Still, you can resolve this by defining your package/packages which includes ballerina files as submodules and setting up the ballerina SDK for those submodules explicitly.

Could you please follow the below steps and let us know whether your issue is fixed?

1. Go to to **File -> Project Structure** and select **Modules**

2. Click the **"+"** button and choose **New Module**  to add your submodule

![screenshot from 2018-08-07 16-26-17](https://user-images.githubusercontent.com/29032600/43772077-a3aac054-9a5e-11e8-97c8-b94613f39df3.png)

3. Select **Ballerina** as the module type and proceed to the next window.

4. Select your ballerina SDK as the project SDK and proceed to the next window.

5. Then set up a module name and set your package location in the **Content root** field and click **Finish**

![screenshot from 2018-08-07 16-34-07](https://user-images.githubusercontent.com/29032600/43772505-f55f2646-9a5f-11e8-8ea7-a6da64a2ec75.png)

**Comment by rabbah** [comment]
Thanks - re-configuring my project structure removed the warning.
