### ISSUE TITLE
Compiler crashes on fork with no join

### ISSUE THREAD

**Issue by autodidaddict** [ballerina-platform/ballerina-lang#9988]
[ballerina-internal-fork-no-join.log](https://github.com/ballerina-platform/ballerina-lang/files/2274163/ballerina-internal-fork-no-join.log)

**Description:**
Trying to write a simple example that illustrates two workers communicating. If you leave off the join statement, compiler should politely warn you of a syntax error. Instead it crashes with the attached stack trace from ballerina-internal.log

**Steps to reproduce:**
Attempt to run the following code:
```ballerina
import ballerina/io;

function main(string... args) {

    fork {
        worker stdin_read {
            string s = io:readln(());
            string smod = "[ECHO] " + s;
            smod -> stdout_write;
        }

        worker stdout_write {
            string s;

            s <- stdin_read;
            io:println(s);       
        }
    }
}
```

**Affected Versions:**
0.980.1

**OS, DB, other environment details and versions:**
MacOS High Sierra 10.13.6

**Suggested Labels (optional):**
bug

**Comment by riyafa** [comment]
Refer mail: https://groups.google.com/d/msg/ballerina-dev/sBkMkHZ83Fs/g_2jZqjvAAAJ

**Comment by ayomawdb** [comment]
@autodidaddict As the mail thread also suggests, there are major changes currently happening in concurrency constructs. This issue will be addresses after relevant changes are available.

**Comment by lankavitharana** [comment]
We changed fork join syntax a bit, so now we longer have join and timeout blocks, new syntax only has the `fork` which will spawn new execution flows for the workers specified inside the fork. If you need to join the results of those workers, then you have to use `wait` expression to do that, 

you can refer concurrency section of the Ballerina By example site[1] for more details about the new syntax. More specifically [2] and [3] links.

Closing this issue because we no longer have these join statements, please reopen if you think there are any other areas to be fixed or improved.

[1] - https://ballerina.io/learn/by-example/
[2] - https://ballerina.io/learn/by-example/fork.html
[3] - https://ballerina.io/learn/by-example/fork-variable-access.html
